### ISSUE TITLE
Resources: New palettes of Lima

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmg-palette#1003]
**以下內容已被手動編輯，以最新版本代替 (6 Jan 2024)**

**Reference link:** https://es.wikipedia.org/wiki/Metro_de_Lima_y_Callao

**Justification:** Update palettes of Lima

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "lima",
    "country": "PE",
    "name": {
        "en": "Lima",
        "es": "Lima",
        "zh-Hans": "利马",
        "zh-Hant": "利馬"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "lm1",
        "colour": "#509e2f",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "es": "Línea 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "lm2",
        "colour": "#ffb81c",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "es": "Línea 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "lm3",
        "colour": "#00c1d5",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "es": "Línea 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "lm4",
        "colour": "#da291c",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "es": "Línea 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "lm5",
        "colour": "#f57eb6",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "es": "Línea 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "lm6",
        "colour": "#8b84d7",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "es": "Línea 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，经检查我们发现以下问题：

- 根据您所提供来源，您所提交的下述线路的颜色与来源中的颜色不匹配：
  - 1号线（来源中颜色为`#509e2f`）
  - 2号线（来源中颜色为`#ffb81c`）
  - 3号线（来源中颜色为`#00c1d5`）
  - 4号线（来源中颜色为`#da291c`）
  - 5号线（来源中颜色为`#f57eb6`）
  - 6号线（来源中颜色为`#8b84d7`）

请在修正上述错误后于本issue下重新提交修正后的线路颜色。感谢您对本项目的支持！

**Comment by linchen1965** [comment]
**Reference link:** https://es.wikipedia.org/wiki/Metro_de_Lima_y_Callao

**Justification:** Update palettes of Lima

**Do not edit lines below, they are meant for bots only!!!**



<details repo="rmg-palette" type="city">{
    "id": "lima",
    "country": "PE",
    "name": {
        "en": "Lima",
        "es": "Lima",
        "zh-Hans": "利马",
        "zh-Hant": "利馬"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "lm1",
        "colour": "#509e2f",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "es": "Línea 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "lm2",
        "colour": "#ffb81c",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "es": "Línea 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "lm3",
        "colour": "#00c1d5",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "es": "Línea 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "lm4",
        "colour": "#da291c",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "es": "Línea 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "lm5",
        "colour": "#f57eb6",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "es": "Línea 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "lm6",
        "colour": "#8b84d7",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "es": "Línea 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
经检查，所有问题已经修复。

**Comment by 28yfang** [comment]
@52PD 你汇入的好像是修改之前的pr

**Comment by 28yfang** [comment]
![image](https://github.com/railmapgen/rmg-palette/assets/123239445/e69c3573-617e-408b-badc-926ee9371f8f)

**Comment by 52PD** [comment]
收到，正在处理

**Comment by wongchito** [comment]
> @52PD 你汇入的好像是修改之前的pr

PR的源程式碼變更實為更新後的顏色，可於Commits中檢視。而PR正文未跟隨更新，稍後我將修復該問題。
