### ISSUE TITLE
Resources: New palettes of Algiers

### ISSUE THREAD

**Issue by Rainyang2022** [railmapgen/rmg-palette#1006]
**Reference link:** https://baike.baidu.com/item/%E9%98%BF%E5%B0%94%E5%8F%8A%E5%B0%94%E5%9C%B0%E9%93%81/14892872?fr=ge_ala

**Justification:** 阿尔及尔是非洲第二个拥有地铁的城市

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "DZA",
    "name": {
        "en": "Algeria",
        "zh-Hans": "阿尔及利亚",
        "zh-Hant": "Algérie"
    },
    "language": "ar"
}</details>

<details repo="rmg-palette" type="city">{
    "id": "algiers",
    "country": "DZA",
    "name": {
        "en": "Algiers",
        "zh-Hans": "阿尔及尔",
        "zh-Hant": "阿爾及爾"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "L1",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线"
        }
    }
]</details>

**Comment by 28yfang** [comment]
Hi, we do not accept Baidu Baike as a trustworthy source. See https://github.com/railmapgen/rmg-palette/wiki/Review-Criteria for our list of accepted sources :)

**Comment by Windows-Taskmgr** [comment]
您好，由于您已经超过一个月未回复，此issue将会被关闭，感谢您的理解。如有需要，请再次打开一个新issue。
