### ISSUE TITLE
Resources: New palettes of Taizhou

### ISSUE THREAD

**Issue by microharddemo** [railmapgen/rmg-palette#1023]
**Data source:** 9. 其他（请于下方注明）

**Reference link:** https://baike.baidu.com/item/%E5%8F%B0%E5%B7%9E%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A/22847227

**Justification:** 添加y颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"taizhou","country":"CN","name":{"en":"Taizhou","zh-Hans":"台州","zh-Hant":"台州"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"tz1","colour":"#1194d4","fg":"#fff","name":{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1号线"}}]</details>

**Comment by Windows-Taskmgr** [comment]
您好，我们不支持来自百度百科的来源，请您换一个更可靠的来源重新提交，感谢您的贡献。

**Comment by langonginc** [comment]
Close as no response
