### ISSUE TITLE
Resources: New palettes of Taizhou

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-palette#1033]
**Data source:** 9. 其他（请于下方注明）

**Reference link:** https://baike.baidu.com/item/台州市域铁路S1线/20165654?fr=ge_ala

**Justification:** 提供台州的颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"taizhou","country":"CN","name":{"en":"Taizhou","zh-Hans":"台州","zh-Hant":"台州","ja":"台州","ko":"타이저우"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"tzs1","colour":"#2392e7","fg":"#fff","name":{"en":"Line S1","zh-Hans":"S1线","zh-Hant":"S1線","ja":"S1線","ko":"S1선"}}]</details>

**Comment by Windows-Taskmgr** [comment]
您好，我们暂不支持来自百度百科的来源，请您更换来源提交，感谢您的贡献。
