### ISSUE TITLE
关于天津地铁每条线路的颜色

### ISSUE THREAD

**Issue by HatsuneMikuZD** [railmapgen/rmg-palette#1037]
原文地址(http://www.baidu.com/link?url=dTFLTmZaYLx99qfjrPr-HgmBFaD-6kk-qjfg6saiupKOKx0WoJNs2MgzHPYFQuAjcWDnaInaQUUcMGh0TvzPbkTbDzXR9suXHB-mdMpqwHl2-nTBsy6Oojms4GZo-WUHDJRtiKub9qZItnaoSyWgxsZlplNL5xN6jyc5sh11nZBoSz19RXWF6XwgEA8GHL7f&wd=&eqid=feb9eff000054c2300000003659505e6)

[454.2.pdf](https://github.com/railmapgen/rmg/files/13816451/454.2.pdf)
那里面有关于规划的地铁线路、市域铁路颜色

如果这文档里的颜色可以的话，怎么添加到调色板上

**Comment by HatsuneMikuZD** [comment]
[DB12T 454.2-2023 公共交通信息导向标志系统设置要求 第2部分：城市轨道交通.pdf](https://github.com/railmapgen/rmg-palette/files/13817698/DB12T.454.2-2023.2.pdf)

无水印版本

**Comment by Charlis-Wong** [comment]
您好，請問您的意思是怎麼提交Palette範本嗎？

**Comment by HatsuneMikuZD** [comment]
@Charlis-Wong 就是那个上头那个公开文档里是潘通色和CMYK值，但是调色板要的是RGB值，不知道怎么弄调色板里

**Comment by wongchito** [comment]
Hi @HatsuneMikuZD ,

閣下可以將「使用Pantone」設定為「是」，然後輸入Pantone色號。系統將自動調用官方API取得RGB顏色。

![image](https://github.com/railmapgen/rmg-palette/assets/9390786/6e2bee47-39d9-474f-9036-e49fb13df0f6)

**Comment by HatsuneMikuZD** [comment]
@wongchito 是输入Pantone 288C还是288C，但是我输入潘通代码之后，它自己就消失了，颜色也没有变化

**Comment by wongchito** [comment]
> @wongchito 是输入Pantone 288C还是288C，但是我输入潘通代码之后，它自己就消失了，颜色也没有变化

288 C

數字和字母之間存在一個空格

**Comment by HatsuneMikuZD** [comment]
@wongchito 谢了

**Comment by wongchito** [comment]
Completed by #1063
