### ISSUE TITLE
Resources: New palettes of Liuzhou

### ISSUE THREAD

**Issue by liuzhou0925** [railmapgen/rmg-palette#1038]
**Data source:** 3. Code of design standard published by the government or legislature

**Reference link:** http://en.wikipedia org

**Justification:** 我的变更为加入中国广西柳州市的地图以便生成它的铁路地图

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"Liuzhou","country":"CN","name":{"en":"Liuzhou","zh-Hans":"柳州","zh-Hant":"柳州"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"lz1","colour":"#ff9900","fg":"#fff","name":{"en":"line 1","zh-Hans":"一号线","zh-Hant":"一号线"}},{"id":"lz2","colour":"#ff0000","fg":"#fff","name":{"en":"line 2","zh-Hans":"2号线","zh-Hant":"2号线"}},{"id":"lz3","colour":"#4a86e8","fg":"#fff","name":{"en":"line 3","zh-Hans":"3号线","zh-Hant":"3号线"}},{"id":"lz4","colour":"#44ff0d","fg":"#fff","name":{"en":"line 4","zh-Hans":"4号线","zh-Hant":"4号线"}},{"id":"lz5","colour":"#9900ff","fg":"#fff","name":{"en":"line 5","zh-Hans":"5号线","zh-Hant":"5号线"}}]</details>

**Comment by wongchito** [comment]
Hi @liuzhou0925 ,

請提供直達「政府或立法機關發佈的設計守則」連結，以便我們核實數據。多謝！
