### ISSUE TITLE
Resources: New palettes of Guiyang

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-palette#1046]
**Data source:** 2. 官方社交媒体发布的设计标准

**Reference link:** https://mi.mbd.baidu.com/r/1cmadGfjKko?f=cp&u=3653c62d2da06f6a

**Justification:** 更新3号线及S1线颜色，以及调整1号线和2号线颜色。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"guiyang","country":"CN","name":{"en":"Guiyang","ko":"구이양","zh-Hans":"贵阳","zh-Hant":"貴陽"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"gy1","colour":"#7ab74b","fg":"#fff","name":{"en":"Line 1","ko":"1호선","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"gy2","colour":"#121e59","fg":"#fff","name":{"en":"Line 2","ko":"2호선","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"gy3","colour":"#ff0000","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線","ko":"3호선"}},{"id":"gys1","colour":"#720160","fg":"#fff","name":{"en":"Line S1","zh-Hans":"S1线","zh-Hant":"S1線","ko":"S1선"}}]</details>

**Comment by Windows-Taskmgr** [comment]
您好，我们暂不支持来自百度的来源，请您更换来源提交，感谢您的贡献。
