### ISSUE TITLE
Resources: New palettes of Changchun

### ISSUE THREAD

**Issue by Xiaoshuabc** [railmapgen/rmg-palette#1051]
**Data source:** 9. 其他（请于下方注明）

**Reference link:** https://baike.baidu.com/starmap/view?nodeId=5c29a1b90b6f7af14d877cef&lemmaTitle=%E9%95%BF%E6%98%A5%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A3%E5%8F%B7%E7%BA%BF&lemmaId=10403286&starMapFrom=lemma_relation_starMap&fromModule=lemma_starMap

**Justification:** 百度百科上的百科星图：长春轨道交通线路上的5,6,7,9号线已更换颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"changchun","country":"CN","name":{"en":"Changchun","zh-Hans":"长春","zh-Hant":"長春"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"cc1","colour":"#e50012","fg":"#fff","name":{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"cc2","colour":"#1a4695","fg":"#fff","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"cc3","colour":"#009844","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"cc4","colour":"#684184","fg":"#fff","name":{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號線"}},{"id":"cc5","colour":"#a88546","fg":"#fff","name":{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號線"}},{"id":"cc6","colour":"#e48aa4","fg":"#fff","name":{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線"}},{"id":"cc7","colour":"#ab5797","fg":"#fff","name":{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號線"}},{"id":"cc8","colour":"#4bb4b8","fg":"#fff","name":{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號線"}},{"id":"cc9","colour":"#2e79ba","fg":"#fff","name":{"en":"Line 9","zh-Hans":"9号线","zh-Hant":"9號線"}}]</details>

**Comment by Windows-Taskmgr** [comment]
您好，我们暂不支持来自百度百科的来源，请您更换来源提交，感谢您的贡献。

**Comment by langonginc** [comment]
Close as no response.
