### ISSUE TITLE
Resources: New palettes of Hong Kong

### ISSUE THREAD

**Issue by pokOSlanx** [railmapgen/rmg-palette#1056]
**Data source:** 9. 其他（请于下方注明）

**Reference link:** https://hkrail.fandom.com/

**Justification:** 现已停止运营的路线资料或规划中的路线：其他-https://hkrail.fandom.com/（及其参考资料） / 九广铁路-https://zh.wikipedia.org/wiki/%E4%B9%9D%E5%BB%A3%E9%90%B5%E8%B7%AF
正在运营的路线资料：重铁-https://www.mtr.com.hk/ch/customer/services/system_map.html / 轻铁-https://www.mtr.com.hk/ch/customer/services/routemap_index.html

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"hongkong","country":"CN","name":{"en":"Hong Kong","zh-Hans":"香港","zh-Hant":"香港"}}</details>

<details repo="rmg-palette" type="city">{"id":"hongkong","country":"CN","name":{"en":"Hong Kong","zh-Hans":"香港","zh-Hant":"香港"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"ktl","colour":"#01a040","fg":"#fff","name":{"en":"Kwun Tong Line","zh-Hans":"观塘线","zh-Hant":"觀塘綫"}},{"id":"twl","colour":"#e60013","fg":"#fff","name":{"en":"Tsuen Wan Line","zh-Hans":"荃湾线","zh-Hant":"荃灣綫"}},{"id":"isl","colour":"#0275c2","fg":"#fff","name":{"en":"Island Line","zh-Hans":"港岛线","zh-Hant":"港島綫"}},{"id":"tkl","colour":"#7e3c92","fg":"#fff","name":{"en":"Tseung Kwan O Line","zh-Hans":"将军澳线","zh-Hant":"將軍澳綫"}},{"id":"tcl","colour":"#f3982c","fg":"#fff","name":{"en":"Tung Chung Line","zh-Hans":"东涌线","zh-Hant":"東涌綫"}},{"id":"ael","colour":"#00888d","fg":"#fff","name":{"en":"Airport Express","zh-Hans":"机场快线 (机铁)","zh-Hant":"機場快綫 (機鐵)"}},{"id":"erl","colour":"#5db7e8","fg":"#fff","name":{"en":"East Rail Line","zh-Hans":"东铁线","zh-Hant":"東鐵綫"}},{"id":"tml","colour":"#9c2e00","fg":"#fff","name":{"en":"Tuen Ma Line","zh-Hans":"屯马线","zh-Hant":"屯馬綫"}},{"id":"drl","colour":"#e66ea5","fg":"#fff","name":{"en":"Disneyland Resort Line","zh-Hans":"迪士尼线","zh-Hant":"迪士尼綫"}},{"id":"sil","colour":"#cad301","fg":"#fff","name":{"en":"South Island Line","zh-Hans":"南港岛线","zh-Hant":"南港島綫"}},{"id":"hsr","colour":"#9d948b","fg":"#fff","name":{"en":"High Speed Rail","zh-Hans":"高速铁路 (高铁)","zh-Hant":"高速鐵路 (高鐵)"}},{"id":"sz","colour":"#c2c4c6","fg":"#fff","name":{"en":"Shenzhen Metro Network","zh-Hans":"深圳地铁网络","zh-Hant":"深圳地鐵網絡"}},{"id":"lr","colour":"#dbb301","fg":"#fff","name":{"en":"Light Rail","zh-Hans":"轻铁 (港铁路线图)","zh-Hant":"輕鐵 (港鐵路綫圖)"}},{"id":"lr505","colour":"#da2127","fg":"#fff","name":{"en":"Light Rail Route 505","zh-Hans":"轻铁505线","zh-Hant":"輕鐵505綫"}},{"id":"lr507","colour":"#00a64e","fg":"#fff","name":{"en":"Light Rail Route 507","zh-Hans":"轻铁507线","zh-Hant":"輕鐵507綫"}},{"id":"lr610","colour":"#541911","fg":"#fff","name":{"en":"Light Rail Route 610","zh-Hans":"轻铁610线","zh-Hant":"輕鐵610綫"}},{"id":"lr614","colour":"#16c0f2","fg":"#fff","name":{"en":"Light Rail Route 614","zh-Hans":"轻铁614线","zh-Hant":"輕鐵614綫"}},{"id":"lr614p","colour":"#f3858d","fg":"#fff","name":{"en":"Light Rail Route 614P","zh-Hans":"轻铁614P线","zh-Hant":"輕鐵614P綫"}},{"id":"lr615","colour":"#ffdc00","fg":"#000","name":{"en":"Light Rail Route 615","zh-Hans":"轻铁615线","zh-Hant":"輕鐵615綫"}},{"id":"lr615p","colour":"#016584","fg":"#fff","name":{"en":"Light Rail Route 615P","zh-Hans":"轻铁615P线","zh-Hant":"輕鐵615P綫"}},{"id":"lr705","colour":"#70bf44","fg":"#fff","name":{"en":"Light Rail Route 705 (Tin Shui Wai Circular)","zh-Hans":"轻铁705线 (天水围循环线)","zh-Hant":"輕鐵705綫 (天水圍循環綫)"}},{"id":"lr706","colour":"#b278b5","fg":"#fff","name":{"en":"Light Rail Route 706 (Tin Shui Wai Circular)","zh-Hans":"轻铁706线 (天水围循环线)","zh-Hant":"輕鐵706綫 (天水圍循環綫)"}},{"id":"lr751","colour":"#f58220","fg":"#fff","name":{"en":"Light Rail Route 751","zh-Hans":"轻铁751线","zh-Hant":"輕鐵751綫"}},{"id":"lr761p","colour":"#6e2c91","fg":"#fff","name":{"en":"Light Rail Route 761P","zh-Hans":"轻铁761P线","zh-Hant":"輕鐵761P綫"}},{"id":"kcrlr","colour":"#f48933","fg":"#fff","name":{"en":"KCR Light Rail","zh-Hans":"九广轻铁","zh-Hant":"九廣輕鐵"}},{"id":"nol","colour":"#b0008e","fg":"#fff","name":{"en":"Northern Link","zh-Hans":"北环线","zh-Hant":"北環綫"}},{"id":"ekl","colour":"#009758","fg":"#fff","name":{"en":"East Kowloon Line","zh-Hans":"东九龙线","zh-Hant":"東九龍綫"}},{"id":"silw","colour":"#9182c2","fg":"#fff","name":{"en":"South Island Line (West)","zh-Hans":"南港岛线（西段）","zh-Hant":"南港島綫（西段）"}},{"id":"mis","colour":"#ff0000","fg":"#fff","name":{"en":"Modified Initial System","zh-Hans":"修正早期系统","zh-Hant":"修正早期系統"}},{"id":"wrl","colour":"#b6008d","fg":"#fff","name":{"en":"West Rail Line","zh-Hans":"西铁线","zh-Hant":"西鐵綫"}},{"id":"kcrer","colour":"#08498e","fg":"#fff","name":{"en":"KCR East Rail","zh-Hans":"九广东铁","zh-Hant":"九廣東鐵"}},{"id":"kcrwr","colour":"#a3238f","fg":"#fff","name":{"en":"KCR West Rail","zh-Hans":"九广西铁","zh-Hant":"九廣西鐵"}},{"id":"mosr","colour":"#761e10","fg":"#fff","name":{"en":"Ma On Shan Rail","zh-Hans":"马鞍山铁路","zh-Hant":"馬鞍山鐵路"}}]</details>

**Comment by pokOSlanx** [comment]
提交了新版本
此版本包含了**輕鐵/規劃中/曾經運營**的路綫

提交了新版本
此版本包含了**轻铁/规划中/曾经运营**的路线

**Comment by wongchito** [comment]
Hi @pokOSlanx ,

經檢查，閣下所提交的數據存在以下問題：
- 重鐵網絡中所選取的顏色，與PDF檔案不符。請使用sRGB十六進位顏色
- 請勿變更現存路綫的ID，以保持向後相容性
- 請勿移除舊有路綫，如九廣東鐵等

然而閣下提供了極佳品質的顏色來源，如閣下未在一個月內提交修正，我們將使用該來源自行更新調色盤。多謝！

**Comment by wongchito** [comment]
![image](https://github.com/railmapgen/rmg-palette/assets/9390786/c527499c-d4bb-459b-8754-5672f1e25ae3)

**Comment by pokOSlanx** [comment]
> ![image](https://private-user-images.githubusercontent.com/9390786/296113877-c527499c-d4bb-459b-8754-5672f1e25ae3.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwMjg5ODcsIm5iZiI6MTcwNTAyODY4NywicGF0aCI6Ii85MzkwNzg2LzI5NjExMzg3Ny1jNTI3NDk5Yy1kNGJiLTQ1OWItODc1NC01NjcyZjFlMjVhZTMuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDAzMDQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMWFlN2JhMGFkNGJiNzgxZTEyNjYxYzUyMTg1MGRjOTU1OWJjNGFlOGM1NjEwYzU0Y2UxZmIzZGVmOGIxNzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QDPNRe6PzsNND2HasLB7FqKnM47FY9h8w3HfVz50Qwc)

已提交新嘅修正
已提交新的修正
