### ISSUE TITLE
资源：鸭子的新调色板

### ISSUE THREAD

**Issue by RyanZhangZ** [railmapgen/rmg-palette#1058]
**Data source:** 9. 其他（请于下方注明）

**Reference link:** https://duckingcraft.com

**Justification:** 娱乐用途，无其他

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{"id":"duckingcraft","name":{"en":"Duckingcraft","zh-Hans":"鸭子市","zh-Hant":"鸭子市"},"language":"zh-Hans"}</details>

<details repo="rmg-palette" type="city">{"id":"duck","country":"duckingcraft","name":{"en":"duck","zh-Hans":"鸭子市","zh-Hant":"鸭子市"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"duck1","colour":"#ff2600","fg":"#fff","name":{"en":"line 1","zh-Hans":"1号线","zh-Hant":"鸭子市"}}]</details>

**Comment by Windows-Taskmgr** [comment]
您好，RMG调色板不是用来搞笑的，请不要把城市改成鸭子糊弄我们，谢谢。
