### ISSUE TITLE
Resources: New palettes of Busan

### ISSUE THREAD

**Issue by t-chai** [railmapgen/rmg-palette#1073]
**Data source:** 9. 其他（请于下方注明）

**Reference link:** https://namu.wiki/w/%EC%96%91%EC%82%B0%20%EB%8F%84%EC%8B%9C%EC%B2%A0%EB%8F%84

**Justification:** 新增梁山都市铁道，数据、色号来自韩国当地维基百科网站

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"busan","country":"KR","name":{"en":"Busan","ko":"부산","zh-Hans":"釜山","zh-Hant":"釜山"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"bu1","colour":"#f06a00","fg":"#000","name":{"en":"Line 1","ko":"1호선","zh-Hans":"1号线","zh-Hant":"1號缐"}},{"id":"bu2","colour":"#81bf48","fg":"#000","name":{"en":"Line 2","ko":"2호선","zh-Hans":"2号线","zh-Hant":"2號缐"}},{"id":"bu3","colour":"#bb8c00","fg":"#000","name":{"en":"Line 3","ko":"3호선","zh-Hans":"3号线","zh-Hant":"3號缐"}},{"id":"bu4","colour":"#217dcb","fg":"#000","name":{"en":"Line 4","ko":"4호선","zh-Hans":"4号线","zh-Hant":"4號缐"}},{"id":"bu5","colour":"#ff007a","fg":"#000","name":{"en":"Line 5","ko":"5호선","zh-Hans":"5号线","zh-Hant":"5號缐"}},{"id":"bugl","colour":"#875cac","fg":"#fff","name":{"en":"Busan-Gimhae LRT","ko":"부산김해경전철","zh-Hans":"釜山金海轻电铁","zh-Hant":"釜山金海輕電鐵"}},{"id":"budh","colour":"#0054a6","fg":"#fff","name":{"en":"Donghae Line","ko":"동해선","zh-Hans":"东海线","zh-Hant":"東海線"}},{"id":"ym","colour":"#a2272a","fg":"#fff","name":{"en":"Yangsan Metro","zh-Hans":"梁山都市铁道","zh-Hant":"梁山都市鐵道","ko":"양산도시철도"}}]</details>

**Comment by DQB061204** [comment]
您好 您所提供的链接似乎不是维基百科或者釜山地铁的官网 （非官方人员建议）

**Comment by t-chai** [comment]
> 您好 您所提供的链接似乎不是维基百科或者釜山地铁的官网 （非官方人员建议）

您好，这个是韩国当地的维基百科，较维基百科信息更全，更新更及时，虽然不是维基百科，但也有一定参考价值

**Comment by DQB061204** [comment]
> > 您好 您所提供的链接似乎不是维基百科或者釜山地铁的官网 （非官方人员建议）
> 
> 您好，这个是韩国当地的维基百科，较维基百科信息更全，更新更及时，虽然不是维基百科，但也有一定参考价值

您好 我访问了官网 显示出错了 我会尽量劝说官方工作人员采用您的链接的

**Comment by wongchito** [comment]
Hi @t-chai ,

感謝閣下的貢獻！
