### ISSUE TITLE
Resources: New palettes of Central Area (Tokai)

### ISSUE THREAD

**Issue by zeekliu** [railmapgen/rmg-palette#1079]
**Data source:** 8. 维基百科

**Reference link:** https://ja.wikipedia.org/wiki/%E6%9D%B1%E6%B5%B7%E6%97%85%E5%AE%A2%E9%89%84%E9%81%93#%E8%B7%AF%E7%B7%9A

**Justification:** 补充现有调色板缺失的内容。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"jrtokai","country":"JP","name":{"en":"Central Area (Tokai)","zh-Hans":"中部地方（东海）","ja":"中部地方（東海）","zh-Hant":"中部地方（東海）"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"ca","colour":"#f57615","fg":"#fff","name":{"en":"Tōkaidō Main Line","zh-Hans":"东海道本线","ja":"東海道本線","zh-Hant":"東海道本線"}},{"id":"cb","colour":"#40743c","fg":"#fff","name":{"en":"Gotemba Line","zh-Hans":"御殿场线","ja":"御殿場線","zh-Hant":"御殿場線"}},{"id":"cc","colour":"#6f2d98","fg":"#fff","name":{"en":"Minobu Line","zh-Hans":"身延线","ja":"身延線","zh-Hant":"身延線"}},{"id":"cd","colour":"#75a2db","fg":"#fff","name":{"en":"Iida Line","zh-Hans":"饭田线","ja":"飯田線","zh-Hant":"飯田線"}},{"id":"ce","colour":"#83502f","fg":"#fff","name":{"en":"Taketoyo Line","zh-Hans":"武丰线","ja":"武豊線","zh-Hant":"武豐線"}},{"id":"cf","colour":"#3b6c9c","fg":"#fff","name":{"en":"Chūō Main Line","zh-Hans":"中央本线","ja":"中央本線","zh-Hant":"中央本線"}},{"id":"cg","colour":"#9c1618","fg":"#fff","name":{"en":"Takayama Main Line","zh-Hans":"高山本线","ja":"高山本線","zh-Hant":"高山本線"}},{"id":"ci","colour":"#bfba2f","fg":"#fff","name":{"en":"Taita Line","zh-Hans":"太多线","ja":"太多線","zh-Hant":"太多線"}},{"id":"cj","colour":"#3dbc87","fg":"#fff","name":{"en":"Kansai Main Line","zh-Hans":"关西本线","ja":"関西本線","zh-Hant":"關西本線"}}]</details>

**Comment by DQB061204** [comment]
这个 没有使用官方的内容吧。。。

**Comment by Swiftiecott** [comment]
> 这个 没有使用官方的内容吧。。。

您好，目前除官方来源外，维基百科来源也是支持的（即使维基百科来源与官方来源颜色有误差）。
