### ISSUE TITLE
Resources: New palettes of Jinan

### ISSUE THREAD

**Issue by CSZ7943** [railmapgen/rmg-palette#1081]
**Data source:** 9. 其他（请于下方注明）

**Reference link:** https://baike.baidu.com/

**Justification:** 修改4号线，增加5，6，7，8，9号线标志色，内容来源于百度

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"jinan","country":"CN","name":{"en":"Jinan","zh-Hans":"济南","zh-Hant":"濟南"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"jn1","colour":"#BE1FA1","fg":"#fff","name":{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"jn2","colour":"#FFB620","fg":"#fff","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"jn3","colour":"#0073CE","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"jn4","colour":"#ca0106","fg":"#fff","name":{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號線"}},{"id":"jn5","colour":"#a0c3dc","fg":"#fff","name":{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號線"}},{"id":"jn6","colour":"#02772f","fg":"#fff","name":{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線"}},{"id":"jn7","colour":"#f07a01","fg":"#fff","name":{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號線"}},{"id":"jn8","colour":"#663100","fg":"#fff","name":{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號線"}},{"id":"jn9","colour":"#970296","fg":"#fff","name":{"en":"Line 9","zh-Hans":"9号线","zh-Hant":"9號線"}}]</details>

**Comment by linchen1965** [comment]
Hi @CSZ7943 ,

很抱歉我们不认可原始来源为百度百科的资讯，请使用其他来源，多谢！
