### ISSUE TITLE
Resources: New palettes of Guiyang

### ISSUE THREAD

**Issue by G9913** [railmapgen/rmg-palette#1083]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Data source:** 4. 内部流出的来源

**Reference link:** http://gongzhongfuwu.guiyang3haoxian.cn/app/index.html#/travel

**Justification:** 新增贵阳地铁3号线标识色：中国红

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"guiyang","country":"CN","name":{"en":"Guiyang","ko":"구이양","zh-Hans":"贵阳","zh-Hant":"貴陽"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"gy1","colour":"#259b24","fg":"#fff","name":{"en":"Line 1","ko":"1호선","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"gy2","colour":"#005bac","fg":"#fff","name":{"en":"Line 2","ko":"2호선","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"gy3","colour":"#ff0000","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}}]</details>

**Comment by linchen1965** [comment]
Hi @G9913，
由于您提供的3号线颜色（ff0000）与来源链接中的3号线颜色（F02828）存在较大差异，且当前调色板中已有更加准确、完整的调色板存在，因此我们不接受此次更新。感谢关注！
