### ISSUE TITLE
Resources: New palettes of Guiyang

### ISSUE THREAD

**Issue by Jinkelavicii** [railmapgen/rmg-palette#1091]
**Data source:** 7. 从有损压缩的图片（如 JPG）提取的颜色

**Reference link:** https://baike.baidu.com/item/%E8%B4%B5%E9%98%B3%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A3%E5%8F%B7%E7%BA%BF/16024214; https://baike.baidu.com/item/%E8%B4%B5%E9%98%B3%E5%9F%8E%E5%B8%82%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9AS1%E7%BA%BF/20313645

**Justification:** 添加3号线及S1线标识色（取自网页上的图片，可能有偏差）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"guiyang","country":"CN","name":{"en":"Guiyang","ko":"구이양","zh-Hans":"贵阳","zh-Hant":"貴陽"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"gy1","colour":"#259b24","fg":"#fff","name":{"en":"Line 1","ko":"1호선","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"gy2","colour":"#005bac","fg":"#fff","name":{"en":"Line 2","ko":"2호선","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"gy3","colour":"#f72120","fg":"#fff","name":{"en":"Line 3","ko":"3호선","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"gys1","colour":"#a241b4","fg":"#fff","name":{"en":"Line S1","ko":"S1선","zh-Hans":"S1线","zh-Hant":"S1線"}}]</details>

**Comment by wongchito** [comment]
Hi @Jinkelavicii ,

我們不認可**原始**來源為百度百科的資訊，請使用其他來源，多謝！
