### ISSUE TITLE
Resources: New palettes of Taizhou (Zhejiang)

### ISSUE THREAD

**Issue by PomeloOfficial** [railmapgen/rmg-palette#1102]
**Data source:** 7. 从有损压缩的图片（如 JPG）提取的颜色

**Reference link:** 
https://mp.weixin.qq.com/s/9RigboeDo-xnaJHPA0i50A
https://mmbiz.qpic.cn/mmbiz_jpg/3sT4025BlscxUyqPmkzXHiaicsLjNnk4NSfA6wRWePGL8zKRbPmrJD8xfXMKg7xUVOibqWHxCEicd1Jf8zibGPf5Bqw/640?wx_fmt=jpeg

**Justification:** 新增台州轨道交通S1线配色。因为找不到任何相关的设计标准，只能从官网线路图中选取比较相近的颜色。
Added the palette of Taizhou Rail Transit Line S1. Due to the lack of relevant design standards, I chose a color that was closer.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"taizhou","country":"CN","name":{"en":"Taizhou","zh-Hans":"台州","zh-Hant":"台州"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"tzs1","colour":"#0c9cdc","fg":"#fff","name":{"en":"Line S1","zh-Hans":"S1线","zh-Hant":"S1綫"}}]</details>

**Comment by wongchito** [comment]
Hi @PomeloOfficial ,

感謝閣下的貢獻！
