### ISSUE TITLE
Resources: New palettes of Beijing

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmg-palette#1104]
**Data source:** 9. 其他（请于下方注明）

**Reference link:** https://www.bjsubway.com/station/xltzs/

**Justification:** 从北京地铁官方网站PNG格式线路图中提取；线路排序按照官方线路图图例顺序

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"beijing","country":"CN","name":{"en":"Beijing","zh-Hans":"北京","zh-Hant":"北京"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"bj1","colour":"#c13931","fg":"#fff","name":{"en":"Line 1/Batong Line","zh-Hans":"1号线/八通线","zh-Hant":"1號線/八通線"}},{"id":"bj2","colour":"#146097","fg":"#fff","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"bj3","colour":"#d90627","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"bj4","colour":"#008e9c","fg":"#fff","name":{"en":"Line 4/Daxing Line","zh-Hans":"4号线/大兴线","zh-Hant":"4號線/大興線"}},{"id":"bj5","colour":"#a61c80","fg":"#fff","name":{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號線"}},{"id":"bj6","colour":"#d29708","fg":"#fff","name":{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線"}},{"id":"bj7","colour":"#fac671","fg":"#000","name":{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號線"}},{"id":"bj8","colour":"#009b6b","fg":"#fff","name":{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號線"}},{"id":"bj9","colour":"#8ec31f","fg":"#000","name":{"en":"Line 9","zh-Hans":"9号线","zh-Hant":"9號線"}},{"id":"bj10","colour":"#009bc0","fg":"#fff","name":{"en":"Line 10","zh-Hans":"10号线","zh-Hant":"10號線"}},{"id":"bj11","colour":"#ed796a","fg":"#fff","name":{"en":"Line 11","zh-Hans":"11号线","zh-Hant":"11號線"}},{"id":"bj12","colour":"#9c4f01","fg":"#fff","name":{"en":"Line 12","zh-Hans":"12号线","zh-Hant":"12號線"}},{"id":"bj13","colour":"#f6e613","fg":"#000","name":{"en":"Line 13","zh-Hans":"13号线","zh-Hant":"13號線"}},{"id":"bj14","colour":"#d5a7a1","fg":"#000","name":{"en":"Line 14","zh-Hans":"14号线","zh-Hant":"14號線"}},{"id":"bj15","colour":"#6a357e","fg":"#fff","name":{"en":"Line 15","zh-Hans":"15号线","zh-Hant":"15號線"}},{"id":"bj16","colour":"#76a22d","fg":"#fff","name":{"en":"Line 16","zh-Hans":"16号线","zh-Hant":"16號線"}},{"id":"bj17","colour":"#00A9A9","fg":"#fff","name":{"en":"Line 17","zh-Hans":"17号线","zh-Hant":"17號線"}},{"id":"bj19","colour":"#D6ABC1","fg":"#000","name":{"en":"Line 19","zh-Hans":"19号线","zh-Hant":"19號線"}},{"id":"bj22","colour":"#f4c1ca","fg":"#000","name":{"en":"Line 22 (Pinggu Line)","zh-Hans":"22号线（平谷线）","zh-Hant":"22號線（平谷線）"}},{"id":"bj28","colour":"#476205","fg":"#fff","name":{"en":"Line 28","zh-Hans":"28号线","zh-Hant":"28號線"}},{"id":"bj25fs","colour":"#e36022","fg":"#fff","name":{"en":"Fangshan Line/Yanfang Line","zh-Hans":"房山线/燕房线","zh-Hant":"房山線/燕房線"}},{"id":"bj27cp","colour":"#dd82b3","fg":"#000","name":{"en":"Changping Line","zh-Hans":"昌平线","zh-Hant":"昌平線"}},{"id":"bj24yz","colour":"#e40077","fg":"#fff","name":{"en":"Yizhuang Line","zh-Hans":"亦庄线","zh-Hant":"亦莊線"}},{"id":"bj26s1","colour":"#b25a21","fg":"#fff","name":{"en":"Line S1","zh-Hans":"S1线","zh-Hant":"S1線"}},{"id":"btxj","colour":"#e6061a","fg":"#fff","name":{"en":"Xijiao Line","zh-Hans":"西郊线","zh-Hant":"西郊線"}},{"id":"btt1","colour":"#e6061a","fg":"#fff","name":{"en":"Yizhuang T1 Line","zh-Hans":"亦庄T1线","zh-Hant":"亦莊T1線"}},{"id":"bj34sj","colour":"#a39bbb","fg":"#000","name":{"en":"Capital Airport Express","zh-Hans":"首都机场线","zh-Hant":"首都機場線"}},{"id":"bj35dj","colour":"#034ba0","fg":"#fff","name":{"en":"Daxing Airport Express","zh-Hans":"大兴机场线","zh-Hant":"大興機場線"}}]</details>

**Comment by Swiftiecott** [comment]
您好，抱歉久等了。

感谢您对本项目的支持。经检查您们目前所提交的线路颜色均已在可接受的误差范围内。

不过由于北京地铁官方的原因，目前存储于颜色库中的北京地铁颜色（来自于北京地铁官方的html格式互动网站，因此各线路色号均可通过浏览器自带的开发者模式查到而无需截图提取）和北京地铁官方提供下载的png格式线路图也存在着各线路颜色不同的情况。

考虑到该情况，因此我们希望最终是采用更新后的颜色方案还是保留当前的颜色方案由您来决定，谢谢。

**Comment by Minwtraft** [comment]
> 您好，抱歉久等了。
> 
> 感谢您对本项目的支持。经检查您们目前所提交的线路颜色均已在可接受的误差范围内。
> 
> 不过由于北京地铁官方的原因，目前存储于颜色库中的北京地铁颜色（来自于北京地铁官方的html格式互动网站，因此各线路色号均可通过浏览器自带的开发者模式查到而无需截图提取）和北京地铁官方提供下载的png格式线路图也存在着各线路颜色不同的情况。
> 
> 考虑到该情况，因此我们希望最终是采用更新后的颜色方案还是保留当前的颜色方案由您来决定，谢谢。

您好！

感谢您对颜色方案的认可。我个人仍希望该issue中的颜色方案能被采纳。

若该颜色方案能投入使用，我将再次感谢！

**Comment by Windows-Taskmgr** [comment]
感谢您的贡献，我们将汇入您的作品至调色板中。
