### ISSUE TITLE
Resources: New palettes of Qingdao

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmg-palette#1106]
**Data source:** 4. 内部流出的来源

**Reference link:** https://weibo.com/5124782558/IBbR389tI

**Justification:** 来自微博@哆啦Joe 一手资料

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"qingdao","country":"CN","name":{"en":"Qingdao","zh-Hans":"青岛","zh-Hant":"青島"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"qd1","colour":"#f7b000","fg":"#fff","name":{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"qd2","colour":"#c32a05","fg":"#fff","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"qd3","colour":"#006dbb","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"qd4","colour":"#00763c","fg":"#fff","name":{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號線"}},{"id":"qd5","colour":"#9e1a96","fg":"#fff","name":{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號線"}},{"id":"qd6","colour":"#6ca3d8","fg":"#fff","name":{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線"}},{"id":"qd7","colour":"#AD96DC","fg":"#fff","name":{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號線"}},{"id":"qd8","colour":"#e74893","fg":"#fff","name":{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號線"}},{"id":"qd9","colour":"#62a60a","fg":"#fff","name":{"en":"Line 9","zh-Hans":"9号线","zh-Hant":"9號線"}},{"id":"qd10","colour":"#b46e00","fg":"#fff","name":{"en":"Line 10","zh-Hans":"10号线","zh-Hant":"10號線"}},{"id":"qd11","colour":"#304299","fg":"#fff","name":{"en":"Line 11","zh-Hans":"11号线","zh-Hant":"11號線"}},{"id":"qd12","colour":"#8246ac","fg":"#fff","name":{"en":"Line 12","zh-Hans":"12号线","zh-Hant":"12號線"}},{"id":"qd13","colour":"#009c86","fg":"#fff","name":{"en":"Line 13","zh-Hans":"13号线","zh-Hant":"13號線"}},{"id":"qd14","colour":"#ff5859","fg":"#fff","name":{"en":"Line 14","zh-Hans":"14号线","zh-Hant":"14號線"}},{"id":"qd15","colour":"#f3a9b3","fg":"#fff","name":{"en":"Line 15","zh-Hans":"15号线","zh-Hant":"15號線"}},{"id":"qd16","colour":"#71dbd5","fg":"#fff","name":{"en":"Line 16","zh-Hans":"16号线","zh-Hant":"16號線"}}]</details>

**Comment by wongchito** [comment]
Hi @Minwtraft ,

我們無法確認閣下提供之微博內容來源是否有效，請問是否有關於來源或微博作者的更多資訊？

**Comment by Minwtraft** [comment]
@wongchito 您好！
以下链接中的文章正文末尾有标准颜色图片信息（文章发布者即为微博作者），从旧到新有3个版本
https://mp.weixin.qq.com/s/Q53hrwbuZZ1YaTaVIYfKNQ
颜色信息来源于青岛市青岛地铁展示馆（百度地图：https://j.map.baidu.com/39/8T4c）
以下为在展示馆内拍摄的照片
![青岛地铁展示馆--地铁色彩](https://github.com/railmapgen/rmg-palette/assets/137034903/6b5fea6b-dc0b-4764-b2b6-3eb147fd8a91)

**Comment by wongchito** [comment]
Hi @Minwtraft ,

感謝閣下的補充。
