### ISSUE TITLE
Resources: New palettes of Riyadh

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmg-palette#111]
**Justification:** (http://riyadhmetro.sa/)http://[riyadhmetro.sa](http://riyadhmetro.sa/)/

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "SA",
    "name": {
        "en": "Saudi Arabia",
        "ar": "المملكة العربية السعودية",
        "zh-Hans": "沙特阿拉伯",
        "zh-Hant": "沙特阿拉伯"
    }
}</details>

<details repo="rmg-palette" type="city">{
    "id": "riyadh",
    "country": "SA",
    "name": {
        "en": "Riyadh",
        "ar": "الرياض",
        "zh-Hans": "利雅得",
        "zh-Hant": "利雅得"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "ry1",
        "colour": "#2bb4e5",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "ar": "1خط ",
            "zh-Hans": "1号线",
            "zh-Hant": "1號缐"
        }
    },
    {
        "id": "ry2",
        "colour": "#d52f45",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "ar": "2خط ",
            "zh-Hans": "2号线",
            "zh-Hant": "2號缐"
        }
    },
    {
        "id": "ry3",
        "colour": "#ed7127",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "ar": "3خط ",
            "zh-Hans": "3号线",
            "zh-Hant": "3號缐"
        }
    },
    {
        "id": "ry4",
        "colour": "#e4d611",
        "fg": "#000",
        "name": {
            "en": "Line 4",
            "ar": "4خط ",
            "zh-Hans": "4号线",
            "zh-Hant": "4號缐"
        }
    },
    {
        "id": "ry5",
        "colour": "#52a531",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "ar": "5خط ",
            "zh-Hans": "5号线",
            "zh-Hant": "5號缐"
        }
    },
    {
        "id": "ry6",
        "colour": "#981980",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "ar": "6خط ",
            "zh-Hans": "6号线",
            "zh-Hant": "6號缐"
        }
    }
]</details>

**Comment by wongchito** [comment]
Traditional Chinese names are being fixed in #113.
