### ISSUE TITLE
Let users confirm if they want to clear recently used colors in Palette Picker

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmg-palette#1112]
This can prevent anyone from accidentally removing all recently used colors.

**Comment by wongchito** [comment]
A second confirmation ('Clear all' button) is required when clearing all history (after clicking 'Clear' button). 

<img width="539" alt="image" src="https://github.com/user-attachments/assets/d6d36def-fa9e-4b85-a087-0a83abc1ec3a">
