### ISSUE TITLE
单一清除调色板“最近使用”的颜色

### ISSUE THREAD

**Issue by Windows-Taskmgr** [railmapgen/rmg-palette#1113]
这可以使某一个不需要的颜色从“最近使用”里删除（而不需全部删除）。

**Comment by wongchito** [comment]
Added bin icon in each recently used theme. They're visible when you click 'Clear' button and enter the clearing mode.

<img width="539" alt="image" src="https://github.com/user-attachments/assets/0f414e83-2793-47cd-a72c-60655e9beab5">
