### ISSUE TITLE
Resources: New palettes of Shenzhen

### ISSUE THREAD

**Issue by D134679** [railmapgen/rmg-palette#1121]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Data source:** 4. 内部流出的来源

**Reference link:** https://www.ditiee.com/forum.php?mod=viewthread&tid=15174&extra=page%3D1%26filter%3Dtypeid%26typeid%3D646

**Justification:** 内部流出的深圳地铁远期标识色方案，上传更新后，画图时可以更加方便。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"shenzhen","country":"CN","name":{"en":"Shenzhen","zh-Hans":"深圳","zh-Hant":"深圳"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"sz1","colour":"#00B140","fg":"#fff","name":{"en":"Line 1 (Luobao Line)","zh-Hans":"1号线（罗宝线）","zh-Hant":"1號線（羅寶線）"}},{"id":"sz2","colour":"#B94700","fg":"#fff","name":{"en":"Line 2 (Shekou Line)","zh-Hans":"2号线（蛇口线）","zh-Hant":"2號線（蛇口線）"}},{"id":"sz3","colour":"#00A9E0","fg":"#fff","name":{"en":"Line 3 (Longgang Line)","zh-Hans":"3号线（龙岗线）","zh-Hant":"3號線（龍崗線）"}},{"id":"sz4","colour":"#DA291C","fg":"#fff","name":{"en":"Line 4 (Longhua Line)","zh-Hans":"4号线（龙华线）","zh-Hant":"4號線（龍華線）"}},{"id":"sz5","colour":"#A05EB5","fg":"#fff","name":{"en":"Line 5 (Huanzhong Line)","zh-Hans":"5号线（环中线）","zh-Hant":"5號線（環中線）"}},{"id":"sz6","colour":"#00C7B1","fg":"#fff","name":{"en":"Line 6（Guangming Line)","zh-Hans":"6号线（光明线）","zh-Hant":"6號線（光明線）"}},{"id":"sz6b","colour":"#008578","fg":"#fff","name":{"en":"Line 6 Branch","zh-Hans":"6号线支线","zh-Hant":"6號線支線"}},{"id":"sz7","colour":"#0032a0","fg":"#fff","name":{"en":"Line 7 (Xili Line)","zh-Hans":"7号线（西丽线）","zh-Hant":"7號線（西麗線）"}},{"id":"sz8","colour":"#b94700","fg":"#fff","name":{"en":"Line 8 (Yantian Line)","zh-Hans":"8号线（盐田线）","zh-Hant":"8號線（鹽田線）"}},{"id":"sz9","colour":"#7B6469","fg":"#fff","name":{"en":"Line 9 (Meilin Line)","zh-Hans":"9号线（梅林线）","zh-Hant":"9號線（梅林線）"}},{"id":"sz10","colour":"#f67599","fg":"#fff","name":{"en":"Line 10 (Bantian Line)","zh-Hans":"10号线（坂田线）","zh-Hant":"10號線（坂田線）"}},{"id":"sz11","colour":"#672146","fg":"#fff","name":{"en":"Line 11 (Airport Line)","zh-Hans":"11号线（机场线）","zh-Hant":"11號線（機場線）"}},{"id":"sz12","colour":"#A192B2","fg":"#fff","name":{"en":"Line 12 (Nanbao Line)","zh-Hans":"12号线（南宝线）","zh-Hant":"12號線（南寶線）"}},{"id":"sz13","colour":"#DE7C00","fg":"#fff","name":{"en":"Line 13 (Shiyan Line)","zh-Hans":"13号线（石岩线）","zh-Hant":"13號線（石岩線）"}},{"id":"sz14","colour":"#F2C75C","fg":"#fff","name":{"en":"Line 14 (Eastern Express)","zh-Hans":"14号线（东部快线）","zh-Hant":"14號線（東部快線）"}},{"id":"sz15","colour":"#84BD00","fg":"#fff","name":{"en":"Line 15 (Qiannan Line)","zh-Hans":"15号线（前南线）","zh-Hant":"15號線（前南線）"}},{"id":"sz16","colour":"#1E22AA","fg":"#fff","name":{"en":"Line 16 (Longping Line)","zh-Hans":"16号线（龙坪线）","zh-Hant":"16號線（龍坪線）"}},{"id":"sz17","colour":"#d3c0cd","fg":"#fff","name":{"en":"Line 17 (Pinghu Line)","zh-Hans":"17号线（平湖线）","zh-Hant":"17號線（平湖線）"}},{"id":"sz18","colour":"#00558c","fg":"#fff","name":{"en":"Line 18 (Baoyan Line)","zh-Hans":"18号线（宝盐线）","zh-Hant":"18號線（寶鹽線）"}},{"id":"sz19","colour":"#bb16a3","fg":"#fff","name":{"en":"Line 19 (Pingshan Line)","zh-Hans":"19号线（坪山线）","zh-Hant":"19號線（坪山線）"}},{"id":"sz20","colour":"#88DBDF","fg":"#fff","name":{"en":"Line 20 (Exhibition Express)","zh-Hans":"20号线（会展快线）","zh-Hant":"20號線（會展快線）"}},{"id":"sz21","colour":"#8a391b","fg":"#fff","name":{"en":"Line 21 (Nanlong Line)","zh-Hans":"21号线（南龙线）","zh-Hant":"21號線（南龍線）"}},{"id":"sz22","colour":"#fbe122","fg":"#fff","name":{"en":"Line 22 (Central Line)","zh-Hans":"22号线（中轴线）","zh-Hant":"22號線（中軸線）"}},{"id":"sz23","colour":"#be3a34","fg":"#fff","name":{"en":"Line 23 (Pingkui Line)","zh-Hans":"23号线（坪葵线）","zh-Hant":"23號線（坪葵線）"}},{"id":"sz24","colour":"#6cace4","fg":"#fff","name":{"en":"Line 24 (Sungang Line)","zh-Hans":"24号线（笋岗线）","zh-Hant":"24號線（筍崗線）"}},{"id":"sz25","colour":"#fead77","fg":"#fff","name":{"en":"Line 25 (Shilang Line)","zh-Hans":"25号线（石浪线）","zh-Hant":"25號線（石浪線）"}},{"id":"sz26","colour":"#9f912a","fg":"#fff","name":{"en":"Line 26 (Baoguang Line)","zh-Hans":"26号线（宝光线）","zh-Hant":"26號線（寶光線）"}},{"id":"sz27","colour":"#4f868e","fg":"#fff","name":{"en":"Line 27","zh-Hans":"27号线","zh-Hant":"27號線"}},{"id":"sz28","colour":"#e31c79","fg":"#fff","name":{"en":"Line 28 (Xiwan Line)","zh-Hans":"28号线（西湾线）","zh-Hant":"28號線（西灣線）"}},{"id":"sz29","colour":"#91d6ac","fg":"#fff","name":{"en":"Line 29 (Nanguang Line)","zh-Hans":"29号线（南光线）","zh-Hant":"29號線（南光線）"}},{"id":"sz30","colour":"#ae8a79","fg":"#fff","name":{"en":"Line 30","zh-Hans":"30号线","zh-Hant":"30號線"}},{"id":"sz31","colour":"#614b79","fg":"#fff","name":{"en":"Line 31","zh-Hans":"31号线","zh-Hant":"31號線"}},{"id":"sz32","colour":"#744f28","fg":"#fff","name":{"en":"Line 32 (Dapeng Line)","zh-Hans":"32号线（大鹏线）","zh-Hant":"32號線（大鵬線）"}},{"id":"sz33","colour":"#7da1c4","fg":"#fff","name":{"en":"Line 33 (Shenda Intercity Railway)","zh-Hans":"33号线（深大城际）","zh-Hant":"33號線（深大城際）"}},{"id":"tram","colour":"#ebd5a4","fg":"#fff","name":{"en":"Longhua Modern Tram","zh-Hans":"龙华现代有轨电车","zh-Hant":"龍華現代有軌電車"}},{"id":"szpsyb","colour":"#0a66b1","fg":"#fff","name":{"en":"Pingshan sky shuttlo Line 1","zh-Hans":"坪山云巴1号线","zh-Hant":"坪山雲巴1號線"}},{"id":"sz8orig","colour":"#E45DBF","fg":"#fff","name":{"en":"Line 8 (Original)","zh-Hans":"8号线（原）","zh-Hant":"8號線（原）"}}]</details>

**Comment by Swiftiecott** [comment]
您好，经检查我们发现以下问题（下述颜色均为Pantone转换至HEX后的结果）：

- 6号线支线在来源中颜色经转换后应为`#00837A`；
- 10号线在来源中颜色经转换后应为`#FB7497`；
- 17号线在来源中颜色经转换后应为`#D4BFCC`；
- 18号线在来源中颜色经转换后应为`#00538A`；
- 19号线在来源中颜色经转换后应为`#C114A1`；
- 21号线在来源中颜色经转换后应为`#8D3A18`；
- 22号线在来源中颜色经转换后应为`#FEE01E`；
- 23号线在来源中颜色经转换后应为`#C33A32`；
- 24号线在来源中颜色经转换后应为`#6CAAE4`；
- 25号线在来源中颜色经转换后应为`#FFAE75`；
- 26号线在来源中颜色经转换后应为`#A09028`；
- 27号线在来源中颜色经转换后应为`#4D858D`；
- 28号线在来源中颜色经转换后应为`#EA1D75`；
- 29号线在来源中颜色经转换后应为`#91D5AB`；
- 30号线在来源中颜色经转换后应为`#B28877`；
- 31号线在来源中颜色经转换后应为`#634B77`；
- 32号线在来源中颜色经转换后应为`#774D27`；
- 33号线在来源中颜色经转换后应为`#7DA0C3`；
- 此外，您所提供的来源中并未包含您所修改的龙华现代有轨电车、坪山云巴1号线和旧8号线相关颜色。

请在修正上述问题后新开一个议题重新提交，并在新议题下附上本议题编号，谢谢。

**Comment by Windows-Taskmgr** [comment]
您好，此模板已超过一个月未回复，遵循惯例我们将关闭此issue，谢谢配合。感谢您的贡献。
