### ISSUE TITLE
Resources: New palettes of Hangzhou

### ISSUE THREAD

**Issue by aaaaaa000000** [railmapgen/rmg-palette#1123]
**Data source:** 7. 从有损压缩的图片（如 JPG）提取的颜色

**Reference link:** https://baike.baidu.com/starmap/view?nodeId=b7f93dd6bc57efd7ab3eaf4e

**Justification:** 更改颜色，添加线路，修改编号

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"hangzhou","country":"CN","name":{"en":"Hangzhou","zh-Hans":"杭州","zh-Hant":"杭州"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"hz1","colour":"#dd1c5f","fg":"#fff","name":{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線","ar":""}},{"id":"hz2","colour":"#ec4c08","fg":"#fff","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"hz3","colour":"#f4c201","fg":"#000","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"hz4","colour":"#54ac45","fg":"#fff","name":{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號線"}},{"id":"hz5","colour":"#0ba4b9","fg":"#fff","name":{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號線"}},{"id":"hz6","colour":"#166aad","fg":"#fff","name":{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線"}},{"id":"hz7","colour":"#6d1c7b","fg":"#fff","name":{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號線"}},{"id":"hz8","colour":"#8c005d","fg":"#fff","name":{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號線"}},{"id":"hz9","colour":"#ab3b03","fg":"#fff","name":{"en":"Line 9","zh-Hans":"9号线","zh-Hant":"9號線"}},{"id":"hz10","colour":"#cc9f0c","fg":"#fff","name":{"en":"Line 10","zh-Hans":"10号线","zh-Hant":"10號線"}},{"id":"hz12","colour":"#037da4","fg":"#fff","name":{"en":"Line 12","zh-Hans":"12号线","zh-Hant":"12號線"}},{"id":"hz15","colour":"#fa89a3","fg":"#fff","name":{"en":"Line 15","zh-Hans":"15号线","zh-Hant":"15號線"}},{"id":"hz16","colour":"#f08f40","fg":"#fff","name":{"en":"Line 16","zh-Hans":"16号线","zh-Hant":"16號線"}},{"id":"hz18","colour":"#84d785","fg":"#fff","name":{"en":"Line 18","zh-Hans":"18号线","zh-Hant":"18號線"}},{"id":"hz19","colour":"#58bfd1","fg":"#fff","name":{"en":"Line 19","zh-Hans":"19号线","zh-Hant":"19號線"}},{"id":"hzhncj","colour":"#0e4996","fg":"#fff","name":{"en":"Hangzhou-Haining Intercity Rail","zh-Hans":"杭海城际","zh-Hant":"杭海城際"}}]</details>

**Comment by wongchito** [comment]
Hi @aaaaaa000000 ,

閣下所提供的來源優先級不及原來源（#860 ）「5. 官方網站的程式碼」，因此我們不接納是次更新。多謝閣下的關注！
