### ISSUE TITLE
Resources: New palettes of Foshan

### ISSUE THREAD

**Issue by qcdbgcd** [railmapgen/rmg-palette#1126]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Data source:** 8. 维基百科

**Reference link:** https://fsbus.top/index.php/%E9%A6%96%E9%A1%B5

**Justification:** 更改标志色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"foshan","country":"CN","name":{"en":"Foshan","zh-Hans":"佛山","zh-Hant":"佛山"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"fs1","colour":"#C4D600","fg":"#000","name":{"en":"Guangfo Line","zh-Hans":"广佛线","zh-Hant":"廣佛線"}},{"id":"fs2","colour":"#F5333F","fg":"#fff","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"fs3","colour":"#002F87","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"fs4","colour":"#923A7F","fg":"#fff","name":{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號線"}},{"id":"fs11","colour":"#035c67","fg":"#fff","name":{"en":"Line 11","zh-Hans":"11号线","zh-Hant":"11號線"}},{"id":"tnh1","colour":"#5EB3E4","fg":"#fff","name":{"en":"Nanhai Tram Line 1","zh-Hans":"南海有轨1号线","zh-Hant":"南海有軌1號線"}},{"id":"tgm1","colour":"#4CA585","fg":"#fff","name":{"en":"Gaoming Tram Line 1","zh-Hans":"高明有轨1号线","zh-Hant":"高明有軌1號線"}}]</details>

**Comment by wongchito** [comment]
Hi @qcdbgcd ,

請閣下提供直達顏色頁面的連結，以便我們審核。多謝！
