### ISSUE TITLE
Resources: New palettes of Valparaiso

### ISSUE THREAD

**Issue by Matx-29** [railmapgen/rmg-palette#1128]
**Data source:** 1. Design standard published in the official website

**Reference link:** https://railmapgen.github.io/?app=rmg-palette-upload

**Justification:** Metro de Valparaíso es lo que falta

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"valparaiso","country":"CL","name":{"en":"Valparaiso","es":"Valparaiso","zh-Hans":"瓦尔帕莱索","zh-Hant":"瓦爾帕賴索 "}}</details>

<details repo="rmg-palette" type="lines">[{"id":"mv1","colour":"#0b48fe","fg":"#fff","name":{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線","es":"Línea 1"}},{"id":"bl","colour":"#00ff00","fg":"#fff","name":{"en":"Bus to Limache","zh-Hans":"到 利马什 的巴士","zh-Hant":"到 利馬什 的巴士","es":"Bus a Limache"}},{"id":"bq","colour":"#ff9900","fg":"#fff","name":{"en":"Bus to Quillota","zh-Hans":"到 基约塔 的巴士","zh-Hant":"到 基約塔 的巴士","es":"Bus a Quillota"}},{"id":"blc","colour":"#00ffff","fg":"#fff","name":{"en":"Bus to La Calera","zh-Hans":"到 拉卡莱拉 的巴士","zh-Hant":"到 拉卡萊拉 的巴士","es":"Bus a La Calera"}}]</details>

**Comment by wongchito** [comment]
Hi @Matx-29 ,

Please submit the correct reference link instead of the link to our website. Thanks!
