### ISSUE TITLE
Resources: New palettes of Guiyang

### ISSUE THREAD

**Issue by MgOBeniamino** [railmapgen/rmg-palette#1149]
**Data source:** 1. Design standard published in the official website

**Reference link:** https://zh.wikipedia.org/wiki/%E8%B4%B5%E9%98%B3%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A

**Justification:** Update the Line 3 opened in 2024

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"guiyang","country":"CN","name":{"en":"Guiyang","ko":"구이양","zh-Hans":"贵阳","zh-Hant":"貴陽"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"gy1","colour":"#259b24","fg":"#fff","name":{"en":"Line 1","ko":"1호선","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"gy2","colour":"#005bac","fg":"#fff","name":{"en":"Line 2","ko":"2호선","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"gy3","colour":"#ff0000","fg":"#fff","name":{"en":"Line 3","ko":"3호선","zh-Hans":"3号线","zh-Hant":"3號線"}}]</details>

**Comment by linchen1965** [comment]
Hi @MgOBeniamino ,

Please submit the reference link of data source you have chosen. Thanks!
