### ISSUE TITLE
Resources: New palettes of Xiangxi Tujia and Miao Autonomous Prefecture

### ISSUE THREAD

**Issue by TG14-1919F** [railmapgen/rmg-palette#1154]
**Data source:** 7. 从有损压缩的图片（如 JPG）提取的颜色

**Reference link:** https://bkimg.cdn.bcebos.com/pic/b812c8fcc3cec3fdfc039f6573dbc33f8794a4c289da?x-bce-process=image/format,f_auto/watermark,image_d2F0ZXIvYmFpa2UyNzI,g_7,xp_5,yp_5,P_20/resize,m_lfit,limit_1,h_1080

**Justification:** 添加新的线路，方便用户提取颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"xiangxitujiazumiaozuzizhizhou","country":"CN","name":{"en":"Xiangxi Tujia and Miao Autonomous Prefecture","zh-Hans":"湘西土家族苗族自治州","zh-Hant":"湘西土家族苗族自治州"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"xiangxitujiazumiaozuzizhizhoufenghuang","colour":"#9f785a","fg":"#fff","name":{"en":"Fenghuang Maglev Express","zh-Hans":"凤凰磁浮观光快线","zh-Hant":"鳳凰磁浮觀光快線"}}]</details>

**Comment by linchen1965** [comment]
您好，由于您提交的图片并非官网中的线路图而是列车照片，故不能作为有效来源提交，请您更换其他有效来源提交，谢谢。

**Comment by Swiftiecott** [comment]
Closed as no response over 1 months.
