### ISSUE TITLE
Resources: New palettes of Qingyuan

### ISSUE THREAD

**Issue by Inkwinter1116** [railmapgen/rmg-palette#116]
**Justification:** (清远的广清城际缺乏，可以加上)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "qingyuan",
    "country": "CN",
    "name": {
        "zh-Hans": "清远",
        "zh-Hant": "清遠",
        "en": "Qingyuan"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "gqcj",
        "colour": "#00389f",
        "fg": "#fff",
        "name": {
            "zh-Hans": "广清城际",
            "zh-Hant": "廣清城際",
            "en": "Guangzhou-Qingyuan Intercity"
        }
    },
    {
        "id": "lyzx",
        "colour": "#aaaaaa",
        "fg": "#fff",
        "name": {
            "zh-Hans": "清远市磁浮旅游专线",
            "zh-Hant": "清遠市磁浮旅遊專線",
            "en": "Qingyuan Maglev Trip Line"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，如果有时间的话能不能提供一下所添加线路颜色的来源呢，谢谢。

**Comment by Inkwintere1116** [comment]
在这张图用取色器整的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月18日(星期一) 上午6:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [railmapgen/rmg-palette] Resources: New palettes of Qingyuan (Issue #116)






你好，如果有时间的话能不能提供一下所添加线路颜色的来源呢，谢谢。

—
直接回复此邮件，在 GitHub 上查看或取消订阅.
您收到这个消息是因为您创建了这个线程。留言 ID ***@***.***与&gt;

**Comment by 52PD** [comment]
> 在这张图用取色器整的

啊这。。。如果可以的话图能不能直接登录GitHub上发一遍吗，用邮件发图的话我们是看不到的😂

**Comment by 52PD** [comment]
您好，经过我们开发组内部讨论，发现清远城际铁路所属的粤港澳大湾区城际铁路系统无法找到相关官方网站以及官方线路色号（使用维基百科来源的前提是有官方线路颜色来源），加上磁浮旅游专线目前没有官方配色
因此您所提供的线路颜色将不会考虑加入到本项目中，很抱歉这么晚才通知你。

类似的，目前项目中没有官方颜色来源或者由国铁运营的城际线路我们也会在检查后进行移除。
