### ISSUE TITLE
Resources: New palettes of Guiyang

### ISSUE THREAD

**Issue by tin1us** [railmapgen/rmg-palette#1166]
**Data source:** 7. 从有损压缩的图片（如 JPG）提取的颜色

**Reference link:** https://bkimg.cdn.bcebos.com/pic/5fdf8db1cb134954092310f5ec198558d109b3dedc50?x-bce-process=image/resize,m_lfit,w_536,limit_1/quality,Q_70

**Justification:** 贵阳3已开，这里把他提交了。从百度百科与地铁通中提取颜色得

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"guiyang","country":"CN","name":{"en":"Guiyang","ko":"구이양","zh-Hans":"贵阳","zh-Hant":"貴陽"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"gy1","colour":"#259b24","fg":"#fff","name":{"en":"Line 1","ko":"1호선","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"gy2","colour":"#005bac","fg":"#fff","name":{"en":"Line 2","ko":"2호선","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"gy3","colour":"#f62120","fg":"#fff","name":{"en":"Line 3","ko":"3호선","zh-Hans":"3号线","zh-Hant":"3號線"}}]</details>

**Comment by linchen1965** [comment]
您好，我们暂不支持来自百度百科或地铁通的来源，请您更换来源提交，感谢您的贡献。
