### ISSUE TITLE
Resources: New palettes of Doha

### ISSUE THREAD

**Issue by vicemoter0062** [railmapgen/rmg-palette#1171]
**Data source:** 1. 官方網站發佈的設計標準

**Reference link:** https://www.qr.com.qa/home

**Justification:** 新增电车橙线

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"doha","country":"QA","name":{"en":"Doha","zh-Hans":"多哈","zh-Hant":"多哈","ar":"الدوحة"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"rl","colour":"#df2112","fg":"#fff","name":{"en":"Red line","zh-Hans":" 红线","zh-Hant":"紅綫","ar":"والأحمر"}},{"id":"gl","colour":"#7ebb00","fg":"#fff","name":{"en":"Green Line","zh-Hans":"绿线","zh-Hant":"綠綫","ar":"الأخضر"}},{"id":"goldl","colour":"#ffb616","fg":"#fff","name":{"en":"Gold line","zh-Hans":"金线","zh-Hant":"金綫","ar":"والذهبي"}},{"id":"qto","colour":"#ec7525","fg":"#fff","name":{"en":"Orange（Tram）","zh-Hans":"橙线（电车）","zh-Hant":"橙綫（電車）","ar":"البرتقالي"}}]</details>

**Comment by Swiftiecott** [comment]
Closed as no response over 1 months.
