### ISSUE TITLE
Resources: New palettes of Xiangtan

### ISSUE THREAD

**Issue by XiaoZiMo1234** [railmapgen/rmg-palette#1176]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Data source:** 1. 官方网站发布的设计标准

**Reference link:** https://www.hncsmtr.com/906/922/content_71002.html

**Justification:** 长株潭城际轨道交通西环线一期工程起于沪昆高铁湘潭北站，至长沙地铁3号线一期工程起点山塘站，串联起湘潭，长沙两市，并于2023年6月28日开通运营。本网站没有关于这个线路的调色板，故此添加

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"Xiangtan","country":"CN","name":{"en":"Xiangtan","zh-Hans":"湘潭","zh-Hant":"湘潭"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"xtxhl","colour":"#cc8899","fg":"#fff","name":{"en":"Changsha-Zhuzhou-Xiangtan Intercity Metro Xihuan Line","zh-Hans":"长株潭城际轨道交通西环线","zh-Hant":"長株潭城際軌道交通西環線"}}]</details>

**Comment by Windows-Taskmgr** [comment]
您好，西环线的颜色在长沙地铁的调色板里，所以无需再添加，感谢您的贡献。
