### ISSUE TITLE
新增长春线路颜色模板

### ISSUE THREAD

**Issue by GrassRabbit1410** [railmapgen/rmg-palette#118]
信息来源：长春轨道交通官网线路图     http://www.ccqg.com/xccx
![c01](https://user-images.githubusercontent.com/94828677/179651612-6800306b-4184-4f36-bd2b-372cef62393c.jpg)

[长春-Changchun.txt](https://github.com/railmapgen/rmg-palette/files/9136967/-Changchun.txt)

**Comment by 52PD** [comment]
已收到👍

不过由于旧版投稿方式由于需要我们手动整合进资源中所以会比较麻烦，下次如需投稿的话可以参考https://github.com/railmapgen/rmg-palette/wiki/How-to-add-color-palette 中所提供的新方式，这样也方便我们更快整合到资源中。

总之，我们也会尽快将你提供的内容整合进去，感谢你对项目的支持。

**Comment by 52PD** [comment]
额。。。。你好，如果你需要用新方法提供线路颜色的话，麻烦重新开一个issue，直接复制到现有的issue的话因为无法触发我们设定的机器人程序我们也没办法整合到项目中啊😂

此外，在用新方法提交线路颜色的时候，请将Justification之后的“请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)”这句话替换掉，否则同样无法触发bot😂
