### ISSUE TITLE
Resources: New palettes of Macao

### ISSUE THREAD

**Issue by MACChrischan2009** [railmapgen/rmg-palette#1188]
**Data source:** 1. 官方網站發佈的設計標準

**Reference link:** https://www.mlm.com.mo/tc/index.html

**Justification:** 政府發佈了對澳門輕軌的發展規劃

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"macao","country":"MO","name":{"en":"Macao","pt":"Macau","zh-Hans":"澳门","zh-Hant":"澳門"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"taipa","colour":"#A4D65E","fg":"#fff","name":{"en":"Taipa Line","pt":"Linha da Taipa","zh-Hans":"氹仔线","zh-Hant":"氹仔線"}},{"id":"peninsula","colour":"#FF0000","fg":"#fff","name":{"en":"Linha da Península de Macau","zh-Hans":"澳门线","zh-Hant":"澳門線"}},{"id":"2afase","colour":"#00BFFF","fg":"#fff","name":{"en":"West Line","zh-Hans":"澳门半島西线","zh-Hant":"澳門半島西線","pt":"Linha Oeste"}},{"id":"seacpaivan","colour":"#e6007e","fg":"#fff","name":{"pt":"Linha Seac Pai Van","zh-Hans":"石排湾线","zh-Hant":"石排灣線","en":"Seac Pai Van Line"}},{"id":"hengqin","colour":"#FFA500","fg":"#fff","name":{"pt":"Linha de Hengqin","zh-Hans":"横琴线","zh-Hant":"橫琴線","en":"Hengqin Line"}},{"id":"leste","colour":"#714b9e","fg":"#fff","name":{"en":"East Line ","zh-Hans":"澳氹东线","zh-Hant":"澳氹東線","pt":"Linha Leste"}}]</details>

**Comment by wongchito** [comment]
Hi @MACChrischan2009 ,

閣下提供的網站（https://www.mlm.com.mo/tc/route.html）顯示，雖然石排灣線內附地圖展示為紅色，但於同一地圖的氹仔線展示的藍色並不符合現時設計，我們認為按鈕顏色更可能為未來將會採用的顏色。同時，該網站未有顯示任何西線相關的資料。請閣下修正後再次提交。多謝！

**Comment by Swiftiecott** [comment]
Closed as no response over 1 months.
