### ISSUE TITLE
Resources: New palettes of Suzhou

### ISSUE THREAD

**Issue by PandaWorkgroup** [railmapgen/rmg-palette#1189]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Data source:** 1. 官方网站发布的设计标准

**Reference link:** http://www.sz-mtr.com/service/guide/map/mobile_zh.html

**Justification:** 添加

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"so","country":"CN","name":{"en":"Suzhou","zh-Hans":"苏州","zh-Hant":"蘇州"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"sz2","colour":"#ff3a2f","fg":"#fff","name":{"en":"Suzhou Rail Transit Line 2","zh-Hans":"苏州轨道交通2号线","zh-Hant":"蘇州軌道交通2號線"}}]</details>

**Comment by linchen1965** [comment]
Closed as invalid resources
