### ISSUE TITLE
Resources: New palettes of Kekslingen

### ISSUE THREAD

**Issue by PinguinTux11** [railmapgen/rmg-palette#1207]
**Data source:** 1. Design standard published in the official website

**Reference link:** http://infinitycookie.de/Bahnnetz.png

**Justification:** Created the new fictive city "Kekslingen, from a german minecraft server called "infinitycookie.de"

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"kekslingen","country":"DE","name":{"de":"Kekslingen","en":"Kekslingen"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"U1","colour":"#ff0000","fg":"#fff","name":{"en":"U1"}},{"id":"U2","colour":"#55ff55","fg":"#fff","name":{"en":""}},{"id":"U3","colour":"#5555ff","fg":"#fff","name":{"en":""}},{"id":"U4","colour":"#dcdc00","fg":"#fff","name":{"en":""}},{"id":"U5","colour":"#884422","fg":"#fff","name":{"en":""}},{"id":"U6","colour":"#aa00aa","fg":"#fff","name":{"en":""}},{"id":"U7","colour":"#ff8000","fg":"#fff","name":{"en":""}},{"id":"U8","colour":"#ff8000","fg":"#fff","name":{"en":""}}]</details>

**Comment by linchen1965** [comment]
Sorry, we won't accept the palettes from the virtual world at the current time. Thank you!
