### ISSUE TITLE
Resources: New palettes of Seville

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmg-palette#1209]
**Data source:** 8. Wikipedia

**Reference link:** https://es.wikipedia.org/wiki/L%C3%ADnea_3_(Metro_de_Sevilla)

**Justification:** Add palettes of Metro Lines

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"sevilla","country":"ES","name":{"es":"Sevilla","en":"Seville"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"C1","colour":"#4c90c3","fg":"#fff","name":{"es":"Cercanías 1","en":"Commuter 1"}},{"id":"C2","colour":"#067b34","fg":"#fff","name":{"es":"Cercanías 2","en":"Commuter 2"}},{"id":"C3","colour":"#e4242d","fg":"#fff","name":{"es":"Cercanías 3","en":"Commuter 3"}},{"id":"C4","colour":"#8e2182","fg":"#fff","name":{"es":"Cercanías 4","en":"Commuter 4"}},{"id":"C5","colour":"#073588","fg":"#fff","name":{"es":"Cercanías 5","en":"Commuter 5"}},{"id":"m1","colour":"#01820B","fg":"#fff","name":{"en":"Metro Line 1","zh-Hans":"地铁1号线","zh-Hant":"地鐡1號缐","es":"Metro Línea 1"}},{"id":"m2","colour":"#1275AA","fg":"#fff","name":{"en":"Metro Line 2","zh-Hans":"地铁2号线","zh-Hant":"地鐡2號缐","es":"Metro Línea 2"}},{"id":"m3","colour":"#C9013B","fg":"#fff","name":{"en":"Metro Line 3","zh-Hans":"地铁3号线","zh-Hant":"地鐡3號缐","es":"Metro Línea 3"}},{"id":"m4","colour":"#E4AF29","fg":"#fff","name":{"en":"Metro Line 4","zh-Hans":"地铁4号线","zh-Hant":"地鐡4號缐","es":"Metro Línea 4"}}]</details>

**Comment by Swiftiecott** [comment]
您好，经检查我们发现以下问题：

- 虽然西班牙语维基百科上并未直接将各线路颜色纳入新西兰队可更改范围内，但考虑到其上传的线路颜色标识均为SVG矢量图故可以直接通过浏览器开发者模式取色这一点：四条地铁线路的颜色应当为：
  - 1号线应当为`#01820B`；
  - 2号线应当为`#1275AA`；
  - 3号线应当为`#C9013B`；
  - 4号线应当为`#E4AF29`。

请在修正上述问题后于本议题下重新提交，谢谢。

**Comment by linchen1965** [comment]
**Data source:** 8. Wikipedia

**Reference link:** https://es.wikipedia.org/wiki/L%C3%ADnea_3_(Metro_de_Sevilla)

**Justification:** Add palettes of Metro Lines

**Do not edit lines below, they are meant for bots only!!!**



<details repo="rmg-palette" type="city">{"id":"sevilla","country":"ES","name":{"es":"Sevilla","en":"Seville"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"C1","colour":"#4c90c3","fg":"#fff","name":{"es":"Cercanías 1","en":"Commuter 1"}},{"id":"C2","colour":"#067b34","fg":"#fff","name":{"es":"Cercanías 2","en":"Commuter 2"}},{"id":"C3","colour":"#e4242d","fg":"#fff","name":{"es":"Cercanías 3","en":"Commuter 3"}},{"id":"C4","colour":"#8e2182","fg":"#fff","name":{"es":"Cercanías 4","en":"Commuter 4"}},{"id":"C5","colour":"#073588","fg":"#fff","name":{"es":"Cercanías 5","en":"Commuter 5"}},{"id":"m1","colour":"#01820B","fg":"#fff","name":{"en":"Metro Line 1","zh-Hans":"地铁1号线","zh-Hant":"地鐡1號缐","es":"Metro Línea 1"}},{"id":"m2","colour":"#1275AA","fg":"#fff","name":{"en":"Metro Line 2","zh-Hans":"地铁2号线","zh-Hant":"地鐡2號缐","es":"Metro Línea 2"}},{"id":"m3","colour":"#C9013B","fg":"#fff","name":{"en":"Metro Line 3","zh-Hans":"地铁3号线","zh-Hant":"地鐡3號缐","es":"Metro Línea 3"}},{"id":"m4","colour":"#E4AF29","fg":"#fff","name":{"en":"Metro Line 4","zh-Hans":"地铁4号线","zh-Hant":"地鐡4號缐","es":"Metro Línea 4"}}]</details>

**Comment by Swiftiecott** [comment]
您好，经检查所有问题均已经修复。感谢您对本项目的贡献
