### ISSUE TITLE
Resources: New palettes of Foshan

### ISSUE THREAD

**Issue by SujiaL816** [railmapgen/rmg-palette#121]
**Justification:** Hi RMG team! I would like to contribute the palettes below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "foshan",
    "country": "CN",
    "name": {
        "en": "Foshan",
        "zh": "佛山"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "fs1",
        "colour": "#C4D600",
        "fg": "#000",
        "name": {
            "en": "Guangfo Line",
            "zh-Hans": "广佛线",
            "zh-Hant": "廣佛線"
        }
    },
    {
        "id": "fs2",
        "colour": "#F5333F",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "fs3",
        "colour": "#4747c5",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "fs4",
        "colour": "#923A7F",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "fs6",
        "colour": "#FFB81D",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "fs9",
        "colour": "#A25EB5",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "fs11",
        "colour": "#035C67",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "fs13",
        "colour": "#32B7EA",
        "fg": "#fff",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "tnh1",
        "colour": "#5EB3E4",
        "fg": "#fff",
        "name": {
            "en": "Nanhai Tram Line 1",
            "zh-Hans": "南海有轨1号线",
            "zh-Hant": "南海有軌1號線"
        }
    },
    {
        "id": "tgm1",
        "colour": "#4CA585",
        "fg": "#fff",
        "name": {
            "en": "Gaoming Tram Line 1",
            "zh-Hans": "高明有轨1号线",
            "zh-Hant": "高明有軌1號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，请问你方便的话是否能够提供线路颜色的来源呢？

我们不会接受任何无颜色来源的投稿

**Comment by 52PD** [comment]
您好，很抱歉由于拒上次提及线路颜色稿件缺失来源后，你以及超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
