### ISSUE TITLE
Resources: New palettes of London

### ISSUE THREAD

**Issue by blueescapism88** [railmapgen/rmg-palette#1216]
**Data source:** 1. Design standard published in the official website

**Reference link:** https://blog.tfl.gov.uk/2022/12/22/digital-colour-standard/

**Justification:** Add support colours for Thameslink and readjust line order according to official website

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"london","country":"GBENG","name":{"en":"London","zh-Hans":"伦敦","zh-Hant":"倫敦"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"bakerloo","colour":"#B26300","fg":"#fff","name":{"en":"Bakerloo Line","zh-Hans":"贝克卢线","zh-Hant":"必嘉老綫"}},{"id":"central","colour":"#DC241F","fg":"#fff","name":{"en":"Central Line","zh-Hans":"中央线","zh-Hant":"中央綫"}},{"id":"circle","colour":"#FFD329","fg":"#fff","name":{"en":"Circle Line","zh-Hant":"環綫"}},{"id":"district","colour":"#007D32","fg":"#fff","name":{"en":"District Line"}},{"id":"hsmithcity","colour":"#F4A9BE","fg":"#fff","name":{"en":"Hammersmith &amp; City Line","zh-Hant":"咸默史密夫及城市綫"}},{"id":"jubilee","colour":"#A1A5A7","fg":"#fff","name":{"en":"Jubilee Line","zh-Hans":"银禧线","zh-Hant":"銀禧綫"}},{"id":"metropolitan","colour":"#9B0058","fg":"#fff","name":{"en":"Metropolitan Line","zh-Hans":"大都会线","zh-Hant":"大都會綫"}},{"id":"northern","colour":"#000000","fg":"#fff","name":{"en":"Northern Line"}},{"id":"piccadily","colour":"#0019A8","fg":"#fff","name":{"en":"Piccadily Line"}},{"id":"victoria","colour":"#0098D8","fg":"#fff","name":{"en":"Victoria Line","zh-Hans":"维多利亚线","zh-Hant":"維多利亞綫"}},{"id":"waterloocity","colour":"#93CEBA","fg":"#fff","name":{"en":"Waterloo &amp; City Line","zh-Hans":"滑铁卢及城市线","zh-Hant":"窩打老及城市綫"}},{"id":"emirates","colour":"#DC241F","fg":"#fff","name":{"en":"Emirates Air Line"}},{"id":"dlr","colour":"#00AFAD","fg":"#fff","name":{"en":"Docklands Light Railway"}},{"id":"elizabeth","colour":"#9364CC","fg":"#fff","name":{"en":"Elizabeth Line","zh-Hant":"伊利沙伯綫"}},{"id":"thameslink","colour":"#da4290","fg":"#fff","name":{"en":"Thameslink","zh-Hans":"","zh-Hant":""}},{"id":"tfl","colour":"#0019A8","fg":"#fff","name":{"en":"TfL Rail"}},{"id":"overground","colour":"#EF7B10","fg":"#fff","name":{"en":"London Overground"}},{"id":"trams","colour":"#00BD19","fg":"#fff","name":{"en":"London Trams"}}]</details>

**Comment by Swiftiecott** [comment]
您好，经检查我们发现以下问题：

- 首先，本项目颜色模版不支持提供航空公司颜色，因此您所提供的阿联酋航空的颜色将被拒收。此外，在您所提供的颜色来源中亦未提供阿联酋航空之相关颜色。

请在修正上述问题后于本议题下重新提交，谢谢。

**Comment by Windows-Taskmgr** [comment]
您好，此模板已超过一个月未回复，遵循惯例我们将关闭此issue，谢谢配合。感谢您的贡献。
