### ISSUE TITLE
Resources: New palettes of Chongqing

### ISSUE THREAD

**Issue by OIer-Tan** [railmapgen/rmg-palette#1220]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Data source:** 8. 维基百科

**Reference link:** https://zh.wikipedia.org/wiki/%E9%87%8D%E5%BA%86%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A#%E7%BA%BF%E8%B7%AF%E8%AF%86%E5%88%AB%E8%89%B2

**Justification:** 所有线路改为使用Pantone色号，24号线更改，新增19~23，25、26、28、璧铜线。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"chongqing","country":"CN","name":{"en":"Chongqing","zh-Hans":"重庆","zh-Hant":"重慶"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"loop","colour":"#F2A900","fg":"#fff","pantone":"130 C","name":{"en":"Loop Line","zh-Hans":"环线","zh-Hant":"環線"}},{"id":"cq1","colour":"#E4002B","fg":"#fff","pantone":"185 C","name":{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"cq2","colour":"#007A33","fg":"#fff","pantone":"356 C","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"cq3","colour":"#003DA5","fg":"#fff","pantone":"293 C","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"cq4","colour":"#DC8633","fg":"#fff","pantone":"7413 C","name":{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號線"}},{"id":"cq5","colour":"#00A3E0","fg":"#fff","pantone":"299 C","name":{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號線"}},{"id":"cq6","colour":"#F67599","fg":"#fff","pantone":"190 C","name":{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線"}},{"id":"cq7","colour":"#008C95","fg":"#fff","pantone":"321 C","name":{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號線"}},{"id":"cq8","colour":"#7A9A01","fg":"#fff","pantone":"377 C","name":{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號線"}},{"id":"cq9","colour":"#862041","fg":"#fff","pantone":"208 C","name":{"en":"Line 9","zh-Hans":"9号线","zh-Hant":"9號線"}},{"id":"cq10","colour":"#5F249F","fg":"#fff","pantone":"267 C","name":{"en":"Line 10","zh-Hans":"10号线","zh-Hant":"10號線"}},{"id":"cq11","colour":"#D986BA","fg":"#fff","pantone":"673 C","name":{"en":"Line 11","zh-Hans":"11号线","zh-Hant":"11號線"}},{"id":"cq12","colour":"#D2D755","fg":"#fff","pantone":"584 C","name":{"en":"Line 12","zh-Hans":"12号线","zh-Hant":"12號線"}},{"id":"cq13","colour":"#B89D18","fg":"#fff","pantone":"457 C","name":{"en":"Line 13","zh-Hans":"13号线","zh-Hant":"13號線"}},{"id":"cq14","colour":"#B94700","fg":"#fff","pantone":"1525 C","name":{"en":"Line 14","zh-Hans":"14号线","zh-Hant":"14號線"}},{"id":"cq15","colour":"#0057B7","fg":"#fff","pantone":"2935 C","name":{"en":"Line 15","zh-Hans":"15号线","zh-Hant":"15號線"}},{"id":"cq16","colour":"#B04A5A","fg":"#fff","pantone":"7419 C","name":{"en":"Line 16","zh-Hans":"16号线","zh-Hant":"16號線"}},{"id":"cq17","colour":"#9F5CC0","fg":"#fff","pantone":"7441 C","name":{"en":"Line 17","zh-Hans":"17号线","zh-Hant":"17號線"}},{"id":"cq18","colour":"#2AD2C9","fg":"#fff","pantone":"3252 C","name":{"en":"Line 18","zh-Hans":"18号线","zh-Hant":"18號線"}},{"id":"cq19","colour":"#BC204B","fg":"#fff","pantone":"7636 C","name":{"en":"Line 19","zh-Hans":"19号线","zh-Hant":"19號線"}},{"id":"cq20","colour":"#E31C79","fg":"#fff","pantone":"213 C","name":{"en":"Line 20","zh-Hans":"20号线","zh-Hant":"20號線"}},{"id":"cq21","colour":"#007FA3","fg":"#fff","pantone":"314 C","name":{"en":"Line 21","zh-Hans":"21号线","zh-Hant":"21號線"}},{"id":"cq22","colour":"#003D4C","fg":"#fff","pantone":"548 C","name":{"en":"Line 22","zh-Hans":"22号线","zh-Hant":"22號線"}},{"id":"cq23","colour":"#E35205","fg":"#fff","pantone":"166 C","name":{"en":"Line 23","zh-Hans":"23号线","zh-Hant":"23號線"}},{"id":"cq24","colour":"#D7A048","fg":"#fff","pantone":"4025 C","name":{"en":"Line 24","zh-Hans":"24号线","zh-Hant":"24號線"}},{"id":"cq25","colour":"#00685E","fg":"#fff","pantone":"329 C","name":{"en":"Line 25","zh-Hans":"25号线","zh-Hant":"25號線"}},{"id":"cq26","colour":"#00C389","fg":"#fff","pantone":"3395 C","name":{"en":"Line 26","zh-Hans":"26号线","zh-Hant":"26號線"}},{"id":"cq27","colour":"#685BC7","fg":"#fff","pantone":"2725 C","name":{"en":"Line 27","zh-Hans":"27号线","zh-Hant":"27號線"}},{"id":"cq28","colour":"#007398","fg":"#fff","pantone":"7468 C","name":{"en":"Line 28","zh-Hans":"28号线","zh-Hant":"28號線"}},{"id":"jiangtiao","colour":"#0077C8","fg":"#fff","pantone":"3005 C","name":{"en":"Jiangtiao Line","zh-Hans":"江跳线","zh-Hant":"江跳線"}},{"id":"bitong","colour":"#685BC7","fg":"#fff","pantone":"2725 C","name":{"en":"Bitong Line","zh-Hans":"璧铜线","zh-Hant":"璧銅線"}}]</details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
