### ISSUE TITLE
一座虚拟城市蛙塘市的调色板

### ISSUE THREAD

**Issue by watangcity** [railmapgen/rmg-palette#1225]
**Data source:** 9. 其他（请于下方注明）

**Reference link:** https://railmapgen.gitlab.io

**Justification:** 一座虚拟城市

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{"id":"HARM","name":{"en":"Coast People's Republic","zh-Hans":"海岸人民共和国","zh-Hant":"海岸人民共和國"},"language":"zh-Hans"}</details>

<details repo="rmg-palette" type="city">{"id":"harmwt.241","country":"HARM","name":{"en":"Wa‘tang","zh-Hans":"蛙塘市","zh-Hant":"蛙塘市"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"wt1","colour":"#ff0000","fg":"#fff","name":{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"wt2","colour":"#ffff00","fg":"#000","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"wt3","colour":"#3967b1","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"wt5","colour":"#0000ff","fg":"#fff","name":{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號線"}},{"id":"wt7","colour":"#9900ff","fg":"#fff","name":{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號線"}},{"id":"wt10","colour":"#ff9900","fg":"#fff","name":{"en":"Line 10","zh-Hans":"10号线","zh-Hant":"10號線"}},{"id":"wt15","colour":"#0fa90f","fg":"#fff","name":{"en":"Line 15","zh-Hans":"15号线","zh-Hant":"15號線"}},{"id":"wt18","colour":"#ffff85","fg":"#000","name":{"en":"Line 18","zh-Hans":"18号线","zh-Hant":"18號線"}},{"id":"wt19","colour":"#00006b","fg":"#fff","name":{"en":"Line 19","zh-Hans":"19号线","zh-Hant":"19號線"}},{"id":"wt21","colour":"#4e8b2d","fg":"#fff","name":{"en":"Line 21","zh-Hans":"21号线","zh-Hant":"21號線"}},{"id":"wt22","colour":"#699cec","fg":"#fff","name":{"en":"Line 22","zh-Hans":"22号线","zh-Hant":"22號線"}},{"id":"wt4","colour":"#003d9e","fg":"#fff","name":{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號線"}}]</details>

**Comment by watangcity** [comment]
有人吗

**Comment by 28yfang** [comment]
您好，调色板是不能添加非现实中的城市的，您可以在RMP中使用自定义颜色画完线路图后捐赠上传到RMP画廊 :)
