### ISSUE TITLE
Resources: New palettes of Jinan

### ISSUE THREAD

**Issue by Cmbself** [railmapgen/rmg-palette#123]
**Justification:** 济南地铁四号线还未开通，处于建设中状态，且还需4~5年才可建成，故将其暂时删去。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "jinan",
    "country": "CN",
    "name": {
        "en": "Jinan",
        "zh-Hans": "济南",
        "zh-Hant": "濟南"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "jn1",
        "colour": "#BE1FA1",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "jn2",
        "colour": "#FFB620",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "jn3",
        "colour": "#0073CE",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，请问你方便的话是否能够提供线路颜色的来源呢？

我们不会接受任何无颜色来源的投稿

**Comment by 52PD** [comment]
你好，投稿线路颜色与投稿线路模版不同的是即使是未开通线路只要有可靠颜色来源我们也会正常接收。

如果您本次的投稿只是单纯删除掉未开通线路的话我们是不会接受您的投稿的，谢谢。
