### ISSUE TITLE
Resources: New palettes of Yerres

### ISSUE THREAD

**Issue by Rerepro2023** [railmapgen/rmg-palette#1245]
**Data source:** 1. Design standard published in the official website

**Reference link:** https://fr.m.wikipedia.org/wiki/R%C3%A9seau_de_bus_Val_d%27Yerres_Val_de_Seine

**Justification:** Lignes de bus du secteur de Yerres

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"yerres","country":"FR","name":{"fr":"Yerres","en":"Yerres","zh-Hans":"Yerres","zh-Hant":"Yerres"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"busa","colour":"#4c89d9","fg":"#fff","name":{"en":"Line A","zh-Hans":"A","zh-Hant":"A","fr":"Ligne A"}}]</details>

**Comment by Rerepro2023** [comment]
C'est bon

**Comment by linchen1965** [comment]
Hi @Rerepro2023 
Since there are palettes of other Lines in this page. Please submit them all instead of only one!
The Data source should be chosen as "Wikipedia"
Thanks!

**Comment by Windows-Taskmgr** [comment]
Hi @Rerepro2023 
Hello, since this issue has not been modified for more than a month, we will close this issue, thank you for your understanding!
Win-Tsk
