### ISSUE TITLE
Resources: New palettes of Foshan

### ISSUE THREAD

**Issue by CommandBlocktt** [railmapgen/rmg-palette#1248]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Data source:** 7. 从有损压缩的图片（如 JPG）提取的颜色

**Reference link:** https://www.fmetro.net/upload/main/contentmanage/node/image/bb0adcaa2a35406392dbd30036591301.jpg

**Justification:** 佛山地铁有关于广州地铁的色块。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"foshan","country":"CN","name":{"en":"Foshan","zh-Hans":"佛山","zh-Hant":"佛山"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"fs1","colour":"#C4D600","fg":"#000","name":{"en":"Guangfo Line","zh-Hans":"广佛线","zh-Hant":"廣佛線"}},{"id":"fs2","colour":"#F5333F","fg":"#fff","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"fs3","colour":"#002F87","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"fs4","colour":"#923A7F","fg":"#fff","name":{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號線"}},{"id":"fs6","colour":"#FFB81D","fg":"#fff","name":{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線"}},{"id":"fs9","colour":"#A25EB5","fg":"#fff","name":{"en":"Line 9","zh-Hans":"9号线","zh-Hant":"9號線"}},{"id":"fs11","colour":"#2a3976","fg":"#fff","name":{"en":"Line 11","zh-Hans":"11号线","zh-Hant":"11號線"}},{"id":"fs13","colour":"#32B7EA","fg":"#fff","name":{"en":"Line 13","zh-Hans":"13号线","zh-Hant":"13號線"}},{"id":"tnh1","colour":"#5EB3E4","fg":"#fff","name":{"en":"Nanhai Tram Line 1","zh-Hans":"南海有轨1号线","zh-Hant":"南海有軌1號線"}},{"id":"tgm1","colour":"#4CA585","fg":"#fff","name":{"en":"Gaoming Tram Line 1","zh-Hans":"高明有轨1号线","zh-Hant":"高明有軌1號線"}},{"id":"gzmtr","colour":"#47403c","fg":"#fff","name":{"en":"Guangzhou Metro","zh-Hans":"广州地铁","zh-Hant":"廣州地鐵"}}]</details>

**Comment by wongchito** [comment]
Hi @CommandBlocktt ,

閣下提供的資料來源解析度過低，無法找到一片連續的同色區域作顏色採集。我們亦無法找到某一顏色點合乎閣下提供的`#47403c`。

請閣下嘗試更換更清晰的來源，並使用sRGB色彩空間採集顏色。多謝！
