### ISSUE TITLE
Resources: New palettes of Prague

### ISSUE THREAD

**Issue by Cta85** [railmapgen/rmg-palette#1253]
**Data source:** 9. Others (Please indicate below)

**Reference link:** https://de.wikipedia.org/wiki/Metro_Prag   https://brandarchive.xyz/identity/prague-metro

**Justification:** Changes:
City-Added the city of Prague
Lines-Added 3 line in operation currently(A,B,C), 1 Line expecting open soon

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{"id":"CZ","name":{"en":"Czechia","zh-Hans":"捷克","de":"Tschechien","zh-Hant":"捷克"},"language":"de"}</details>

<details repo="rmg-palette" type="city">{"id":"prague","country":"CZ","name":{"en":"Prague","zh-Hans":"布拉格","de":"Prag","zh-Hant":"布拉格"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"pra","colour":"#078243","fg":"#fff","name":{"en":"Metro Line A","zh-Hans":"A线","zh-Hant":"A線","de":"Linie A"}},{"id":"prb","colour":"#fad203","fg":"#fff","name":{"en":"Metro Line B","zh-Hans":"B线","zh-Hant":"B線","de":"Linie B"}},{"id":"prc","colour":"#d61220","fg":"#fff","name":{"en":"Metro Line C","zh-Hans":"C线","zh-Hant":"C線","de":"Linie C"}},{"id":"prd","colour":"#002177","fg":"#fff","name":{"en":"Metro Line D","zh-Hans":"D线","zh-Hant":"D線","de":"Linie D"}}]</details>

**Comment by linchen1965** [comment]
Hi, depending on the source you provide, the colour of the Line C you submit is different from the colour from the reference:
(#EA1220 in reference)
Please resubmit the corrected line colour under this issue after correcting the above errors. Thank you for your support of this project!
