### ISSUE TITLE
Resources: New palettes of Nagoya

### ISSUE THREAD

**Issue by Xiao-qian111** [railmapgen/rmg-palette#1255]
**Data source:** 7. 从有损压缩的图片（如 JPG）提取的颜色

**Reference link:** https://cn.bing.com/images/search?view=detailV2&ccid=ToA2R0b7&id=8AADD713223890C10C2F6D266D3D738234FF23E8&thid=OIP.ToA2R0b7VrenZ_CS9oYJuQHaFQ&mediaurl=https%3a%2f%2fp1.ssl.qhmsg.com%2ft01b64416fc16e64cb2.png&cdnurl=https%3a%2f%2fts1.cn.mm.bing.net%2fth%2fid%2fR-C.4e80364746fb56b7a767f092f68609b9%3frik%3d6CP%252fNIJzPW0mbQ%26pid%3dImgRaw%26r%3d0&exph=568&expw=800&q=%e5%90%8d%e5%8f%a4%e5%b1%8b%e5%9c%b0%e9%93%81&simid=608035677599249558&FORM=IRPRST&ck=A3D34E0FDA9FB3A99AE359736216E20A&selectedIndex=14&itb=0&ajaxhist=0&ajaxserp=0

**Justification:** 添加两条线路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"nagoya","country":"JP","name":{"en":"Nagoya","zh-Hans":"名古屋","zh-Hant":"名古屋","ja":"名古屋","ko":"나고야"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"h","colour":"#fab123","fg":"#fff","name":{"en":"Higashiyama Line","zh-Hans":"东山线","zh-Hant":"東山線","ja":"東山線","ko":"히가시야마선"}},{"id":"m","colour":"#b074d6","fg":"#fff","name":{"en":"Meijo Line","zh-Hans":"名城线","zh-Hant":"名城線","ja":"名城線","ko":"메이조선"}},{"id":"e","colour":"#b074d6","fg":"#fff","name":{"en":"Meiko Line","zh-Hans":"名港线","zh-Hant":"名港線","ja":"名港線","ko":"메이코선"}},{"id":"t","colour":"#009bbf","fg":"#fff","name":{"en":"Tsurumai Line","zh-Hans":"鹤舞线","zh-Hant":"鶴舞線","ja":"鶴舞線","ko":"쓰루마이선"}},{"id":"s","colour":"#c92f44","fg":"#fff","name":{"en":"Sakura-dori Line","zh-Hans":"樱通线","zh-Hant":"櫻通線","ja":"桜通線","ko":"사쿠라도리선"}},{"id":"k","colour":"#fc78b4","fg":"#fff","name":{"en":"Kamiiida Line","zh-Hans":"上饭田线","zh-Hant":"上飯田線","ja":"上飯田線","ko":"가미이다선"}},{"id":"y","colour":"#343f97","fg":"#fff","name":{"en":"Aonami Line/Yutorito Line/Linimo","zh-Hans":"青波线/尤托里线/东部丘陵线","zh-Hant":"青波線/尤托裏線/東部丘陵線","ja":"あおなみ缐/ゆとりーとライソ/リニモ"}},{"id":"mk","colour":"#ff7f7f","fg":"#fff","name":{"en":"Menelsu Komaki Line","zh-Hans":"名铁小牧线","zh-Hant":"名鉄小牧線","ja":"名鉄小牧線"}}]</details>

**Comment by linchen1965** [comment]
您好，您提交的图片并非来自我们认可的来源，请您更换来源提交，感谢您的贡献。

**Comment by Windows-Taskmgr** [comment]
您好，由于此议题已经超过一个月未修改，我们将关闭此议题，感谢理解！
