### ISSUE TITLE
Resources: New palettes of Changsha

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmg-palette#1278]
**Data source:** 7. 从有损压缩的图片（如 JPG）提取的颜色

**Reference link:** https://www.hncsmtr.com/webapp/dt/yyt.jsp

**Justification:** 图片来自长沙轨道交通官网

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"changsha","country":"CN","name":{"en":"Changsha","zh-Hans":"长沙","zh-Hant":"長沙"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"cs1","colour":"#DA291C","fg":"#fff","name":{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"cs2","colour":"#8DC8E8","fg":"#fff","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"cs3","colour":"#C0DF16","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"cs4","colour":"#A51890","fg":"#fff","name":{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號線"}},{"id":"cs5","colour":"#FFD100","fg":"#000","name":{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號線"}},{"id":"cs6","colour":"#0077C8","fg":"#fff","name":{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線"}},{"id":"cs7","colour":"#009739","fg":"#fff","name":{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號線"}},{"id":"cs8","colour":"#D9027D","fg":"#fff","name":{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號線"}},{"id":"cs9","colour":"#00BFB2","fg":"#000","name":{"en":"Line 9","zh-Hans":"9号线","zh-Hant":"9號線"}},{"id":"cs10","colour":"#81312F","fg":"#fff","name":{"en":"Line 10","zh-Hans":"10号线","zh-Hant":"10號線"}},{"id":"cs11","colour":"#DE7C00","fg":"#fff","name":{"en":"Line 11","zh-Hans":"11号线","zh-Hant":"11號線"}},{"id":"cs12","colour":"#9063CD","fg":"#fff","name":{"en":"Line 12","zh-Hans":"12号线","zh-Hant":"12號線"}},{"id":"intercitytrain","colour":"#083d23","fg":"#fff","name":{"en":"Changsha-Zhuzhou-Xiangtan Inter-city Train","zh-Hans":"长株潭城际（S1）","zh-Hant":"長株潭城際（S1）"}},{"id":"maglev","colour":"#F891A5","fg":"#fff","name":{"en":"S2","zh-Hans":"S2线","zh-Hant":"S2線"}},{"id":"csxl","colour":"#db7093","fg":"#fff","name":{"en":"Xihuan Line","zh-Hans":"西环线","zh-Hant":"西環線"}},{"id":"bus","colour":"#ec931f","fg":"#fff","name":{"en":"Mango Bus","zh-Hans":"芒果巴士","zh-Hant":"芒果巴士"}}]</details>

**Comment by Minwtraft** [comment]
磁浮快线线路代码未改动，是为了便于导入文件时颜色被正确识别

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
