### ISSUE TITLE
Resources: New palettes of Central Area (Tokai)

### ISSUE THREAD

**Issue by zhouaomiao** [railmapgen/rmg-palette#1312]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

(REPLACE ME/替代我)
**Data source:** 6. 从 PDF 文件提取的颜色

**Reference link:** https://www.meitetsu.co.jp/train/station_info/rosenzu.pdf

**Justification:** 名古屋鉄道

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"jrtokai","country":"JP","name":{"en":"Central Area (Tokai)","zh-Hans":"中部地方（东海）","ja":"中部地方（東海）","zh-Hant":"中部地方（東海）"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"ca","colour":"#f57615","fg":"#fff","name":{"en":"Tōkaidō Main Line","zh-Hans":"东海道本线","ja":"東海道本線","zh-Hant":"東海道本線"}},{"id":"cb","colour":"#40743c","fg":"#fff","name":{"en":"Gotemba Line","zh-Hans":"御殿场线","ja":"御殿場線","zh-Hant":"御殿場線"}},{"id":"cc","colour":"#6f2d98","fg":"#fff","name":{"en":"Minobu Line","zh-Hans":"身延线","ja":"身延線","zh-Hant":"身延線"}},{"id":"cd","colour":"#75a2db","fg":"#fff","name":{"en":"Iida Line","zh-Hans":"饭田线","ja":"飯田線","zh-Hant":"飯田線"}},{"id":"ce","colour":"#83502f","fg":"#fff","name":{"en":"Taketoyo Line","zh-Hans":"武丰线","ja":"武豊線","zh-Hant":"武豐線"}},{"id":"cf","colour":"#3b6c9c","fg":"#fff","name":{"en":"Chūō Main Line","zh-Hans":"中央本线","ja":"中央本線","zh-Hant":"中央本線"}},{"id":"cg","colour":"#9c1618","fg":"#fff","name":{"en":"Takayama Main Line","zh-Hans":"高山本线","ja":"高山本線","zh-Hant":"高山本線"}},{"id":"ci","colour":"#bfba2f","fg":"#fff","name":{"en":"Taita Line","zh-Hans":"太多线","ja":"太多線","zh-Hant":"太多線"}},{"id":"cj","colour":"#3dbc87","fg":"#fff","name":{"en":"Kansai Main Line","zh-Hans":"关西本线","ja":"関西本線","zh-Hant":"關西本線"}},{"id":"NH/TK","colour":"#ce182a","fg":"#fff","name":{"en":"Meitetsu Nagoya Line, Toyokawa Line","zh-Hans":"名铁名古屋本线·丰川线","ja":"名鉄名古屋本線・豊川線","zh-Hant":"名鐵名古屋本線·豐川線"}},{"id":"MU/GN","colour":"#6558a5","fg":"#fff","name":{"en":"Meitetsu Mikawa Line, Nishio Line, Gamagōri Line","zh-Hans":"名铁三河线·西尾线·蒲郡线","ja":"名鉄三河線・西尾線・蒲郡線","zh-Hant":"名鐵三河線·西尾線·䈬郡線"}},{"id":"MY/TT","colour":"#9bab43","fg":"#fff","name":{"en":"Meitetsu Mikawa Line, Toyota Line","zh-Hans":"名铁三河线·丰田线","ja":"名鉄三河線・豊田線","zh-Hant":"名鐵三河線·豐田線"}},{"id":"TA","colour":"#0072bc","fg":"#fff","name":{"en":"Meitetsu Tokoname Line, Airport Line","zh-Hans":"名铁常滑线·机场线","ja":"名鉄常滑線・空港線","zh-Hant":"名鐵常滑線·機場線"}},{"id":"CH","colour":"#6c6d70","fg":"#fff","name":{"en":"Meitetsu Chikkō Line","zh-Hans":"名铁筑港线","ja":"名鉄築港線","zh-Hant":"名鐵築港線"}},{"id":"KC","colour":"#06aeef","fg":"#fff","name":{"en":"Meitetsu Kōwa Line, Chita Line","zh-Hans":"名铁河和线·知多新线","ja":"名鉄河和線・知多新線","zh-Hant":"名鐵河和線·知多新線"}},{"id":"TB/BS","colour":"#f15920","fg":"#fff","name":{"en":"Meitetsu Tsushima Line, Bisai Line","zh-Hans":"名铁津岛线·尾西线","ja":"名鉄津島線・尾西線","zh-Hant":"名鐵津島線·尾西線"}},{"id":"TH","colour":"#d09928","fg":"#fff","name":{"en":"Meitetsu Takehana Line, Hashima Line","zh-Hans":"名铁竹鼻线·羽岛线","ja":"名鉄竹鼻線・羽島線","zh-Hant":"名鐵竹鼻線·羽島線"}},{"id":"IY/HM/KG","colour":"#0a914b","fg":"#fff","name":{"en":"Meitetsu Inuyama Line, Hiromi Line, Kakamigahara Line","zh-Hans":"名铁犬山线·广见线·各务原线","ja":"名鉄犬山線・広見線・各務原線","zh-Hant":"名鐵犬山線·廣見線·各務原線"}},{"id":"KM","colour":"#ef59a1","fg":"#fff","name":{"en":"Meitetsu Komaki Line","zh-Hans":"名铁小牧线","ja":"名鉄小牧線","zh-Hant":"名鐵小牧線"}},{"id":"ST","colour":"#802990","fg":"#fff","name":{"en":"Meitetsu Seto Line","zh-Hans":"名铁濑户线","ja":"名鉄瀬戸線","zh-Hant":"名鐵瀨戶線"}}]</details>

**Comment by wongchito** [comment]
Hi @zhouaomiao ,

請於提交Issue前移除「替代我」字樣，以便機械人識別及執行自動化。多謝！

由於提交時間距今已逾2個月，因此現關閉該Issue。觀迎閣下更新提交。
