### ISSUE TITLE
Resources: New palettes of Hefei

### ISSUE THREAD

**Issue by ARE-hfL3** [railmapgen/rmg-palette#1313]
**Data source:** 9. 其他（请于下方注明）

**Reference link:** https://hfgdjt.com/X5SiRAm5HFKiXl34HodvfAzQh0bTgqZWS_ED%2BlOl4Be%2B7_KZb7tBSdx6HsgH0B2p?encrypt=1

**Justification:** S1号线未来会延伸12号线，提前加入于线路代码

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"hefei","country":"CN","name":{"zh-Hans":"合肥","zh-Hant":"合肥","en":"Hefei"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"hf1","colour":"#e61e25","fg":"#fff","name":{"zh-Hans":"1号线","en":"Line 1","zh-Hant":"1號線"}},{"id":"hf2","colour":"#0168b3","fg":"#fff","name":{"zh-Hans":"2号线","en":"Line 2","zh-Hant":"2號線"}},{"id":"hf3","colour":"#00843d","fg":"#fff","name":{"zh-Hans":"3号线","en":"Line 3","zh-Hant":"3號線"}},{"id":"hf4","colour":"#f79727","fg":"#fff","name":{"zh-Hans":"4号线","en":"Line 4","zh-Hant":"4號線"}},{"id":"hf5","colour":"#c1d72f","fg":"#fff","name":{"zh-Hans":"5号线","en":"Line 5","zh-Hant":"5號線"}},{"id":"hf6","colour":"#c99fcd","fg":"#fff","name":{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號線"}},{"id":"hf7","colour":"#f1cc40","fg":"#fff","name":{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號線"}},{"id":"hf8","colour":"#65aee3","fg":"#fff","name":{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號線"}},{"id":"hf12s1","colour":"#bca488","fg":"#fff","name":{"en":"Line S1","zh-Hans":"S1号线","zh-Hant":"S1號線"}}]</details>

**Comment by linchen1965** [comment]
您好，由于线路代码更改不会影响调色板的显示，鉴于该issue没有对调色板进行实质性的更改，我们无法接纳此次更新，感谢您对本项目的支持！
