### ISSUE TITLE
Resources: New palettes of 

### ISSUE THREAD

**Issue by sqdodlapf** [railmapgen/rmg-palette#1318]
**Data source:** 8. Wikipedia

**Reference link:** http://www.2944402543@qq.com

**Justification:** 无

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"","country":"","name":{"en":"","zh-Hans":"","zh-Hant":""}}</details>

<details repo="rmg-palette" type="lines">[{"id":"","colour":"#00ffff","fg":"#fff","name":{"en":"line1","zh-Hans":"1号线"}}]</details>

**Comment by linchen1965** [comment]
Closed as empty issue
