### ISSUE TITLE
Resources: New palettes of Hefei

### ISSUE THREAD

**Issue by growingtochase** [railmapgen/rmg-palette#132]
**Justification:** 提交合肥轨道交通线路 

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hefei",
    "country": "CN",
    "name": {
        "zh": "合肥",
        "en": "Hefei"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "hf1",
        "colour": "#e61e25",
        "fg": "#fff",
        "name": {
            "zh": "1号线",
            "en": "Line 1"
        }
    },
    {
        "id": "hf2",
        "colour": "#0168b3",
        "fg": "#fff",
        "name": {
            "zh": "2号线",
            "en": "Line 2"
        }
    },
    {
        "id": "hf3",
        "colour": "#00843d",
        "fg": "#fff",
        "name": {
            "zh": "3号线",
            "en": "Line 3"
        }
    },
    {
        "id": "hf4",
        "colour": "#f79727",
        "fg": "#fff",
        "name": {
            "zh": "4号线",
            "en": "Line 4"
        }
    },
    {
        "id": "hf5",
        "colour": "#c1d72f",
        "fg": "#fff",
        "name": {
            "zh": "5号线",
            "en": "Line5"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，虽然很感谢你对本项目部所做的贡献，但请问你方便的话是否能够提供线路颜色的来源呢？

我们不会接受任何无颜色来源的投稿

**Comment by growingtochase** [comment]
来源图片链接:http://www.hfgdjt.com/smap/images/xian.png

 图片是合肥轨道交通官网上的
从该图片线路上直接取色
@52PD

**Comment by 52PD** [comment]
> 来源图片链接:http://www.hfgdjt.com/smap/images/xian.png
>
> 图片是合肥轨道交通官网上的
> 从该图片线路上直接取色

好的，感谢提供来源。我们会在近期将你提供的线路颜色整合进项目中，敬请期待。
再次感谢你对本项目的支持🙏。
