### ISSUE TITLE
Resources: New palettes of Kaohsiung

### ISSUE THREAD

**Issue by Benson20110806** [railmapgen/rmg-palette#1326]
**Data source:** 9. 其他（請於下方註明）

**Reference link:** https://youtu.be/5WuicsHuSlg?si=AjSpKJZ-SHxFu51J

**Justification:** 本影片講述1年前的最新規劃
佛光山線和右昌線已併入紫線
藍線與黃線路廊相近，可視為已併入黃線

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"kaohsiung","country":"TW","name":{"en":"Kaohsiung","zh-Hans":"高雄","zh-Hant":"高雄"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"red","colour":"#e20b65","fg":"#fff","name":{"en":"Red Line","zh-Hans":"红线","zh-Hant":"紅線"}},{"id":"orange","colour":"#faa73f","fg":"#fff","name":{"en":"Orange Line","zh-Hans":"橘线","zh-Hant":"橘線"}},{"id":"circular","colour":"#7cbd52","fg":"#fff","name":{"en":"Circular Line (KLRT)","zh-Hans":"环状轻轨","zh-Hant":"環狀輕軌"}},{"id":"y","colour":"#ffc100","fg":"#000","name":{"en":"Yellow Line","zh-Hans":"黄线","zh-Hant":"黃線"}},{"id":"purple","colour":"#c100ff","fg":"#fff","name":{"en":"Purple Line","zh-Hans":"紫线","zh-Hant":"紫線"}},{"id":"cyan","colour":"#00bfff","fg":"#fff","name":{"en":"Cyan Line","zh-Hans":"青线","zh-Hant":"青線"}},{"id":"silver","colour":"#929292","fg":"#fff","name":{"en":"Silver Line","zh-Hans":"银线","zh-Hant":"銀線"}},{"id":"pink","colour":"#FFC0CB","fg":"#fff","name":{"en":"Pink Line","zh-Hans":"粉红线","zh-Hant":"粉紅線"}}]</details>

**Comment by linchen1965** [comment]
您好，由於您提交的Reference link並非我們認可的來源，很抱歉我們無法接納此次更新，感謝您對項目的支持。
