### ISSUE TITLE
Resources: New palettes of Greater KL/Klang Valley

### ISSUE THREAD

**Issue by aaronyz2007** [railmapgen/rmg-palette#1328]
**Data source:** 6. 从 PDF 文件提取的颜色

**Reference link:** https://myrapid.com.my/wp-content/uploads/2023/12/20230808_Transit-Map_Terminal1n2-c.pdf

**Justification:** 各线路标识色与官网（rapid KL）提供线路图中的标识色有较严重的误差，因此根据官网线路图pdf进行取色更改，同时原版颜色的巴生港线（2号线）和格拉那再也线（5号线）色差过小难以辨别，根据线路图更改后更易辨别。
由于环状线（13号线）近期还无法开通，官方线路图上未有标注，因此暂时不进行更改

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"klangvalley","country":"MY","name":{"en":"Greater KL/Klang Valley","ms":"Kuala Lumpur Raya/Lembah Klang","zh-Hans":"大吉隆坡/巴生谷","zh-Hant":"大吉隆坡/巴生谷"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"kl1","colour":"#0168b3","fg":"#fff","name":{"en":"KTM Seremban Line","ms":"KTM Laluan Seremban","zh-Hans":"芙蓉线","zh-Hant":"芙蓉線"}},{"id":"kl2","colour":"#ee2e22","fg":"#fff","name":{"en":"KTM Port Klang Line","ms":"KTM Laluan Port Klang","zh-Hans":"巴生港线","zh-Hant":"巴生港線"}},{"id":"kl3","colour":"#f4901d","fg":"#fff","name":{"en":"LRT Ampang Line","ms":"LRT Laluan Ampang","zh-Hans":"安邦线","zh-Hant":"安邦線"}},{"id":"kl4","colour":"#8b0a02","fg":"#fff","name":{"en":"LRT Sri Petaling Line","ms":"LRT Laluan Sri Petaling","zh-Hans":"大城堡线","zh-Hant":"大城堡線"}},{"id":"kl5","colour":"#ed154e","fg":"#fff","name":{"en":"LRT Kelana Jaya Line","ms":"LRT Laluan Kelana Jaya","zh-Hans":"格拉那再也线","zh-Hant":"格拉那再也線"}},{"id":"kl6","colour":"#a0218c","fg":"#fff","name":{"en":"ERL KLIA Ekspres Line","ms":"ERL Laluan KLIA Ekspres","zh-Hans":"吉隆坡机场快线","zh-Hant":"吉隆坡機場快線"}},{"id":"kl7","colour":"#00a0b0","fg":"#fff","name":{"en":"ERL KLIA Transit Line","ms":"ERL Laluan KLIA Transit","zh-Hans":"吉隆坡机场支线","zh-Hant":"吉隆坡機場支線"}},{"id":"kl8","colour":"#8bc63e","fg":"#fff","name":{"en":"KL Monorail Line","ms":"Laluan Monorel KL","zh-Hans":"吉隆坡单轨","zh-Hant":"吉隆坡單軌"}},{"id":"kl9","colour":"#00843d","fg":"#fff","name":{"en":"MRT Sungai Buloh-Kajang Line","ms":"MRT Laluan Sungai Buloh-Kajang","zh-Hans":"加影线","zh-Hant":"加影線"}},{"id":"kl10","colour":"#827c00","fg":"#fff","name":{"en":"KTM Skypark Line","ms":"KTM Laluan Skypark","zh-Hans":"天空花园线","zh-Hant":"天空花園線"}},{"id":"kl11","colour":"#00a5e3","fg":"#fff","name":{"en":"LRT Shah Alam Line","ms":"LRT Laluan Shah Alam","zh-Hans":"莎阿南线","zh-Hant":"莎阿南線"}},{"id":"kl12","colour":"#fed105","fg":"#fff","name":{"en":"MRT Putrajaya Line","ms":"MRT Laluan Putrajaya","zh-Hans":"布城线","zh-Hant":"布城線"}},{"id":"kl13","colour":"#685BC7","fg":"#fff","pantone":"2725 C","name":{"en":"MRT Circle Line","ms":"MRT Laluan Lingkaran","zh-Hans":"环状线","zh-Hant":"環狀線"}},{"id":"klb1","colour":"#00502e","fg":"#fff","name":{"en":"BRT Sunway Line","ms":"BRT Laluan Sunway","zh-Hans":"双威BRT","zh-Hant":"雙威BRT"}}]</details>

**Comment by thekingofcity** [comment]
Hi, thanks for your contribution. Your work is merged and will be available soon :)
