### ISSUE TITLE
Resources: New palettes of Greater KL/Klang Valley

### ISSUE THREAD

**Issue by datosiri** [railmapgen/rmg-palette#1338]
**Data source:** 1. Design standard published in the official website

**Reference link:** https://www.mymrt.com.my/projects/travel-with-mrt/

**Justification:** The station code can be find for Rapid KL at
https://myrapid.com.my/bus-train/rapid-kl/lrt/
(MRT can be also find at MRT Section)

For KTM,
https://www.researchgate.net/figure/KTM-Komuter-route-map_fig1_356411414

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"klangvalley","country":"MY","name":{"en":"Greater KL/Klang Valley","ms":"Kuala Lumpur Raya/Lembah Klang","zh-Hans":"大吉隆坡/巴生谷","zh-Hant":"大吉隆坡/巴生谷"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"KA/C","colour":"#0000ff","fg":"#fff","name":{"en":"KTM Seremban Line","ms":"KTM Laluan Seremban","zh-Hans":"芙蓉线","zh-Hant":"芙蓉線"}},{"id":"KB/D","colour":"#c80000","fg":"#fff","name":{"en":"KTM Port Klang Line","ms":"KTM Laluan Port Klang","zh-Hans":"巴生港线","zh-Hant":"巴生港線"}},{"id":"AG","colour":"#ff8000","fg":"#fff","name":{"en":"LRT Ampang Line","ms":"LRT Laluan Ampang","zh-Hans":"安邦线","zh-Hant":"安邦線"}},{"id":"SP","colour":"#8b0a02","fg":"#fff","name":{"en":"LRT Sri Petaling Line","ms":"LRT Laluan Sri Petaling","zh-Hans":"大城堡线","zh-Hant":"大城堡線"}},{"id":"KJ","colour":"#ff0000","fg":"#fff","name":{"en":"LRT Kelana Jaya Line","ms":"LRT Laluan Kelana Jaya","zh-Hans":"格拉那再也线","zh-Hant":"格拉那再也線"}},{"id":"KX","colour":"#a0218c","fg":"#fff","name":{"en":"ERL KLIA Ekspres Line","ms":"ERL Laluan KLIA Ekspres","zh-Hans":"吉隆坡机场快线","zh-Hant":"吉隆坡機場快線"}},{"id":"KT","colour":"#00a0b0","fg":"#fff","name":{"en":"ERL KLIA Transit Line","ms":"ERL Laluan KLIA Transit","zh-Hans":"吉隆坡机场支线","zh-Hant":"吉隆坡機場支線"}},{"id":"MR","colour":"#8bc63e","fg":"#fff","name":{"en":"KL Monorail Line","ms":"Laluan Monorel KL","zh-Hans":"吉隆坡单轨","zh-Hant":"吉隆坡單軌"}},{"id":"KG","colour":"#00843d","fg":"#fff","name":{"en":"MRT Sungai Buloh-Kajang Line","ms":"MRT Laluan Sungai Buloh-Kajang","zh-Hans":"加影线","zh-Hant":"加影線"}},{"id":"KS","colour":"#827c00","fg":"#fff","name":{"en":"KTM Skypark Line","ms":"KTM Laluan Skypark","zh-Hans":"天空花园线","zh-Hant":"天空花園線"}},{"id":"SA","colour":"#00a5e3","fg":"#fff","name":{"en":"LRT Shah Alam Line","ms":"LRT Laluan Shah Alam","zh-Hans":"莎阿南线","zh-Hant":"莎阿南線"}},{"id":"PY","colour":"#fed105","fg":"#000","name":{"en":"MRT Putrajaya Line","ms":"MRT Laluan Putrajaya","zh-Hans":"布城线","zh-Hant":"布城線"}},{"id":"CC","colour":"#685BC7","fg":"#fff","pantone":"2725 C","name":{"en":"MRT Circle Line","ms":"MRT Laluan Lingkaran","zh-Hans":"环状线","zh-Hant":"環狀線"}},{"id":"SB","colour":"#00502e","fg":"#fff","name":{"en":"BRT Sunway Line","ms":"BRT Laluan Sunway","zh-Hans":"双威BRT","zh-Hant":"雙威BRT"}}]</details>

**Comment by linchen1965** [comment]
您好，由于早前已有时效性更强的颜色更新(2024年7月)，而您提供的资料来源更新日期为2023年6月，因此我们不能接纳您的更新。感谢您对项目的支持！
