### ISSUE TITLE
Resources: New palettes of Hangzhou

### ISSUE THREAD

**Issue by PaladinNeptune** [railmapgen/rmg-palette#134]
**Justification:** 杭州地铁3号线应为黄底黑字，杭绍城际正式名称应为绍兴1号线。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hangzhou",
    "country": "CN",
    "name": {
        "en": "Hangzhou",
        "zh": "杭州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "hz1",
        "colour": "#DF4661",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "hz2",
        "colour": "#DE7C00",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "hz3",
        "colour": "#FAC62B",
        "fg": "#000",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "hz4",
        "colour": "#6CC24A",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "hz5",
        "colour": "#00AEC7",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "hz6",
        "colour": "#0072CE",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "hz7",
        "colour": "#87189D",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "hz8",
        "colour": "#AC145A",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "hz9",
        "colour": "#BE4D00",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "hz10",
        "colour": "#AA8A00",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "hz16",
        "colour": "#FFB25B",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "sx1",
        "colour": "#C5003E",
        "fg": "#fff",
        "name": {
            "en": "Shaoxing Line 1",
            "zh-Hans": "绍兴1号线",
            "zh-Hant": "紹興1號線"
        }
    },
    {
        "id": "hhic",
        "colour": "#9BCBEB",
        "fg": "#fff",
        "name": {
            "en": "Hangzhou-Haining Intercity",
            "zh-Hans": "杭海城际",
            "zh-Hant": "杭海城際"
        }
    }
]</details>

**Comment by wongchito** [comment]
若杭州市內車站再無「杭紹城際」標識，請另開紹興調色盤，再將其從杭州調色盤中移除。否則，請參考廣州廣佛線/佛山1號線處理方法。
