### ISSUE TITLE
Resources: New palettes of Zhongshan

### ISSUE THREAD

**Issue by CaiFengXiang0709** [railmapgen/rmg-palette#1352]
**Data source:** 1. 官方网站发布的设计标准

**Reference link:** https://td.gd.gov.cn/dtxw_n/gdjrxw/content/post_4144943.html

**Justification:** 添加中山的第一条线路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"zhongshan","country":"CN","name":{"en":"Zhongshan","zh-Hans":"中山","zh-Hant":"中山"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"gz18s","colour":"#0047ba","fg":"#fff","name":{"en":"Guangzhou Metro Line 18 South Extension Section (Nanzhong Intercity)","zh-Hans":"广州地铁18号线南延段（南中城际）","zh-Hant":"廣州地鐵18號線南延段（南中城際）"}}]</details>

**Comment by wongchito** [comment]
Hi @CaiFengXiang0709 ,

根據 #1359， 廣州地鐵18號線顏色已更新為`#3040b6`，因此我們將相應更新閣下提交的調色盤。另，我們亦會規範化路線命名方式。
