### ISSUE TITLE
Resources: New palettes of Ningbo

### ISSUE THREAD

**Issue by HBreadHuang** [railmapgen/rmg-palette#1389]
**Data source:** 7. 从有损压缩的图片（如 JPG）提取的颜色

**Reference link:** https://mp.weixin.qq.com/s/54s1D07IYXBtQoilqSt_3Q

**Justification:** 勘误既有色号、添加新线色号

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"ningbo","country":"CN","name":{"en":"Ningbo","zh-Hans":"宁波","zh-Hant":"寧波"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"nb1","colour":"#1590cb","fg":"#fff","name":{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號缐"}},{"id":"nb2","colour":"#d80e19","fg":"#fff","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號缐"}},{"id":"nb3","colour":"#ff9800","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號缐"}},{"id":"nb4","colour":"#81ba2d","fg":"#fff","name":{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號缐"}},{"id":"nb5","colour":"#0a1f8f","fg":"#fff","name":{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號缐"}},{"id":"nb6","colour":"#167f3d","fg":"#fff","name":{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號缐"}},{"id":"nb7","colour":"#7c572d","fg":"#fff","name":{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號缐"}},{"id":"nb8","colour":"#d33a94","fg":"#fff","name":{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號缐"}},{"id":"nb10","colour":"#9a8dc3","fg":"#fff","name":{"en":"Line 10","zh-Hans":"10号线","zh-Hant":"10號缐"}},{"id":"nb12","colour":"#42bdca","fg":"#fff","name":{"en":"Line 12","zh-Hans":"12号线","zh-Hant":"12號缐"}}]</details>

**Comment by linchen1965** [comment]
您好，由于您提供的来源仅包括10号线的标识色，而您提交的palette当中包含来源没有的12号线，如果您不能提供该色板得到可靠来源，那么最终我们汇入项目中的颜色模版将不会包括12号线。

**Comment by HBreadHuang** [comment]
十二号线标识色来源如下，本人曾于今年6月初在宁波市一城建交流群截获设计稿切片，内容与四号线金山路站慈城方向月台于今年7月底更换的通长内容一致





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "railmapgen/rmg-palette"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月12日(星期六) 晚上9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [railmapgen/rmg-palette] Resources: New palettes of Ningbo (Issue #1389)





 
您好，由于您提供的来源仅包括10号线的标识色，而您提交的palette当中包含来源没有的12号线，如果您不能提供该色板得到可靠来源，那么最终我们汇入项目中的颜色模版将不会包括12号线。

**Comment by HBreadHuang** [comment]
![2024-06-04 154949](https://github.com/user-attachments/assets/1634d632-7482-45aa-beaa-1f6b34ee62d9)
![IMG_8965](https://github.com/user-attachments/assets/f347e66d-8927-4e94-b5a9-8ebb11e32028)

**Comment by wongchito** [comment]
Hi @HBreadHuang ,

由於早前已有關於寧波的顏色更新(#1263)，而閣下提供的資料來源清晰度不佳，因此我們不能接納閣下的更新。感謝閣下的支持！

**Comment by HBreadHuang** [comment]
> Hi @HBreadHuang ,
> 
> 由於早前已有關於寧波的顏色更新(#1263)，而閣下提供的資料來源清晰度不佳，因此我們不能接納閣下的更新。感謝閣下的支持！

#1263号更新仅包含1-8号线，无10、12号线，故本人的更新仍具有有效性

**Comment by wongchito** [comment]
Hi @HBreadHuang ，

#1263 包含1-12號線的顏色，且其包含路線名稱的修正。稍後時間閣下將能於「調色盤」應用程式中瀏覽。

如閣下認為顏色需進一步更新，歡迎閣下開啟新的Issue並提交更優的顏色及其來源。

感謝閣下的關注！

**Comment by HBreadHuang** [comment]
#1263之10號綫顔色為5號綫導向標識製作方使用的錯誤顔色，12號縣則爲舊有方案（現為青色），9、11號綫目前則未得到甬軌官方證實

**Comment by HBreadHuang** [comment]
![20240728 宁波2号线鼓楼站1a](https://github.com/user-attachments/assets/4a6cdd42-b2ca-465d-bb82-ea9d2456be15)
![20240628 宁波5号线骆驼桥站站台3](https://github.com/user-attachments/assets/aa391cfc-65f6-43c1-a15f-2d1e5fb6870f)

**Comment by wongchito** [comment]
Hi @HBreadHuang ,

感謝閣下持續提供相關資訊。對於閣下提及的4條路線的顏色，煩請閣下開啟一個新的Issue，提交更新後的調色盤，並提供以下說明：

10號線：詳細說明上述兩圖的製作時間，如何判定其中一條路線的廠家使用了錯誤的顏色

12號線：無需額外敘述

9號線及11號線：由於維基百科屬於可信任的資料來源，而我們亦接納尚未開通路線之顏色，因此我們不會移除

多謝閣下的貢獻！

**Comment by linchen1965** [comment]
> Hi @HBreadHuang ,
> 
> 感謝閣下持續提供相關資訊。對於閣下提及的4條路線的顏色，煩請閣下開啟一個新的Issue，提交更新後的調色盤，並提供以下說明：
> 
> 10號線：詳細說明上述兩圖的製作時間，如何判定其中一條路線的廠家使用了錯誤的顏色
> 
> 12號線：無需額外敘述
> 
> 9號線及11號線：由於維基百科屬於可信任的資料來源，而我們亦接納尚未開通路線之顏色，因此我們不會移除
> 
> 多謝閣下的貢獻！

9~12号线均为未开通，但#1263当中的维基百科链接并无任何关于9、11号线的信息，属于是无中生有

**Comment by wongchito** [comment]
> 
> 9~12号线均为未开通，但#1263当中的维基百科链接并无任何关于9、11号线的信息，属于是无中生有

維基百科中寧波軌道交通模版源程式碼來自以下連結，其包含9號線及11號線：

https://zh.wikipedia.org/wiki/Module:Adjacent_stations/%E5%AE%81%E6%B3%A2%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A

**Comment by HBreadHuang** [comment]
> Hi @HBreadHuang ,
> 
> 感謝閣下持續提供相關資訊。對於閣下提及的4條路線的顏色，煩請閣下開啟一個新的Issue，提交更新後的調色盤，並提供以下說明：
> 
> 10號線：詳細說明上述兩圖的製作時間，如何判定其中一條路線的廠家使用了錯誤的顏色
> 
> 12號線：無需額外敘述
> 
> 9號線及11號線：由於維基百科屬於可信任的資料來源，而我們亦接納尚未開通路線之顏色，因此我們不會移除
> 
> 多謝閣下的貢獻！

#1429 已提交，暫保留9、11號線顔色，待開通運營前夕（預計于2030年前後）甬軌官方發佈相關資訊后另行更改
