### ISSUE TITLE
Resources: New palettes of Cork Kent

### ISSUE THREAD

**Issue by IrishRail** [railmapgen/rmg-palette#1397]
**Data source:** 1. Design standard published in the official website

**Reference link:** https://idontknow.ie

**Justification:**                                         

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"cknt","country":"IE","name":{"en":"Cork Kent","ga":"Corcaigh Ceannt"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"int","colour":"#148f16","fg":"#fff","name":{"en":"InterCity","zh-Hans":"                   ","zh-Hant":"                 "}},{"id":"cmu","colour":"#c0c0c0","fg":"#fff","name":{"en":"Commuter","zh-Hans":"                     ","zh-Hant":"                         "}}]</details>

**Comment by linchen1965** [comment]
Hi, the Reference link does not exist, please attach a valid Reference link
