### ISSUE TITLE
Adding color palettes of Bucharest, Lisbon, Daegu and Eskişehir

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmg-palette#14]
[lisboa.txt](https://github.com/railmapgen/rmg-palette/files/7920424/lisboa.txt)
[bucharest.txt](https://github.com/railmapgen/rmg-palette/files/7920425/bucharest.txt)
[daegu.txt](https://github.com/railmapgen/rmg-palette/files/7920503/daegu.txt)
[eskisehir.txt](https://github.com/railmapgen/rmg-palette/files/7920504/eskisehir.txt)
Adding color palettes of 4 cities.

**Comment by thekingofcity** [comment]
That's a speed of light⚡

But as we are in the very early stage of rmg-palette, we didn't have the chance to update the wiki. The new process will be greatly simplified and I'll let you know in the coming days. Only small lines need to be updated and lots of TS type will be removed.

**Comment by thekingofcity** [comment]
Hi, we update the [wiki](https://github.com/railmapgen/rmg-palette/wiki/How-to-add-color-palette) and invite you to update these data. Feel free to report any inconvenience in the new procedure and congrats to you for the very first contributor.

**Comment by linchen1965** [comment]
> to update these data.

Hmm... How can I update these data?

**Comment by linchen1965** [comment]
> Hi, we update the [wiki](https://github.com/railmapgen/rmg-palette/wiki/How-to-add-color-palette) and invite you to update these data. Feel free to report any inconvenience in the new procedure and congrats to you for the very first contributor.

Hmm... How can I update these data?

**Comment by thekingofcity** [comment]
Never mind. Let me use the old format to update the resources but use the new format for the next issue.

PS: The RMG will not be updated before wongchito/RailMapGenerator#229 is fixed.

**Comment by wongchito** [comment]
Hi @linchen1965 , 

Please be aware that language code of Korean is `ko`, which is different from the country code for Republic of Korea `kr`. I have corrected in the released version. Thanks for your contribution.
