### ISSUE TITLE
Resources: New palettes of Paris

### ISSUE THREAD

**Issue by manoofficial303** [railmapgen/rmg-palette#1422]
**Data source:** 2. Design standard published by the official social media

**Reference link:** https://www.youtube.com/@manoo303_hry/featured

**Justification:** Test

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"paris","country":"FR","name":{"en":"Paris","zh-Hans":"巴黎","zh-Hant":"巴黎"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"t1a","colour":"#ff0080","fg":"#fff","name":{"en":"Tram 1A","fr":"Tram 1A","zh-Hans":"t1a","zh-Hant":"t1a"}},{"id":"t1b","colour":"#ff71b8","fg":"#fff","name":{"en":"Tram 1B","fr":"Tram 1B","zh-Hans":"t1b","zh-Hant":"t1b"}},{"id":"b14","colour":"#ff8040","fg":"#fff","name":{"en":"Bus 14","fr":"Bus 14","zh-Hans":"b14","zh-Hant":"b14"}},{"id":"b28","colour":"#c0c0c0","fg":"#fff","name":{"en":"Bus 28","zh-Hans":"b28","zh-Hant":"b28","fr":"Bus 28"}},{"id":"b59","colour":"#c0c0c0","fg":"#fff","name":{"fr":"Bus 59","en":"Bus 59","zh-Hans":"b59","zh-Hant":"b59"}}]</details>

**Comment by linchen1965** [comment]
您好，由于该链接并非我们认可的可靠来源，很抱歉我们无法采纳此次更新，感谢您对项目的支持。
