### ISSUE TITLE
Resources: New palettes of Ningbo

### ISSUE THREAD

**Issue by HBreadHuang** [railmapgen/rmg-palette#1429]
**Data source:** 7. 从有损压缩的图片（如 JPG）提取的颜色

**Reference link:** https://mp.weixin.qq.com/s/JZRDHYhZEmBn3790sphJUA

**Justification:** 勘误7、10、12号线颜色（说明：①5号线新通长于2024年4月中旬开始更换、至5月末已尽数更换，为1-5号线中最早更换通长的线路；②4号线新通长于2024年7月末开始更换、至9月末已尽数更换，同时1、2、3号线部分车站亦更换通长；③5号线由甬轨旗下”智能运营分公司“营运（该公司未来亦将接手6、7、8号线），其洽得的制作方对通长上的7、10号线使用了存在偏差的颜色，正确的标志色为1、2、3、4号线（由另一分公司营运）通长的版本；④甬轨官方尚未在任何场合（包括且不限于“民生e点通”平台）直接回应任何有关9、11号线标志色的问题）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"ningbo","country":"CN","name":{"en":"Ningbo","zh-Hans":"宁波","zh-Hant":"寧波"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"nb1","colour":"#1590ca","fg":"#fff","name":{"en":"Line 1","zh-Hans":"1号线","zh-Hant":"1號線"}},{"id":"nb2","colour":"#d60e19","fg":"#fff","name":{"en":"Line 2","zh-Hans":"2号线","zh-Hant":"2號線"}},{"id":"nb3","colour":"#f39800","fg":"#fff","name":{"en":"Line 3","zh-Hans":"3号线","zh-Hant":"3號線"}},{"id":"nb4","colour":"#abcd03","fg":"#fff","name":{"en":"Line 4","zh-Hans":"4号线","zh-Hant":"4號線"}},{"id":"nb5","colour":"#1d2088","fg":"#fff","name":{"en":"Line 5","zh-Hans":"5号线","zh-Hant":"5號線"}},{"id":"nb6","colour":"#167f3d","fg":"#fff","name":{"en":"Line 6","zh-Hans":"6号线","zh-Hant":"6號缐"}},{"id":"nb7","colour":"#7c572d","fg":"#fff","name":{"en":"Line 7","zh-Hans":"7号线","zh-Hant":"7號缐"}},{"id":"nb8","colour":"#d33a94","fg":"#fff","name":{"en":"Line 8","zh-Hans":"8号线","zh-Hant":"8號缐"}},{"id":"nb9","colour":"#d16d57","fg":"#fff","name":{"en":"Line 9","zh-Hans":"9号线","zh-Hant":"9號線"}},{"id":"nb10","colour":"#9a8dc3","fg":"#fff","name":{"en":"Line 10","zh-Hans":"10号线","zh-Hant":"10號缐"}},{"id":"nb11","colour":"#c8bf40","fg":"#fff","name":{"en":"Line 11","zh-Hans":"11号线","zh-Hant":"11號線"}},{"id":"nb12","colour":"#42bdca","fg":"#fff","name":{"en":"Line 12","zh-Hans":"12号线","zh-Hant":"12號缐"}}]</details>

**Comment by wongchito** [comment]
Hi @HBreadHuang ,

感謝閣下的說明及貢獻！
