### ISSUE TITLE
Resources: New palettes of Macao

### ISSUE THREAD

**Issue by uidsjhncjdk45326** [railmapgen/rmg-palette#1436]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_
**Data source:** 8. Wikipedia

**Reference link:** https://zh.wikipedia.org/zh-tw/%E6%BE%B3%E9%96%80%E8%BC%95%E8%BB%8C

**Justification:** Palette according to Wikipedia

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"macao","country":"MO","name":{"en":"Macao","pt":"Macau","zh-Hans":"澳门","zh-Hant":"澳門"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"taipa","colour":"#96c93c","fg":"#fff","name":{"en":"Taipa Line","pt":"Linha da Taipa","zh-Hans":"氹仔线","zh-Hant":"氹仔線"}},{"id":"peninsula","colour":"#ab744a","fg":"#fff","name":{"en":"Linha da Península de Macau","zh-Hans":"澳门线","zh-Hant":"澳門線"}},{"id":"2afase","colour":"#00BFFF","fg":"#fff","name":{"en":"Linha Oeste","zh-Hans":"澳门半岛西线","zh-Hant":"澳門半島西線"}},{"id":"seacpaivan","colour":"#8966c3","fg":"#fff","name":{"en":"Linha Seac Pai Van","zh-Hans":"石排湾线","zh-Hant":"石排灣線"}},{"id":"hengqin","colour":"#e33c12","fg":"#fff","name":{"en":"Linha de Extensão da Ilha de Hengqin","zh-Hans":"横琴延伸线","zh-Hant":"橫琴延伸線"}},{"id":"leste","colour":"#ffc933","fg":"#fff","name":{"en":"Linha Leste","zh-Hans":"澳氹东线","zh-Hant":"澳氹東線"}},{"id":"hmz","colour":"#f400a1","fg":"#fff","name":{"en":"Linha da Ponte HMZ","zh-Hans":"港珠澳大桥线","zh-Hant":"港珠澳大橋線"}}]</details>

**Comment by 28yfang** [comment]
您好，经检查，您提供的信息有以下问题：
1. 横琴线名称错误，正确的为：简体 - 横琴线，繁体 - 橫琴線，英文 - Hengqin Line，葡萄牙语 - Linha de Hengqin
2. 部分线路的英文名称中写了葡萄牙语名称，请改正。

请在修正后重新提交，并附上本议题编号（#1436），感谢！
