### ISSUE TITLE
Resources: New palettes of Beijing

### ISSUE THREAD

**Issue by htxtianxianghuhtx** [railmapgen/rmg-palette#1444]
**Data source:** 3. Code of design standard published by the government or legislature

**Reference link:** https://dbba.sacinfo.org.cn/stdDetail/dd07f66ad7286140d052b7664d1617f27d9e050cee986b8b2bad00737b873859

**Justification:** 公共交通客运标志 第2部分：城市轨道交通
DB11/T 657.2-2024
发布日期: 2024-03-25
实施日期: 2024-07-01 

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{"id":"beijing","country":"CN","name":{"en":"Beijing","zh-Hans":"北京","zh-Hant":"北京"}}</details>

<details repo="rmg-palette" type="lines">[{"id":"BJ-L1","colour":"#a4343a","fg":"#fff","name":{"zh-Hans":"1号线","zh-Hant":"1號線","en":"Line 1"}},{"id":"BJ-BATONG","colour":"#a4343a","fg":"#fff","name":{"zh-Hans":"八通线","zh-Hant":"八通線","en":"Batong Line"}},{"id":"BJ-L2","colour":"#004b87","fg":"#fff","name":{"zh-Hans":"2号线","zh-Hant":"2號線","en":"Line 2"}},{"id":"BJ-L3","colour":"#c8102e","fg":"#fff","name":{"zh-Hans":"3号线","zh-Hant":"3號線","en":"Line 3"}},{"id":"BJ-L4","colour":"#008c95","fg":"#fff","name":{"zh-Hans":"4号线","zh-Hant":"4號線","en":"Line 4"}},{"id":"BJ-DAXING","colour":"#008c95","fg":"#fff","name":{"zh-Hans":"大兴线","zh-Hant":"大興線","en":"Daxing Line"}},{"id":"BJ-L5","colour":"#aa0061","fg":"#fff","name":{"zh-Hans":"5号线","zh-Hant":"5號線","en":"Line 5"}},{"id":"BJ-L6","colour":"#b58500","fg":"#fff","name":{"zh-Hans":"6号线","zh-Hant":"6號線","en":"Line 6"}},{"id":"BJ-L7","colour":"#ffc56e","fg":"#fff","name":{"zh-Hans":"7号线","zh-Hant":"7號線","en":"Line 7"}},{"id":"BJ-L8","colour":"#009b77","fg":"#fff","name":{"zh-Hans":"8号线","zh-Hant":"8號線","en":"Line 8"}},{"id":"BJ-L9","colour":"#97d700","fg":"#fff","name":{"zh-Hans":"9号线","zh-Hant":"9號線","en":"Line 9"}},{"id":"BJ-L10","colour":"#0092bc","fg":"#fff","name":{"zh-Hans":"10号线","zh-Hant":"10號線","en":"Line 10"}},{"id":"BJ-L11","colour":"#ff8674","fg":"#fff","name":{"zh-Hans":"11号线","zh-Hant":"11號線","en":"Line 11"}},{"id":"BJ-L12","colour":"#9b5a1a","fg":"#fff","name":{"zh-Hans":"12号线","zh-Hant":"12號線","en":"Line 12"}},{"id":"BJ-L13","colour":"#f4da40","fg":"#fff","name":{"zh-Hans":"13号线","zh-Hant":"13號線","en":"Line 13"}},{"id":"BJ-L13A","colour":"#f4da40","fg":"#fff","name":{"zh-Hans":"13A号线","zh-Hant":"13A號線","en":"Line 13A"}},{"id":"BJ-L13B","colour":"#e8bb71","fg":"#fff","name":{"zh-Hans":"13B号线","zh-Hant":"13B號線","en":"Line 13B"}},{"id":"BJ-L14","colour":"#ca9a8e","fg":"#fff","name":{"zh-Hans":"14号线","zh-Hant":"14號線","en":"Line 14"}},{"id":"BJ-L15","colour":"#653379","fg":"#fff","name":{"zh-Hans":"15号线","zh-Hant":"15號線","en":"Line 15"}},{"id":"BJ-L16","colour":"#6ba539","fg":"#fff","name":{"zh-Hans":"16号线","zh-Hant":"16號線","en":"Line 16"}},{"id":"BJ-L17","colour":"#00b2a9","fg":"#fff","name":{"zh-Hans":"17号线","zh-Hant":"17號線","en":"Line 17"}},{"id":"BJ-L19","colour":"#dd9cdf","fg":"#fff","name":{"zh-Hans":"19号线","zh-Hant":"19號線","en":"Line 19"}},{"id":"BJ-L22","colour":"#f4c1ca","fg":"#fff","name":{"zh-Hans":"22号线","zh-Hant":"22號線","en":"Line 22"}},{"id":"BJ-YIZHUANG","colour":"#d00070","fg":"#fff","name":{"zh-Hans":"亦庄线","zh-Hant":"亦莊線","en":"Yizhuang Line"}},{"id":"BJ-FANGSHAN","colour":"#d86018","fg":"#fff","name":{"zh-Hans":"房山线","zh-Hant":"房山線","en":"Fangshan Line"}},{"id":"BJ-YANFANG","colour":"#d86018","fg":"#fff","name":{"zh-Hans":"燕房线","zh-Hant":"燕房線","en":"Yanfang Line"}},{"id":"BJ-S1","colour":"#a45a2a","fg":"#fff","name":{"zh-Hans":"S1号线","zh-Hant":"S1號線","en":"Line S1"}},{"id":"BJ-CHANGPING","colour":"#d986ba","fg":"#fff","name":{"zh-Hans":"昌平线","zh-Hant":"昌平線","en":"Changping Line"}},{"id":"BJ-L28","colour":"#476205","fg":"#fff","name":{"zh-Hans":"28号线","zh-Hant":"28號線","en":"Line 28"}},{"id":"BJ-SHOUDUJICHANG","colour":"#a192b2","fg":"#fff","name":{"zh-Hans":"首都机场线","zh-Hant":"首都機場線","en":"Capital Airport Express"}},{"id":"BJ-DAXINGJICHANG","colour":"#0047bb","fg":"#fff","name":{"zh-Hans":"大兴机场线","zh-Hant":"大興機場線","en":"Daxing Airport Express"}},{"id":"BJ-TRAMXIJIAO","colour":"#d22730","fg":"#fff","name":{"zh-Hans":"西郊线","zh-Hant":"西郊線","en":"Tram Xijiao Line"}},{"id":"BJ-TRAMYIZHUANGT1","colour":"#d22730","fg":"#fff","name":{"zh-Hans":"亦庄T1线","zh-Hant":"亦莊T1線","en":"Tram Yizhuang Line T1"}}]</details>

**Comment by langonginc** [comment]
您好，请不要修改线路id，谢谢
