### ISSUE TITLE
Resources: New palettes of Chengdu

### ISSUE THREAD

**Issue by JQR20090720** [railmapgen/rmg-palette#147]
Justification:色源来自轻地铁

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "chengdu",
    "country": "CN",
    "name": {
        "en": "Chengdu",
        "zh": "成都"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "cd1",
        "colour": "#10069F",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "cd2",
        "colour": "#FF5C39",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "cd3",
        "colour": "#D9027D",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "cd4",
        "colour": "#00B047",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "cd5",
        "colour": "#BB29BB",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "cd6",
        "colour": "#B36924",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "cd7",
        "colour": "#59CBE8",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "cd8",
        "colour": "#C4D600",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "cd9",
        "colour": "#FFB81C",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "cd10",
        "colour": "#003DA5",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "cd11",
        "colour": "#8C7732",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "cd12",
        "colour": "#772583",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "cd13",
        "colour": "#C5A900",
        "fg": "#fff",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "cd14",
        "colour": "#6F263D",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "cd15",
        "colour": "#DFA0C9",
        "fg": "#fff",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "cd16",
        "colour": "#0085CA",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "cd17",
        "colour": "#80E0A7",
        "fg": "#fff",
        "name": {
            "en": "Line 17",
            "zh-Hans": "17号线",
            "zh-Hant": "17號線"
        }
    },
    {
        "id": "cd18",
        "colour": "#006271",
        "fg": "#fff",
        "name": {
            "en": "Line 18",
            "zh-Hans": "18号线",
            "zh-Hant": "18號線"
        }
    },
    {
        "id": "cd19",
        "colour": "#89ABE3",
        "fg": "#fff",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线",
            "zh-Hant": "19號線"
        }
    },
    {
        "id": "cd20",
        "colour": "#B86125",
        "fg": "#fff",
        "name": {
            "en": "Line 20",
            "zh-Hans": "20号线",
            "zh-Hant": "20號線"
        }
    },
    {
        "id": "cd21",
        "colour": "#FFC27B",
        "fg": "#fff",
        "name": {
            "en": "Line 21",
            "zh-Hans": "21号线",
            "zh-Hant": "21號線"
        }
    },
    {
        "id": "cd22",
        "colour": "#6AD1E3",
        "fg": "#fff",
        "name": {
            "en": "Line 22",
            "zh-Hans": "22号线",
            "zh-Hant": "22號線"
        }
    },
    {
        "id": "cd23",
        "colour": "#E57200",
        "fg": "#fff",
        "name": {
            "en": "Line 23",
            "zh-Hans": "23号线",
            "zh-Hant": "23號線"
        }
    },
    {
        "id": "cd24",
        "colour": "#C98BDB",
        "fg": "#fff",
        "name": {
            "en": "Line 24",
            "zh-Hans": "24号线",
            "zh-Hant": "24號線"
        }
    },
    {
        "id": "cd25",
        "colour": "#DA291C",
        "fg": "#fff",
        "name": {
            "en": "Line 25",
            "zh-Hans": "25号线",
            "zh-Hant": "25號線"
        }
    },
    {
        "id": "cd26",
        "colour": "#43B02A",
        "fg": "#fff",
        "name": {
            "en": "Line 26",
            "zh-Hans": "26号线",
            "zh-Hant": "26號線"
        }
    },
    {
        "id": "cd27",
        "colour": "#00A3E0",
        "fg": "#fff",
        "name": {
            "en": "Line 27",
            "zh-Hans": "27号线",
            "zh-Hant": "27號線"
        }
    },
    {
        "id": "cd28",
        "colour": "#9678D3",
        "fg": "#fff",
        "name": {
            "en": "Line 28",
            "zh-Hans": "28号线",
            "zh-Hant": "28號線"
        }
    },
    {
        "id": "cd29",
        "colour": "#776E64",
        "fg": "#fff",
        "name": {
            "en": "Line 29",
            "zh-Hans": "29号线",
            "zh-Hant": "29號線"
        }
    },
    {
        "id": "cd30",
        "colour": "#F67599",
        "fg": "#fff",
        "name": {
            "en": "Line 30",
            "zh-Hans": "30号线",
            "zh-Hant": "30號線"
        }
    },
    {
        "id": "cd31",
        "colour": "#9B26B6",
        "fg": "#fff",
        "name": {
            "en": "Line 31",
            "zh-Hans": "31号线",
            "zh-Hant": "31號線"
        }
    },
    {
        "id": "cd32",
        "colour": "#003DA5",
        "fg": "#fff",
        "name": {
            "en": "Line 32",
            "zh-Hans": "32号线",
            "zh-Hant": "32號線"
        }
    },
    {
        "id": "cd33",
        "colour": "#8EDD65",
        "fg": "#fff",
        "name": {
            "en": "Line 33",
            "zh-Hans": "33号线",
            "zh-Hant": "33號線"
        }
    },
    {
        "id": "cd34",
        "colour": "#A4D65E",
        "fg": "#fff",
        "name": {
            "en": "Line 34",
            "zh-Hans": "34号线",
            "zh-Hant": "34號線"
        }
    },
    {
        "id": "cd35",
        "colour": "#00A3E0",
        "fg": "#fff",
        "name": {
            "en": "Line 35",
            "zh-Hans": "35号线",
            "zh-Hant": "35號線"
        }
    },
    {
        "id": "cd36",
        "colour": "#004C97",
        "fg": "#fff",
        "name": {
            "en": "Line 36",
            "zh-Hans": "36号线",
            "zh-Hant": "36號線"
        }
    },
    {
        "id": "cd37",
        "colour": "#00B5E2",
        "fg": "#fff",
        "name": {
            "en": "Line 37",
            "zh-Hans": "37号线",
            "zh-Hant": "37號線"
        }
    },
    {
        "id": "cd38",
        "colour": "#97D700",
        "fg": "#fff",
        "name": {
            "en": "Line 38",
            "zh-Hans": "38号线",
            "zh-Hant": "38號線"
        }
    },
    {
        "id": "cd39",
        "colour": "#5C88DA",
        "fg": "#fff",
        "name": {
            "en": "Line 39/Meishan Line",
            "zh-Hans": "39号线/眉山线",
            "zh-Hant": "39號線/眉山線"
        }
    },
    {
        "id": "cd40",
        "colour": "#737B4C",
        "fg": "#fff",
        "name": {
            "en": "Line 40/Deyang Line",
            "zh-Hans": "40号线/德阳线",
            "zh-Hant": "40號線/德陽線"
        }
    },
    {
        "id": "jyl",
        "colour": "#FF808B",
        "fg": "#fff",
        "name": {
            "en": "Jianyang Line",
            "zh-Hans": "简阳线",
            "zh-Hant": "簡陽線"
        }
    },
    {
        "id": "zyl",
        "colour": "#75787B",
        "fg": "#fff",
        "name": {
            "en": "Ziyang Line",
            "zh-Hans": "资阳线",
            "zh-Hant": "資陽線"
        }
    },
    {
        "id": "t1",
        "colour": "#FF6720",
        "fg": "#fff",
        "name": {
            "en": "Tram T1",
            "zh-Hans": "蓉1号线",
            "zh-Hant": "蓉1號線"
        }
    },
    {
        "id": "t2",
        "colour": "#44D62C",
        "fg": "#fff",
        "name": {
            "en": "Tram T2",
            "zh-Hans": "蓉2号线",
            "zh-Hant": "蓉2號線"
        }
    },
    {
        "id": "t3",
        "colour": "#893B67",
        "fg": "#fff",
        "name": {
            "en": "Tram T3",
            "zh-Hans": "蓉3号线",
            "zh-Hant": "蓉3號線"
        }
    },
    {
        "id": "t4",
        "colour": "#0057B7",
        "fg": "#fff",
        "name": {
            "en": "Tram T4",
            "zh-Hans": "蓉4号线",
            "zh-Hant": "蓉4號線"
        }
    },
    {
        "id": "t5",
        "colour": "#D00070",
        "fg": "#fff",
        "name": {
            "en": "Tram T5",
            "zh-Hans": "蓉5号线",
            "zh-Hant": "蓉5號線"
        }
    },
    {
        "id": "t6",
        "colour": "#99D6EA",
        "fg": "#fff",
        "name": {
            "en": "Tram T6",
            "zh-Hans": "蓉6号线",
            "zh-Hant": "蓉6號線"
        }
    },
    {
        "id": "CR ",
        "colour": "#b5b5c5",
        "fg": "#fff",
        "name": {
            "en": "China  High-speed Railway",
            "zh-Hans": "中国高速铁路",
            "zh-Hant": "中國高速鐵路"
        }
    },
    {
        "id": "CR",
        "colour": "#b5b5c5",
        "fg": "#fff",
        "name": {
            "en": "China Railway",
            "zh-Hans": "中国铁路",
            "zh-Hant": "中國鐵路"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，像国铁和高速铁路这类属于国家级范围的铁路系统，因此我们不会接受此类线路颜色的补充。

请在添加线路颜色时将你所添加的线路所属系统控制住一个城市或者一个都市圈范围内，谢谢。
