### ISSUE TITLE
Resources: New palettes of Fuzhou

### ISSUE THREAD

**Issue by GrassRabbit1410** [railmapgen/rmg-palette#150]
**Justification:**Offical Website：http://www.fzmtr.com/html/fzdt/xlcx/index.html

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "fuzhou",
    "country": "CN",
    "name": {
        "en": "Fuzhou",
        "zh-Hans": "福州",
        "zh-Hant": "福州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "fz1",
        "colour": "#e90012",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "fz2",
        "colour": "#006931",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "fz5",
        "colour": "#973e69",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    }
]</details>

**Comment by wongchito** [comment]
你好 @GrassRabbit1410 ，經查詢閣下所提供之官方網站，我們發現閣下所提供之顏色與官方網站所用之顏色並不匹配。

CSS連結：http://www.fzmtr.com/cms/templates/680426833765420000/css/middle.css
<img width="463" alt="image" src="https://user-images.githubusercontent.com/9390786/183925042-68864fda-20ef-4867-baed-ba178b8e9c11.png">

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色稿件中有颜色与来源不一样后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
