### ISSUE TITLE
Resources: New palettes of Nanchang

### ISSUE THREAD

**Issue by FrankZhangCC** [railmapgen/rmg-palette#172]
**Justification:** 系统里面没有中国南昌的地铁色号。以下色号来源取自南昌地铁地铁图。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "nanchang",
    "country": "CN",
    "name": {
        "en": "Nanchang",
        "zh": "南昌"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "nc1",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "zh": "1号线",
            "en": "Line 1"
        }
    },
    {
        "id": "nc2",
        "colour": "#ffff00",
        "fg": "#000",
        "name": {
            "zh": "2号线",
            "en": "Line 2"
        }
    },
    {
        "id": "nc3",
        "colour": "#006ce0",
        "fg": "#fff",
        "name": {
            "zh": "3号线",
            "en": "Line 3"
        }
    },
    {
        "id": "nc4",
        "colour": "#00b300",
        "fg": "#fff",
        "name": {
            "zh": "4号线",
            "en": "Line 4"
        }
    }
]</details>

**Comment by linchen1965** [comment]
感谢对项目的支持与贡献，不过你提供的似乎来自于官方页面的工程图？据我们所知工程图上面的颜色通常不是官方配色，如果可以的话，请提供南昌官方的色号，谢谢理解。
