### ISSUE TITLE
Resources: New palettes of Taipei

### ISSUE THREAD

**Issue by Andy1782010** [railmapgen/rmg-palette#174]
**Justification:** (Modified by @52PD )
-------------------------------分割线-------------------------------

![image](https://user-images.githubusercontent.com/78524390/185736876-7a833335-a2f2-4445-8d17-02d95863389a.png)
根据这张图可以看到，图例中的 环状线 以及 中和新芦线 前景色均为黑色，我也针对这一点进行了修改

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "taipei",
    "country": "TW",
    "name": {
        "en": "Taipei",
        "zh": "台北"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "br",
        "colour": "#c48c31",
        "fg": "#fff",
        "name": {
            "en": "Wenhu Line (BR)",
            "zh-Hant": "文湖線"
        }
    },
    {
        "id": "r",
        "colour": "#e3002c",
        "fg": "#fff",
        "name": {
            "en": "Tamsui-Xinyi Line (R)",
            "zh-Hant": "淡水信義線"
        }
    },
    {
        "id": "rb",
        "colour": "#fd92a3",
        "fg": "#fff",
        "name": {
            "en": "Xinbeitou Branch Line",
            "zh-Hant": "新北投支線"
        }
    },
    {
        "id": "g",
        "colour": "#008659",
        "fg": "#fff",
        "name": {
            "en": "Songshan-Xindian Line (G)",
            "zh-Hant": "松山新店線"
        }
    },
    {
        "id": "gb",
        "colour": "#cfdb00",
        "fg": "#fff",
        "name": {
            "en": "Xiaobitan Branch Line",
            "zh-Hant": "小碧潭支線"
        }
    },
    {
        "id": "o",
        "colour": "#f8b61c",
        "fg": "#000",
        "name": {
            "en": "Zhonghe-Xinlu Line (O)",
            "zh-Hant": "中和新蘆線"
        }
    },
    {
        "id": "bl",
        "colour": "#0070bd",
        "fg": "#fff",
        "name": {
            "en": "Bannan Line (BL)",
            "zh-Hant": "板南線"
        }
    },
    {
        "id": "y",
        "colour": "#fedb00",
        "fg": "#000",
        "name": {
            "en": "Circular Line (Y)",
            "zh-Hant": "環狀線"
        }
    },
    {
        "id": "lg",
        "colour": "#a1d884",
        "fg": "#fff",
        "name": {
            "en": "Wanda-Zhonghe-Shulin Line (LG)",
            "zh-Hant": "萬大-中和-樹林線"
        }
    },
    {
        "id": "sb",
        "colour": "#25aae1",
        "fg": "#fff",
        "name": {
            "en": "Minsheng-Xizhi Line",
            "zh-Hant": "民生汐止線"
        }
    },
    {
        "id": "sbb",
        "colour": "#283991",
        "fg": "#fff",
        "name": {
            "en": "Donghu Branch Line",
            "zh-Hant": "東湖支線"
        }
    },
    {
        "id": "lr",
        "colour": "#e40078",
        "fg": "#fff",
        "name": {
            "en": "Shezi Line",
            "zh-Hant": "社子線"
        }
    },
    {
        "id": "mao",
        "colour": "#77bc1f",
        "fg": "#fff",
        "name": {
            "en": "Maokong Gondola",
            "zh-Hant": "貓空䌫車"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，目前您的稿件已经通过审核并准备汇入到项目中，不过在此之前我对稿件做出了部分细微改动：
1. 考虑到原稿件中未包含各线路简体中文名称，由于在RMG的简体中文界面下无简体中文名的线路会只显示其英文名，因此我在已有繁体中文线路名的基础上补加了简体中文名称。
2. 针对线路显示顺序进行了部分调整。

以上改动仅作为代码汇入项目前的细节优化，本次投稿将仍然算作是您对本项目的贡献内容。

感谢您对本项目的支持！👍
