### ISSUE TITLE
Resources: New palettes of Taoyuan

### ISSUE THREAD

**Issue by JasperkangYT** [railmapgen/rmg-palette#180]
**Justification:** 請提供適當的來源或理由，否則我們不會處理你的申請。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "taoyuan",
    "country": "TW",
    "name": {
        "en": "Taoyuan",
        "zh": "桃園"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "a",
        "colour": "#8246af",
        "fg": "#fff",
        "name": {
            "zh": "桃園機場捷運",
            "en": "Taoyuan Airport MRT"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，虽然很感谢你对本项目部所做的贡献，但请问你方便的话是否能够提供线路颜色的来源呢？

我们不会接受任何无颜色来源的投稿

此外，请在提交线路颜色时讲下面这行字替换掉：

> 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

以上这行字不替换的话我们负责汇入资源的bot就无法触发，因此我们也就无法将其汇入资源。
