### ISSUE TITLE
Resources: New palettes of Shanghai

### ISSUE THREAD

**Issue by huzch1** [railmapgen/rmg-palette#181]
**Justification:** 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shanghai",
    "country": "CN",
    "name": {
        "en": "Shanghai",
        "zh": "上海"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sh1",
        "colour": "#E4002B",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "sh2",
        "colour": "#97D700",
        "fg": "#000",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "sh3",
        "colour": "#FFD100",
        "fg": "#000",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "sh4",
        "colour": "#5F259F",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "sh5",
        "colour": "#AC4FC6",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "sh6",
        "colour": "#D9027D",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "sh7",
        "colour": "#FF6900",
        "fg": "#000",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "sh8",
        "colour": "#00A3E0",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "sh9",
        "colour": "#71C5E8",
        "fg": "#000",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "sh10",
        "colour": "#C1A7E2",
        "fg": "#000",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "sh11",
        "colour": "#76232F",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "sh12",
        "colour": "#007B5F",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "sh13",
        "colour": "#EF95CF",
        "fg": "#000",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "sh14",
        "colour": "#827A04",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "sh15",
        "colour": "#BBA786",
        "fg": "#000",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "sh16",
        "colour": "#2CD5C4",
        "fg": "#000",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "sh17",
        "colour": "#C09C83",
        "fg": "#fff",
        "name": {
            "en": "Line 17",
            "zh-Hans": "17号线",
            "zh-Hant": "17號線"
        }
    },
    {
        "id": "sh18",
        "colour": "#D6A461",
        "fg": "#000",
        "name": {
            "en": "Line 18",
            "zh-Hans": "18号线",
            "zh-Hant": "18號線"
        }
    },
    {
        "id": "pjl",
        "colour": "#999999",
        "fg": "#fff",
        "name": {
            "en": "Pujiang Line",
            "zh-Hans": "浦江线",
            "zh-Hant": "浦江線"
        }
    },
    {
        "id": "t1",
        "colour": "#FF0000",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T1",
            "zh-Hans": "松江有轨电车1号线",
            "zh-Hant": "松江有軌電車1號線"
        }
    },
    {
        "id": "t2",
        "colour": "#46837B",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T2",
            "zh-Hans": "松江有轨电车2号线",
            "zh-Hant": "松江有軌電車2號線"
        }
    },
    {
        "id": "t3",
        "colour": "#009400",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T3",
            "zh-Hans": "松江有轨电车3号线",
            "zh-Hant": "松江有軌電車3號線"
        }
    },
    {
        "id": "t4",
        "colour": "#FF00FF",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T4",
            "zh-Hans": "松江有轨电车4号线",
            "zh-Hant": "松江有軌電車4號線"
        }
    },
    {
        "id": "t5",
        "colour": "#00FD00",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T5",
            "zh-Hans": "松江有轨电车5号线",
            "zh-Hant": "松江有軌電車5號線"
        }
    },
    {
        "id": "t6",
        "colour": "#6E00DD",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T6",
            "zh-Hans": "松江有轨电车6号线",
            "zh-Hant": "松江有軌電車6號線"
        }
    },
    {
        "id": "maglev",
        "colour": "#009090",
        "fg": "#fff",
        "name": {
            "en": "Shanghai Maglev Train",
            "zh-Hans": "磁浮线",
            "zh-Hant": "磁浮線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，由于以下问题，我们不会接受你的投稿：
1. 没有提供适当来源，无适当来源的投稿我们不会直接接收。
2. 没有更改“请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)”这句话，不更改这句话会导致我们设立的项目汇入机器人无法触发，从而导致我们无法将线路颜色代码汇入项目中。
3. 您所提供的上海地铁线路颜色与目前项目中拥有的上海地铁颜色完全相同，因此我们无法确定您提交本issue是因为疏忽未注意到上海地铁颜色已经存在于项目中还是为了恶意破坏。
