### ISSUE TITLE
Resources: New palettes of Huhhot

### ISSUE THREAD

**Issue by kxztf123** [railmapgen/rmg-palette#190]
**Justification:** 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "huhhot",
    "country": "CN",
    "name": {
        "en": "Huhhot",
        "zh": "呼和浩特"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "hu1",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh": "1号线",
            "zh-HK": "1號綫",
            "zh-TW": "1号線"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，虽然很感谢你对本项目部所做的贡献，但请问你方便的话是否能够提供线路颜色的来源呢？

我们不会接受任何无颜色来源的投稿

此外，请在提交线路颜色时讲下面这行字替换掉：

> 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

以上这行字不替换的话我们负责汇入资源的bot就无法触发，因此我们也就无法将其汇入资源。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色稿件缺失来源后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
