### ISSUE TITLE
Adding color palettes of Zhengzhou, Budapest and Vienna

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmg-palette#20]
[zhengzhou.txt](https://github.com/railmapgen/rmg-palette/files/7957155/zhengzhou.txt)
[wien.txt](https://github.com/railmapgen/rmg-palette/files/7957351/wien.txt)
[budapest.txt](https://github.com/railmapgen/rmg-palette/files/7957437/budapest.txt)
Adding color palettes of 3 cities (including Zhengzhou so that the original palettes can be improved with official color palettes)
@C1P918R @thekingofcity 
By the way, the color of Barcelona Metro L13 should be **#ED3FAE** (from Wikipedia) and the color of Madrid Metro should be **#17A099** (from https://decide.madrid.es/proposals/23240-nueva-linea-13-de-metro)
![image](https://user-images.githubusercontent.com/92020676/151520421-640a8713-9b13-4834-8417-d13b334f11cd.png)

**Comment by thekingofcity** [comment]
Hi, thanks for your persistent contribution and the Zhengzhou update. We'll merge this as long as wongchito/RailMapGenerator#229 is fixed.

**Comment by wongchito** [comment]
Thank you for your contribution @linchen1965. These palettes are added to resources version 0.2.5. 

From this release, the name of every contributor will be added to the commit message as 'co-author', which makes the contributor visible from the home page. 
![image](https://user-images.githubusercontent.com/9390786/154333966-a436979d-5216-4c43-93f9-8606bc569fa5.png)

Please do continue to contribute to rmg-palette. Thank you!
