### ISSUE TITLE
Resources: New palettes of Jinhua

### ISSUE THREAD

**Issue by JiangYuanshen** [railmapgen/rmg-palette#207]
**Justification:** 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)
網圖
**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "jinhua",
    "country": "CN",
    "name": {
        "zh-Hans": "金华",
        "zh-Hant": "金華",
        "en": "Jinhua"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "JYD",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "zh-Hans": "金义东线",
            "zh-Hant": "金義東綫",
            "en": "Jinyidong Line"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，虽然很感谢你对本项目部所做的贡献，但请问你方便的话是否能够提供线路颜色的来源呢？

我们不会接受任何无颜色来源的投稿

此外，请在提交线路颜色时讲下面这行字替换掉：

> 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

以上这行字不替换的话我们负责汇入资源的bot就无法触发，因此我们也就无法将其汇入资源。

(请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by JiangYuanshen** [comment]
來自於百度，和地鐵通

**Comment by 52PD** [comment]
> 來自於百度

您好，您所说的“百度”是一个搜索引擎，并不是确切的线路颜色来源
请提供一个确切的线路颜色来源谢谢。

> 和地鐵通

您好，我们不接受像地铁通这类来自于第三方的不可靠颜色来源。请至少从官方的地方标准文件/官方网站/百度百科/维基百科这四个可靠性高的来源中选择一个作为您所提交的线路颜色来源。

**Comment by 52PD** [comment]
您好，在上次提出本稿件的相关问题后，您已经有超过15天未对其进行处理。
在您看到本条消息后，请及时恢复我们并尽快提交修改后的稿件
请注意，如您的问题稿件超过1个月后仍未有回应的话，我们将会直接拒绝收录您所提交的内容。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及稿件相关问题后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
