### ISSUE TITLE
Resources: New palettes of Moscow

### ISSUE THREAD

**Issue by JiangYuanshen** [railmapgen/rmg-palette#208]
**Justification:** 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "moscow",
    "country": "RU",
    "name": {
        "en": "Moscow",
        "zh-Hans": "莫斯科",
        "zh-Hant": "莫斯科"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "Mo1",
        "colour": "#cb2a2a",
        "fg": "#fff",
        "name": {
            "en": "Line 1"
        }
    },
    {
        "id": "Mo2",
        "colour": "#05bd05",
        "fg": "#fff",
        "name": {
            "en": "Line 2"
        }
    },
    {
        "id": "Mo3",
        "colour": "#1a5ac1",
        "fg": "#fff",
        "name": {
            "en": "Line 3"
        }
    },
    {
        "id": "Mo4",
        "colour": "#8fbaff",
        "fg": "#fff",
        "name": {
            "en": "Line 4"
        }
    },
    {
        "id": "Mo5",
        "colour": "#9a3820",
        "fg": "#fff",
        "name": {
            "en": "Line 5(Loop Line）"
        }
    },
    {
        "id": "Mo6",
        "colour": "#ff9900",
        "fg": "#fff",
        "name": {
            "en": "Line 6"
        }
    },
    {
        "id": "Mo7",
        "colour": "#aa0eaa",
        "fg": "#fff",
        "name": {
            "en": "Line 7"
        }
    },
    {
        "id": "Mo8",
        "colour": "#ffff00",
        "fg": "#000",
        "name": {
            "en": "Line 8"
        }
    },
    {
        "id": "Mo9",
        "colour": "#808080",
        "fg": "#fff",
        "name": {
            "en": "Line 9"
        }
    },
    {
        "id": "Mo10",
        "colour": "#b6bd00",
        "fg": "#fff",
        "name": {
            "en": "Line 10"
        }
    },
    {
        "id": "Mo11",
        "colour": "#17dede",
        "fg": "#fff",
        "name": {
            "en": "Line 11"
        }
    },
    {
        "id": "Mo14",
        "colour": "#ff0095",
        "fg": "#fff",
        "name": {
            "en": "Line 14"
        }
    }
]</details>

**Comment by 52PD** [comment]
> 出自於百度

您所说的”指的是搜索引擎，并不是一个确切的数据来源地址
麻烦提供一个确切的来源谢谢。

另外麻烦阁下认真对待您的投稿谢谢。

**Comment by JiangYuanshen** [comment]
https://map.baidu.com/@-13701224.297003021,6287346.050015184,21z

**Comment by 52PD** [comment]
您好，我们不接受百度地图的颜色来源。请至少从官方的地方标准文件/官方网站/百度百科（极不推荐）/维基百科这四个可靠性高的来源中选择一个作为您所提交的线路颜色来源。

**Comment by 52PD** [comment]
您好，在上次提出本稿件的相关问题后，您已经有超过15天未对其进行处理。
在您看到本条消息后，请及时恢复我们并尽快提交修改后的稿件
请注意，如您的问题稿件超过1个月后仍未有回应的话，我们将会直接拒绝收录您所提交的内容。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及稿件相关问题后，你已经长时间未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
