### ISSUE TITLE
Resources: New palettes of Pyongyang

### ISSUE THREAD

**Issue by JiangYuanshen** [railmapgen/rmg-palette#209]
**Justification:** 來自於百度，否则我们不会处理您的申请。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "NK",
    "name": {
        "en": "DPRKorea",
        "zh-Hans": "朝鲜",
        "zh-Hant": "北朝鮮"
    }
}</details>

<details repo="rmg-palette" type="city">{
    "id": "pyongyang",
    "country": "NK",
    "name": {
        "zh-Hans": "平壤",
        "zh-Hant": "平壤",
        "en": "Pyongyang"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "C",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "ko": "천리마선",
            "zh-Hans": "千里马线",
            "zh-Hant": "千里馬綫",
            "en": "Chollima Line"
        }
    },
    {
        "id": "H",
        "colour": "#00ff00",
        "fg": "#fff",
        "name": {
            "ko": "혁신선",
            "zh-Hans": "革新线",
            "zh-Hant": "革新綫",
            "en": "Hyoksin Line"
        }
    }
]</details>

**Comment by 52PD** [comment]
你所说的”百度“指的是搜索引擎，并不是一个确切的数据来源地址
麻烦提供一个确切的来源谢谢。

此外，介于你近期对投稿极其不负责的行为，我们将做出警告，如果再继续大量提交无来源投稿，我们会将其直接作为恶意破坏行为拒绝。

**Comment by 52PD** [comment]
您好，在上次提出本稿件的相关问题后，您已经有超过15天未对其进行处理。
在您看到本条消息后，请及时恢复我们并尽快提交修改后的稿件
请注意，如您的问题稿件超过1个月后仍未有回应的话，我们将会直接拒绝收录您所提交的内容。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及稿件相关问题后，你已经长时间未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
