### ISSUE TITLE
Resources: New palettes of Hohhot,

### ISSUE THREAD

**Issue by JiangYuanshen** [railmapgen/rmg-palette#210]
**Justification:** 來自於百度。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hohhot",
    "country": "CN",
    "name": {
        "en": "Hohhot,",
        "zh-Hans": "呼和浩特",
        "zh-Hant": "呼和浩特"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "HH1",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Line 1 ",
            "zh-Hans": "1号线",
            "zh-Hant": "1號綫"
        }
    },
    {
        "id": "HH2",
        "colour": "#0000ff",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號綫"
        }
    }
]</details>

**Comment by JiangYuanshen** [comment]
來自於http://www.hhhtmetro.com/org/platform

**Comment by 52PD** [comment]
你好，经查询阁下所提供之官方网站，我们发现阁下所提供之颜色与官方网站所用之颜色并不匹配。

请在检查你所提供的颜色后在本issue提交一次修正后的线路颜色，谢谢。

**Comment by 52PD** [comment]
您好，在上次提出本稿件的相关问题后，您已经有超过15天未对其进行处理。
在您看到本条消息后，请及时恢复我们并尽快提交修改后的稿件
请注意，如您的问题稿件超过1个月后仍未有回应的话，我们将会直接拒绝收录您所提交的内容。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及稿件相关问题后，你已经长时间未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
