### ISSUE TITLE
Resources: New palettes of Vancouver

### ISSUE THREAD

**Issue by JiangYuanshen** [railmapgen/rmg-palette#211]
**Justification:** 來自於百度地圖。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "vancouver",
    "country": "CA",
    "name": {
        "en": "Vancouver",
        "zh-Hant": "溫哥華",
        "zh-Hans": "温哥华"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "C",
        "colour": "#4a86e8",
        "fg": "#fff",
        "name": {
            "en": "Canada Line"
        }
    },
    {
        "id": "EXPO",
        "colour": "#0000ff",
        "fg": "#fff",
        "name": {
            "en": "Expo Line"
        }
    },
    {
        "id": "M",
        "colour": "#e4e401",
        "fg": "#fff",
        "name": {
            "en": "Millennium Line"
        }
    },
    {
        "id": "SB",
        "colour": "#ffff00",
        "fg": "#000",
        "name": {
            "en": "Sea Bus"
        }
    }
]</details>

**Comment by 52PD** [comment]
我们不接受百度地图的颜色来源。请至少从官方的地方标准文件/官方网站/百度百科（极不推荐）/维基百科这四个可靠性高的来源中选择一个作为您所提交的线路颜色来源。

**Comment by 52PD** [comment]
您好，在上次提出本稿件的相关问题后，您已经有超过15天未对其进行处理。
在您看到本条消息后，请及时恢复我们并尽快提交修改后的稿件
请注意，如您的问题稿件超过1个月后仍未有回应的话，我们将会直接拒绝收录您所提交的内容。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及稿件相关问题后，你已经长时间未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
