### ISSUE TITLE
Adding color palettes of some German Cities and City-group

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmg-palette#22]
[rhein-ruhr-gebiet.txt](https://github.com/railmapgen/rmg-palette/files/8047284/rhein-ruhr-gebiet.txt)
[berlin.txt](https://github.com/railmapgen/rmg-palette/files/8047286/berlin.txt)
[frankfurtammain.txt](https://github.com/railmapgen/rmg-palette/files/8047287/frankfurtammain.txt)
[munich.txt](https://github.com/railmapgen/rmg-palette/files/8047288/munich.txt)
Adding color palettes of Berlin, Munich, Frankfurt and Rhein-Ruhr Gebiet (including Essen, Mülheim, Oberhausen, Bochum, Gelsenkirchen, Herne, Düsseldorf, Duisburg, Krefeld and Wuppertal)

**Comment by wongchito** [comment]
Hi @linchen1965, 

We noticed that there's few errors of the submitted files, which took us extra time to correct them and merge them the code base. Please could you double check the format of the files before uploading.

By the way, we're planning to build a create/upload portal to automate this process, which may help to reduce these kinds of human errors.
