### ISSUE TITLE
Resources: New palettes of Sao Paulo

### ISSUE THREAD

**Issue by edug5** [railmapgen/rmg-palette#222]
**Justification:** Please provide any source or justification or we will not proceed with your request. (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "saopaulo",
    "country": "BR",
    "name": {
        "en": "Sao Paulo",
        "pt": "São Paulo",
        "zh-Hans": "圣保罗",
        "zh-Hant": "聖保羅"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sp1",
        "colour": "#0153A0",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "pt": "Linha 1"
        }
    },
    {
        "id": "sp2",
        "colour": "#008061",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "pt": "Linha 2"
        }
    },
    {
        "id": "sp3",
        "colour": "#EE3E34",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "pt": "Linha 3"
        }
    },
    {
        "id": "sp4",
        "colour": "#FED304",
        "fg": "#000",
        "name": {
            "en": "Line 4",
            "pt": "Linha 4"
        }
    },
    {
        "id": "sp5",
        "colour": "#784D9F",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "pt": "Linha 5"
        }
    },
    {
        "id": "sp6",
        "colour": "#F27C00",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "pt": "Linha 6"
        }
    },
    {
        "id": "sp7",
        "colour": "#9E1766",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "pt": "Linha 7"
        }
    },
    {
        "id": "sp8",
        "colour": "#9E9E93",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "pt": "Linha 8"
        }
    },
    {
        "id": "sp9",
        "colour": "#00A78E",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "pt": "Linha 9"
        }
    },
    {
        "id": "sp10",
        "colour": "#007C8F",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "pt": "Linha 10"
        }
    },
    {
        "id": "sp11",
        "colour": "#F04D22",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "pt": "Linha 11"
        }
    },
    {
        "id": "sp12",
        "colour": "#083E89",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "pt": "Linha 12"
        }
    },
    {
        "id": "sp13",
        "colour": "#00AB5B",
        "fg": "#fff",
        "name": {
            "en": "Line 13",
            "pt": "Linha 13"
        }
    },
    {
        "id": "sp15",
        "colour": "#858D90",
        "fg": "#fff",
        "name": {
            "en": "Line 15",
            "pt": "Linha 15"
        }
    },
    {
        "id": "sp14",
        "colour": "#000000",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "pt": "Linha 14"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，虽然很感谢你对本项目部所做的贡献，但请问你方便的话是否能够提供线路颜色的来源呢？

我们不会接受任何无颜色来源的投稿

此外，请在提交线路颜色时讲下面这行字替换掉：

> Please provide any source or justification or we will not proceed with your request. (REPLACE ME)

以上这行字不替换的话我们负责汇入资源的bot就无法触发，因此我们也就无法将其汇入资源。

(请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by linchen1965** [comment]
The detected color of Line 14 from Wikipedia is 0A1013 instead of 000000. Otherwise, the line is under prospective planning after its 2013 Proposal was replaced by the Line 13 Express.

**Comment by 52PD** [comment]
Hi, since we mentioned about problem inside your palette last time, you already have a very long time not response.

Consider we cannot keep any issue without author's responsibility forever, we will refuse your palette and close this issue immediately.

Please take responsibility for your next palette request once we send you massage for any problem.
