### ISSUE TITLE
Update Shenzhen line 14,16,20

### ISSUE THREAD

**Issue by thekingofcity** [railmapgen/rmg-palette#23]
> Official Website: htps://www.szmc.net/map/
> Line color of Shenzhen metro Line 20 was changed. The color code of line 20 should be 9CD0CB.
> For line 14 and line 16. The line color codes should be F2C75C and 1E22AA (data from Wikipedia)

_Originally posted by @linchen1965 in https://github.com/wongchito/RailMapGenerator/issues/250_

**Comment by thekingofcity** [comment]
@XHG78999

**Comment by XHG78999** [comment]
OK

**Comment by thekingofcity** [comment]
You may have a look at #10 and #11 on how we update the code base.

**Comment by wongchito** [comment]
Hey @XHG78999, 

Please remember to add contributor's name to the commit message :)

Example:

```
#23 Update palettes for Shenzhen


Co-Authored-By: linchen1965 <92020676+linchen1965@users.noreply.github.com>
```

You may use GitHub Desktop to find out the email address of each contributor, or just simply use GitHub Desktop to amend the latest commit with co-author. 

![image](https://user-images.githubusercontent.com/9390786/154334869-d4f91fcc-4208-4920-92b6-6c58aeec70b3.png)
