### ISSUE TITLE
Resources: New palettes of Fuzhou

### ISSUE THREAD

**Issue by ghost** [railmapgen/rmg-palette#233]
**Justification:** 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "fuzhou",
    "country": "CN",
    "name": {
        "zh": "福州",
        "en": "Fuzhou"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "fz1",
        "colour": "#c5001a",
        "fg": "#fff",
        "name": {
            "zh": "1号线",
            "en": "Line 1"
        }
    },
    {
        "id": "fz2",
        "colour": "#36562b",
        "fg": "#fff",
        "name": {
            "zh": "2号线",
            "en": "Line 2"
        }
    },
    {
        "id": "fz5",
        "colour": "#7d3b67",
        "fg": "#fff",
        "name": {
            "zh": "5号线",
            "en": "Line 5"
        }
    },
    {
        "id": "fz6",
        "colour": "#3763dd",
        "fg": "#fff",
        "name": {
            "zh": "6号线",
            "en": "Line 6"
        }
    }
]</details>

**Comment by ZDZAVIDW** [comment]
add fuzhou

**Comment by ZDZAVIDW** [comment]
福州已开通4条线路

**Comment by linchen1965** [comment]
你好，感谢你对本项目部所做的贡献。但我们不会接受任何无可靠来源的投稿，请在提交线路颜色时替换掉下面这行字：

》请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)《

（请在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将不会汇入）

**Comment by 52PD** [comment]
Closed due to original author account has been deleted while question for this post still not solved.
