### ISSUE TITLE
Resources: New palettes of Lanzhou

### ISSUE THREAD

**Issue by ghost** [railmapgen/rmg-palette#234]
**Justification:** 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "lanzhou",
    "country": "CN",
    "name": {
        "zh-Hans": "兰州",
        "zh-Hant": "蘭州",
        "en": "Lanzhou"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "lz1",
        "colour": "#4d9bfc",
        "fg": "#fff",
        "name": {
            "zh-Hans": "1号线",
            "zh-Hant": "1號線",
            "en": "Line 1"
        }
    }
]</details>

**Comment by ZDZAVIDW** [comment]
兰州1条地铁线

**Comment by linchen1965** [comment]
你好，感谢你对本项目部所做的贡献。但我们不会接受任何无可靠来源的投稿，请在提交线路颜色时替换掉下面这行字：

》请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)《

（请在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将不会汇入）

**Comment by ZDZAVIDW** [comment]
![QQ浏览器截图20221029082102](https://user-images.githubusercontent.com/116615354/198753124-f228cae1-02af-49c3-b068-16b8b40eea1d.png)
来自百度百科

**Comment by ZDZAVIDW** [comment]
来自百度百科
![QQ浏览器截图20221029082102](https://user-images.githubusercontent.com/116615354/198753242-2ac7dae9-5d52-4983-961a-435f9937ed65.png)

**Comment by ZDZAVIDW** [comment]
来自百度百科
![QQ浏览器截图20221029082339](https://user-images.githubusercontent.com/116615354/198753255-c8b6596d-3663-4b8a-83b7-1beb2b668ee5.png)

**Comment by ZDZAVIDW** [comment]
![QQ浏览器截图20221029082339](https://user-images.githubusercontent.com/116615354/198753724-02ab5b9c-4be0-413e-9d6d-965f20f2a1c9.png)
来自百度百科

**Comment by 52PD** [comment]
Closed due to original author account has been deleted while question for this post still not solved.
