### ISSUE TITLE
Resources: New palettes of Hong Kong

### ISSUE THREAD

**Issue by SheeshOrdinaryLightnSheeshOrdinaryDark** [railmapgen/rmg-palette#241]
**Justification:** 請提供適當的來源或理由，否則我們不會處理你的申請。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hongkong",
    "country": "HK",
    "name": {
        "en": "Hong Kong",
        "zh": "香港"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "twl",
        "colour": "#E2231A",
        "fg": "#fff",
        "name": {
            "en": "Tsuen Wan Line",
            "zh-Hans": "荃湾线",
            "zh-Hant": "荃灣綫"
        }
    },
    {
        "id": "ktl",
        "colour": "#00AF41",
        "fg": "#fff",
        "name": {
            "en": "Kwun Tong Line",
            "zh-Hans": "观塘线",
            "zh-Hant": "觀塘綫"
        }
    },
    {
        "id": "isl",
        "colour": "#0071CE",
        "fg": "#fff",
        "name": {
            "en": "Island Line",
            "zh-Hans": "港岛线",
            "zh-Hant": "港島綫"
        }
    },
    {
        "id": "tkl",
        "colour": "#A35EB5",
        "fg": "#fff",
        "name": {
            "en": "Tseung Kwan O Line",
            "zh-Hans": "将军澳线",
            "zh-Hant": "將軍澳綫"
        }
    },
    {
        "id": "tcl",
        "colour": "#F38B00",
        "fg": "#fff",
        "name": {
            "en": "Tung Chung Line",
            "zh-Hans": "东涌线",
            "zh-Hant": "東涌綫"
        }
    },
    {
        "id": "drl",
        "colour": "#E777CB",
        "fg": "#fff",
        "name": {
            "en": "Disney Resort Line",
            "zh-Hans": "迪士尼线",
            "zh-Hant": "迪士尼綫"
        }
    },
    {
        "id": "ael",
        "colour": "#007078",
        "fg": "#fff",
        "name": {
            "en": "Airport Express",
            "zh-Hans": "机场快线",
            "zh-Hant": "機場快綫"
        }
    },
    {
        "id": "sile",
        "colour": "#B6BD00",
        "fg": "#fff",
        "name": {
            "en": "South Island Line (East)",
            "zh-Hans": "南港岛线（东段）",
            "zh-Hant": "南港島綫（東段）"
        }
    },
    {
        "id": "silw",
        "colour": "#9182C2",
        "fg": "#fff",
        "name": {
            "en": "South Island Line (West)",
            "zh-Hans": "南港岛线（西段）",
            "zh-Hant": "南港島綫（西段）"
        }
    },
    {
        "id": "ekl",
        "colour": "#00FF00",
        "fg": "#fff",
        "name": {
            "en": "East Kowloon Line",
            "zh-Hans": "东九龙线",
            "zh-Hant": "東九龍綫"
        }
    },
    {
        "id": "eal",
        "colour": "#61B4E4",
        "fg": "#fff",
        "name": {
            "en": "East Rail Line",
            "zh-Hans": "东铁线",
            "zh-Hant": "東鐵綫"
        }
    },
    {
        "id": "mol",
        "colour": "#9A3820",
        "fg": "#fff",
        "name": {
            "en": "Tuen Ma Line",
            "zh-Hans": "屯马线",
            "zh-Hant": "屯馬綫"
        }
    },
    {
        "id": "nol",
        "colour": "#FF0066",
        "fg": "#fff",
        "name": {
            "en": "Northern Link",
            "zh-Hans": "北环线",
            "zh-Hant": "北環綫"
        }
    },
    {
        "id": "lrl",
        "colour": "#CD9700",
        "fg": "#fff",
        "name": {
            "en": "Light Rail",
            "zh-Hans": "轻铁",
            "zh-Hant": "輕鐵"
        }
    },
    {
        "id": "efls",
        "colour": "#000000",
        "fg": "#fff",
        "name": {
            "en": "Environmentally Friendly Linkage System",
            "zh-Hans": "环保连接系统",
            "zh-Hant": "環保連接系統"
        }
    },
    {
        "id": "hsr",
        "colour": "#9D968D",
        "fg": "#fff",
        "name": {
            "en": "High Speed Rail",
            "zh-Hans": "高速铁路",
            "zh-Hant": "高速鐵路"
        }
    },
    {
        "id": "np360",
        "colour": "#94989A",
        "fg": "#fff",
        "name": {
            "en": "Ngong Ping 360",
            "zh": "昂坪360"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，由于你删除了当前版本的中部分线路，但并未提供删除线路的适当理由，我们不会接受你的投稿。
