### ISSUE TITLE
Resources: New palettes of Xiabeize

### ISSUE THREAD

**Issue by chengran1234** [railmapgen/rmg-palette#250]
**Justification:** 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "xiabeize",
    "country": "JP",
    "name": {
        "zh": "下北泽",
        "en": "Xiabeize"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "xbx",
        "colour": "#114514",
        "fg": "#fff",
        "name": {
            "zh": "先辈线",
            "en": "Xianbei Line"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，虽然很感谢你对本项目部所做的贡献，但请问你方便的话是否能够提供线路颜色的来源呢？

我们不会接受任何无颜色来源的投稿

此外，请在提交线路颜色时讲下面这行字替换掉：

> 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

以上这行字不替换的话我们负责汇入资源的bot就无法触发，因此我们也就无法将其汇入资源。

(请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by linchen1965** [comment]
Close as invalid data.

**Comment by 52PD** [comment]
嗨，我们暂不支持非现实世界中的调色板，感谢您对项目的支持！
