### ISSUE TITLE
Resources: New palettes of Seoul (Metropolitan Area)

### ISSUE THREAD

**Issue by WanyunMediaGroup** [railmapgen/rmg-palette#253]
**Justification:** (Modified by @52PD ) 2022年5月28日，新林线开通。本次修改加入了新林线，同时每条线路加入了中文。望采纳。
新林线的资料来源于首尔交通公社官方网站颜色资料。 

http://www.seoulmetro.co.kr/ https://info.korail.com/ https://www.ictr.or.kr/ https://www.shinbundang.co.kr/ https://www.arex.or.kr/main.do http://www.ever-line.co.kr/ http://www.uitrans.co.kr/ https://www.ulrt.co.kr/ https://gimpogoldline.com/

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "seoul",
    "country": "KR",
    "name": {
        "en": "Seoul (Metropolitan Area)",
        "ko": "서울(수도권)",
        "zh-Hans": "首尔（首都圈）",
        "zh-Hant": "首爾（首都圈）"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "su1",
        "colour": "#0052A4",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "ko": "1호선",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "su2",
        "colour": "#009D3E",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "ko": "2호선",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "su3",
        "colour": "#EF7C1C",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "ko": "3호선",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "su4",
        "colour": "#00A5DE",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "ko": "4호선",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "su5",
        "colour": "#996CAC",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "ko": "5호선",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "su6",
        "colour": "#CD7C2F",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "ko": "6호선",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "su7",
        "colour": "#747F00",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "ko": "7호선",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "su8",
        "colour": "#EA545D",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "ko": "8호선",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "su9",
        "colour": "#BDB092",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "ko": "9호선",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "arx",
        "colour": "#0090D2",
        "fg": "#fff",
        "name": {
            "en": "Airport Railroad Express",
            "ko": "인천국제공항철도",
            "zh-Hans": "仁川国际机场铁道",
            "zh-Hant": "仁川國際機場鐵道"
        }
    },
    {
        "id": "gye",
        "colour": "#77C4A3",
        "fg": "#fff",
        "name": {
            "en": "Gyeongui–Jungang Line",
            "ko": "경의·중앙선",
            "zh-Hans": "京义·中央线",
            "zh-Hant": "京義·中央線"
        }
    },
    {
        "id": "bun",
        "colour": "#F5A200",
        "fg": "#fff",
        "name": {
            "en": "Suin–Bundang Line",
            "ko": "수인·분당선",
            "zh-Hans": "水仁·盆唐线",
            "zh-Hant": "水仁·盆唐線"
        }
    },
    {
        "id": "gg",
        "colour": "#003DA5",
        "fg": "#fff",
        "name": {
            "en": "Gyeonggang Line",
            "ko": "경강선",
            "zh-Hans": "京江线",
            "zh-Hant": "京江線"
        }
    },
    {
        "id": "chun",
        "colour": "#0C8E72",
        "fg": "#fff",
        "name": {
            "en": "Gyeongchun Line",
            "ko": "경춘선",
            "zh-Hans": "京春线",
            "zh-Hant": "京春線"
        }
    },
    {
        "id": "ui",
        "colour": "#b0ce18",
        "fg": "#fff",
        "name": {
            "en": "Ui LRT",
            "ko": "우이신설선",
            "zh-Hans": "牛耳新设线",
            "zh-Hant": "牛耳新設線"
        }
    },
    {
        "id": "sin",
        "colour": "#D4003B",
        "fg": "#fff",
        "name": {
            "en": "Shinbundang Line",
            "ko": "신분당선",
            "zh-Hans": "新盆唐线",
            "zh-Hant": "新盆唐線"
        }
    },
    {
        "id": "seo",
        "colour": "#81A914",
        "fg": "#fff",
        "name": {
            "en": "Seohae Line",
            "ko": "서해선",
            "zh-Hans": "西海线",
            "zh-Hant": "西海線"
        }
    },
    {
        "id": "i1",
        "colour": "#7CA8D5",
        "fg": "#fff",
        "name": {
            "en": "Incheon Subway Line 1",
            "ko": "인천 1호선",
            "zh-Hans": "仁川1号线",
            "zh-Hant": "仁川1號線"
        }
    },
    {
        "id": "i2",
        "colour": "#ED8B00",
        "fg": "#fff",
        "name": {
            "en": "Incheon Subway Line 2",
            "ko": "인천 2호선",
            "zh-Hans": "仁川2号线",
            "zh-Hant": "仁川2號線"
        }
    },
    {
        "id": "uij",
        "colour": "#fda600",
        "fg": "#fff",
        "name": {
            "en": "U Line",
            "ko": "의정부경전철",
            "zh-Hans": "议政府轻电铁",
            "zh-Hant": "議政府輕電鐵"
        }
    },
    {
        "id": "im",
        "colour": "#FFCD12",
        "fg": "#fff",
        "name": {
            "en": "Incheon Airport Maglev",
            "ko": "인천공항 자기부상철도",
            "zh-Hans": "仁川机场磁悬浮线",
            "zh-Hant": "仁川機場磁懸浮線"
        }
    },
    {
        "id": "gim",
        "colour": "#A17800",
        "fg": "#fff",
        "name": {
            "en": "Gimpo Goldline",
            "ko": "김포 도시철도",
            "zh-Hans": "金浦都市铁道",
            "zh-Hant": "金浦都市鐵道"
        }
    },
    {
        "id": "ever",
        "colour": "#509F22",
        "fg": "#fff",
        "name": {
            "en": "Everline",
            "ko": "에버라인",
            "zh-Hans": "龙仁轻电铁",
            "zh-Hant": "龍仁輕電鐵"
        }
    },
    {
        "id": "silm",
        "colour": "#688acb",
        "fg": "#fff",
        "name": {
            "en": "Sillim Line",
            "ko": "신림선",
            "zh-Hans": "新林线",
            "zh-Hant": "新林線"
        }
    }
]</details>

**Comment by linchen1965** [comment]
感谢你对本项目部所做的贡献，请在投稿时将来源的链接取代下面这行字：

> 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

（请在收到本条消息后尽快及时回复，超过一个月未回复的我们将不会汇入）

**Comment by WanyunMediaGroup** [comment]
Roger. 收到。



在 2022-11-24 03:34:45，"linchen1965" ***@***.***> 写道：

感谢你对本项目部所做的贡献，请在投稿时将来源的链接取代下面这行字：

请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

（请在收到本条消息后尽快及时回复，超过一个月未回复的我们将不会汇入）

**Comment by 52PD** [comment]
你好 @WanyunMediaGroup ，经查询新林线官方网站，我们发现阁下所提供的新林线颜色与该网站所用之颜色并不匹配。
![Screenshot 2022-11-26 at 4 04 40 PM](https://user-images.githubusercontent.com/98044618/204108883-76710b4f-ef08-47cc-80c1-633f41b14341.png)
因为我们建议您及时检查您所提供的线路颜色并本issue中提交正确的颜色。感谢您对本项目的支持。

此外，对于此前其他资源管理员未经审核就将其汇入项目的失误，我们深感抱歉。
(请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
Closed as no response.
