### ISSUE TITLE
Resources: New palettes of Tokyo (Greater Tokyo Area)

### ISSUE THREAD

**Issue by WanyunMediaGroup** [railmapgen/rmg-palette#254]
**Justification:** (Modified by @52PD ) 这一次本人已将各条路线的中文部分进行了增补，望采纳。来源：中文维基百科、东日本旅客铁道官方网站、东武铁道官方网站、京滨急行电铁官方网站、京成电铁官方网站等。

https://www.tokyometro.jp/ https://www.jreast.co.jp/ https://www.tobu.co.jp/ https://www.seiburailway.jp/ https://www.keikyu.co.jp/ https://www.odakyu.jp/ https://www.keio.co.jp/ https://www.tokyu.co.jp/ https://www.keisei.co.jp/ https://www.choshi-dentetsu.jp/ https://www.new-shuttle.jp/ https://www.shinkeisei.co.jp/ https://www.hokuso-railway.co.jp/ https://www.sotetsu.co.jp/ https://www.kotsu.metro.tokyo.jp/ https://www.yurikamome.co.jp/ https://www.twr.co.jp/

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "tokyo",
    "country": "JP",
    "name": {
        "en": "Tokyo (Greater Tokyo Area)",
        "ja": "東京（首都圏）",
        "zh-Hans": "东京（首都圈）",
        "zh-Hant": "東京（首都圈）"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "g",
        "colour": "#ff9500",
        "fg": "#fff",
        "name": {
            "en": "Ginza Line (G)",
            "ja": "銀座線",
            "zh-Hans": "银座线",
            "zh-Hant": "銀座線"
        }
    },
    {
        "id": "m",
        "colour": "#f62e36",
        "fg": "#fff",
        "name": {
            "en": "Marunouchi Line (M)",
            "ja": "丸ノ内線",
            "zh-Hans": "丸之内线",
            "zh-Hant": "丸之內線"
        }
    },
    {
        "id": "h",
        "colour": "#b5b5ac",
        "fg": "#fff",
        "name": {
            "en": "Hibiya Line (H)",
            "ja": "日比谷線",
            "zh-Hans": "日比谷线",
            "zh-Hant": "日比谷線"
        }
    },
    {
        "id": "t",
        "colour": "#009bbf",
        "fg": "#fff",
        "name": {
            "en": "Tōzai Line (T)",
            "ja": "東西線",
            "zh-Hans": "东西线",
            "zh-Hant": "東西線"
        }
    },
    {
        "id": "c",
        "colour": "#00bb85",
        "fg": "#fff",
        "name": {
            "en": "Chiyoda Line (C)",
            "ja": "千代田線",
            "zh-Hans": "千代田线",
            "zh-Hant": "千代田線"
        }
    },
    {
        "id": "y",
        "colour": "#c1a470",
        "fg": "#fff",
        "name": {
            "en": "Yūrakuchō Line (Y)",
            "ja": "有楽町線",
            "zh-Hans": "有乐町线",
            "zh-Hant": "有樂町線"
        }
    },
    {
        "id": "z",
        "colour": "#8f76d6",
        "fg": "#fff",
        "name": {
            "en": "Hanzōmon Line (Z)",
            "ja": "半蔵門線",
            "zh-Hans": "半藏门线",
            "zh-Hant": "半藏門線"
        }
    },
    {
        "id": "n",
        "colour": "#00ac9b",
        "fg": "#fff",
        "name": {
            "en": "Namboku Line (N)",
            "ja": "南北線",
            "zh-Hans": "南北线",
            "zh-Hant": "南北線"
        }
    },
    {
        "id": "f",
        "colour": "#9c5e31",
        "fg": "#fff",
        "name": {
            "en": "Fukutoshin Line (F)",
            "ja": "副都心線",
            "zh-Hans": "副都心线",
            "zh-Hant": "副都心線"
        }
    },
    {
        "id": "a",
        "colour": "#ec6e65",
        "fg": "#fff",
        "name": {
            "en": "Asakusa Line (A)",
            "ja": "浅草線",
            "zh-Hans": "浅草线",
            "zh-Hant": "淺草線"
        }
    },
    {
        "id": "i",
        "colour": "#006ab8",
        "fg": "#fff",
        "name": {
            "en": "Mita Line (I)",
            "ja": "三田線",
            "zh-Hans": "三田线",
            "zh-Hant": "三田線"
        }
    },
    {
        "id": "s",
        "colour": "#b0bf1e",
        "fg": "#fff",
        "name": {
            "en": "Shinjuku Line (S)",
            "ja": "新宿線",
            "zh-Hans": "新宿线",
            "zh-Hant": "新宿線"
        }
    },
    {
        "id": "o",
        "colour": "#ce045b",
        "fg": "#fff",
        "name": {
            "en": "Ōedo Line (O)",
            "ja": "大江戸線",
            "zh-Hans": "大江户线",
            "zh-Hant": "大江戶線"
        }
    },
    {
        "id": "jy",
        "colour": "#B1CB39",
        "fg": "#fff",
        "name": {
            "en": "Yamanote Line (JY)",
            "ja": "山手線",
            "zh-Hans": "山手线",
            "zh-Hant": "山手線"
        }
    },
    {
        "id": "jk",
        "colour": "#1DAED1",
        "fg": "#fff",
        "name": {
            "en": "Keihin-Tōhoku Line/Negishi Line (JK)",
            "ja": "京浜東北線・根岸線",
            "zh-Hans": "京濱東北線·根岸線",
            "zh-Hant": "京滨东北线·根岸线"
        }
    },
    {
        "id": "jb",
        "colour": "#F2D01F",
        "fg": "#fff",
        "name": {
            "en": "Chūō Line/Sōbu Line (Local) (JB)",
            "ja": "中央・総武線",
            "zh-Hans": "中央·总武缓行线",
            "zh-Hant": "中央·總武緩行線"
        }
    },
    {
        "id": "jc",
        "colour": "#DD6935",
        "fg": "#fff",
        "name": {
            "en": "Chūō Line (Rapid)/Chūō Line/Ōme Line/Itsukaichi Line (JC)",
            "ja": "中央線快速・中央本線・青梅線・五日市線",
            "zh-Hans": "中央线快速·中央线·青梅线·五日市线",
            "zh-Hant": "中央線快速·中央線·青梅線·五日市線"
        }
    },
    {
        "id": "jo",
        "colour": "#1069B4",
        "fg": "#fff",
        "name": {
            "en": "Yokosuka Line/Sōbu Line (Rapid)/Sōbu Line/Narita Line (JO)",
            "ja": "横須賀線・総武快速線・総武本線・成田線",
            "zh-Hans": "横须贺线·总武快速线·总武线·成田线",
            "zh-Hant": "橫須賀線·總武快速線·總武線·成田線"
        }
    },
    {
        "id": "ju",
        "colour": "#F18E41",
        "fg": "#fff",
        "name": {
            "en": "Utsunomiya Line/Takasaki Line (JU)",
            "ja": "宇都宮線・高崎線",
            "zh-Hans": "宇都宫线·高崎线",
            "zh-Hant": "宇都宮線·高崎線"
        }
    },
    {
        "id": "jt",
        "colour": "#F0862B",
        "fg": "#fff",
        "name": {
            "en": "Tōkaidō Line/Itō Line (JT)",
            "ja": "東海道線・伊東線",
            "zh-Hans": "东海道线·伊东线",
            "zh-Hant": "東海道線·伊東線"
        }
    },
    {
        "id": "ja",
        "colour": "#14A676",
        "fg": "#fff",
        "name": {
            "en": "Saikyō Line (JA)",
            "ja": "埼京線",
            "zh-Hans": "埼京线",
            "zh-Hant": "埼京線"
        }
    },
    {
        "id": "js",
        "colour": "#DB2027",
        "fg": "#fff",
        "name": {
            "en": "Shōnan-Shinjuku Line (JS)",
            "ja": "湘南新宿ライン",
            "zh-Hans": "湘南新宿线",
            "zh-Hant": "湘南新宿線"
        }
    },
    {
        "id": "jj",
        "colour": "#1DAF7E",
        "fg": "#fff",
        "name": {
            "en": "Jōban Line (Rapid) (JJ)",
            "ja": "常磐線快速電車",
            "zh-Hans": "常磐快速线",
            "zh-Hant": "常磐快速線"
        }
    },
    {
        "id": "jl",
        "colour": "#868587",
        "fg": "#fff",
        "name": {
            "en": "Jōban Line (Local) (JL)",
            "ja": "常磐線各駅停車",
            "zh-Hans": "常磐缓行线",
            "zh-Hant": "常磐緩行線"
        }
    },
    {
        "id": "je",
        "colour": "#D01827",
        "fg": "#fff",
        "name": {
            "en": "Keiyō Line (JE)",
            "ja": "京葉線",
            "zh-Hans": "京叶线",
            "zh-Hant": "京葉線"
        }
    },
    {
        "id": "jh",
        "colour": "#B1CB39",
        "fg": "#fff",
        "name": {
            "en": "Yokohama Line (JH)",
            "ja": "横浜線",
            "zh-Hans": "横滨线",
            "zh-Hant": "橫濱線"
        }
    },
    {
        "id": "jm",
        "colour": "#EB5A28",
        "fg": "#fff",
        "name": {
            "en": "Musashino Line (JM)",
            "ja": "武蔵野線",
            "zh-Hans": "武藏野线",
            "zh-Hant": "武藏野線"
        }
    },
    {
        "id": "jn",
        "colour": "#F2D01F",
        "fg": "#fff",
        "name": {
            "en": "Nambu Line (JN)",
            "ja": "南武線",
            "zh-Hans": "南武线",
            "zh-Hant": "南武線"
        }
    },
    {
        "id": "ji",
        "colour": "#F2D01F",
        "fg": "#fff",
        "name": {
            "en": "Tsurumi Line (JI)",
            "ja": "鶴見線",
            "zh-Hans": "鹤见线",
            "zh-Hant": "鶴見線"
        }
    },
    {
        "id": "mo",
        "colour": "#26326A",
        "fg": "#fff",
        "name": {
            "en": "Tokyo Monorail Haneda Airport Line (MO)",
            "ja": "東京モノレール羽田空港線",
            "zh-Hans": "东京单轨电车羽田机场线",
            "zh-Hant": "東京單軌電車羽田機場線"
        }
    },
    {
        "id": "yb",
        "colour": "#2F56A5",
        "fg": "#fff",
        "name": {
            "en": "Yokohama Municipal Subway Blue Line (B)",
            "ja": "横浜市営地下鉄ブルーライン",
            "zh-Hans": "横滨市营地铁蓝线",
            "zh-Hant": "橫濱市營地下鐵藍線"
        }
    },
    {
        "id": "yg",
        "colour": "#28846E",
        "fg": "#fff",
        "name": {
            "en": "Yokohama Municipal Subway Green Line (G)",
            "ja": "横浜市営地下鉄グリーンライン",
            "zh-Hans": "横滨市营地铁绿线",
            "zh-Hant": "橫濱市營地下鐵綠線"
        }
    },
    {
        "id": "ty",
        "colour": "#DA0042",
        "fg": "#fff",
        "name": {
            "en": "Tōkyū Tōyoko Line (TY)",
            "ja": "東急東横線",
            "zh-Hans": "东急东横线",
            "zh-Hant": "東急東橫線"
        }
    },
    {
        "id": "mg",
        "colour": "#009CD3",
        "fg": "#fff",
        "name": {
            "en": "Tōkyū Meguro Line (MG)",
            "ja": "東急目黒線",
            "zh-Hans": "东急目黑线",
            "zh-Hant": "東急目黑線"
        }
    },
    {
        "id": "dt",
        "colour": "#00AA8D",
        "fg": "#fff",
        "name": {
            "en": "Tōkyū Den-en-toshi Line (DT)",
            "ja": "東急田園都市線",
            "zh-Hans": "东急田园都市线",
            "zh-Hant": "東急田園都市線"
        }
    },
    {
        "id": "om",
        "colour": "#F18C43",
        "fg": "#fff",
        "name": {
            "en": "Tōkyū Ōimachi Line (OM)",
            "ja": "東急大井町線",
            "zh-Hans": "东急大井町线",
            "zh-Hant": "東急大井町線"
        }
    },
    {
        "id": "ik",
        "colour": "#EE86A8",
        "fg": "#fff",
        "name": {
            "en": "Tōkyū Ikegami Line (IK)",
            "ja": "東急池上線",
            "zh-Hans": "东急池上线",
            "zh-Hant": "東急池上線"
        }
    },
    {
        "id": "tm",
        "colour": "#AE0079",
        "fg": "#fff",
        "name": {
            "en": "Tōkyū Tamagawa Line (TM)",
            "ja": "東急多摩川線",
            "zh-Hans": "东急多摩川线",
            "zh-Hant": "東急多摩川線"
        }
    },
    {
        "id": "kd",
        "colour": "#0071BE",
        "fg": "#fff",
        "name": {
            "en": "Kodomonokuni Line (KD)",
            "ja": "こどもの国線",
            "zh-Hans": "子供之国线",
            "zh-Hant": "子供之國線"
        }
    },
    {
        "id": "sg",
        "colour": "#FCC800",
        "fg": "#fff",
        "name": {
            "en": "Tōkyū Setagaya Line (SG)",
            "ja": "東急世田谷線",
            "zh-Hans": "东急世田谷线",
            "zh-Hant": "東急世田谷線"
        }
    },
    {
        "id": "si",
        "colour": "#EF7A00",
        "fg": "#fff",
        "name": {
            "en": "Seibu Ikebukuro Line (SI)",
            "ja": "西武池袋線",
            "zh-Hans": "西武池袋线",
            "zh-Hant": "西武池袋線"
        }
    },
    {
        "id": "ss",
        "colour": "#00A6BF",
        "fg": "#fff",
        "name": {
            "en": "Seibu Shinjuku Line (SS)",
            "ja": "西武新宿線",
            "zh-Hans": "西武新宿线",
            "zh-Hant": "西武新宿線"
        }
    },
    {
        "id": "sk",
        "colour": "#38b35c",
        "fg": "#fff",
        "name": {
            "en": "Seibu Kokubunji Line (SK)",
            "ja": "西武国分寺線",
            "zh-Hans": "西武国分寺线",
            "zh-Hant": "西武國分寺線"
        }
    },
    {
        "id": "sw",
        "colour": "#f17c24",
        "fg": "#fff",
        "name": {
            "en": "Seibu Tamagawa Line (SW)",
            "ja": "西武多摩川線",
            "zh-Hans": "西武多摩川线",
            "zh-Hant": "西武多摩川線"
        }
    },
    {
        "id": "st",
        "colour": "#f7aa2c",
        "fg": "#fff",
        "name": {
            "en": "Seibu Tamako Line (ST)",
            "ja": "西武多摩湖線",
            "zh-Hans": "西武多摩湖线",
            "zh-Hant": "西武多摩湖線"
        }
    },
    {
        "id": "sy",
        "colour": "#ec4840",
        "fg": "#fff",
        "name": {
            "en": "Seibu Yamaguchi Line (SY)",
            "ja": "西武山口線",
            "zh-Hans": "西武山口线",
            "zh-Hant": "西武山口線"
        }
    },
    {
        "id": "ts",
        "colour": "#006CBA",
        "fg": "#fff",
        "name": {
            "en": "Tōbu Skytree Line (TS)",
            "ja": "東武スカイツリーライン",
            "zh-Hans": "东武晴空塔线",
            "zh-Hant": "東武晴空塔線"
        }
    },
    {
        "id": "ti",
        "colour": "#E61919",
        "fg": "#fff",
        "name": {
            "en": "Tōbu Isesaki Line (TI)",
            "ja": "東武伊勢崎線",
            "zh-Hans": "东武伊势崎线",
            "zh-Hant": "東武伊勢崎線"
        }
    },
    {
        "id": "tn",
        "colour": "#F5A200",
        "fg": "#fff",
        "name": {
            "en": "Tōbu Nikkō Line (TN)",
            "ja": "東武日光線",
            "zh-Hans": "东武日光线",
            "zh-Hant": "東武日光線"
        }
    },
    {
        "id": "td",
        "colour": "#40B4E5",
        "fg": "#fff",
        "name": {
            "en": "Tōbu Urban Park Line (TD)",
            "ja": "東武アーバンパークライン",
            "zh-Hans": "东武都市公园线",
            "zh-Hant": "東武都市公園線"
        }
    },
    {
        "id": "tj",
        "colour": "#00428E",
        "fg": "#fff",
        "name": {
            "en": "Tōbu Tōjō Line (TJ)",
            "ja": "東武東上線",
            "zh-Hans": "东武东上线",
            "zh-Hant": "東武東上線"
        }
    },
    {
        "id": "ks",
        "colour": "#005AAA",
        "fg": "#fff",
        "name": {
            "en": "Keisei Main Line (KS)",
            "ja": "京成本線",
            "zh-Hans": "京成本线",
            "zh-Hant": "京成本線"
        }
    },
    {
        "id": "ksnrt",
        "colour": "#FF8620",
        "fg": "#fff",
        "name": {
            "en": "Keisei Narita Airport Line (KS)",
            "ja": "京成成田空港線",
            "zh-Hans": "京成成田机场线",
            "zh-Hant": "京成成田機場線"
        }
    },
    {
        "id": "sl",
        "colour": "#EF59A1",
        "fg": "#fff",
        "name": {
            "en": "Shin-Keisei Line (SL)",
            "ja": "新京成線",
            "zh-Hans": "新京成线",
            "zh-Hant": "新京成線"
        }
    },
    {
        "id": "hs",
        "colour": "#00bdf2",
        "fg": "#fff",
        "name": {
            "en": "Hokusō Line (HS)",
            "ja": "北総線",
            "zh-Hans": "北总线",
            "zh-Hant": "北總線"
        }
    },
    {
        "id": "sr",
        "colour": "#00A650",
        "fg": "#fff",
        "name": {
            "en": "Shibayama Railway Line (SR)",
            "ja": "芝山鉄道線",
            "zh-Hans": "芝山铁道线",
            "zh-Hant": "芝山鐵道線"
        }
    },
    {
        "id": "oh",
        "colour": "#0085CE",
        "fg": "#fff",
        "name": {
            "en": "Odakyū Lines (OH/OE/OT)",
            "ja": "小田急線",
            "zh-Hans": "小田急线",
            "zh-Hant": "小田急線"
        }
    },
    {
        "id": "ko",
        "colour": "#D5007F",
        "fg": "#fff",
        "name": {
            "en": "Keiō Line (KO)",
            "ja": "京王線",
            "zh-Hans": "京王线",
            "zh-Hant": "京王線"
        }
    },
    {
        "id": "in",
        "colour": "#103675",
        "fg": "#fff",
        "name": {
            "en": "Keiō Inokashira Line (IN)",
            "ja": "京王井の頭線",
            "zh-Hans": "京王井之头线",
            "zh-Hant": "京王井之頭線"
        }
    },
    {
        "id": "kk",
        "colour": "#00BFFF",
        "fg": "#fff",
        "name": {
            "en": "Keikyū Main Line (KK)",
            "ja": "京急本線",
            "zh-Hans": "京急本线",
            "zh-Hant": "京急本線"
        }
    },
    {
        "id": "so",
        "colour": "#0071C1",
        "fg": "#fff",
        "name": {
            "en": "Sōtetsu Main Line (SO)",
            "ja": "相鉄本線",
            "zh-Hans": "相铁本线",
            "zh-Hant": "相鐵本線"
        }
    },
    {
        "id": "r",
        "colour": "#00418e",
        "fg": "#fff",
        "name": {
            "en": "Rinkai Line (R)",
            "ja": "りんかい線",
            "zh-Hans": "临海线",
            "zh-Hant": "臨海線"
        }
    },
    {
        "id": "u",
        "colour": "#1662B8",
        "fg": "#fff",
        "name": {
            "en": "New Transit Yurikamome (U)",
            "ja": "新交通ゆりかもめ",
            "zh-Hans": "百合海鸥线",
            "zh-Hant": "百合海鷗線"
        }
    },
    {
        "id": "sa",
        "colour": "#d75b80",
        "fg": "#fff",
        "name": {
            "en": "Tokyo Sakura Tram (SA)",
            "ja": "東京さくらトラム（都電荒川線）",
            "zh-Hans": "东京樱花有轨电车",
            "zh-Hant": "東京櫻花路面電車"
        }
    },
    {
        "id": "nt",
        "colour": "#D53A77",
        "fg": "#fff",
        "name": {
            "en": "Nippori-Toneri Liner (NT)",
            "ja": "日暮里・舎人ライナー",
            "zh-Hans": "日暮里-舍人线",
            "zh-Hant": "日暮里-舍人線"
        }
    },
    {
        "id": "mm",
        "colour": "#19559F",
        "fg": "#fff",
        "name": {
            "en": "Minatomirai Line (MM)",
            "ja": "みなとみらい線",
            "zh-Hans": "港未来线",
            "zh-Hant": "港未來線"
        }
    },
    {
        "id": "en",
        "colour": "#f6be18",
        "fg": "#fff",
        "name": {
            "en": "Enoshima Dentetsu Line (EN)",
            "ja": "江ノ島電鉄線",
            "zh-Hans": "江之岛电铁线",
            "zh-Hant": "江之島電鐵線"
        }
    },
    {
        "id": "tr",
        "colour": "#5AB65C",
        "fg": "#fff",
        "name": {
            "en": "Tōyō Rapid Railway Line (TR)",
            "ja": "東葉高速線",
            "zh-Hans": "东叶高速线",
            "zh-Hant": "東葉高速線"
        }
    },
    {
        "id": "srr",
        "colour": "#3564AF",
        "fg": "#fff",
        "name": {
            "en": "Saitama Rapid Railway Line (SR)",
            "ja": "埼玉高速鉄道線",
            "zh-Hans": "埼玉高速铁道线",
            "zh-Hant": "埼玉高速鐵道線"
        }
    },
    {
        "id": "tt",
        "colour": "#27625E",
        "fg": "#fff",
        "name": {
            "en": "Tama Toshi Monorail Line",
            "ja": "多摩都市モノレール線",
            "zh-Hans": "多摩都市单轨电车线",
            "zh-Hant": "多摩都市單軌電車線"
        }
    },
    {
        "id": "ns",
        "colour": "#18A698",
        "fg": "#fff",
        "name": {
            "en": "Ina Line (NS)",
            "ja": "伊奈線",
            "zh-Hans": "伊奈线",
            "zh-Hant": "伊奈線"
        }
    },
    {
        "id": "cd",
        "colour": "#a52a2a",
        "fg": "#fff",
        "name": {
            "en": "Chōshi Electric Railway Line (CD)",
            "ja": "銚子電気鉄道線",
            "zh-Hans": "铫子电气铁道线",
            "zh-Hant": "銚子電氣鐵道線"
        }
    },
    {
        "id": "cm",
        "colour": "#2843ba",
        "fg": "#fff",
        "name": {
            "en": "Chiba Urban Monorail (CM)",
            "ja": "千葉都市モノレール",
            "zh-Hans": "千叶都市单轨电车",
            "zh-Hant": "千葉都市單軌電車"
        }
    }
]</details>

**Comment by linchen1965** [comment]
感谢你对本项目部所做的贡献，请在投稿时将来源的链接取代下面这行字：

> 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

（请在收到本条消息后尽快及时回复，超过一个月未回复的我们将不会汇入）

**Comment by WanyunMediaGroup** [comment]
Roger. 收到。



在 2022-11-24 03:35:29，"linchen1965" ***@***.***> 写道：

感谢你对本项目部所做的贡献，请在投稿时将来源的链接取代下面这行字：

请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

（请在收到本条消息后尽快及时回复，超过一个月未回复的我们将不会汇入）

**Comment by 52PD** [comment]
你好 @WanyunMediaGroup ，经查询阁下所提供之维基百科，我们发现阁下所提供的除东京地下铁外的大部分颜色与维基百科所用之颜色并不匹配。
因为我们建议您及时检查您所提供的线路颜色并本issue中提交正确的颜色。感谢您对本项目的支持。

此外，对于此前其他资源管理员未经审核就将其汇入项目的失误，我们深感抱歉。
(请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
Closed as no response.
