### ISSUE TITLE
Resources: New palettes of Taoyuan

### ISSUE THREAD

**Issue by WanyunMediaGroup** [railmapgen/rmg-palette#256]
**Justification:** (Modified by @52PD ) 台北、新北两地捷运的路线均已增加颜色。桃园也是台北都市圈的一部分，建议将桃园捷运颜色纳入其中。所有颜色根据中文维基百科以及桃园捷运公司官方网站上路线的官方资料颜色取色进行制作。

https://www.tymetro.com.tw/tymetro-new/tw/_pages/travel-guide/road.html

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "taoyuan",
    "country": "TW",
    "name": {
        "en": "Taoyuan",
        "zh-Hans": "桃园",
        "zh-Hant": "桃園"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "tyg",
        "colour": "#62a130",
        "fg": "#fff",
        "name": {
            "en": "Green Line",
            "zh-Hans": "绿线",
            "zh-Hant": "綠線"
        }
    },
    {
        "id": "tybr",
        "colour": "#824729",
        "fg": "#fff",
        "name": {
            "en": "Brown Line",
            "zh-Hans": "棕线",
            "zh-Hant": "棕線"
        }
    },
    {
        "id": "tyo",
        "colour": "#ffa500",
        "fg": "#fff",
        "name": {
            "en": "Orange Line",
            "zh-Hans": "橘线",
            "zh-Hant": "橘線"
        }
    },
    {
        "id": "tya",
        "colour": "#8344b1",
        "fg": "#fff",
        "name": {
            "en": "Taoyuan Airport MRT",
            "zh-Hans": "桃园机场捷运",
            "zh-Hant": "桃園機場捷運"
        }
    }
]</details>

**Comment by linchen1965** [comment]
感谢你对本项目部所做的贡献，请在投稿时将来源的链接取代下面这行字：

> 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

（请在收到本条消息后尽快及时回复，超过一个月未回复的我们将不会汇入）

**Comment by WanyunMediaGroup** [comment]
Roger. 收到。



在 2022-11-24 03:34:27，"linchen1965" ***@***.***> 写道：

感谢你对本项目部所做的贡献，请在投稿时将来源的链接取代下面这行字：

请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

（请在收到本条消息后尽快及时回复，超过一个月未回复的我们将不会汇入）

**Comment by 52PD** [comment]
你好 @WanyunMediaGroup ，经查询阁下所提供之维基百科，我们发现阁下所提供的蓝线与机场捷运颜色与官方网站所用之颜色并不匹配。
![Screenshot 2022-11-26 at 3 51 29 PM](https://user-images.githubusercontent.com/98044618/204108423-3750dcbe-c1a3-4b77-bc3a-675a949f2e0e.png)
因为我们建议您及时检查您所提供的线路颜色并本issue中提交正确的颜色。感谢您对本项目的支持。

此外，对于此前其他资源管理员未经审核就将其汇入项目的失误，我们深感抱歉。
(请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
Closed as no response.
