### ISSUE TITLE
Resources: New palettes of Nantong

### ISSUE THREAD

**Issue by JaSevDon** [railmapgen/rmg-palette#265]
**Justification:** 
Wikipedia [https://zh.wikipedia.org/wiki/%E5%8D%97%E9%80%9A%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A](url)
Official Site [https://service.ntrailway.com/#/Siteguides](url)
**南通地铁现已开通，可将其加入到调色板中。**

第三次创建页面了......前两个页面因为自己不熟练和一些奇怪的原因失败了，希望这次可以成功。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "nantong",
    "country": "CN",
    "name": {
        "en": "Nantong",
        "zh-Hans": "南通",
        "zh-Hant": "南通"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "nt1",
        "colour": "#e6000d",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號綫"
        }
    },
    {
        "id": "nt2",
        "colour": "#5d9ccf",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號綫"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好 @JaSevDon ，经查询阁下所提供之维基百科，我们发现阁下所提供之颜色与官方网站所用之颜色并不匹配。
![Screenshot 2022-11-26 at 3 27 30 PM](https://user-images.githubusercontent.com/98044618/204107839-66036651-fe65-44e6-96be-e75bc2fb7cda.png)
因为我们建议您及时检查您所提供的线路颜色并在本issue后提交正确的颜色。感谢您对本项目的支持。

此外，对于此前其他资源管理员未经审核就将其汇入项目的失误，我们深感抱歉。
(请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
> 请问是直接在Issues回复颜色的RGB代码就可以了吗？还是要进行手动修改

给RGB代码就行，之后的汇入处理交给我们就行

**Comment by 52PD** [comment]
您好，有关重新提供的颜色请问能否提供一下确切来源呢？

我刚刚对您所重新提供的颜色与官方线路图进行了相关对比，发现两者色差仍然明显，因此我们需要再度核对您所提供颜色的来源以确保颜色与所提供来源相符。谢谢。

![rBVxA2MruW2ANDSWAA4xHgiuHtc855%5E%5E%5E%5E%E7%BA%BF%E8%B7%AFi%E5%9B%BE](https://user-images.githubusercontent.com/98044618/204150139-578d5688-fff3-47a7-9417-4d8de13295dc.jpg)
（上图左侧为您所提供的颜色，右侧为官方线路图所用颜色）

**Comment by 52PD** [comment]
好的，这次检查后已经没问题了
