### ISSUE TITLE
"Supplement 1" of Changsha Metro Color palette should be renamed as "Maglev Line"

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmg-palette#29]
http://www.hncsmtr.com/attachment/201789/15022650755656559.jpg
This picture of Changsha Metro official site (published in 2017, shows old planning) shows the color of "Maglev Line". It uses the current "Supplement 1" color of Changsha Metro Color palette, which published in 2010. The Maglev Line opened in 2016 and use the pink color of "Supplement 1".
As the new planning of Changsha Metro shows, it'll be 14 metro lines and the Maglev Line in the network. So the "Supplement 2" must belongs to Line 13. And Line 14 will have a unpublished new color.

**Comment by wongchito** [comment]
Hi @linchen1965,

According to the picture provided and some researches I did, I'll do the following changes to Changsha's palette:

1. Supplement 1 -> Maglev Express (磁浮快線)
2. Foreground of Maglev Express: black -> white

However, there's no enough evidence to support that Supplement 2 colour is reserve for any new line. Could you please provide more detail or we can update that later. 

Thank you!

**Comment by linchen1965** [comment]
The 14-Lines-planning is a long term planning so it's hard to find a evidence to support it now. So we can update the changed name of Supplement 2 color later.
(The Maglev Express opened in 2016 and used the Supplement 1 color .The original Color palette was published in 2010. So I think the same thing might be happened on Supplement 2)
