### ISSUE TITLE
Resources: New palettes of 

### ISSUE THREAD

**Issue by sfyygy-001** [railmapgen/rmg-palette#291]
**Justification:** Please provide any source or justification or we will not proceed with your request. (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "",
    "country": "CN",
    "name": {
        "en": ""
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "",
        "colour": "#00ffff",
        "fg": "#fff",
        "name": {
            "en": ""
        }
    }
]</details>

**Comment by 52PD** [comment]
Closed as vandalism content.
This issue will also been locked.
