### ISSUE TITLE
Resources: New palettes of Xiangyang

### ISSUE THREAD

**Issue by chenrunye** [railmapgen/rmg-palette#294]
**Justification:** 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "xiangyang",
    "country": "CN",
    "name": {
        "en": "Xiangyang",
        "zh-Hans": "襄阳",
        "zh-Hant": "襄陽"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "xy1",
        "colour": "#e8303a",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "xy2",
        "colour": "#495adf",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "xy3",
        "colour": "#f570dd",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "xy4",
        "colour": "#9a26d9",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "xy5",
        "colour": "#88f05c",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
Closed as invalid data.
