### ISSUE TITLE
Resources: New palettes of Hefei

### ISSUE THREAD

**Issue by PDpg** [railmapgen/rmg-palette#298]
将一些在建线路颜色添加了进来

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hefei",
    "country": "CN",
    "name": {
        "zh": "合肥",
        "en": "Hefei"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "hf1",
        "colour": "#e61e25",
        "fg": "#fff",
        "name": {
            "zh": "1号线",
            "en": "Line 1"
        }
    },
    {
        "id": "hf2",
        "colour": "#0168b3",
        "fg": "#fff",
        "name": {
            "zh": "2号线",
            "en": "Line 2"
        }
    },
    {
        "id": "hf3",
        "colour": "#00843d",
        "fg": "#fff",
        "name": {
            "zh": "3号线",
            "en": "Line 3"
        }
    },
    {
        "id": "hf4",
        "colour": "#f79727",
        "fg": "#fff",
        "name": {
            "zh": "4号线",
            "en": "Line 4"
        }
    },
    {
        "id": "hf5",
        "colour": "#c1d72f",
        "fg": "#fff",
        "name": {
            "zh": "5号线",
            "en": "Line 5"
        }
    },
    {
        "id": "hf6",
        "colour": "#613ee0",
        "fg": "#fff",
        "name": {
            "zh": "6号线",
            "en": "Line 6"
        }
    },
    {
        "id": "hf7",
        "colour": "#fee920",
        "fg": "#fff",
        "name": {
            "zh": "7号线",
            "en": "Line 7"
        }
    },
    {
        "id": "hf8",
        "colour": "#2bd6f3",
        "fg": "#fff",
        "name": {
            "zh": "8号线",
            "en": "Line 8"
        }
    },
    {
        "id": "hfs1",
        "colour": "#905730",
        "fg": "#fff",
        "name": {
            "zh": "S1号线",
            "en": "Line S1"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，请问你方便的话是否能够提供线路颜色的来源呢？

我们不会接受任何无颜色来源的投稿

此外，请在提交线路颜色时讲下面这行字替换掉：

> 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

以上这行字不替换的话我们负责汇入资源的bot就无法触发，因此我们也就无法将其汇入资源。

(请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色稿件缺失来源后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
