### ISSUE TITLE
Resources: New palettes of Luoyang

### ISSUE THREAD

**Issue by SeasaltYan** [railmapgen/rmg-palette#300]
**Justification:** 新增洛阳轨道交通1号线、2号线标识色信息，数据来源于轨道集团官方回复。
**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "luoyang",
    "country": "CN",
    "name": {
        "en": "Luoyang",
        "zh-Hans": "洛阳",
        "zh-Hant": "洛陽"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "ly1",
        "colour": "#c4608c",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "ly2",
        "colour": "#6fba2c",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
> 数据来源于轨道集团官方回复。

您好，您所提供的来源为无效来源。如果您所获得的线路颜色来源来自于官方回复，那么请您将所回复内容中包含线路颜色的部分同样上传上来，这样我们才能对您所提供之颜色进行核实，谢谢。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
感谢。经检查已经没有任何问题了。

由于目前项目中仍有其他线路颜色我们正在等待提供者提供更多信息，我们将会在这些项目准备完成后将您所提供的线路颜色一并汇入到项目中，敬请期待！
