### ISSUE TITLE
Resources: New palettes of Hangzhou

### ISSUE THREAD

**Issue by Benteds** [railmapgen/rmg-palette#305]
**Justification:** 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hangzhou",
    "country": "CN",
    "name": {
        "en": "Hangzhou",
        "zh": "杭州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "hz1",
        "colour": "#DF4661",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "hz2",
        "colour": "#f1803a",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "hz3",
        "colour": "#ffcd00",
        "fg": "#000",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "hz4",
        "colour": "#6CC24A",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "hz5",
        "colour": "#00AEC7",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "hz6",
        "colour": "#0072CE",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "hz7",
        "colour": "#87189D",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "hz8",
        "colour": "#AC145A",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "hz9",
        "colour": "#BE4D00",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "hz10",
        "colour": "#daaa00",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "hz16",
        "colour": "#FFB25B",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "hz19",
        "colour": "#05c3de",
        "fg": "#fff",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线",
            "zh-Hant": "19號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，虽然很感谢你对本项目部所做的贡献，但请问你方便的话是否能够提供线路颜色的来源呢？

我们不会接受任何无颜色来源的投稿

此外，请在提交线路颜色时讲下面这行字替换掉：

> 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

以上这行字不替换的话我们负责汇入资源的bot就无法触发，因此我们也就无法将其汇入资源。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
您好，由于以下问题，我们不会接受你的投稿：
1. 没有提供适当来源，无适当来源的投稿我们不会直接接收。
2. 没有更改“请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)”这句话，不更改这句话会导致我们设立的项目汇入机器人无法触发，从而导致我们无法将线路颜色代码汇入项目中。
3. 您所提供的重庆地铁线路颜色与目前项目中拥有的重庆地铁颜色完全相同，因此我们无法确定您提交本issue是因为疏忽未注意到重庆地铁颜色已经存在于项目中还是为了恶意破坏。
