### ISSUE TITLE
*Vandalism Content*

### ISSUE THREAD

**Issue by JKsn916** [railmapgen/rmg-palette#306]
**Justification:** 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "wuhan",
    "country": "CN",
    "name": {
        "en": "Wuhan",
        "zh-Hans": "武汉",
        "zh-Hant": "武漢"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "wh1",
        "colour": "#3D84C6",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "wh2",
        "colour": "#EB7CAF",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "wh3",
        "colour": "#D9B966",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "wh4",
        "colour": "#00ff00",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "wh5",
        "colour": "#E63F00",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "wh6",
        "colour": "#008536",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "wh7",
        "colour": "#EB7900",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "wh8",
        "colour": "#98ACAB",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "wh9",
        "colour": "#A5D4AD",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "wh10",
        "colour": "#8C3626",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "wh11",
        "colour": "#F2CF01",
        "fg": "#000",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "wh12",
        "colour": "#00ffff",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "wh13",
        "colour": "#25CAD0",
        "fg": "#fff",
        "name": {
            "en": "Line 13",
            "zh-Hans": "校校通线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "wh14",
        "colour": "#7D55A3",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "wh16",
        "colour": "#CC0256",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "wh21",
        "colour": "#CF0192",
        "fg": "#fff",
        "name": {
            "en": "Line 21",
            "zh-Hans": "21号线",
            "zh-Hant": "21號線"
        }
    },
    {
        "id": "wh17",
        "colour": "#ecb1ac",
        "fg": "#000",
        "name": {
            "en": "Line 17",
            "zh-Hans": "刘莹线",
            "zh-Hant": "刘莹線"
        }
    }
]</details>

**Comment by 52PD** [comment]
请问方便的话是否能够提供线路颜色的来源？

我们不会接受任何无颜色来源的投稿

（请在收到本条消息后尽快及时回复，任何无回应的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
Closed as vandalism content.
This issue will also been locked.
