### ISSUE TITLE
Resources: New palettes of Beijing

### ISSUE THREAD

**Issue by lty110** [railmapgen/rmg-palette#308]
**Justification:** 北京地铁3号线和12号线即将开通 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "beijing",
    "country": "CN",
    "name": {
        "en": "Beijing",
        "zh-Hans": "北京",
        "zh-Hant": "北京"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "bj1",
        "colour": "#c23a30",
        "fg": "#fff",
        "name": {
            "en": "Line 1/Batong Line",
            "zh-Hans": "1号线/八通线",
            "zh-Hant": "1號線/八通線"
        }
    },
    {
        "id": "bj2",
        "colour": "#006098",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "bj4",
        "colour": "#008e9c",
        "fg": "#fff",
        "name": {
            "en": "Line 4/Daxing Line",
            "zh-Hans": "4号线/大兴线",
            "zh-Hant": "4號線/大興線"
        }
    },
    {
        "id": "bj5",
        "colour": "#a6217f",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "bj6",
        "colour": "#d29700",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "bj7",
        "colour": "#f6c582",
        "fg": "#000",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "bj8",
        "colour": "#009b6b",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "bj9",
        "colour": "#8fc31f",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "bj10",
        "colour": "#009bc0",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "bj11",
        "colour": "#ED796B",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "bj13",
        "colour": "#f9e700",
        "fg": "#000",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "bj14",
        "colour": "#d5a7a1",
        "fg": "#000",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "bj15",
        "colour": "#5b2c68",
        "fg": "#fff",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "bj16",
        "colour": "#76a32e",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "bj17",
        "colour": "#00A9A9",
        "fg": "#fff",
        "name": {
            "en": "Line 17",
            "zh-Hans": "17号线",
            "zh-Hant": "17號線"
        }
    },
    {
        "id": "bj19",
        "colour": "#D6ABC1",
        "fg": "#000",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线",
            "zh-Hant": "19號線"
        }
    },
    {
        "id": "bj25fs",
        "colour": "#e46022",
        "fg": "#fff",
        "name": {
            "en": "Fangshan Line/Yanfang Line",
            "zh-Hans": "房山线/燕房线",
            "zh-Hant": "房山線/燕房線"
        }
    },
    {
        "id": "bj27cp",
        "colour": "#de82b2",
        "fg": "#fff",
        "name": {
            "en": "Changping Line",
            "zh-Hans": "昌平线",
            "zh-Hant": "昌平線"
        }
    },
    {
        "id": "bj24yz",
        "colour": "#e40077",
        "fg": "#fff",
        "name": {
            "en": "Yizhuang Line",
            "zh-Hans": "亦庄线",
            "zh-Hant": "亦莊線"
        }
    },
    {
        "id": "bj26s1",
        "colour": "#b35a20",
        "fg": "#fff",
        "name": {
            "en": "Line S1",
            "zh-Hans": "S1线",
            "zh-Hant": "S1線"
        }
    },
    {
        "id": "bj34sj",
        "colour": "#a29bbb",
        "fg": "#fff",
        "name": {
            "en": "Capital Airport Express",
            "zh-Hans": "首都机场线",
            "zh-Hant": "首都機場線"
        }
    },
    {
        "id": "bj35dj",
        "colour": "#004a9f",
        "fg": "#fff",
        "name": {
            "en": "Daxing Airport Express",
            "zh-Hans": "大兴机场线",
            "zh-Hant": "大興機場線"
        }
    },
    {
        "id": "btxj",
        "colour": "#e50619",
        "fg": "#fff",
        "name": {
            "en": "Xijiao Line",
            "zh-Hans": "西郊线",
            "zh-Hant": "西郊線"
        }
    },
    {
        "id": "btt1",
        "colour": "#e5061b",
        "fg": "#fff",
        "name": {
            "en": "Yizhuang T1 Line",
            "zh-Hans": "亦庄T1线",
            "zh-Hant": "亦莊T1線"
        }
    },
    {
        "id": "bj3",
        "colour": "#ee1b24",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "bj12",
        "colour": "#945124",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
你好，请问你方便的话是否能够提供线路颜色的来源呢？

我们不会接受任何无颜色来源的投稿

(请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色稿件缺失来源后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
