### ISSUE TITLE
深圳地铁新

### ISSUE THREAD

**Issue by JiangYuanshen** [railmapgen/rmg-palette#309]
Hi RMG team! I would like to contribute the palettes below.

**Justification:** Please provide any source or justification or we will not proceed with your request. (REPLACE ME)
**Justification:** 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shenzhen",
    "country": "CN",
    "name": {
        "en": "Shenzhen",
        "zh-Hans": "深圳",
        "zh-Hant": "深圳"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sz1",
        "colour": "#00B140",
        "fg": "#fff",
        "name": {
            "en": "Line 1 (Luobao Line)",
            "zh-Hans": "1号线（罗宝线）",
            "zh-Hant": "1號綫（羅寶綫）"
        }
    },
    {
        "id": "sz2",
        "colour": "#B94700",
        "fg": "#fff",
        "name": {
            "en": "Line 2 (Shekou Line)",
            "zh-Hans": "2号线（蛇口线）",
            "zh-Hant": "2號綫（蛇口綫）"
        }
    },
    {
        "id": "sz3",
        "colour": "#00A9E0",
        "fg": "#fff",
        "name": {
            "en": "Line 3 (Longgang Line)",
            "zh-Hans": "3号线（龙岗线）",
            "zh-Hant": "3號綫（龍崗綫）"
        }
    },
    {
        "id": "sz4",
        "colour": "#DA291C",
        "fg": "#fff",
        "name": {
            "en": "Line 4 (Longhua Line)",
            "zh-Hans": "4号线（龙华线）",
            "zh-Hant": "4號綫（龍華綫）"
        }
    },
    {
        "id": "sz5",
        "colour": "#A05EB5",
        "fg": "#fff",
        "name": {
            "en": "Line 5 (Huanzhong Line)",
            "zh-Hans": "5号线（环中线）",
            "zh-Hant": "5號綫（環中綫）"
        }
    },
    {
        "id": "sz6",
        "colour": "#00C7B1",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號綫"
        }
    },
    {
        "id": "sz6b",
        "colour": "#168773",
        "fg": "#fff",
        "name": {
            "en": "Line 6 branch",
            "zh-Hans": "6号线支线",
            "zh-Hant": "6號綫支綫"
        }
    },
    {
        "id": "sz7",
        "colour": "#0033A0",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號綫"
        }
    },
    {
        "id": "sz8",
        "colour": "#E45DBF",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號綫"
        }
    },
    {
        "id": "sz9",
        "colour": "#7B6469",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號綫"
        }
    },
    {
        "id": "sz10",
        "colour": "#F8779E",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號綫"
        }
    },
    {
        "id": "sz11",
        "colour": "#672146",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號綫"
        }
    },
    {
        "id": "sz12",
        "colour": "#A192B2",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號綫"
        }
    },
    {
        "id": "sz13",
        "colour": "#DE7C00",
        "fg": "#fff",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號綫"
        }
    },
    {
        "id": "sz14",
        "colour": "#F2C75C",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號綫"
        }
    },
    {
        "id": "sz15",
        "colour": "#84BD00",
        "fg": "#fff",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號綫"
        }
    },
    {
        "id": "sz16",
        "colour": "#1E22AA",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號綫"
        }
    },
    {
        "id": "sz17",
        "colour": "#017c83",
        "fg": "#fff",
        "name": {
            "en": "Line 17",
            "zh-Hans": "17号线",
            "zh-Hant": "17號綫"
        }
    },
    {
        "id": "sz18",
        "colour": "#1e90ff",
        "fg": "#fff",
        "name": {
            "en": "Line 18",
            "zh-Hans": "18号线",
            "zh-Hant": "18號綫"
        }
    },
    {
        "id": "sz20",
        "colour": "#88DBDF",
        "fg": "#fff",
        "name": {
            "en": "Line 20",
            "zh-Hans": "20号线",
            "zh-Hant": "20號綫"
        }
    },
    {
        "id": "sz23",
        "colour": "#aa5d4a",
        "fg": "#fff",
        "name": {
            "en": "Line 23",
            "zh-Hans": "23号线",
            "zh-Hant": "23號綫"
        }
    },
    {
        "id": "sz24",
        "colour": "#f54f1b",
        "fg": "#fff",
        "name": {
            "en": "Line 24",
            "zh-Hans": "24号线",
            "zh-Hant": "24號綫"
        }
    },
    {
        "id": "sz25",
        "colour": "#4269de",
        "fg": "#fff",
        "name": {
            "en": "Line 25",
            "zh-Hans": "25号线",
            "zh-Hant": "25號綫"
        }
    },
    {
        "id": "sz26",
        "colour": "#c72c88",
        "fg": "#fff",
        "name": {
            "en": "Line 26",
            "zh-Hans": "26号线",
            "zh-Hant": "26號綫"
        }
    },
    {
        "id": "sz27",
        "colour": "#3c8065",
        "fg": "#fff",
        "name": {
            "en": "Line 27",
            "zh-Hans": "27号线",
            "zh-Hant": "27號綫"
        }
    },
    {
        "id": "sz29",
        "colour": "#9f2f47",
        "fg": "#fff",
        "name": {
            "en": "Line 29",
            "zh-Hans": "29号线",
            "zh-Hant": "29號綫"
        }
    },
    {
        "id": "sz32",
        "colour": "#ba5801",
        "fg": "#fff",
        "name": {
            "en": "Line 32",
            "zh-Hans": "32号线",
            "zh-Hant": "32號綫"
        }
    },
    {
        "id": "szyg",
        "colour": "#b7b7b9",
        "fg": "#fff",
        "name": {
            "en": "Tram",
            "zh-Hans": "有轨电车",
            "zh-Hant": "有軌電車"
        }
    }
]</details>
_Enter new palettes data and follow instruction in https://railmapgen.github.io/rmg-palette/new_

**Comment by JiangYuanshen** [comment]
[深圳地铁.docx](https://github.com/railmapgen/rmg-palette/files/10311541/default.docx)

**Comment by 52PD** [comment]
您好，很抱歉由于您所提交的issue格式有问题，我们无法将其汇入项目中。

我们建议您通过[railmapgen.github.io/rmg-palette](https://railmapgen.github.io/rmg-palette)重新提交一次issue。

此外，请在重新提交issue时补充线路颜色来源，任何没有来源的issue我们会拒绝汇入。
