### ISSUE TITLE
Resources: New palettes of Taiyuan

### ISSUE THREAD

**Issue by xrdrsp** [railmapgen/rmg-palette#311]
**Justification:** Taiyuan, Shanxi, China (Reference: wikipedia & [AtoZ wiki](https://atozwiki.com/Line_2_(Taiyuan_Metro)))

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "taiyuan",
    "country": "CN",
    "name": {
        "en": "Taiyuan",
        "zh-Hans": "太原"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "2",
        "colour": "#da2b30",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，经检查我们发现您所提交的线路颜色（#DA2B30）与AtoZ Wiki中的颜色相符，但与维基百科中的颜色（#B31C21）有不同

考虑到我们现只接受官方网站和维基百科中的颜色，我们在最终汇入的版本中会优先采用您所提供的维基百科中的颜色。谢谢。

**Comment by xrdrsp** [comment]
对不起，当时没访问上wikipedia，麻烦了
