### ISSUE TITLE
*Vandalism Content*

### ISSUE THREAD

**Issue by BinguoCity** [railmapgen/rmg-palette#315]
Hi RMG team! I would like to contribute the palettes below.

**Justification:** Please provide any source or justification or we will not proceed with your request. (REPLACE ME)

_Enter new palettes data and follow instruction in **Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "BG",
    "name": {
        "zh": "宾果/賓果/Binguo"
    }
}</details>

<details repo="rmg-palette" type="city">{
    "id": "binguo",
    "country": "BG",
    "name": {
        "zh": "宾果市/賓果市/Binguo City"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "BGRT1",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "zh-Hans": "一号线"
        }
    }
]</details>https://railmapgen.github.io/rmg-palette/new_

**Comment by 52PD** [comment]
Closed as vandalism content.
This issue will also been locked.
