### ISSUE TITLE
Resources: New palettes of New York

### ISSUE THREAD

**Issue by t-chai** [railmapgen/rmg-palette#317]
Hi RMG team! I would like to contribute the palettes below.

**Justification:** (Modified by @52PD ) https://en.wikipedia.org/wiki/New_York_City_Subway

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "newyork",
    "country": "US",
    "name": {
        "en": "New York",
        "zh-Hans": "纽约",
        "zh-Hant": "紐約"
    }
}</details>

<details repo="rmg-palette" type="lines">[ { "id": "nybdfm", "colour": "#ff6319", "fg": "#fff", "name": { "en": "IND Sixth Avenue Line", "zh-Hans": "IND第六大道线" } }, { "id": "nyace", "colour": "#0039a6", "fg": "#fff", "name": { "en": "IND Eighth Avenue Line", "zh-Hans": "IND第八大道线" } }, { "id": "nyl", "colour": "#a7a9ac", "fg": "#fff", "name": { "en": "BMT Canarsie Line", "zh-Hans": "BMT卡纳西线" } }, { "id": "nyg", "colour": "#6cbe45", "fg": "#fff", "name": { "en": "IND Crosstown Line", "zh-Hans": "IND跨城线" } }, { "id": "nyjz", "colour": "#996633", "fg": "#fff", "name": { "en": "BMT Nassau Street Line", "zh-Hans": "BMT纳苏街线" } }, { "id": "nynqrw", "colour": "#fccc0a", "fg": "#000", "name": { "en": "BMT Broadway Line", "zh-Hans": "BMT百老汇线" } }, { "id": "ny456", "colour": "#00933c", "fg": "#fff", "name": { "en": "IRT Lexington Avenue Line", "zh-Hans": "IRT莱辛顿大道线" } }, { "id": "ny123", "colour": "#ee352e", "fg": "#fff", "name": { "en": "IRT Broadway–Seventh Avenue Line", "zh-Hans": "IRT百老汇-第七大道线" } }, { "id": "nyt", "colour": "#00add0", "fg": "#fff", "name": { "en": "IND Second Avenue Line", "zh-Hans": "IND第二大道线" } }, { "id": "ny7", "colour": "#b933ad", "fg": "#fff", "name": { "en": "IRT Flushing Line", "zh-Hans": "IRT法拉盛线" } }, { "id": "nys", "colour": "#808183", "fg": "#fff", "name": { "en": "Shuttles", "zh-Hans": "接驳线" } } ]</details>

**Comment by 52PD** [comment]
Closed as invalid data. The previous merge will be rollback soon.

请给每条线路提供正确的ID名，谢谢。

**Comment by 52PD** [comment]
OK

经检查已经没问题了。
