### ISSUE TITLE
Resources: New palettes of Shenzhen

### ISSUE THREAD

**Issue by s1s1s1s1s1s** [railmapgen/rmg-palette#318]
Hi RMG team! I would like to contribute the palettes below.

**Justification:** 《深圳市城市轨道交通第五期建设规划（2023-2028年）》已批复，预计2023年开工
_Enter new palettes data and follow instruction in https://railmapgen.github.io/rmg-palette/new_
**Justification:** 来源：《深圳市城市轨道交通第五期建设规划（2023-2028年）》环评第二次公示

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shenzhen",
    "country": "CN",
    "name": {
        "en": "Shenzhen",
        "zh": "深圳"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sz1",
        "colour": "#00B140",
        "fg": "#fff",
        "name": {
            "en": "Line 1 (Luobao Line)",
            "zh-Hans": "1号线（罗宝线）",
            "zh-Hant": "1號線（羅寶線）"
        }
    },
    {
        "id": "sz2",
        "colour": "#B94700",
        "fg": "#fff",
        "name": {
            "en": "Line 2 (Shekou Line)",
            "zh-Hans": "2号线（蛇口线）",
            "zh-Hant": "2號線（蛇口線）"
        }
    },
    {
        "id": "sz3",
        "colour": "#00A9E0",
        "fg": "#fff",
        "name": {
            "en": "Line 3 (Longgang Line)",
            "zh-Hans": "3号线（龙岗线）",
            "zh-Hant": "3號線（龍崗線）"
        }
    },
    {
        "id": "sz4",
        "colour": "#DA291C",
        "fg": "#fff",
        "name": {
            "en": "Line 4 (Longhua Line)",
            "zh-Hans": "4号线（龙华线）",
            "zh-Hant": "4號線（龍華線）"
        }
    },
    {
        "id": "sz5",
        "colour": "#A05EB5",
        "fg": "#fff",
        "name": {
            "en": "Line 5 (Huanzhong Line)",
            "zh-Hans": "5号线（环中线）",
            "zh-Hant": "5號線（環中線）"
        }
    },
    {
        "id": "sz6",
        "colour": "#00C7B1",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "sz6b",
        "colour": "#168773",
        "fg": "#fff",
        "name": {
            "en": "Line 6 branch",
            "zh-Hans": "6号线支线",
            "zh-Hant": "6號線支線"
        }
    },
    {
        "id": "sz7",
        "colour": "#0033A0",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "sz8",
        "colour": "#E45DBF",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "sz9",
        "colour": "#7B6469",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "sz10",
        "colour": "#F8779E",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "sz11",
        "colour": "#672146",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "sz12",
        "colour": "#A192B2",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "sz13",
        "colour": "#DE7C00",
        "fg": "#fff",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "sz14",
        "colour": "#F2C75C",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "sz15",
        "colour": "#84BD00",
        "fg": "#fff",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "sz16",
        "colour": "#1E22AA",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "sz17",
        "colour": "#027c83",
        "fg": "#fff",
        "name": {
            "en": "Line 17",
            "zh-Hans": "17号线",
            "zh-Hant": "17號線"
        }
    },
    {
        "id": "sz18",
        "colour": "#1e90ff",
        "fg": "#fff",
        "name": {
            "en": "Line 18",
            "zh-Hans": "18号线",
            "zh-Hant": "18號線"
        }
    },
    {
        "id": "sz19",
        "colour": "#3d8b6a",
        "fg": "#fff",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线",
            "zh-Hant": "19號線"
        }
    },
    {
        "id": "sz20",
        "colour": "#88DBDF",
        "fg": "#fff",
        "name": {
            "en": "Line 20",
            "zh-Hans": "20号线",
            "zh-Hant": "20號線"
        }
    },
    {
        "id": "sz21",
        "colour": "#936741",
        "fg": "#fff",
        "name": {
            "en": "Line 21",
            "zh-Hans": "21号线",
            "zh-Hant": "21號線"
        }
    },
    {
        "id": "sz22",
        "colour": "#13825f",
        "fg": "#fff",
        "name": {
            "en": "Line 22",
            "zh-Hans": "22号线",
            "zh-Hant": "22號線"
        }
    },
    {
        "id": "sz25",
        "colour": "#426ade",
        "fg": "#fff",
        "name": {
            "en": "Line 25",
            "zh-Hans": "25号线",
            "zh-Hant": "25號線"
        }
    },
    {
        "id": "sz27",
        "colour": "#347664",
        "fg": "#fff",
        "name": {
            "en": "Line 27",
            "zh-Hans": "27号线",
            "zh-Hant": "27號線"
        }
    },
    {
        "id": "sz29",
        "colour": "#ad3d4c",
        "fg": "#fff",
        "name": {
            "en": "Line 29",
            "zh-Hans": "29号线",
            "zh-Hant": "29號線"
        }
    },
    {
        "id": "sz32",
        "colour": "#8c60d3",
        "fg": "#fff",
        "name": {
            "en": "Line 32",
            "zh-Hans": "32号线",
            "zh-Hant": "32號線"
        }
    },
    {
        "id": "sz33",
        "colour": "#e874b6",
        "fg": "#fff",
        "name": {
            "en": "Line 33(Shenzhen International Airport-Dayawan Intercity Railway)",
            "zh-Hans": "33号线（深大城际）",
            "zh-Hant": "33號線（深大城際）"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，经查阅网络，我们并未找到任何包括“《深圳市城市轨道交通第五期建设规划（2023-2028年）》”字样的网站中有提供新增线路颜色的图块/代码，因此我们无法检查新增线路颜色是否正确。

请提供您所使用的颜色来源的确切网址，谢谢。

**Comment by 52PD** [comment]
Update the closing status to "closed as not planned".
