### ISSUE TITLE
Resources: New palettes of Guiyang

### ISSUE THREAD

**Issue by AceMendeleev** [railmapgen/rmg-palette#327]
**Justification:** 这是从贵阳轨道交通发布的图片上取色得到的

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "guiyang",
    "country": "CN",
    "name": {
        "zh-Hans": "贵阳",
        "en": "Guiyang"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "gy1",
        "colour": "#33cc33",
        "fg": "#fff",
        "name": {
            "zh-Hans": "1号线",
            "en": "Line 1"
        }
    },
    {
        "id": "gy2",
        "colour": "#0034c7",
        "fg": "#fff",
        "name": {
            "zh-Hans": "2号线",
            "en": "Line 2"
        }
    },
    {
        "id": "gy3",
        "colour": "#f72121",
        "fg": "#fff",
        "name": {
            "zh-Hans": "3号线",
            "en": "Line 3"
        }
    },
    {
        "id": "gys1",
        "colour": "#30e5e2",
        "fg": "#fff",
        "name": {
            "zh-Hans": "S1号线",
            "en": "Line S1"
        }
    },
    {
        "id": "gys2",
        "colour": "#f19149",
        "fg": "#fff",
        "name": {
            "zh-Hans": "S2号线",
            "en": "Line S2"
        }
    }
]</details>

**Comment by 52PD** [comment]
> 这是从贵阳轨道交通发布的图片上取色得到的

您好，请问能否提供确切来源（比如系统线路图或者来源网址等）？

从您所提及的来源中我们无法准确定位您所说的来源具体来自何处。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by AceMendeleev** [comment]
https://baike.baidu.com/pic/%E8%B4%B5%E9%98%B3%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A1%E5%8F%B7%E7%BA%BF/16024076/1/4ec2d5628535e5dde7114e0ce78db0efce1b9c16c486?fr=lemma&fromModule=lemma_top-image&ct=single#aid=1&pic=4ec2d5628535e5dde7114e0ce78db0efce1b9c16c486

https://baike.baidu.com/pic/%E8%B4%B5%E9%98%B3%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A2%E5%8F%B7%E7%BA%BF/14890750/1/a6efce1b9d16fdfaaf51163d25c49b5494eef11fcd86?fr=lemma&fromModule=lemma_top-image&ct=single#aid=1&pic=a6efce1b9d16fdfaaf51163d25c49b5494eef11fcd86

https://baike.baidu.com/pic/%E8%B4%B5%E9%98%B3%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A3%E5%8F%B7%E7%BA%BF/16024214/1/d8f9d72a6059252dd42aa84b8cce143b5bb5c9ea137c?fr=lemma&fromModule=lemma_top-image&ct=single#aid=1&pic=d8f9d72a6059252dd42aa84b8cce143b5bb5c9ea137c

https://baike.baidu.com/pic/%E8%B4%B5%E9%98%B3%E5%9F%8E%E5%B8%82%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9AS1%E7%BA%BF/20313645/1/908fa0ec08fa513d2697396e853842fbb2fb4316737f?fr=lemma&fromModule=lemma_top-image&ct=single#aid=1&pic=908fa0ec08fa513d2697396e853842fbb2fb4316737f

https://baike.baidu.com/pic/%E8%B4%B5%E9%98%B3%E5%9C%B0%E9%93%81S2%E5%8F%B7%E7%BA%BF/20303106/1/060828381f30e924b899e380f45d79061d950a7b597e?fr=lemma&fromModule=lemma_top-image&ct=single#aid=1&pic=060828381f30e924b899e380f45d79061d950a7b597e

**Comment by 52PD** [comment]
您好，由于考虑到百度百科上所提供颜色大多是时候都不准确，很抱歉我们不接受来自百度百科的颜色的来源。

目前我们只接受来自维基百科或者该城市/地区轨道交通官网上的颜色来源。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色来源无效后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
