### ISSUE TITLE
Resources: New palettes of Tokyo (Greater Tokyo Area)

### ISSUE THREAD

**Issue by t-chai** [railmapgen/rmg-palette#334]
**Justification:** (Comment by @52PD ) The sources are add below.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "tokyo",
    "country": "JP",
    "name": {
        "en": "Tokyo (Greater Tokyo Area)",
        "ja": "東京（首都圏）",
        "zh-Hans": "东京（首都圈）",
        "zh-Hant": "東京（首都圈）"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "g",
        "colour": "#ff9500",
        "fg": "#fff",
        "name": {
            "en": "Ginza Line (G)",
            "ja": "銀座線",
            "zh-Hans": "银座线",
            "zh-Hant": "銀座線"
        }
    },
    {
        "id": "m",
        "colour": "#f62e36",
        "fg": "#fff",
        "name": {
            "en": "Marunouchi Line (M)",
            "ja": "丸ノ内線",
            "zh-Hans": "丸之内线",
            "zh-Hant": "丸之內線"
        }
    },
    {
        "id": "h",
        "colour": "#b5b5ac",
        "fg": "#fff",
        "name": {
            "en": "Hibiya Line (H)",
            "ja": "日比谷線",
            "zh-Hans": "日比谷线",
            "zh-Hant": "日比谷線"
        }
    },
    {
        "id": "t",
        "colour": "#009bbf",
        "fg": "#fff",
        "name": {
            "en": "Tōzai Line (T)",
            "ja": "東西線",
            "zh-Hans": "东西线",
            "zh-Hant": "東西線"
        }
    },
    {
        "id": "c",
        "colour": "#00bb85",
        "fg": "#fff",
        "name": {
            "en": "Chiyoda Line (C)",
            "ja": "千代田線",
            "zh-Hans": "千代田线",
            "zh-Hant": "千代田線"
        }
    },
    {
        "id": "y",
        "colour": "#c2a570",
        "fg": "#fff",
        "name": {
            "en": "Yurakucho Line (Y)",
            "ja": "有楽町線",
            "zh-Hans": "有乐町线",
            "zh-Hant": "有樂町線"
        }
    },
    {
        "id": "z",
        "colour": "#9077d7",
        "fg": "#fff",
        "name": {
            "en": "Hanzomon Line (Z)",
            "ja": "半蔵門線",
            "zh-Hans": "半藏门线",
            "zh-Hant": "半藏門線"
        }
    },
    {
        "id": "n",
        "colour": "#00ac9b",
        "fg": "#fff",
        "name": {
            "en": "Namboku Line (N)",
            "ja": "南北線",
            "zh-Hans": "南北线",
            "zh-Hant": "南北線"
        }
    },
    {
        "id": "f",
        "colour": "#9d5e2d",
        "fg": "#fff",
        "name": {
            "en": "Fukutoshin Line (F)",
            "ja": "副都心線",
            "zh-Hans": "副都心线",
            "zh-Hant": "副都心線"
        }
    },
    {
        "id": "a",
        "colour": "#ed6e65",
        "fg": "#fff",
        "name": {
            "en": "Asakusa Line (A)",
            "ja": "浅草線",
            "zh-Hans": "浅草线",
            "zh-Hant": "淺草線"
        }
    },
    {
        "id": "i",
        "colour": "#006ab9",
        "fg": "#fff",
        "name": {
            "en": "Mita Line (I)",
            "ja": "三田線",
            "zh-Hans": "三田线",
            "zh-Hant": "三田線"
        }
    },
    {
        "id": "s",
        "colour": "#b1c018",
        "fg": "#fff",
        "name": {
            "en": "Shinjuku Line (S)",
            "ja": "新宿線",
            "zh-Hans": "新宿线",
            "zh-Hant": "新宿線"
        }
    },
    {
        "id": "e",
        "colour": "#cf005b",
        "fg": "#fff",
        "name": {
            "en": "Oedo Line (E)",
            "ja": "大江戸線",
            "zh-Hans": "大江户线",
            "zh-Hant": "大江戶線"
        }
    },
    {
        "id": "jy",
        "colour": "#b2cc36",
        "fg": "#fff",
        "name": {
            "en": "Yamanote Line (JY)",
            "ja": "山手線",
            "zh-Hant": "山手線",
            "zh-Hans": "山手线"
        }
    },
    {
        "id": "jk",
        "colour": "#17afd2",
        "fg": "#fff",
        "name": {
            "en": "Keihin-Tohoku Line/Negishi Line (JK)",
            "ja": "京浜東北線・根岸線",
            "zh-Hans": "京滨东北线·根岸线"
        }
    },
    {
        "id": "jb",
        "colour": "#ffd400",
        "fg": "#fff",
        "name": {
            "en": "Chūō Line/Sōbu Line (Local) (JB)",
            "ja": "中央・総武緩行線",
            "zh-Hans": "中央·总武缓行线"
        }
    },
    {
        "id": "jc",
        "colour": "#f15a22",
        "fg": "#fff",
        "name": {
            "en": "Chuo Rapid/Chuo Line/Ome Line/Itsukaichi Line (JC)",
            "ja": "中央線快速・中央本線・青梅線・五日市線",
            "zh-Hans": "中央快速线·中央本线·青梅线·五日市线"
        }
    },
    {
        "id": "jo",
        "colour": "#0769b5",
        "fg": "#fff",
        "name": {
            "en": "Yokosuka Line/Sōbu Line (Rapid)/Sōbu Line/Narita Line (JO)",
            "ja": "横須賀・総武快速線・総武本線・成田線",
            "zh-Hans": "横须贺·总武快速线·总武本线·成田线（佐仓~成田机场）"
        }
    },
    {
        "id": "ju",
        "colour": "#f68b1e",
        "fg": "#fff",
        "name": {
            "en": "Utsunomiya Line/Takasaki Line (JU)",
            "ja": "宇都宮線・高崎線",
            "zh-Hans": "宇都宫线·高崎线"
        }
    },
    {
        "id": "jt",
        "colour": "#f68b1e",
        "fg": "#fff",
        "name": {
            "en": "Tōkaidō Line/Itō Line (JT)",
            "ja": "東海道線・伊東線",
            "zh-Hans": "东海道线·伊东线"
        }
    },
    {
        "id": "ja",
        "colour": "#00ac9a",
        "fg": "#fff",
        "name": {
            "en": "Saikyo Line (JA)",
            "ja": "埼京線",
            "zh-Hans": "埼京线"
        }
    },
    {
        "id": "js",
        "colour": "#e31f26",
        "fg": "#fff",
        "name": {
            "en": "Shonan-Shinjuku Line (JS)",
            "ja": "湘南新宿ライン",
            "zh-Hans": "湘南新宿线",
            "zh-Hant": "湘南新宿線"
        }
    },
    {
        "id": "jj",
        "colour": "#16b07f",
        "fg": "#fff",
        "name": {
            "en": "Joban Line (Rapid) (JJ)",
            "ja": "常磐快速線",
            "zh-Hans": "常磐快速线"
        }
    },
    {
        "id": "jl",
        "colour": "#878688",
        "fg": "#fff",
        "name": {
            "en": "Jōban Line (Local) (JL)",
            "ja": "常磐緩行線",
            "zh-Hans": "常磐缓行线"
        }
    },
    {
        "id": "je",
        "colour": "#c9242f",
        "fg": "#fff",
        "name": {
            "en": "Keiyo Line (JE)",
            "ja": "京葉線",
            "zh-Hans": "京叶线",
            "zh-Hant": "京葉線"
        }
    },
    {
        "id": "jh",
        "colour": "#9acd32",
        "fg": "#fff",
        "name": {
            "en": "Yokohama Line (JH)",
            "ja": "横浜線",
            "zh-Hans": "横滨线"
        }
    },
    {
        "id": "jm",
        "colour": "#f15a22",
        "fg": "#fff",
        "name": {
            "en": "Musashino Line (JM)",
            "ja": "武蔵野線",
            "zh-Hans": "武藏野线"
        }
    },
    {
        "id": "jn",
        "colour": "#ffd400",
        "fg": "#fff",
        "name": {
            "en": "Nambu Line (JN)",
            "ja": "南武線",
            "zh-Hans": "南武线",
            "zh-Hant": "南武線"
        }
    },
    {
        "id": "ji",
        "colour": "#ffd400",
        "fg": "#fff",
        "name": {
            "en": "Tsurumi Line (JI)",
            "ja": "鶴見線",
            "zh-Hans": "鹤见线",
            "zh-Hant": "鶴見線"
        }
    },
    {
        "id": "mo",
        "colour": "#003686",
        "fg": "#fff",
        "name": {
            "en": "Tokyo Monorail Haneda Airport Line (MO)",
            "ja": "東京モノレール羽田空港線",
            "zh-Hans": "东京单轨电车羽田机场线",
            "zh-Hant": "東京單軌電車羽田機場線"
        }
    },
    {
        "id": "yb",
        "colour": "#2b55a6",
        "fg": "#fff",
        "name": {
            "en": "Yokohama Municipal Subway Blue Line (B)",
            "ja": "横浜市営地下鉄ブルーライン",
            "zh-Hans": "横滨市营地铁蓝线"
        }
    },
    {
        "id": "yg",
        "colour": "#23856e",
        "fg": "#fff",
        "name": {
            "en": "Yokohama Municipal Subway Green Line (G)",
            "ja": "横浜市営地下鉄グリーンライン",
            "zh-Hans": "横滨市营地铁绿线"
        }
    },
    {
        "id": "ty",
        "colour": "#db0040",
        "fg": "#fff",
        "name": {
            "en": "Tokyu Toyoko Line (TY)",
            "ja": "東急東横線",
            "zh-Hans": "东急东横线"
        }
    },
    {
        "id": "mg",
        "colour": "#009dd4",
        "fg": "#fff",
        "name": {
            "en": "Tōkyū Meguro Line (MG)",
            "ja": "東急目黒線",
            "zh-Hans": "东急目黑线",
            "zh-Hant": "東急目黑線"
        }
    },
    {
        "id": "dt",
        "colour": "#00ab8e",
        "fg": "#fff",
        "name": {
            "en": "Tokyu Den-en-toshi Line (DT)",
            "ja": "東急田園都市線",
            "zh-Hans": "东急田园都市线",
            "zh-Hant": "東急田園都市線"
        }
    },
    {
        "id": "om",
        "colour": "#f18d41",
        "fg": "#fff",
        "name": {
            "en": "Tokyu Oimachi Line (OM)",
            "ja": "東急大井町線",
            "zh-Hans": "东急大井町线",
            "zh-Hant": "東急大井町線"
        }
    },
    {
        "id": "ik",
        "colour": "#ee87a9",
        "fg": "#fff",
        "name": {
            "en": "Tokyu Ikegami Line (IK)",
            "ja": "東急池上線",
            "zh-Hans": "东急池上线",
            "zh-Hant": "東急池上線"
        }
    },
    {
        "id": "tm",
        "colour": "#af007a",
        "fg": "#fff",
        "name": {
            "en": "Tokyu Tamagawa Line (TM)",
            "ja": "東急多摩川線",
            "zh-Hans": "东急多摩川线",
            "zh-Hant": "東急多摩川線"
        }
    },
    {
        "id": "kd",
        "colour": "#0072bf",
        "fg": "#fff",
        "name": {
            "en": "Kodomonokuni Line (KD)",
            "ja": "こどもの国線",
            "zh-Hans": "东急子供之国线"
        }
    },
    {
        "id": "sg",
        "colour": "#fcc900",
        "fg": "#000",
        "name": {
            "en": "Tokyu Setagaya Line (SG)",
            "ja": "東急世田谷線",
            "zh-Hans": "东急世田谷线",
            "zh-Hant": "東急世田谷線"
        }
    },
    {
        "id": "si",
        "colour": "#ef7b00",
        "fg": "#fff",
        "name": {
            "en": "Seibu Ikebukuro Line/Chichibu Line/Yurakucho Line/Toshima Line/Sayama Line (SI)",
            "ja": "西武池袋線・秩父線・有楽町線・豊島線・狭山線",
            "zh-Hans": "西武池袋线·秩父线·有乐町线·丰岛线·狭山线",
            "zh-Hant": "西武池袋線"
        }
    },
    {
        "id": "ss",
        "colour": "#00a7c0",
        "fg": "#fff",
        "name": {
            "en": "Seibu Shinjuku Line/Haijima Line (SS)",
            "ja": "西武新宿線・拝島線",
            "zh-Hans": "西武新宿线·拜岛线",
            "zh-Hant": "西武新宿線"
        }
    },
    {
        "id": "sk",
        "colour": "#35b45c",
        "fg": "#fff",
        "name": {
            "en": "Seibu Kokubunji Line/Seibuen Line (SK)",
            "ja": "西武国分寺線・西武園線",
            "zh-Hans": "西武国分寺线·西武园线",
            "zh-Hant": "西武國分寺線·西武園線"
        }
    },
    {
        "id": "sw",
        "colour": "#f17d1f",
        "fg": "#fff",
        "name": {
            "en": "Seibu Tamagawa Line (SW)",
            "ja": "西武多摩川線",
            "zh-Hans": "西武多摩川线",
            "zh-Hant": "西武多摩川線"
        }
    },
    {
        "id": "st",
        "colour": "#f7ab28",
        "fg": "#fff",
        "name": {
            "en": "Seibu Tamako Line (ST)",
            "ja": "西武多摩湖線",
            "zh-Hans": "西武多摩湖线"
        }
    },
    {
        "id": "sy",
        "colour": "#ed463e",
        "fg": "#fff",
        "name": {
            "en": "Seibu Yamaguchi Line (SY)",
            "ja": "西武山口線",
            "zh-Hans": "西武山口线"
        }
    },
    {
        "id": "ts",
        "colour": "#006cbb",
        "fg": "#fff",
        "name": {
            "en": "Tobu Skytree Line/Kameido Line/Daishi Line (TS)",
            "ja": "東武スカイツリーライン・亀戸線・大師線",
            "zh-Hans": "东武晴空塔线·龟户线·大师线",
            "zh-Hant": "東武晴空塔線"
        }
    },
    {
        "id": "ti",
        "colour": "#E61919",
        "fg": "#fff",
        "name": {
            "en": "Tobu Isesaki Line/Sano Line/Kiryu Line/Koizumi Line (TI)",
            "ja": "東武伊勢崎線・佐野線・桐生線・小泉線",
            "zh-Hans": "东武伊势崎线·佐野线·桐生线·小泉线"
        }
    },
    {
        "id": "tn",
        "colour": "#f5a300",
        "fg": "#fff",
        "name": {
            "en": "Tobu Nikko Line (TN)",
            "ja": "東武日光線・宇都宮線・鬼怒川線",
            "zh-Hans": "东武日光线·宇都宫线·鬼怒川线"
        }
    },
    {
        "id": "td",
        "colour": "#3eb5e6",
        "fg": "#fff",
        "name": {
            "en": "Tobu Urban Park Line (TD)",
            "ja": "東武アーバンパークライン",
            "zh-Hans": "东武野田线"
        }
    },
    {
        "id": "tj",
        "colour": "#00408f",
        "fg": "#fff",
        "name": {
            "en": "Tobu Tojo Line/Ogose Line (TJ)",
            "ja": "東武東上本線・越生線",
            "zh-Hans": "东武东上本线·越生线",
            "zh-Hant": "東武東上線"
        }
    },
    {
        "id": "ks",
        "colour": "#001368",
        "fg": "#fff",
        "name": {
            "en": "Keisei Main Line (KS)",
            "ja": "京成本線・東成田線・押上線・金町線・千葉線・千原線",
            "zh-Hans": "京成本线·东成田线·押上线·金町线·千叶线",
            "zh-Hant": "京成本線"
        }
    },
    {
        "id": "ksnrt",
        "colour": "#ee7b00",
        "fg": "#fff",
        "name": {
            "en": "Keisei Narita Airport Line (KS)",
            "ja": "京成成田空港線",
            "zh-Hans": "京成成田机场线"
        }
    },
    {
        "id": "sl",
        "colour": "#ef58a2",
        "fg": "#fff",
        "name": {
            "en": "Shin-Keisei Line (SL)",
            "ja": "新京成線",
            "zh-Hans": "新京成线"
        }
    },
    {
        "id": "hs",
        "colour": "#00bfff",
        "fg": "#fff",
        "name": {
            "en": "Hokuso Line (HS)",
            "ja": "北総線",
            "zh-Hans": "北总线",
            "zh-Hant": "北總線"
        }
    },
    {
        "id": "sr",
        "colour": "#00805a",
        "fg": "#fff",
        "name": {
            "en": "Shibayama Railway Line (SR)",
            "ja": "芝山鉄道線",
            "zh-Hans": "芝山铁道线",
            "zh-Hant": "芝山鐵道線"
        }
    },
    {
        "id": "oh",
        "colour": "#0d82c7",
        "fg": "#fff",
        "name": {
            "en": "Odakyu Lines (OH/OE/OT)",
            "ja": "小田急線",
            "zh-Hans": "小田急线",
            "zh-Hant": "小田急線"
        }
    },
    {
        "id": "ko",
        "colour": "#d60080",
        "fg": "#fff",
        "name": {
            "en": "Keiō Line (KO)",
            "ja": "京王線",
            "zh-Hans": "京王线",
            "zh-Hant": "京王線"
        }
    },
    {
        "id": "in",
        "colour": "#073376",
        "fg": "#fff",
        "name": {
            "en": "Keiō Inokashira Line (IN)",
            "ja": "京王井の頭線",
            "zh-Hans": "京王井之头线",
            "zh-Hant": "京王井之頭線"
        }
    },
    {
        "id": "kk",
        "colour": "#00BFFF",
        "fg": "#fff",
        "name": {
            "en": "Keikyu Line (KK)",
            "ja": "京急線",
            "zh-Hans": "京急线"
        }
    },
    {
        "id": "so",
        "colour": "#041452",
        "fg": "#fff",
        "name": {
            "en": "Sotetsu Line (SO)",
            "ja": "相鉄線",
            "zh-Hans": "相铁线"
        }
    },
    {
        "id": "r",
        "colour": "#00389e",
        "fg": "#fff",
        "name": {
            "en": "Rinkai Line (R)",
            "ja": "りんかい線",
            "zh-Hans": "临海线",
            "zh-Hant": "臨海線"
        }
    },
    {
        "id": "u",
        "colour": "#0e62b9",
        "fg": "#fff",
        "name": {
            "en": "New Transit Yurikamome (U)",
            "ja": "新交通ゆりかもめ",
            "zh-Hans": "百合海鸥线",
            "zh-Hant": "百合海鷗線"
        }
    },
    {
        "id": "sa",
        "colour": "#ee86a7",
        "fg": "#fff",
        "name": {
            "en": "Toden Arakawa Line (SA)",
            "ja": "東京さくらトラム（都電荒川線）",
            "zh-Hans": "都电荒川线",
            "zh-Hant": "東京櫻花路面電車"
        }
    },
    {
        "id": "nt",
        "colour": "#D53A77",
        "fg": "#fff",
        "name": {
            "en": "Nippori-Toneri Liner (NT)",
            "ja": "日暮里・舎人ライナー",
            "zh-Hans": "日暮里-舍人线",
            "zh-Hant": "日暮里-舍人線"
        }
    },
    {
        "id": "mm",
        "colour": "#00469c",
        "fg": "#fff",
        "name": {
            "en": "Minatomirai Line (MM)",
            "ja": "みなとみらい線",
            "zh-Hans": "港未来线"
        }
    },
    {
        "id": "en",
        "colour": "#efd463",
        "fg": "#fff",
        "name": {
            "en": "Enoshima Dentetsu Line (EN)",
            "ja": "江ノ島電鉄線",
            "zh-Hans": "江之岛电铁线"
        }
    },
    {
        "id": "tr",
        "colour": "#59b75c",
        "fg": "#fff",
        "name": {
            "en": "Toyo Rapid Railway Line (TR)",
            "ja": "東葉高速線",
            "zh-Hans": "东叶高速线",
            "zh-Hant": "東葉高速線"
        }
    },
    {
        "id": "srr",
        "colour": "#3264b0",
        "fg": "#fff",
        "name": {
            "en": "Saitama Rapid Railway Line (SR)",
            "ja": "埼玉高速鉄道線",
            "zh-Hans": "埼玉高速铁道线"
        }
    },
    {
        "id": "tt",
        "colour": "#22625e",
        "fg": "#fff",
        "name": {
            "en": "Tama Toshi Monorail Line",
            "ja": "多摩都市モノレール線",
            "zh-Hans": "多摩都市单轨电车线"
        }
    },
    {
        "id": "ns",
        "colour": "#11a799",
        "fg": "#fff",
        "name": {
            "en": "Ina Line (NS)",
            "ja": "伊奈線",
            "zh-Hans": "伊奈线"
        }
    },
    {
        "id": "cd",
        "colour": "#a52a2a",
        "fg": "#fff",
        "name": {
            "en": "Choshi Electric Railway Line (CD)",
            "ja": "銚子電気鉄道線",
            "zh-Hans": "铫子电气铁道线"
        }
    },
    {
        "id": "cm",
        "colour": "#2843ba",
        "fg": "#fff",
        "name": {
            "en": "Chiba Urban Monorail (CM)",
            "ja": "千葉都市モノレール",
            "zh-Hans": "千叶都市单轨电车"
        }
    },
    {
        "id": "jrhk",
        "colour": "#a8a39d",
        "fg": "#fff",
        "name": {
            "en": "Hachiko Line/Kawagoe Line",
            "ja": "八高・川越線",
            "zh-Hans": "八高·川越线"
        }
    },
    {
        "id": "jrsg",
        "colour": "#009793",
        "fg": "#fff",
        "name": {
            "en": "Sagami Line",
            "ja": "相模線",
            "zh-Hans": "相模线"
        }
    },
    {
        "id": "jrut",
        "colour": "#800080",
        "fg": "#fff",
        "name": {
            "en": "Ueno–Tokyo Line",
            "ja": "上野東京ライン",
            "zh-Hans": "上野东京线"
        }
    },
    {
        "id": "jrjb",
        "colour": "#3333ff",
        "fg": "#fff",
        "name": {
            "en": "Joban Line/Mito Line",
            "ja": "常磐・水戸線",
            "zh-Hans": "常磐·水户线"
        }
    },
    {
        "id": "jrsb",
        "colour": "#ffc20d",
        "fg": "#fff",
        "name": {
            "en": "Sobu Main Line",
            "ja": "総武本線",
            "zh-Hans": "总武本线"
        }
    },
    {
        "id": "jrna",
        "colour": "#00b261",
        "fg": "#fff",
        "name": {
            "en": "Narita Line",
            "ja": "成田線",
            "zh-Hans": "成田线"
        }
    },
    {
        "id": "jruc",
        "colour": "#00b2e5",
        "fg": "#fff",
        "name": {
            "en": "Uchibo Line",
            "ja": "内房線",
            "zh-Hans": "内房线"
        }
    },
    {
        "id": "jrka",
        "colour": "#c56e2e",
        "fg": "#fff",
        "name": {
            "en": "Kashima Line",
            "ja": "鹿島線",
            "zh-Hans": "鹿岛线"
        }
    },
    {
        "id": "jrst",
        "colour": "#db4028",
        "fg": "#fff",
        "name": {
            "en": "Sotobo Line",
            "ja": "外房線",
            "zh-Hans": "外房线"
        }
    },
    {
        "id": "jrtg",
        "colour": "#f15a22",
        "fg": "#fff",
        "name": {
            "en": "Togane Line",
            "ja": "東金線",
            "zh-Hans": "东金线"
        }
    },
    {
        "id": "jrkr",
        "colour": "#00b5ad",
        "fg": "#fff",
        "name": {
            "en": "Kururi Line",
            "ja": "久留里線",
            "zh-Hans": "久留里线"
        }
    },
    {
        "id": "jrse",
        "colour": "#9acd32",
        "fg": "#fff",
        "name": {
            "en": "Shin'etsu Main Line",
            "ja": "信越本線",
            "zh-Hans": "信越本线"
        }
    },
    {
        "id": "jrjt",
        "colour": "#00b3e6",
        "fg": "#fff",
        "name": {
            "en": "Joetsu Line",
            "ja": "上越線",
            "zh-Hans": "上越线"
        }
    },
    {
        "id": "jrrm",
        "colour": "#ffd400",
        "fg": "#fff",
        "name": {
            "en": "Ryomo Line",
            "ja": "両毛線",
            "zh-Hans": "两毛线"
        }
    },
    {
        "id": "jrat",
        "colour": "#0f5474",
        "fg": "#fff",
        "name": {
            "en": "Agatsuma Line",
            "ja": "吾妻線",
            "zh-Hans": "吾妻线"
        }
    },
    {
        "id": "jrnk",
        "colour": "#880022",
        "fg": "#fff",
        "name": {
            "en": "Nikko Line",
            "ja": "日光線",
            "zh-Hans": "日光线"
        }
    },
    {
        "id": "jrks",
        "colour": "#339966",
        "fg": "#fff",
        "name": {
            "en": "Karasuyama Line",
            "ja": "烏山線",
            "zh-Hans": "乌山线"
        }
    },
    {
        "id": "sh",
        "colour": "#6d4d8a",
        "fg": "#fff",
        "name": {
            "en": "Tokyu Shin-Yokohama Line (SH)",
            "ja": "東急新橫濱線",
            "zh-Hans": "东急新横滨线",
            "zh-Hant": "東急新橫濱線"
        }
    },
    {
        "id": "cb",
        "colour": "#457641",
        "fg": "#fff",
        "name": {
            "en": "Gotemba Line (CB)",
            "ja": "御殿場線",
            "zh-Hans": "御殿场线"
        }
    },
    {
        "id": "jr",
        "colour": "#028d05",
        "fg": "#fff",
        "name": {
            "en": "JR Line",
            "ja": "JR線",
            "zh-Hans": "JR线"
        }
    },
    {
        "id": "thksks",
        "colour": "#006600",
        "fg": "#fff",
        "name": {
            "en": "Tohoku Shinkansen",
            "ja": "東北新幹線",
            "zh-Hans": "东北新干线"
        }
    },
    {
        "id": "tkdsks",
        "colour": "#175baa",
        "fg": "#fff",
        "name": {
            "en": "Tokaido Shinkansen",
            "ja": "東海道新幹線",
            "zh-Hans": "东海道新干线"
        }
    },
    {
        "id": "tx",
        "colour": "#000084",
        "fg": "#fff",
        "name": {
            "en": "Tsukuba Express",
            "ja": "つくばエクスプレス",
            "zh-Hans": "筑波快线"
        }
    },
    {
        "id": "ssl",
        "colour": "#f68b1e",
        "fg": "#fff",
        "name": {
            "en": "Kanazawa Seaside Line",
            "ja": "金沢シーサイドライン",
            "zh-Hans": "金泽海岸线"
        }
    },
    {
        "id": "ksm",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Oarai Kashima Line",
            "ja": "大洗鹿島線",
            "zh-Hans": "大洗鹿岛线"
        }
    },
    {
        "id": "kkk",
        "colour": "#666666",
        "fg": "#fff",
        "name": {
            "en": "Watarase Keikoku Line",
            "ja": "わたらせ渓谷線",
            "zh-Hans": "渡良濑溪谷线"
        }
    },
    {
        "id": "ism",
        "colour": "#ffd400",
        "fg": "#fff",
        "name": {
            "en": "Isumi Line",
            "ja": "いすみ線",
            "zh-Hans": "夷隅线"
        }
    },
    {
        "id": "kgw",
        "colour": "#009933",
        "fg": "#fff",
        "name": {
            "en": "Aizu Kinugawa Line",
            "ja": "会津鬼怒川線",
            "zh-Hans": "会津鬼怒川线"
        }
    },
    {
        "id": "snmn",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Shonan Monorail",
            "ja": "江の島線",
            "zh-Hans": "江之岛线"
        }
    },
    {
        "id": "ktr",
        "colour": "#3333ff",
        "fg": "#fff",
        "name": {
            "en": "Kanto Railway",
            "ja": "関東鉄道",
            "zh-Hans": "关东铁道"
        }
    },
    {
        "id": "oht",
        "colour": "#ea4d15",
        "fg": "#fff",
        "name": {
            "en": "Hakone Tozan Line",
            "ja": "箱根登山鉄道鉄道線",
            "zh-Hans": "箱根登山铁道铁道线 "
        }
    },
    {
        "id": "ykrgk",
        "colour": "#2f9d66",
        "fg": "#fff",
        "name": {
            "en": "Yukarigaoka Line",
            "ja": "ユーカリが丘線",
            "zh-Hans": "有加利丘线"
        }
    },
    {
        "id": "jomo",
        "colour": "#40e0d0",
        "fg": "#fff",
        "name": {
            "en": "Jomo Line",
            "ja": "上毛線",
            "zh-Hans": "上毛线"
        }
    },
    {
        "id": "kmnt",
        "colour": "#ff6347",
        "fg": "#fff",
        "name": {
            "en": "Kominato Line",
            "ja": "小湊鉄道線",
            "zh-Hans": "小凑铁道线"
        }
    },
    {
        "id": "joshin",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Joshin Line",
            "ja": "上信線",
            "zh-Hans": "上信线"
        }
    },
    {
        "id": "id",
        "colour": "#0000ff",
        "fg": "#fff",
        "name": {
            "en": "Daiyuzan Line",
            "ja": "大雄山線",
            "zh-Hans": "大雄山线"
        }
    }
]</details>

**Comment by 52PD** [comment]
您哈，我们注意到你所提交的issue中对多条现有线路进行了修改，然而我们您并未提供有效的颜色来源。

请问如果方便的话能否提供一下您修改线路颜色时所使用的来源呢？我们是拒绝接收任何无来源的跑路稿件的。

(请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by t-chai** [comment]
https://zh.wikipedia.org/wiki/%E5%A4%A7%E6%9D%B1%E4%BA%AC%E5%9C%B0%E5%8D%80%E9%81%8B%E8%BC%B8
没有的再进具体页面（如筑波快线：https://ja.wikipedia.org/wiki/%E9%A6%96%E9%83%BD%E5%9C%8F%E6%96%B0%E9%83%BD%E5%B8%82%E9%89%84%E9%81%93%E3%81%A4%E3%81%8F%E3%81%B0%E3%82%A8%E3%82%AF%E3%82%B9%E3%83%97%E3%83%AC%E3%82%B9，以此类推）

**Comment by 52PD** [comment]
您好，您所提交的颜色的多条线路中的颜色与所提供来源颜色并不相符，请重新检查一遍后将修改后的颜色告诉我们。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by t-chai** [comment]
您好，东京线路数量非常多，可否具体告诉我哪几条存在问题？我都是一条一条根据日文维基百科的线路标或代表色取色的

**Comment by 52PD** [comment]
您好，经我们检查，有乐町线、半藏门线、副都心线，都营地下铁全部4条线路颜色与您所提供的维基百科上的颜色不符。

山手线之后线路我们并未对其进行检查，因为这些路线绝大部分线路运营范围已经超出东京都范围或直接不在东京都范围内。考虑到我们的颜色库是按照城市（如北京）/都市圈（如大多伦多及汉密尔顿地区）划分的，因此我们不建议将其写入。
