### ISSUE TITLE
Resources: New palettes of Seville

### ISSUE THREAD

**Issue by KazuoNara** [railmapgen/rmg-palette#337]
**Reference link:** https://www.renfe.com/es/es/cercanias/cercanias-sevilla/mapas

**Justification:** Palette from existing + upcoming transport lines in Seville.
**Comment by @52PD : ** Due to no response by issue provider, lines except Cercanías 1-5 are removed.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "Sevilla",
    "country": "ES",
    "name": {
        "es": "Sevilla",
        "en": "Seville"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "C1",
        "colour": "#4c90c3",
        "fg": "#fff",
        "name": {
            "es": "Cercanías 1",
            "en": "Commuter 1"
        }
    },
    {
        "id": "C2",
        "colour": "#067b34",
        "fg": "#fff",
        "name": {
            "es": "Cercanías 2",
            "en": "Commuter 2"
        }
    },
    {
        "id": "C3",
        "colour": "#e4242d",
        "fg": "#fff",
        "name": {
            "es": "Cercanías 3",
            "en": "Commuter 3"
        }
    },
    {
        "id": "C4",
        "colour": "#8e2182",
        "fg": "#fff",
        "name": {
            "es": "Cercanías 4",
            "en": "Commuter 4"
        }
    },
    {
        "id": "C5",
        "colour": "#073588",
        "fg": "#fff",
        "name": {
            "es": "Cercanías 5",
            "en": "Commuter 5"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，我们注意到您所提供的来源中并未提供除Cercanías 1/2/3/4/5这五条线路外的线路颜色。

请问方便的话能否提供其他线路颜色来源，谢谢。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色来源问题后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们将只汇入1-5号线颜色。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
