### ISSUE TITLE
Resources: New palettes of Tianjin

### ISSUE THREAD

**Issue by epis2048** [railmapgen/rmg-palette#339]
**Reference link:** https://tjmetro.epis2048.net/

**Justification:** 11号线颜色为PPP项目方中国交建的LOGO颜色，来源是微信群的图片，内容是11号线车载PIS屏幕与11号线车辆涂装，无法提供URL。（另，天津地铁官方从未设计并公布过11号线及之后的纯数字线路颜色，网上所有版本均为谣传）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "tianjin",
    "country": "CN",
    "name": {
        "en": "Tianjin",
        "zh": "天津"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "tj1",
        "colour": "#bd0016",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "tj2",
        "colour": "#ece114",
        "fg": "#000",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "tj3",
        "colour": "#128bbe",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "tj4",
        "colour": "#1c7736",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "tj5",
        "colour": "#fb6f14",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "tj6",
        "colour": "#9f216f",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "tj7",
        "colour": "#b17833",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "tj8",
        "colour": "#602e7c",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "tj9",
        "colour": "#020094",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "tj10",
        "colour": "#b9cf09",
        "fg": "#000",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "tj11",
        "colour": "#004fa3",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "tj12",
        "colour": "#3b008c",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "tj13",
        "colour": "#def148",
        "fg": "#000",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "b1",
        "colour": "#e13c4b",
        "fg": "#fff",
        "name": {
            "en": "Line B1",
            "zh-Hans": "B1线",
            "zh-Hant": "B1線"
        }
    },
    {
        "id": "b2",
        "colour": "#fbf053",
        "fg": "#fff",
        "name": {
            "en": "Line B2",
            "zh-Hans": "B2线",
            "zh-Hant": "B2線"
        }
    },
    {
        "id": "b3",
        "colour": "#75c2c9",
        "fg": "#fff",
        "name": {
            "en": "Line B3",
            "zh-Hans": "B3线",
            "zh-Hant": "B3線"
        }
    },
    {
        "id": "b4",
        "colour": "#5cb35d",
        "fg": "#fff",
        "name": {
            "en": "Line B4",
            "zh-Hans": "B4线",
            "zh-Hant": "B4線"
        }
    },
    {
        "id": "b5",
        "colour": "#f6ac5b",
        "fg": "#fff",
        "name": {
            "en": "Line B5",
            "zh-Hans": "B5线",
            "zh-Hant": "B5線"
        }
    },
    {
        "id": "b6",
        "colour": "#eb76bd",
        "fg": "#fff",
        "name": {
            "en": "Line B6",
            "zh-Hans": "B6线",
            "zh-Hant": "B6線"
        }
    },
    {
        "id": "b7",
        "colour": "#d8ad71",
        "fg": "#fff",
        "name": {
            "en": "Line B7",
            "zh-Hans": "B7线",
            "zh-Hant": "B7線"
        }
    },
    {
        "id": "c1",
        "colour": "#d1ce69",
        "fg": "#fff",
        "name": {
            "en": "Line C1",
            "zh-Hans": "C1线",
            "zh-Hant": "C1線"
        }
    },
    {
        "id": "c2",
        "colour": "#dd8dae",
        "fg": "#fff",
        "name": {
            "en": "Line C2",
            "zh-Hans": "C2线",
            "zh-Hant": "C2線"
        }
    },
    {
        "id": "c3",
        "colour": "#769c62",
        "fg": "#fff",
        "name": {
            "en": "Line C3",
            "zh-Hans": "C3线",
            "zh-Hant": "C3線"
        }
    },
    {
        "id": "c4",
        "colour": "#5c480f",
        "fg": "#fff",
        "name": {
            "en": "Line C4",
            "zh-Hans": "C4线",
            "zh-Hant": "C4線"
        }
    },
    {
        "id": "z1",
        "colour": "#626da7",
        "fg": "#fff",
        "name": {
            "en": "Line Z1",
            "zh-Hans": "Z1线",
            "zh-Hant": "Z1線"
        }
    },
    {
        "id": "z2",
        "colour": "#1d6b9a",
        "fg": "#fff",
        "name": {
            "en": "Line Z2",
            "zh-Hans": "Z2线",
            "zh-Hant": "Z2線"
        }
    },
    {
        "id": "z3",
        "colour": "#bd5832",
        "fg": "#fff",
        "name": {
            "en": "Line Z3",
            "zh-Hans": "Z3线",
            "zh-Hant": "Z3線"
        }
    },
    {
        "id": "z4",
        "colour": "#9574ac",
        "fg": "#fff",
        "name": {
            "en": "Line Z4",
            "zh-Hans": "Z4线",
            "zh-Hant": "Z4線"
        }
    },
    {
        "id": "t1",
        "colour": "#8FC31F",
        "fg": "#fff",
        "name": {
            "en": "TEDA Modern Guided Rail Tram",
            "zh-Hans": "导轨1号线",
            "zh-Hant": "導軌1號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，很抱歉我们不接受任何来自非官方/英文维基百科来源的线路颜色，谢谢。

如目前天津地铁官方未提供11号线线路颜色的话我们建议从维基百科上提取相关颜色。另外考虑到颜色准确性，我们建议不要提供环评中所提供的颜色。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by linchen1965** [comment]
![@X~J {7S6B0X7AZ5`L6FM~R](https://user-images.githubusercontent.com/92020676/211424367-c08e29b4-479a-456c-88a7-2ea30138482a.png)
图片截取自英文版维基百科的配图

**Comment by 52PD** [comment]
> 图片截取自英文版维基百科的配图

看了一下，维基百科给的颜色跟作者给的颜色不一样😂

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色来源无效后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
