### ISSUE TITLE
Resources: New palettes of Hangzhou

### ISSUE THREAD

**Issue by 61206180** [railmapgen/rmg-palette#342]
**Reference link:** http://www.hangzhou.gov.cn/art/2022/11/15/art_812269_59068588.html

**Justification:** 此为杭州地铁四期批复线路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hangzhou",
    "country": "CN",
    "name": {
        "en": "Hangzhou",
        "zh": "杭州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "hz1",
        "colour": "#DF4661",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "hz2",
        "colour": "#f1803a",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "hz3",
        "colour": "#ffcd00",
        "fg": "#000",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "hz4",
        "colour": "#6CC24A",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "hz5",
        "colour": "#00AEC7",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "hz6",
        "colour": "#0072CE",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "hz7",
        "colour": "#87189D",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "hz8",
        "colour": "#AC145A",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "hz9",
        "colour": "#BE4D00",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "hz10",
        "colour": "#daaa00",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "hz19",
        "colour": "#05c3de",
        "fg": "#fff",
        "name": {
            "en": "Line 19 (Airport Express)",
            "zh-Hans": "19号线 (机场快线)",
            "zh-Hant": "19號線 (機場快線)"
        }
    },
    {
        "id": "hz12",
        "colour": "#3863a8",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "hz15",
        "colour": "#ec9dec",
        "fg": "#fff",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "hz18",
        "colour": "#8de88d",
        "fg": "#fff",
        "name": {
            "en": "Line 18",
            "zh-Hans": "18号线",
            "zh-Hant": "18號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，您所提交的线路颜色来源中只提及了杭州地铁四期工程中批复了哪些线路，并没有提供任何线路颜色。

请提供一个包含线路颜色的有效来源，谢谢。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色来源无效后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
