### ISSUE TITLE
Resources: New palettes of Shanghai

### ISSUE THREAD

**Issue by Fhooth-YG** [railmapgen/rmg-palette#346]
**Reference link:** https://baike.baidu.com/starmap/view?nodeId=06a4e94ffa114881ede88426

**Justification:** 增加上海预计于2024年后建成的若干条轨道交通线路（市域铁路）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shanghai",
    "country": "CN",
    "name": {
        "en": "Shanghai",
        "zh": "上海"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sh1",
        "colour": "#E4002B",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "sh2",
        "colour": "#97D700",
        "fg": "#000",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "sh3",
        "colour": "#FFD100",
        "fg": "#000",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "sh4",
        "colour": "#5F259F",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "sh5",
        "colour": "#AC4FC6",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "sh6",
        "colour": "#D9027D",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "sh7",
        "colour": "#FF6900",
        "fg": "#000",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "sh8",
        "colour": "#00A3E0",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "sh9",
        "colour": "#71C5E8",
        "fg": "#000",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "sh10",
        "colour": "#C1A7E2",
        "fg": "#000",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "sh11",
        "colour": "#76232F",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "sh12",
        "colour": "#007B5F",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "sh13",
        "colour": "#EF95CF",
        "fg": "#000",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "sh14",
        "colour": "#827A04",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "sh15",
        "colour": "#BBA786",
        "fg": "#000",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "sh16",
        "colour": "#2CD5C4",
        "fg": "#000",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "sh17",
        "colour": "#C09C83",
        "fg": "#fff",
        "name": {
            "en": "Line 17",
            "zh-Hans": "17号线",
            "zh-Hant": "17號線"
        }
    },
    {
        "id": "sh18",
        "colour": "#D6A461",
        "fg": "#000",
        "name": {
            "en": "Line 18",
            "zh-Hans": "18号线",
            "zh-Hant": "18號線"
        }
    },
    {
        "id": "sh19",
        "colour": "#c23724",
        "fg": "#fff",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线",
            "zh-Hant": "19號線"
        }
    },
    {
        "id": "sh20",
        "colour": "#365ba9",
        "fg": "#fff",
        "name": {
            "en": "Line 20",
            "zh-Hans": "20号线",
            "zh-Hant": "20號線"
        }
    },
    {
        "id": "sh21",
        "colour": "#dfc765",
        "fg": "#000",
        "name": {
            "en": "Line 21",
            "zh-Hans": "21号线",
            "zh-Hant": "21號線"
        }
    },
    {
        "id": "sh22",
        "colour": "#ffeebd",
        "fg": "#000",
        "name": {
            "en": "Line 22",
            "zh-Hans": "22号线",
            "zh-Hant": "22號線"
        }
    },
    {
        "id": "sh23",
        "colour": "#ee8564",
        "fg": "#fff",
        "name": {
            "en": "Line 23",
            "zh-Hans": "23号线",
            "zh-Hant": "23號線"
        }
    },
    {
        "id": "t1",
        "colour": "#FF0000",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T1",
            "zh-Hans": "松江有轨电车1号线",
            "zh-Hant": "松江有軌電車1號線"
        }
    },
    {
        "id": "t2",
        "colour": "#46837B",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T2",
            "zh-Hans": "松江有轨电车2号线",
            "zh-Hant": "松江有軌電車2號線"
        }
    },
    {
        "id": "t3",
        "colour": "#009400",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T3",
            "zh-Hans": "松江有轨电车3号线",
            "zh-Hant": "松江有軌電車3號線"
        }
    },
    {
        "id": "t4",
        "colour": "#FF00FF",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T4",
            "zh-Hans": "松江有轨电车4号线",
            "zh-Hant": "松江有軌電車4號線"
        }
    },
    {
        "id": "t5",
        "colour": "#00FD00",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T5",
            "zh-Hans": "松江有轨电车5号线",
            "zh-Hant": "松江有軌電車5號線"
        }
    },
    {
        "id": "t6",
        "colour": "#6E00DD",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T6",
            "zh-Hans": "松江有轨电车6号线",
            "zh-Hant": "松江有軌電車6號線"
        }
    },
    {
        "id": "maglev",
        "colour": "#009090",
        "fg": "#fff",
        "name": {
            "en": "Shanghai Maglev Train",
            "zh-Hans": "磁浮线",
            "zh-Hant": "磁浮線"
        }
    },
    {
        "id": "jml",
        "colour": "#6b394e",
        "fg": "#fff",
        "name": {
            "en": "Jiamin Line",
            "zh-Hans": "嘉闵线",
            "zh-Hant": "嘉閔線"
        }
    },
    {
        "id": "airport-l",
        "colour": "#326a8b",
        "fg": "#fff",
        "name": {
            "en": "Shanghai Rail Transit Airport Link Line",
            "zh-Hans": "机场联络线",
            "zh-Hant": "機場聯絡線"
        }
    },
    {
        "id": "pjl",
        "colour": "#999999",
        "fg": "#fff",
        "name": {
            "en": "Pujiang Line",
            "zh-Hans": "浦江线",
            "zh-Hant": "浦江線"
        }
    },
    {
        "id": "cml",
        "colour": "#6cc19a",
        "fg": "#000",
        "name": {
            "en": "Chongming Line",
            "zh-Hans": "崇明线",
            "zh-Hant": "崇明線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，由于百度百科的准确度很低，我们不接受来自于百度百科的颜色来源。

如方便的话请提供来自于上海地铁官方网站或者维基百科上的颜色来源，谢谢。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色来源无效后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
