### ISSUE TITLE
Resources: New palettes of Changsha

### ISSUE THREAD

**Issue by shenmeyemeiyou** [railmapgen/rmg-palette#351]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

(REPLACE ME/替代我)**Reference link:** https://www.hncsmtr.com/webapp/dt/main.jsp

**Justification:** 长沙地铁颜色错误

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "changsha",
    "country": "CN",
    "name": {
        "en": "Changsha",
        "zh-Hans": "长沙",
        "zh-Hant": "長沙"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "cs1",
        "colour": "#DA291C",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "cs2",
        "colour": "#4db6ea",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "cs3",
        "colour": "#C0DF16",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "cs4",
        "colour": "#A51890",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "cs5",
        "colour": "#FFD100",
        "fg": "#000",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "cs6",
        "colour": "#0077C8",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "cs7",
        "colour": "#009739",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "cs8",
        "colour": "#D9027D",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "cs9",
        "colour": "#00BFB2",
        "fg": "#000",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "cs10",
        "colour": "#81312F",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "cs11",
        "colour": "#DE7C00",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "cs12",
        "colour": "#9063CD",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "maglev",
        "colour": "#F891A5",
        "fg": "#fff",
        "name": {
            "en": "Maglev Express",
            "zh-Hans": "磁浮快线",
            "zh-Hant": "磁浮快線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，您所改动过颜色的线路（2号线）中的颜色（#4DB6EA）与所提供来源颜色（#52A8C9）并不相符，请重新检查一遍后将修改后的颜色告诉我们。

此外，您所提供的来源中，1/3/4/5/6/磁浮快线的颜色均与我们颜色库中的颜色不同但您并未对其进行改动，同时该来源中缺少7/8/9/10/11/12号线的颜色来源。希望您下次对我们颜色库中的颜色修改时仔细核对来源颜色并确保来源中已包括所有颜色库中所包含颜色，谢谢。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色不匹配后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
