### ISSUE TITLE
Resources: New palettes of Changzhou

### ISSUE THREAD

**Issue by CharlieGao2009** [railmapgen/rmg-palette#353]
**Reference link:** http://www.czmetro.net.cn/Html/index.html

**Justification:** 添加常州地铁的线路颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "changzhou",
    "country": "CN",
    "name": {
        "en": "Changzhou",
        "zh-Hans": "常州",
        "zh-Hant": "常州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "cz1",
        "colour": "#da2c30",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "cz2",
        "colour": "#51b5ce",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，您所提交的颜色与所提供来源颜色并不相符（1号线由于色差较小考虑到不同设备在图片中取色都会出现较小色差因此不考虑在内，但2号线色差明显过大），请重新检查一遍后将修改后的颜色告诉我们。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）
