### ISSUE TITLE
Resources: New palettes of shijiazhuang

### ISSUE THREAD

**Issue by nmwdzs** [railmapgen/rmg-palette#374]
**Reference link:** http://www.sjzmetro.cn/cyportal2.3/template/site00_index@gdb.jsp?a1b2dd=7xaac

**Justification:** 颜色库中缺少石家庄市地铁线路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shijiazhuang",
    "country": "CN",
    "name": {
        "zh": "石家庄",
        "en": "shijiazhuang"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sjz1",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Line1",
            "zh": "1号线"
        }
    },
    {
        "id": "sjz2",
        "colour": "#ffff00",
        "fg": "#fff",
        "name": {
            "en": "Line2",
            "zh": "2号线"
        }
    },
    {
        "id": "sjz3",
        "colour": "#5dcef4",
        "fg": "#fff",
        "name": {
            "en": "Line3",
            "zh": "3号线"
        }
    },
    {
        "id": "sjz4",
        "colour": "#c0c0c0",
        "fg": "#fff",
        "name": {
            "en": "Line4",
            "zh": "4号线"
        }
    },
    {
        "id": "sjz5",
        "colour": "#ff9900",
        "fg": "#fff",
        "name": {
            "en": "Line5",
            "zh": "5号线"
        }
    },
    {
        "id": "sjz6",
        "colour": "#0846aa",
        "fg": "#fff",
        "name": {
            "en": "Line6",
            "zh": "6号线"
        }
    },
    {
        "id": "sjz7",
        "colour": "#8de29e",
        "fg": "#fff",
        "name": {
            "en": "Line7",
            "zh": "7号线"
        }
    },
    {
        "id": "sjz8",
        "colour": "#0011ff",
        "fg": "#fff",
        "name": {
            "en": "Line8",
            "zh": "8号线"
        }
    },
    {
        "id": "sjz9",
        "colour": "#9dd747",
        "fg": "#fff",
        "name": {
            "en": "Line9",
            "zh": "9号线"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，我们注意到您所提供的来源中并未提供除1-3号线这三条线路外的线路颜色。

请问方便的话能否提供其他线路颜色来源，谢谢。

（请您在收到本条消息后尽快及时回复，考虑到您所提供的铁路系统为新增且1-3号线已经有准确来源，如超过一个月未回复我们将只汇入1-3号线这三条线路颜色）

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色来源无效后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
