### ISSUE TITLE
New palette for Gdańsk

### ISSUE THREAD

**Issue by THIAS18** [railmapgen/rmg-palette#388]
**Reference link:** https://ztm.gda.pl

**Justification:** ZTM Gdańsk is the official website ZTM Gdańsk is the official website of Gdańsk public transport 

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "gdansk",
    "country": "PL",
    "name": {
        "pl": "Gdańsk",
        "en": "Gdańsk",
        "zh": "格但斯克"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "tram2",
        "colour": "#a4ff63",
        "fg": "#fff",
        "name": {
            "en": "2"
        }
    },
    {
        "id": "tram3",
        "colour": "#ff00ff",
        "fg": "#fff",
        "name": {
            "en": "3"
        }
    },
    {
        "id": "tram4",
        "colour": "#8000db",
        "fg": "#fff",
        "name": {
            "en": "4"
        }
    },
    {
        "id": "tram5",
        "colour": "#ffbb54",
        "fg": "#000",
        "name": {
            "en": "5"
        }
    },
    {
        "id": "tram6",
        "colour": "#00a1d6",
        "fg": "#fff",
        "name": {
            "en": "6"
        }
    },
    {
        "id": "tram7",
        "colour": "#b06700",
        "fg": "#fff",
        "name": {
            "en": "7"
        }
    },
    {
        "id": "tram8",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "8"
        }
    },
    {
        "id": "tram9",
        "colour": "#0044ff",
        "fg": "#fff",
        "name": {
            "en": "9"
        }
    },
    {
        "id": "tram10",
        "colour": "#3d2400",
        "fg": "#fff",
        "name": {
            "en": "10"
        }
    },
    {
        "id": "tram12",
        "colour": "#ff8521",
        "fg": "#fff",
        "name": {
            "en": "12"
        }
    }
]</details>

**Comment by 52PD** [comment]
Hi, it looks like the website you provide didn't have and line color information.
Could you please provide a source with line color? Thank you.

(Please reply this issue as soon as possible. We will refuse to merge any problem issue that the providers not reply our questions over 1 month)

**Comment by 52PD** [comment]
Hi, we want to notify you that you already not response our request over half month.

Please reply this issue as soon as possible. If there is no response over 1 month, we will reject your request. Thank you!

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色来源无效后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
