### ISSUE TITLE
Resources: New palettes of Washington DC

### ISSUE THREAD

**Issue by NNTR** [railmapgen/rmg-palette#394]
**Reference link:** https://zh.wikipedia.org/wiki/華盛頓地鐵

**Justification:** 华盛顿地铁
Comment by @52PD on Feb 3, 2023：Replaced source link to Wikipedia link after review the original link, which the content is copied from Wikipedia.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "washington",
    "country": "US",
    "name": {
        "en": "Washington DC",
        "zh": "华盛顿特区"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "wdcr",
        "colour": "#e31233",
        "fg": "#fff",
        "name": {
            "en": "Red line",
            "zh-Hans": "红线",
            "zh-Hant": "紅線"
        }
    },
    {
        "id": "wdcb",
        "colour": "#0077c0",
        "fg": "#fff",
        "name": {
            "en": "Blue line",
            "zh-Hans": "蓝线",
            "zh-Hant": "藍線"
        }
    },
    {
        "id": "wdco",
        "colour": "#f69318",
        "fg": "#000",
        "name": {
            "en": "Orange line",
            "zh-Hans": "橙线",
            "zh-Hant": "橙線"
        }
    },
    {
        "id": "wdcy",
        "colour": "#ffd300",
        "fg": "#000",
        "name": {
            "en": "Yellow line",
            "zh-Hans": "黄线",
            "zh-Hant": "黃線"
        }
    },
    {
        "id": "wdcg",
        "colour": "#00aa4e",
        "fg": "#fff",
        "name": {
            "en": "Green line",
            "zh-Hans": "绿线",
            "zh-Hant": "綠線"
        }
    },
    {
        "id": "wdcs",
        "colour": "#a2a2a2",
        "fg": "#000",
        "name": {
            "en": " Silver line",
            "zh-Hans": "银线",
            "zh-Hant": "銀線"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @NNTR ,

經檢查，閣下提供的RGB顏色與參考來源（維基百科）所用的顏色不符。以紅線為例子，[路線標誌的影像](https://en.wikipedia.org/wiki/File:WMATA_Red.svg)的源代碼RGB顏色為`#E21936`。請修正後並編輯該 Issue 正文。多謝！

**Comment by NNTR** [comment]
我取色的是这张图 @wongchito
![image](https://user-images.githubusercontent.com/123074394/216938276-a1dfaea1-d3b1-46c1-81fa-b0fdb0c721f4.png)

**Comment by NNTR** [comment]
实在找不到一张红线是#E21936的图，几乎把能找的都找了

**Comment by wongchito** [comment]
> 我取色的是这张图 @wongchito
> 
> ![image](https://user-images.githubusercontent.com/123074394/216938276-a1dfaea1-d3b1-46c1-81fa-b0fdb0c721f4.png)
> 
> 

Hi @NNTR , 

閣下所指的圖片原格式為SVG，但因網頁顯示需要轉換/壓縮為PNG格式。在取色時，應開啟其源檔案（連結見上面的回應）並從源代碼中提取顏色。

**Comment by NNTR** [comment]
对不起， @wongchito ，实在不会弄，你能帮改一下吗？

**Comment by wongchito** [comment]
沒關係 😊

**Comment by wongchito** [comment]
Hi @NNTR ,

華盛頓特區之調色盤已由 #421 所代替。多謝閣下的貢獻！
