### ISSUE TITLE
Resources: New palettes of WENZHOU

### ISSUE THREAD

**Issue by FLYER2048** [railmapgen/rmg-palette#404]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://baike.baidu.com/item/%E6%B8%A9%E5%B7%9E%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9AM4%E7%BA%BF?fromModule=lemma_search-box

**Justification:** 新增温州市轨道交通S1、S2、S3、M1、M2、M3、M4线路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "wenzhou",
    "country": "CN",
    "name": {
        "en": "Wenzhou",
        "zh-Hans": "温州",
        "zh-Hant": "溫州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "wzs1",
        "colour": "#2061ad",
        "fg": "#fff",
        "name": {
            "en": "Line S1",
            "zh": "S1线"
        }
    },
    {
        "id": "wzs2",
        "colour": "#cf3631",
        "fg": "#fff",
        "name": {
            "en": "Line S2",
            "zh": "S2线"
        }
    },
    {
        "id": "wzs3",
        "colour": "#fb7f2c",
        "fg": "#fff",
        "name": {
            "en": "Line S3",
            "zh": "S3线"
        }
    },
    {
        "id": "wzm1",
        "colour": "#6ac1be",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh": "1号线"
        }
    },
    {
        "id": "wzm2",
        "colour": "#6ac1be",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh": "2号线"
        }
    },
    {
        "id": "wzm3",
        "colour": "#fbc733",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh": "3号线"
        }
    },
    {
        "id": "wzm4",
        "colour": "#6ac1be",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh": "4号线"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，由于考虑到百度百科上所提供颜色大多是时候都不准确，很抱歉我们不接受来自百度百科的颜色的来源。

目前我们只接受来自维基百科或者该城市/地区轨道交通官网上的颜色来源。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色来源无效后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
