### ISSUE TITLE
Resources: New palettes of GuangNan

### ISSUE THREAD

**Issue by poorboy12** [railmapgen/rmg-palette#408]
**Reference link:** http://railmapgen.github.io

**Justification:** self

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "guangnan",
    "country": "CN",
    "name": {
        "zh-Hans": "广南",
        "en": "GuangNan"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "gn1",
        "colour": "#00ff00",
        "fg": "#000",
        "name": {
            "zh-Hans": "1号线",
            "en": "Line 1"
        }
    },
    {
        "id": "gn2",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "zh-Hans": "2号线",
            "en": "Line 2"
        }
    },
    {
        "id": "gn3",
        "colour": "#00ffff",
        "fg": "#000",
        "name": {
            "zh-Hans": "3号线",
            "en": "Line 3"
        }
    },
    {
        "id": "gn4",
        "colour": "#9900ff",
        "fg": "#fff",
        "name": {
            "zh-Hans": "4号线",
            "en": "Line 4"
        }
    },
    {
        "id": "gn5",
        "colour": "#ffff00",
        "fg": "#000",
        "name": {
            "zh-Hans": "5号线",
            "en": "Line 5"
        }
    },
    {
        "id": "gn s1",
        "colour": "#0000ff",
        "fg": "#fff",
        "name": {
            "zh-Hans": "S1号线",
            "en": "Line S1"
        }
    }
]</details>

**Comment by linchen1965** [comment]
你好，感谢你对本项目部所做的贡献。但我们不会接受任何无可靠来源的投稿，请在提交线路颜色时替换掉下面这行字：

> 请提供适当的来源或理由，否则我们不会处理您的申请。 (REPLACE ME)

（请在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将不会汇入）

**Comment by 52PD** [comment]
您好，我们不接受任何虚构城市/轨道交通系统的颜色投稿，谢谢。
