### ISSUE TITLE
Resources: New palettes of Jinhua

### ISSUE THREAD

**Issue by leowulinhui** [railmapgen/rmg-palette#411]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** http://www.jhmtr.net/

**Justification:** 金华已开通地铁未添加至生成器

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "jinhua",
    "country": "CN",
    "name": {
        "zh-Hans": "金华",
        "en": "Jinhua",
        "zh-HK": "金華",
        "zh-TW": "金華"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "金义线",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "zh-Hans": "金义线",
            "en": "Jinyi Line",
            "zh-HK": "金義線",
            "zh-TW": "金義線"
        }
    },
    {
        "id": "义东线",
        "colour": "#167cca",
        "fg": "#fff",
        "name": {
            "zh-Hans": "义东线",
            "en": "Yidong Line",
            "zh-HK": "義東線",
            "zh-TW": "義東線"
        }
    }
]</details>

**Comment by linchen1965** [comment]
您好，您所提交的颜色与所提供来源颜色并不相符，请重新检查一遍后将修改后的颜色告诉我们。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色来源无效后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
