### ISSUE TITLE
*Vandalism Content*

### ISSUE THREAD

**Issue by WonderLandFpv** [railmapgen/rmg-palette#423]
**Reference link:** https://t.bilibili.com/365685726175145682?spm_id_from=333.999.0.0

**Justification:** 我要自定义我的城市

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "yc",
    "country": "GBSCT",
    "name": {
        "en": "Yucheng",
        "zh": "雨城"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "circle",
        "colour": "#edd32c",
        "fg": "#000",
        "name": {
            "en": "Circle Line",
            "zh": "环线"
        }
    }
]</details>

**Comment by WonderLandFpv** [comment]
**Reference link:** https://t.bilibili.com/365685726175145682?spm_id_from=333.999.0.0

**Justification:** 我要自定义我的城市

**Do not edit lines below, they are meant for bots only!!!**



<details repo="rmg-palette" type="city">{
    "id": "yc",
    "country": "GBSCT",
    "name": {
        "en": "Yucheng",
        "zh": "雨城"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "circle",
        "colour": "#edd32c",
        "fg": "#000",
        "name": {
            "en": "Circle Line",
            "zh": "环线"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，我们不接受任何虚构城市/轨道交通系统的颜色投稿，谢谢。

此外，请不要发布多次相同的无效内容。如再发现您发布该无效内容我们将会对其视为对本项目的恶意破坏并对您进行封禁处理。
