### ISSUE TITLE
Resources: New palettes of Yucheng

### ISSUE THREAD

**Issue by WonderLandFpv** [railmapgen/rmg-palette#425]
**Reference link:** https://t.bilibili.com/365685726175145682?spm_id_from=333.999.0.0

**Justification:** 73

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "yucheng",
    "country": "CN",
    "name": {
        "zh-Hans": "雨城",
        "zh-Hant": "雨城",
        "en": "Yucheng"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "circle",
        "colour": "#ffdd00",
        "fg": "#000",
        "name": {
            "en": "Circle Line",
            "zh-Hans": "环线",
            "zh-Hant": "环线"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，我们不接受任何虚构城市/轨道交通系统的颜色投稿，谢谢。
