### ISSUE TITLE
Resources: New palettes of Zhengzhou

### ISSUE THREAD

**Issue by C1P918R** [railmapgen/rmg-palette#437]
**Reference link:** https://baike.baidu.com/item/%E9%83%91%E8%AE%B8%E5%B8%82%E5%9F%9F%E9%93%81%E8%B7%AF/22345493

**Justification:** 根据郑州轨道交通规划17号线更名为郑许线

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "zhengzhou",
    "country": "CN",
    "name": {
        "en": "Zhengzhou",
        "zh-Hans": "郑州",
        "zh-Hant": "鄭州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "zz1",
        "colour": "#D20200",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "zz2",
        "colour": "#D28F00",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "zz3",
        "colour": "#CB5100",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "zz4",
        "colour": "#3792D6",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "zz5",
        "colour": "#25AC74",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "zz6",
        "colour": "#852081",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "zz7",
        "colour": "#C0955A",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "zz8",
        "colour": "#E6E394",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "zz9",
        "colour": "#828C47",
        "fg": "#fff",
        "name": {
            "en": "Line 9 Suburban Line",
            "zh-Hans": "9 - 城郊线",
            "zh-Hant": "9 - 城郊線"
        }
    },
    {
        "id": "zz10",
        "colour": "#B15F56",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "zz12",
        "colour": "#225E9E",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "zz14",
        "colour": "#844F7C",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "zz17",
        "colour": "#1D4155",
        "fg": "#fff",
        "name": {
            "en": "Line 17 Zhengxu Line",
            "zh-Hans": "17 - 郑许市域铁路",
            "zh-Hant": "17 - 鄭許市域鐵路"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，感谢您对线路名称错误进行修正。

然而我们注意到您在修改线路名称时完全删除了该线路的编号，然而据考察您所提供的来源（请注意，本项目是不接受百度百科来源的，但考虑到本次更新仅进行了名称修改故算作例外）和维基百科后发现规划中“17号线”这个编号并未彻底废除。

因此我们将在最终汇入版本中将其修改成编号与线路名共存的名称格式。我们建议您在下次进行类似修改时可以参考本Palette中深圳地铁或多伦多地铁的命名方式对这类线路进行命名，谢谢。

**Comment by linchen1965** [comment]
那城郊线是不是也得改成Line 9 Suburban Line🤔

**Comment by 52PD** [comment]
> 那城郊线是不是也得改成Line 9 Suburban Line🤔

提醒我了，马上去改😂

**Comment by C1P918R** [comment]
但是城郊线的官方说法并没有9号线啊😂

**Comment by 52PD** [comment]
> 但是城郊线的官方说法并没有9号线啊😂

查了一下，9号线现在只不过现在以城郊线名称运营。等9号线二期开通后就统一名称为9号线了。
![Screenshot 2023-02-26 at 11 40 24 PM](https://user-images.githubusercontent.com/98044618/221475816-bf8ee005-3bf9-441e-a516-9438d1c2c701.png)

不过既然现在还没以9号线名义运营的话那我先改回来吧。等到时候可以参照Palette里面保留港铁马鞍山线（现屯马线东段）那种提交（即同时保留城郊线和9号线）线路名称。

**Comment by C1P918R** [comment]
不行的话就这样做吧，我感觉以郑州地铁的速度9号线2期9成会再次被鸽😂😂

**Comment by C1P918R** [comment]
然后17号线的话就先按照17号线/郑许市域铁路（郑许线）命名吧，这个据说今年6月前会开通，大概率不会被鸽了😂😂

**Comment by C1P918R** [comment]
17号线/郑许线开通后会将线路图上传上来到时候还要麻烦各位了👀👀
