### ISSUE TITLE
北京地铁颜色相关讨论（修正和颜色添加）

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmg-palette#44]
由于本issue快变成线路颜色的讨论issue了，所以我想了想还是把这issue改成这个新标题合适一些，以后如果有关北京地铁颜色的问题都放在这边吧。

一楼原文：
最近发现生成器里面北京地铁的预设颜色有几个是错的，所以我这里顺带重做了一个颜色模版：
[bjsubway_fixed.txt](https://github.com/wongchito/RailMapGenerator/files/7921620/bjsubway_fixed.txt)

具体修改包括：
1. 7号线/9号线/13号线/14号线/19号线/昌平线/首都机场线的文字颜色应为黑色，而不是白色。
2. 11号线/17号线/19号线/大兴机场线的背景色代码不对
3. 西郊线的名字改成了西郊线/亦庄T1线（因为这两条现代有轨电车线颜色一样）

**Comment by 52PD** [comment]
最近看到隔壁老有人想要提交一些未开通的北京地铁线路颜色（尽管有一些已经定了，但@thekingofcity 已经说过不接受任何未开通线路），这里我还是把以及开始建造但没开通的线路列出来吧（还在规划中的线路我就不列举了），这样方便@wongchito 和@thekingofcity 审核一些。

目前已经开始建造但没开通的线路有这些：
- 3号线（目前计划2023年开通）
- 12号线（目前计划2023年开通）
- 平谷线（目前计划2024-2025年开通）
- 28号线（目前计划2024-2025年开通）
- 13A/13B号线（目前计划2024-2025年开通）

**Comment by thekingofcity** [comment]
😂说起来现在是不是还有线路的颜色没有改过来？issue有点久回忆不起来了。

**Comment by linchen1965** [comment]
> 最近看到隔壁老有人想要提交一些未开通的北京地铁线路颜色（尽管有一些已经定了，但@thekingofcity 已经说过不接受任何未开通线路），这里我还是把以及开始建造但没开通的线路列出来吧（还在规划中的线路我就不列举了），这样方便@wongchito 和@thekingofcity 审核一些。
> 
> 目前已经开始建造但没开通的线路有这些：
> 
> * 3号线（目前计划2023年开通）
> * 12号线（目前计划2023年开通）
> * 平谷线（目前计划2024-2025年开通）
> * 28号线（目前计划2024-2025年开通）
> * 13A/13B号线（目前计划2024-2025年开通）

说一些关于标志色的看法：
我想这里的不接受任何未开通线路应该仅仅是对于线路模板而言吧，毕竟在标志色这块不同城市对待的方式还是差别挺大的。像重庆成都这种是一下子就确定好了未开通的线路颜色，而有的城市就没这么走心，线路一直到开通之前都存在变数。北京就属于后者，去年11号线开通的时候标志色就在西柚色和冰蓝色之间反复横跳。（因为车内LCD显示的颜色是冰蓝色而且本身11号线也是冬奥支线用冰蓝色很切合主题，结果最后还是用了西柚色）对于前者来说提交未开通的线路颜色倒没什么问题。当然还有一种城市就是不公布颜色，要乘客自己去撕闪灯的膏药或者咨询官方才能得到确切色号的（比如南京）
回到北京地铁的颜色，12号线的话只能根据车厢里面的闪灯图粗略判断是棕色系，比6号线要深，具体色号不知道。3号线也不确定，可能是绘图圈一开始有人用了红色大家就都用红色吧，虽然我觉得这个接近于有轨电车配色的颜色用起来其实挺不合理的（平谷线、28号线估计也是这个道理）。虽然3号线的车外表涂装是红色，但在北京车身颜色和线路本身标志色完全不一样的线路也不少。
另外，在我上传的一些国外城市当中也存在标志色出入的情况，例如米兰地铁4号线在官网上显示标志色为#20406A，但在工程官网显示为#001588。（RMG当中的是前者）这两个颜色有肉眼可见的色差，远远大于之前讨论当中北京地铁几条线路在jpg和html界面的色差。这种情况下可能需要请 @thekingofcity 看看保留哪个还是二者都是。

**Comment by thekingofcity** [comment]
对于色差这块我没有太多的看法，特别是当官方说法都不统一时。@wongchito 你呢？

**Comment by 52PD** [comment]
> 我想这里的不接受任何未开通线路应该仅仅是对于线路模板而言吧

其实颜色也不行，#48 就是这么被拒的😂

**Comment by linchen1965** [comment]
> > 我想这里的不接受任何未开通线路应该仅仅是对于线路模板而言吧
> 
> 其实颜色也不行，#48 就是这么被拒的😂

啊这，我先前不知道这点，我看现有的RMG里面很多城市都有未开通线路的色板（比如长沙、广州、青岛、西安等等），所以后面自己上传色板的时候就没管开没开通了。在我第一次上传圣保罗的色板的时候， @thekingofcity 还问我要不要把17号线（未开通）的色板也一并加上，当时没找到标准色号来源所以暂时没加进去。所以我一直觉得对于未开通的线路的颜色是可以加进去的。😅
不过我当前确实没有找到https://github.com/railmapgen/rmg-palette/issues/48 这些色号的来源，我只知道这几个颜色在绘图圈似乎是被接受的。不过我觉得现在还不能加入[这些](https://github.com/railmapgen/rmg-palette/issues/48 )色板的更好原因是：北京地铁的未开通线路标志色变幻莫测的。

**Comment by 52PD** [comment]
> 不过我觉得现在还不能加入这些](https://github.com/railmapgen/rmg-palette/issues/48)色板的更好原因是：北京地铁的未开通线路标志色变幻莫测的。

确实，比如11号线（就像你说的，开通前和车内LED是冰蓝色，而最终配色却是西柚色😂。

**Comment by wongchito** [comment]
> 对于色差这块我没有太多的看法，特别是当官方说法都不统一时。@wongchito 你呢？
> 
> 

我最初個人上載顏色是，是按照以下優先級別：

1. 官方網站下載之設計標準（如倫敦TfL、多倫多TTC）
  - 若設計標準提供RGB顏色，則直接使用
  - 若設計標準提供Pantone色票，則前往Pantone官方網站之Find a Color功能轉換為網頁用RGB顏色
  - 無論標準中提及的路線開通與否，均加入顏色庫中
2. 城市之設計標準（中國城市通常以DB地方標準作規範，如顏色庫中的廣州）
  - 細項按1.處理
3. 官方網站中HTML/CSS所使用之RGB顏色（如愛丁堡）
4. 官方網站下載之PDF格式之線網圖所使用之顏色（如巴黎）
4. 維基百科中相關城市之模板（中國城市通常以Lua書寫）

我不贊成從官方JPG/PNG格式線網圖中取色，因為所取出之顏色，受製圖軟件、色彩模式、輸出模式、壓縮算法、取色軟件等因素，而有所不同。

⬆️以上內容純屬本人之回憶，歡迎大家提供意見。意見整理後，將會發佈至Wiki. 🙂

**Comment by 52PD** [comment]
> ⬆️以上內容純屬本人之回憶，歡迎大家提供意見。意見整理後，將會發佈至Wiki. 

要不要補充個文字配色以什麼為標準的，畢竟像北京地鐵這種已經算是字體配色混用重災區了（2014年底前的老線路（9號線、13號線和昌平線）時白時黑的，2014年底後的線路（7號線、11號線、14號線、19號線和改名後的機場線（即首都機場線））相對好些，但疫情後貼的時刻表還有官網html的文字顏色又全部變白了）😂

**Comment by linchen1965** [comment]
> 這個我覺得還是做保留意見吧，畢竟維基百科上的有時候也不一定准（比如英文維基上昆明的顏色就是錯的（1、2、3、6號線還好，4號線和即將開通的5號線顏色錯得就嚴重了）（其實中文維基上的最初也是錯的，現在的其實是我之後修正了的😂）

说到底还是得看具体城市，有的城市一些线路在维基百科上面的颜色切换成不同语言的版本之后甚至就不一样了😂

**Comment by thekingofcity** [comment]
> 啊这，我先前不知道这点，我看现有的RMG里面很多城市都有未开通线路的色板（比如长沙、广州、青岛、西安等等），所以后面自己上传色板的时候就没管开没开通了。在我第一次上传圣保罗的色板的时候， @thekingofcity 还问我要不要把17号线（未开通）的色板也一并加上，当时没找到标准色号来源所以暂时没加进去。所以我一直觉得对于未开通的线路的颜色是可以加进去的。😅

实在抱歉，我将未开通线路的调色板和模板搞混了。目前我们仅拒绝未开通线路的模板，欢迎添加未开通线路的调色板。🎉

**Comment by 52PD** [comment]
突然想到一点，就北京地铁这种线路名颜色混用的问题来讲，如果把混用线路的两种文字颜色都加进去不知道可不可以 @thekingofcity @wongchito 🤔（如果不行的话那就算了）

**Comment by linchen1965** [comment]
> 突然想到一点，就北京地铁这种线路名颜色混用的问题来讲，如果把混用线路的两种文字颜色都加进去不知道可不可以 @thekingofcity @wongchito 🤔（如果不行的话那就算了）

我想到了广州地铁也出现过线路名颜色混用的情况（图为7号线）
![56bd4c17249d905925bed9ae1ea7ea5](https://user-images.githubusercontent.com/92020676/176983150-b87a3e57-cb3d-401d-b8f8-8313e1423fe0.jpg)

**Comment by 52PD** [comment]
> 我想到了广州地铁也出现过线路名颜色混用的情况（图为7号线） 

这个也挺离谱的😂（而且感觉这个的7号线背景色都错了，浅绿色直接变成垃圾桶绿了）

**Comment by 52PD** [comment]
> 突然想到一点，就北京地铁这种线路名颜色混用的问题来讲，如果把混用线路的两种文字颜色都加进去不知道可不可以 @thekingofcity @wongchito 🤔（如果不行的话那就算了）
>
> 我想到了广州地铁也出现过线路名颜色混用的情况（图为7号线）

要不干脆加一个新要求吧。如果地方标准没规定线路文字颜色的（毕竟不是所有地方标准都会像上海一样连文字颜色都规定掉）那就统一以屏蔽门上的文字颜色为准（比如广州可以看线路名/站台编号/屏蔽门号，北京可以看线路图当前车站）这样应该会好一些（毕竟就像广州地铁那种导向牌再怎么混用屏蔽门线路图也是统一标准的）🤔

**Comment by thekingofcity** [comment]
嗨，@linchen1965 和 @52PD，感谢两位对调色板和线路模板的持续贡献与支持。不知两位是否愿意成为resource admin帮助我们管理railmapgen/rmg-palette和railmapgen/rmg-templates，作为回报我们会在贡献者页面突出两位的存在。

欢迎加入slack讨论更多细节：https://join.slack.com/t/railmapgenerator/shared_invite/zt-1bvl6f95f-blHZgf__iFgH59AaXiNH_w

**Comment by linchen1965** [comment]
> > 突然想到一点，就北京地铁这种线路名颜色混用的问题来讲，如果把混用线路的两种文字颜色都加进去不知道可不可以 @thekingofcity @wongchito 🤔（如果不行的话那就算了）
> > 我想到了广州地铁也出现过线路名颜色混用的情况（图为7号线）
> 
> 要不干脆加一个新要求吧。如果地方标准没规定线路文字颜色的（毕竟不是所有地方标准都会像上海一样连文字颜色都规定掉）那就统一以屏蔽门上的文字颜色为准（比如广州可以看线路名/站台编号/屏蔽门号，北京可以看线路图当前车站）这样应该会好一些（毕竟就像广州地铁那种导向牌再怎么混用屏蔽门线路图也是统一标准的）🤔

我觉得可以，这对绝大多数国内的城市适用。但是有的国外城市的地铁系统没有屏蔽门，在官方网站上的地图当中也是将线路名称放在色块之外的，那种就不好说到底文字颜色是黑是白了。（比如巴库地铁）

**Comment by 52PD** [comment]
> 嗨，@linchen1965 和 @52PD，感谢两位对调色板和线路模板的持续贡献与支持。不知两位是否愿意成为resource admin帮助我们管理railmapgen/rmg-palette和railmapgen/rmg-templates，作为回报我们会在贡献者页面突出两位的存在。

我的话应该可以，@linchen1965 你呢？
（不过我有时候可能不一定有时间，毕竟大学课程还是挺紧张的）

**Comment by linchen1965** [comment]
> > 嗨，@linchen1965 和 @52PD，感谢两位对调色板和线路模板的持续贡献与支持。不知两位是否愿意成为resource admin帮助我们管理railmapgen/rmg-palette和railmapgen/rmg-templates，作为回报我们会在贡献者页面突出两位的存在。
> 
> 我的话应该可以，@linchen1965 你呢？ （不过我有时候可能不一定有时间，毕竟大学课程还是挺紧张的）

我其实也不一定一直都有时间，不过我还是进去了😂

**Comment by 52PD** [comment]
So，之后我跟@wongchito 和 @thekingofcity 在slack上讨论过了，目前北京地铁的背景色已经统一成html地图上所用的颜色，且文字颜色也已经统一以目前屏蔽门线路图上所用颜色。
那么本issue的使命也差不多在这结束了。
之后关于各个城市颜色混用问题的讨论我会重开一个issue专门给大家用于讨论这个方面的问题
