### ISSUE TITLE
Resources: New palettes of Fuzhou

### ISSUE THREAD

**Issue by TakeiDaisei** [railmapgen/rmg-palette#447]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://zh.wikipedia.org/wiki/%E7%A6%8F%E5%B7%9E%E5%9C%B0%E9%93%81

**Justification:** 更改颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "fuzhou",
    "country": "CN",
    "name": {
        "en": "Fuzhou",
        "ko": "푸저우",
        "zh-Hans": "福州",
        "zh-TW": "福州",
        "zh-HK": "福州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "fz1",
        "colour": "#bb1e10",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "ko": "1호선",
            "zh-Hans": "1号线",
            "zh-HK": "1號綫",
            "zh-TW": "1號缐"
        }
    },
    {
        "id": "fz2",
        "colour": "#325928",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "ko": "2호선",
            "zh-Hans": "2号线",
            "zh-HK": "2號綫",
            "zh-TW": "2號缐"
        }
    },
    {
        "id": "fz4",
        "colour": "#ff7f41",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "ko": "4호선",
            "zh-Hans": "4号线",
            "zh-HK": "4號綫",
            "zh-TW": "4號缐"
        }
    },
    {
        "id": "fz5",
        "colour": "#893b67",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "ko": "5호선",
            "zh-Hans": "5号线",
            "zh-HK": "5號綫",
            "zh-TW": "5號缐"
        }
    },
    {
        "id": "fz6",
        "colour": "#005eb8",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "ko": "6호선",
            "zh-Hans": "6号线",
            "zh-HK": "6號綫",
            "zh-TW": "6號缐"
        }
    },
    {
        "id": "fzbh",
        "colour": "#00adbb",
        "fg": "#fff",
        "name": {
            "en": "Binhai Express",
            "ko": "빈해 익스프레스",
            "zh-Hans": "滨海快线",
            "zh-HK": "濱海快綫",
            "zh-TW": "濱海快缐"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，由于考虑到百度百科上所提供颜色大多是时候都不准确，很抱歉我们不接受来自百度百科的颜色的来源。

目前我们只接受来自维基百科或者该城市/地区轨道交通官网上的颜色来源。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by TakeiDaisei** [comment]
福州地铁 - 维基百科，自由的百科全书 (wikipedia.org)




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月5日(星期天) 晚上11:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [railmapgen/rmg-palette] Resources: New palettes of Fuzhou（新增调色板城市及路线） (Issue #447)





 
您好，由于考虑到百度百科上所提供颜色大多是时候都不准确，很抱歉我们不接受来自百度百科的颜色的来源。
 
目前我们只接受来自维基百科或者该城市/地区轨道交通官网上的颜色来源。
 
（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
您好，很抱歉到现在才对您的修改作出回复。

经检查，我们发现您提交的6条线路颜色均与维基百科上所提供颜色不同。请检查您所提交的线路颜色后将修改后的颜色回复到本issue中，谢谢。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by TakeiDaisei** [comment]
**Reference link:** https://zh.wikipedia.org/wiki/%E7%A6%8F%E5%B7%9E%E5%9C%B0%E9%93%81

**Justification:** 更改颜色

**Do not edit lines below, they are meant for bots only!!!**



<details repo="rmg-palette" type="city">{
    "id": "fuzhou",
    "country": "CN",
    "name": {
        "en": "Fuzhou",
        "ko": "푸저우",
        "zh-Hans": "福州",
        "zh-TW": "福州",
        "zh-HK": "福州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "fz1",
        "colour": "#bb1e10",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "ko": "1호선",
            "zh-Hans": "1号线",
            "zh-HK": "1號綫",
            "zh-TW": "1號缐"
        }
    },
    {
        "id": "fz2",
        "colour": "#325928",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "ko": "2호선",
            "zh-Hans": "2号线",
            "zh-HK": "2號綫",
            "zh-TW": "2號缐"
        }
    },
    {
        "id": "fz4",
        "colour": "#ff7f41",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "ko": "4호선",
            "zh-Hans": "4号线",
            "zh-HK": "4號綫",
            "zh-TW": "4號缐"
        }
    },
    {
        "id": "fz5",
        "colour": "#893b67",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "ko": "5호선",
            "zh-Hans": "5号线",
            "zh-HK": "5號綫",
            "zh-TW": "5號缐"
        }
    },
    {
        "id": "fz6",
        "colour": "#005eb8",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "ko": "6호선",
            "zh-Hans": "6号线",
            "zh-HK": "6號綫",
            "zh-TW": "6號缐"
        }
    },
    {
        "id": "fzbh",
        "colour": "#00adbb",
        "fg": "#fff",
        "name": {
            "en": "Binhai Express",
            "ko": "빈해 익스프레스",
            "zh-Hans": "滨海快线",
            "zh-HK": "濱海快綫",
            "zh-TW": "濱海快缐"
        }
    }
]</details>
