### ISSUE TITLE
Resources: New palettes of Expressway

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmg-palette#448]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://www.tw.3822808.com/

**Justification:** 新增国家高速公路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "expressway",
    "country": "CN",
    "name": {
        "en": "Expressway",
        "zh": "高速公路",
        "zh-HK": "高速公路"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "expresswayn",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "National expressway",
            "zh-Hans": "国家高速",
            "zh-Hant": "國家高速"
        }
    },
    {
        "id": "expresswayp",
        "colour": "#ffff00",
        "fg": "#000",
        "name": {
            "en": "Province expressway",
            "zh-Hans": "省级高速",
            "zh-Hant": "省級高速"
        }
    },
    {
        "id": "expresswaynh",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "National Highway",
            "zh-Hans": "国道",
            "zh-Hant": "國道"
        }
    },
    {
        "id": "expresswayj",
        "colour": "#ccff33",
        "fg": "#000",
        "name": {
            "en": "Jingjinji expressway",
            "zh-Hans": "京津冀高速",
            "zh-Hant": "京津冀高速"
        }
    },
    {
        "id": "expresswayph",
        "colour": "#ffff00",
        "fg": "#000",
        "name": {
            "en": "Province Highway",
            "zh-Hans": "省道",
            "zh-Hant": "省道"
        }
    },
    {
        "id": "expresswaycr",
        "colour": "#ffffff",
        "fg": "#000",
        "name": {
            "en": "County road",
            "zh-Hans": "县道",
            "zh-Hant": "縣道"
        }
    },
    {
        "id": "expresswayy",
        "colour": "#ffffff",
        "fg": "#000",
        "name": {
            "en": "Country road",
            "zh-Hans": "乡道",
            "zh-Hant": "鄉道"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，您的参考链接似乎打不开，请您换一个参考链接提交，感谢您的贡献。

**Comment by Windows-Taskmgr** [comment]
（请您在收到此消息后一个月内回复，否则我们会直接拒绝汇入）

**Comment by Swiftiecott** [comment]
Closed as no response for fixing over 1 months.
