### ISSUE TITLE
郑州地铁的线路名称及颜色

### ISSUE THREAD

**Issue by C1P918R** [railmapgen/rmg-palette#46]
添加郑州地铁的6,7,8,10,12,17号线的线路名称及颜色标识
[Zhengzhou.Metro.Color.Palette.txt](https://github.com/railmapgen/rmg/files/8628391/Zhengzhou.Metro.Color.Palette.txt)
[Zhengzhou.Metro.Line.Name.txt](https://github.com/railmapgen/rmg/files/8628392/Zhengzhou.Metro.Line.Name.txt)

**Comment by thekingofcity** [comment]
嗨，请问 #46 和 #47 的区别是什么呢，您可以只保留最新的修改issue为open状态即可。感谢您对项目的支持与贡献。

**Comment by C1P918R** [comment]
@thekingofcity 不好意思啊，那个我朋友上传重复了，就按照这个修改吧

**Comment by thekingofcity** [comment]
更新于 #51，感谢您对项目的支持与贡献
