### ISSUE TITLE
Resources: New palettes of Shanghai

### ISSUE THREAD

**Issue by wongchito** [railmapgen/rmg-palette#466]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://www.doc88.com/p-9651748022421.html

**Justification:** Update palettes with Pantone code after discussion in #446 

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shanghai",
    "country": "CN",
    "name": {
        "en": "Shanghai",
        "zh": "上海"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sh1",
        "colour": "#E4002B",
        "fg": "#fff",
        "pantone": "185 C",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "sh2",
        "colour": "#97D700",
        "fg": "#000",
        "pantone": "375 C",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "sh3",
        "colour": "#FFD100",
        "fg": "#000",
        "pantone": "109 C",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "sh4",
        "colour": "#5F249F",
        "fg": "#fff",
        "pantone": "267 C",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "sh5",
        "colour": "#AC4FC6",
        "fg": "#fff",
        "pantone": "2582 C",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "sh6",
        "colour": "#D60078",
        "fg": "#fff",
        "pantone": "Process Magenta C",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "sh7",
        "colour": "#FF6900",
        "fg": "#000",
        "pantone": "1505 C",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "sh8",
        "colour": "#009CDD",
        "fg": "#fff",
        "pantone": "Process Cyan C",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "sh9",
        "colour": "#71C5E8",
        "fg": "#000",
        "pantone": "297 C",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "sh10",
        "colour": "#C1A7E2",
        "fg": "#000",
        "pantone": "264 C",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "sh11",
        "colour": "#76232F",
        "fg": "#fff",
        "pantone": "188 C",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "sh12",
        "colour": "#007B5F",
        "fg": "#fff",
        "pantone": "335 C",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "sh13",
        "colour": "#EF95CF",
        "fg": "#000",
        "pantone": "223 C",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "sh14",
        "colour": "#827A04",
        "fg": "#fff",
        "pantone": "392 C",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "sh15",
        "colour": "#CEB888",
        "fg": "#000",
        "pantone": "7502 C",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "sh16",
        "colour": "#2CD5C4",
        "fg": "#000",
        "pantone": "3255 C",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "sh17",
        "colour": "#C09C83",
        "fg": "#fff",
        "pantone": "7521 C",
        "name": {
            "en": "Line 17",
            "zh-Hans": "17号线",
            "zh-Hant": "17號線"
        }
    },
    {
        "id": "sh18",
        "colour": "#D6A461",
        "fg": "#000",
        "pantone": "7509 C",
        "name": {
            "en": "Line 18",
            "zh-Hans": "18号线",
            "zh-Hant": "18號線"
        }
    },
    {
        "id": "pjl",
        "colour": "#9EA2A2",
        "fg": "#fff",
        "pantone": "422 C",
        "name": {
            "en": "Pujiang Line",
            "zh-Hans": "浦江线",
            "zh-Hant": "浦江線"
        }
    },
    {
        "id": "t1",
        "colour": "#FF0000",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T1",
            "zh-Hans": "松江有轨电车1号线",
            "zh-Hant": "松江有軌電車1號線"
        }
    },
    {
        "id": "t2",
        "colour": "#46837B",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T2",
            "zh-Hans": "松江有轨电车2号线",
            "zh-Hant": "松江有軌電車2號線"
        }
    },
    {
        "id": "t3",
        "colour": "#009400",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T3",
            "zh-Hans": "松江有轨电车3号线",
            "zh-Hant": "松江有軌電車3號線"
        }
    },
    {
        "id": "t4",
        "colour": "#FF00FF",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T4",
            "zh-Hans": "松江有轨电车4号线",
            "zh-Hant": "松江有軌電車4號線"
        }
    },
    {
        "id": "t5",
        "colour": "#00FD00",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T5",
            "zh-Hans": "松江有轨电车5号线",
            "zh-Hant": "松江有軌電車5號線"
        }
    },
    {
        "id": "t6",
        "colour": "#6E00DD",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T6",
            "zh-Hans": "松江有轨电车6号线",
            "zh-Hant": "松江有軌電車6號線"
        }
    },
    {
        "id": "maglev",
        "colour": "#009090",
        "fg": "#fff",
        "name": {
            "en": "Shanghai Maglev Train",
            "zh-Hans": "磁浮线",
            "zh-Hant": "磁浮線"
        }
    },
    {
        "id": "jsr",
        "colour": "#000000",
        "fg": "#fff",
        "name": {
            "zh": "金山铁路",
            "en": "Jinshan Railway"
        }
    }
]</details>

**Comment by wongchito** [comment]
Display colour (on Chrome macOS version, colour profile: Color LCD):

<img width="533" alt="image" src="https://user-images.githubusercontent.com/9390786/227301544-5b02a353-18b0-4444-837b-6175b2e8e129.png">

**Comment by 203IhzElttil** [comment]
潘通色号取的RGB其实不太准 会偏亮
毕竟这两张官方图上的16号线也是差不多#98D1C0的颜色而跟#2CD5C4差异过大 说明是用cmyk转化的而不是潘通
14号线也是 潘通转的RGB明显过亮
所以还是用cmyk转的rgb吧，颜色差别至少不会太大
![image](https://user-images.githubusercontent.com/106796352/227667195-550cfccf-d7cc-4e56-aa6e-fb7d452f8371.png)
![yb](https://user-images.githubusercontent.com/106796352/227667283-5736d9ee-ffa6-4c22-91de-75c4a520d918.png)
