### ISSUE TITLE
Resources: New palettes of Buenos Aires

### ISSUE THREAD

**Issue by Nachogao** [railmapgen/rmg-palette#474]
**Reference link:** https://buenosaires.gob.ar/subte/mapa-y-combinaciones

**Justification:** 我想要制作布宜诺斯艾利斯地铁线路图

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "AR",
    "name": {
        "es": "Argentina",
        "zh-Hans": "阿根廷",
        "zh-Hant": "阿根廷",
        "en": "Argentina"
    },
    "language": "es"
}</details>

<details repo="rmg-palette" type="city">{
    "id": "buenosaires",
    "country": "AR",
    "name": {
        "es": "Buenos Aires",
        "zh-Hans": "布宜诺斯艾利斯",
        "zh-Hant": "布宜諾斯艾利斯",
        "en": "Buenos Aires"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "baa",
        "colour": "#00aedc",
        "fg": "#fff",
        "name": {
            "zh-Hans": "A线",
            "es": "Línea A"
        }
    },
    {
        "id": "bab",
        "colour": "#ee1b2c",
        "fg": "#fff",
        "name": {
            "es": "Línea B",
            "zh-Hans": "B线"
        }
    },
    {
        "id": "bac",
        "colour": "#0168b3",
        "fg": "#fff",
        "name": {
            "es": "Línea C",
            "zh-Hans": "C线",
            "zh-Hant": ""
        }
    },
    {
        "id": "bad",
        "colour": "#008066",
        "fg": "#fff",
        "name": {
            "es": "Línea D",
            "zh-Hans": "D线",
            "zh-Hant": ""
        }
    },
    {
        "id": "bae",
        "colour": "#6b1f7e",
        "fg": "#fff",
        "name": {
            "es": "Línea E",
            "zh-Hans": "E线",
            "zh-Hant": ""
        }
    },
    {
        "id": "baf",
        "colour": "#800000",
        "fg": "#fff",
        "name": {
            "es": "Línea F",
            "zh-Hans": "F线",
            "zh-Hant": ""
        }
    },
    {
        "id": "bag",
        "colour": "#ff69b4",
        "fg": "#fff",
        "name": {
            "es": "Línea G",
            "zh-Hans": "G线"
        }
    },
    {
        "id": "bah",
        "colour": "#fed105",
        "fg": "#fff",
        "name": {
            "es": "Línea H",
            "zh-Hans": "H线"
        }
    },
    {
        "id": "bai",
        "colour": "#ff4500",
        "fg": "#fff",
        "name": {
            "es": "Línea I",
            "zh-Hans": "I线",
            "zh-Hant": ""
        }
    },
    {
        "id": "bap",
        "colour": "#fdbb2e",
        "fg": "#fff",
        "name": {
            "es": "Línea P",
            "zh-Hans": "P线",
            "zh-Hant": ""
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，我们在您所提供的颜色来源中并未找到F线、G线和I线三条线路的颜色。请问这三条线路的颜色是从何处找到的呢？

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by Nachogao** [comment]
@52PD 您好，这三条线路属于为未动工的规划线路。
此为阿根廷当地[https://www.pagina12.com.ar/419498-linea-f-de-subte-los-detalles-del-proyecto-que-ahora-impulsa](报纸)，其中提供了一个未来规划图参考。

**Comment by Nachogao** [comment]
@52PD 您好，这三条线路属于为未动工的规划线路。
此为阿根廷当地[https://www.pagina12.com.ar/419498-linea-f-de-subte-los-detalles-del-proyecto-que-ahora-impulsa](报纸)，其中提供了一个未来规划图参考。

补充：布宜诺斯艾利斯市政府提供的规划介绍书。[https://buenosaires.gob.ar/subte/plan-estrategico-y-tecnico-para-la-expansion-de-la-red-de-subtes-de-buenos-aires]()
