### ISSUE TITLE
Resources: New palettes of Taizhou

### ISSUE THREAD

**Issue by wwt951** [railmapgen/rmg-palette#478]
**Reference link:** https://www.tz-mtr.com/

**Justification:** 1

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "taizhou",
    "country": "CN",
    "name": {
        "en": "Taizhou",
        "zh": "台州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "S1",
        "colour": "#1d8cc5",
        "fg": "#fff",
        "name": {
            "en": "Line S1",
            "zh": "S1线"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @wwt951 ,

The colour of Line S1 cannot be found in the link you provided. Could you please provide the direct url to the colour. Thanks.

**Comment by wwt951** [comment]
台州市域铁路S1线_百度百科 (baidu.com)



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Chito ***@***.***&gt;; 
发送时间: 2023年4月17日(星期一) 下午5:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [railmapgen/rmg-palette] Resources: New palettes of Taizhou (Issue #478)





 
Hi @wwt951 ,
 
The colour of Line S1 cannot be found in the link you provided. Could you please provide the direct url to the colour. Thanks.

**Comment by 52PD** [comment]
您好，@wwt951 。

很抱歉我们已经不会考虑检查本稿件。首先您之后补充的来源算作无效来源（我们只接受来自铁路公司官方网站或者维基百科的颜色来源）。

此外，在回复本issue之前已经有超过一个月未对其做出回应，而我们是不接受超过一个月未对其修正的问题稿件的。
