### ISSUE TITLE
Resources: New palettes of Kaohsiung

### ISSUE THREAD

**Issue by Benson20110806** [railmapgen/rmg-palette#485]
**Reference link:** https://zh.wikipedia.org/wiki/File:%E9%AB%98%E9%9B%84%E6%8D%B7%E9%81%8B%E8%B7%AF%E7%B6%B2%E5%9C%96_(2020).png

**Justification:** 沒有黃線

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "kaohsiung",
    "country": "TW",
    "name": {
        "en": "Kaohsiung",
        "zh": "高雄"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "red",
        "colour": "#e20b65",
        "fg": "#fff",
        "name": {
            "en": "Red Line",
            "zh-Hans": "红线",
            "zh-Hant": "紅線"
        }
    },
    {
        "id": "orange",
        "colour": "#faa73f",
        "fg": "#fff",
        "name": {
            "en": "Orange Line",
            "zh-Hans": "橘线",
            "zh-Hant": "橘線"
        }
    },
    {
        "id": "circular",
        "colour": "#7cbd52",
        "fg": "#fff",
        "name": {
            "en": "Circular Line (KLRT)",
            "zh-Hans": "环状轻轨",
            "zh-Hant": "環狀輕軌"
        }
    },
    {
        "id": "green",
        "colour": "#50cb00",
        "fg": "#fff",
        "name": {
            "en": "Green Line",
            "zh-Hans": "绿线",
            "zh-Hant": "綠線"
        }
    },
    {
        "id": "silver",
        "colour": "#929292",
        "fg": "#fff",
        "name": {
            "en": "Silver Line",
            "zh-Hans": "银线",
            "zh-Hant": "銀線"
        }
    },
    {
        "id": "blue",
        "colour": "#007fff",
        "fg": "#fff",
        "name": {
            "en": "Blue Line",
            "zh-Hans": "蓝线",
            "zh-Hant": "藍線"
        }
    },
    {
        "id": "cyan",
        "colour": "#00bfff",
        "fg": "#fff",
        "name": {
            "en": "Cyan Line",
            "zh-Hans": "青线",
            "zh-Hant": "青線"
        }
    },
    {
        "id": "foguangshan",
        "colour": "#aa34c0",
        "fg": "#fff",
        "name": {
            "en": "Foguangshan Line",
            "zh-Hans": "佛光山线",
            "zh-Hant": "佛光山線"
        }
    },
    {
        "id": "purple",
        "colour": "#c100ff",
        "fg": "#fff",
        "name": {
            "en": "Purple Line",
            "zh-Hans": "紫线",
            "zh-Hant": "紫線"
        }
    },
    {
        "id": "yh",
        "colour": "#008583",
        "fg": "#fff",
        "name": {
            "en": "Youchang Line",
            "zh-Hans": "右昌线",
            "zh-Hant": "右昌線"
        }
    },
    {
        "id": "pink",
        "colour": "#FFC0CB",
        "fg": "#fff",
        "name": {
            "en": "Pink Line",
            "zh-Hans": "粉红线",
            "zh-Hant": "粉紅線"
        }
    },
    {
        "id": "tra",
        "colour": "#0008bd",
        "fg": "#fff",
        "name": {
            "en": "TRA",
            "zh-Hans": "台湾铁路",
            "zh-Hant": "台灣鐵路"
        }
    },
    {
        "id": "黃線",
        "colour": "#ffc200",
        "fg": "#fff",
        "name": {
            "zh": "黃線",
            "en": "Yellow Line"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @Benson20110806 ,

閣下所提供的路線圖為私人製作，我們不能確認於此圖上所取得之顏色的準確性。當前的高雄捷運顏色來自[https://zh.wikipedia.org/wiki/Template:高雄捷運顏色](https://zh.wikipedia.org/wiki/Template:高雄捷運顏色)，閣下可參考該頁面重新提交。多謝！

**Comment by Benson20110806** [comment]
您好，我已使用#500重新提交，謝謝

**Comment by 52PD** [comment]
Closed as the new updated version is issued in #500 .
