### ISSUE TITLE
Resources: New palettes of Shijiazhuang

### ISSUE THREAD

**Issue by RedLeaf007** [railmapgen/rmg-palette#489]
**Reference link:** ~https://baike.baidu.com/item/%E7%9F%B3%E5%AE%B6%E5%BA%84%E5%9C%B0%E9%93%81~ https://zh.wikipedia.org/wiki/Template:%E7%9F%B3%E5%AE%B6%E5%BA%84%E5%9C%B0%E9%93%81%E9%A2%9C%E8%89%B2 

**Justification:** ~线路颜色取自百科图片。~ wiki现有资料

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shijiazhuang",
    "country": "CN",
    "name": {
        "en": "Shijiazhuang",
        "zh-Hans": "石家庄"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sjz1",
        "colour": "#e53e30",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线"
        }
    },
    {
        "id": "sjz2",
        "colour": "#fec30a",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线"
        }
    },
    {
        "id": "sjz3",
        "colour": "#00a1e0",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，由于考虑到百度百科上所提供颜色大多是时候都不准确，很抱歉我们不接受来自百度百科的颜色的来源。

目前我们只接受来自维基百科或者该城市/地区轨道交通官网上的颜色来源。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by RedLeaf007** [comment]
好吧，目前石家庄4、5、6号线并没有正式的主题色，维基也没有相关信息
维基现有资料只有1、2、3号线
我知道情况了，后续重新制作模板。




---Original---
From: ***@***.***&gt;
Date: Tue, Apr 25, 2023 00:17 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [railmapgen/rmg-palette] Resources: New palettes of Shijiazhuang(Issue #489)




 
您好，由于考虑到百度百科上所提供颜色大多是时候都不准确，很抱歉我们不接受来自百度百科的颜色的来源。
 
目前我们只接受来自维基百科或者该城市/地区轨道交通官网上的颜色来源。
 
（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by 52PD** [comment]
> 我知道情况了，后续重新制作模板。

哦对了，补充一点：关于颜色模版只要不修改城市信息的话是可以直接在本issue中补交的。

**Comment by RedLeaf007** [comment]
wiki现有资料（来源：https://zh.wikipedia.org/wiki/Template:%E7%9F%B3%E5%AE%B6%E5%BA%84%E5%9C%B0%E9%93%81%E9%A2%9C%E8%89%B2）
1号线 #e53e30
2号线 #fec30a
3号线 #00a1e0
