### ISSUE TITLE
Resources: New palettes of Shanghai

### ISSUE THREAD

**Issue by aaronyz2007** [railmapgen/rmg-palette#498]
Hi RMG team! I would like to contribute the palettes below.

**Reference link:** https://zh.wikipedia.org/ https://baike.baidu.com/

**Justification:** 新增线路均已于上海地铁三期规划，临港新片区规划中被审批通过，除19号线预计于今年开工，其他线路均已开工建设，临港新片区T1，T2已投入运营
（参考链接为各新增线路对应词条）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shanghai",
    "country": "CN",
    "name": {
        "en": "Shanghai",
        "zh": "上海"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sh1",
        "colour": "#E3002B",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "sh2",
        "colour": "#8CC220",
        "fg": "#000",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "sh3",
        "colour": "#FCD600",
        "fg": "#000",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "sh4",
        "colour": "#461D84",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "sh5",
        "colour": "#944D9A",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "sh6",
        "colour": "#D40068",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "sh7",
        "colour": "#ED6F00",
        "fg": "#000",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "sh8",
        "colour": "#0094D8",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "sh9",
        "colour": "#87CAED",
        "fg": "#000",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "sh10",
        "colour": "#C6AFD4",
        "fg": "#000",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "sh11",
        "colour": "#871C2B",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "sh12",
        "colour": "#007B61",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "sh13",
        "colour": "#E999C0",
        "fg": "#000",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "sh14",
        "colour": "#626020",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "sh15",
        "colour": "#BCA886",
        "fg": "#000",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "sh16",
        "colour": "#98D1C0",
        "fg": "#000",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "sh17",
        "colour": "#BC796F",
        "fg": "#fff",
        "name": {
            "en": "Line 17",
            "zh-Hans": "17号线",
            "zh-Hant": "17號線"
        }
    },
    {
        "id": "sh18",
        "colour": "#C4984F",
        "fg": "#000",
        "name": {
            "en": "Line 18",
            "zh-Hans": "18号线",
            "zh-Hant": "18號線"
        }
    },
    {
        "id": "sh19",
        "colour": "#48864D",
        "fg": "#fff",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线",
            "zh-Hant": "19號線"
        }
    },
    {
        "id": "sh20",
        "colour": "#365299",
        "fg": "#fff",
        "name": {
            "en": "Line 20",
            "zh-Hans": "20号线",
            "zh-Hant": "20號線"
        }
    },
    {
        "id": "sh21",
        "colour": "#D6C66C",
        "fg": "#000",
        "name": {
            "en": "Line 21",
            "zh-Hans": "21号线",
            "zh-Hant": "21號線"
        }
    },
    {
        "id": "sh23",
        "colour": "#E0815E",
        "fg": "#fff",
        "name": {
            "en": "Line 23",
            "zh-Hans": "23号线",
            "zh-Hant": "23號線"
        }
    },
    {
        "id": "pjl",
        "colour": "#B5B5B6",
        "fg": "#fff",
        "name": {
            "en": "Pujiang Line",
            "zh-Hans": "浦江线",
            "zh-Hant": "浦江線"
        }
    },
    {
        "id": "t1",
        "colour": "#FF0000",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T1",
            "zh-Hans": "松江有轨电车1号线",
            "zh-Hant": "松江有軌電車1號線"
        }
    },
    {
        "id": "t2",
        "colour": "#46837B",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T2",
            "zh-Hans": "松江有轨电车2号线",
            "zh-Hant": "松江有軌電車2號線"
        }
    },
    {
        "id": "t3",
        "colour": "#009400",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T3",
            "zh-Hans": "松江有轨电车3号线",
            "zh-Hant": "松江有軌電車3號線"
        }
    },
    {
        "id": "t4",
        "colour": "#FF00FF",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T4",
            "zh-Hans": "松江有轨电车4号线",
            "zh-Hant": "松江有軌電車4號線"
        }
    },
    {
        "id": "t5",
        "colour": "#00FD00",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T5",
            "zh-Hans": "松江有轨电车5号线",
            "zh-Hant": "松江有軌電車5號線"
        }
    },
    {
        "id": "t6",
        "colour": "#6E00DD",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T6",
            "zh-Hans": "松江有轨电车6号线",
            "zh-Hant": "松江有軌電車6號線"
        }
    },
    {
        "id": "maglev",
        "colour": "#009090",
        "fg": "#fff",
        "name": {
            "en": "Shanghai Maglev Train",
            "zh-Hans": "磁浮线",
            "zh-Hant": "磁浮線"
        }
    },
    {
        "id": "jsr",
        "colour": "#000000",
        "fg": "#fff",
        "name": {
            "zh": "金山铁路",
            "en": "Jinshan Railway"
        }
    },
    {
        "id": "airport",
        "colour": "#266883",
        "fg": "#fff",
        "name": {
            "en": "Airport Link Line",
            "zh-Hans": "机场联络线",
            "zh-Hant": "機場聯絡線"
        }
    },
    {
        "id": "jiamin",
        "colour": "#733C54",
        "fg": "#fff",
        "name": {
            "en": "Jiamin Line",
            "zh-Hans": "嘉闵线",
            "zh-Hant": "嘉閔線"
        }
    },
    {
        "id": "chongming",
        "colour": "#6BB392",
        "fg": "#000",
        "name": {
            "en": "Chongming Line",
            "zh-Hans": "崇明线",
            "zh-Hant": "崇明線"
        }
    }
]</details>

**Comment by aaronyz2007** [comment]
You can find all the standard colors of the metro lines in the baidu baike pages of them, and the standard colors of Lingang Tram in the wikipedia page of Shanghai Lingang Tram (https://zh.wikipedia.org/wiki/%E4%B8%B4%E6%B8%AF%E6%96%B0%E7%89%87%E5%8C%BA%E4%B8%AD%E8%BF%90%E9%87%8F%E7%B3%BB%E7%BB%9F)

**Comment by 52PD** [comment]
您好，经检查，19/20/21/23号线、机场联络线、嘉闵线和崇明线的线路颜色与维基百科上所给颜色并不相符，此外维基百科上并未提供临港新片区中运量系统各线路颜色。

如上述上海地铁线路颜色均取自百度百科的话请考虑重新在维基百科或者上海地铁官网取色，考虑到百度百科的低可靠性我们是不接受来自百度百科的轨道交通线路颜色的。

此外，请提供一份包含临港新片区中运量系统线路颜色的官方来源。如无法提供相关来源的话我们将在最终汇入时删除这一部分颜色内容，谢谢。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by aaronyz2007** [comment]
基于维基百科的重新取色结果如下
19号线 #48864D
20号线 #365299
21号线 #D6C66C
23号线 #E0815E
机场联络线 #266883
嘉闵线 #733C54
崇明线 #6BB392

临港新片区中运量各线路颜色系基于维基百科页面线路图取色，经确认为画者自拟，无官方配色，可删除

**Comment by aaronyz2007** [comment]
基于上海地铁官方微博的重新取色结果如下（官博发的各线路路线图画质较低，取色结果可能稍有误差，取色时以尽量取到最标准的颜色）
20号线 #3E5A96
21号线 #D4CA86
23号线 #F09371

基于维基百科的重新取色结果如下
19号线 #48864D
机场联络线 #266883
嘉闵线 #733C54
崇明线 #6BB392

临港新片区中运量各线路颜色系基于维基百科页面线路图取色，经确认为画者自拟，无官方配色，可删除

**Comment by aaronyz2007** [comment]
官方微博取色结果来自以下三条微博
https://weibo.com/1742987497/MuwUFDv64 （20号线）
https://weibo.com/1742987497/LBVIiiX5W （21号线）
https://weibo.com/1742987497/Ma8N8cOck （23号线）

**Comment by 52PD** [comment]
> 19号线 #48864D
> 机场联络线 #266883
> 嘉闵线 #733C54
> 崇明线 #6BB392

以上线路经查阅已经没有问题，但20/21/23号线考虑到维基百科已经给出相关配色，加之您提及官方微博路线图画质过低，为了保证线路颜色来源统一以及准确性我们汇入时这三条线路将改为维基百科所给颜色（20号线为`#365299`，21号线为`#D6C66C`，23号线为`#E0815E`）

> 临港新片区中运量各线路颜色系基于维基百科页面线路图取色，经确认为画者自拟，无官方配色，可删除

好的，在汇入项目时我们会删除这一部分内容。
