### ISSUE TITLE
Resources: New palettes of Kaosiung

### ISSUE THREAD

**Issue by Benson20110806** [railmapgen/rmg-palette#500]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://translate.google.com/?hl=zh-TW&sl=zh-TW&tl=ko&text=%E7%B4%85%E7%B7%9A&op=translate

**Justification:** 調色盤沒有高雄捷運

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "Kaosiung",
    "country": "TW",
    "name": {
        "en": "Kaosiung",
        "zh-Hans": "高雄",
        "zh-Hant": "高雄",
        "ko": "가오슝"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "R",
        "colour": "#e20b65",
        "fg": "#000",
        "name": {
            "en": "Red Line",
            "zh-Hans": "紅線",
            "zh-Hant": "紅線",
            "ko": "레드 라인"
        }
    },
    {
        "id": "O",
        "colour": "#faa73f",
        "fg": "#000",
        "name": {
            "en": "Orange Line",
            "zh-Hans": "橘線",
            "zh-Hant": "橘線"
        }
    },
    {
        "id": "C",
        "colour": "#7cbd52",
        "fg": "#000",
        "name": {
            "en": "Circular Line",
            "zh-Hans": "環狀輕軌",
            "zh-Hant": "環狀輕軌"
        }
    },
    {
        "id": "Y",
        "colour": "#ffc100",
        "fg": "#000",
        "name": {
            "en": "Yellow Line",
            "zh-Hans": "黃線",
            "zh-Hant": "黃線"
        }
    },
    {
        "id": "P",
        "colour": "#c100ff",
        "fg": "#fff",
        "name": {
            "en": "Purple Line",
            "zh-Hans": "紫線",
            "zh-Hant": "紫線"
        }
    },
    {
        "id": "Q",
        "colour": "#e20b65",
        "fg": "#fff",
        "name": {
            "en": "Qijing Line",
            "zh-Hans": "旗津線",
            "zh-Hant": "旗津線"
        }
    },
    {
        "id": "S",
        "colour": "#929292",
        "fg": "#fff",
        "name": {
            "en": "Sliver Line",
            "zh-Hans": "銀線",
            "zh-Hant": "銀線"
        }
    },
    {
        "id": "Pink",
        "colour": "#ffc0cb",
        "fg": "#fff",
        "name": {
            "en": "Pink Line",
            "zh-Hans": "粉線",
            "zh-Hant": "粉線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，您所提供的线路颜色来源为无效来源（该来源指向谷歌翻译页面而不是线路颜色来源）。

请您提供一份正确的线路颜色来源，谢谢。

（请您在收到本条消息后尽快及时回复，超过一个月未回复的问题稿件我们将会直接拒绝汇入）

**Comment by Benson20110806** [comment]
抱歉，該來源應修改為
https://zh.wikipedia.org/zh-tw/Template:%E9%AB%98%E9%9B%84%E6%8D%B7%E9%81%8B%E9%A1%8F%E8%89%B2
