### ISSUE TITLE
Resources: New palettes of Changzhou

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmg-palette#516]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://en.m.wikipedia.org/wiki/Changzhou_Metro

**Justification:** 增加常州palette，颜色来源于英文维基百科

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "changzhou",
    "country": "CN",
    "name": {
        "en": "Changzhou",
        "ko": "창저우",
        "zh-Hans": "常州",
        "zh-Hant": "常州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "cz1",
        "colour": "#cd5c5c",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "ko": "1호선",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "cz2",
        "colour": "#529fc9",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "ko": "2호선",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    }
]</details>

**Comment by langonginc** [comment]
您好，我从您给出的链接找到的颜色与您提交的并不相同，建议您检查一下。

| Wikipedia | 您的 |
| :----: | :----: |
| `#cd5c5c` | `#bf635f` |
| `#529fc9` | `#659dc5` |

**Comment by 28yfang** [comment]
可能是提取颜色的时候出现了误差
顺便问一下，这个hex color的这六个字母是从哪儿找到的？

**Comment by wongchito** [comment]
維基百科顏色應用通常來自於模塊（Module），以閣下提供的英文版詞條作例子，對應的模塊為：https://en.wikipedia.org/wiki/Module:Adjacent_stations/Changzhou_Metro
