### ISSUE TITLE
【线路颜色】渥太华轻轨线路颜色

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmg-palette#52]
[Ottawa O-Train Color Palette.txt](https://github.com/railmapgen/rmg-palette/files/8735756/Ottawa.O-Train.Color.Palette.txt)

关于里面没开通的3/4号线，既然之前之前@wongchito 在##44 说过未开通线路的颜色还是会照样加入颜色库中的，这里我就连着这两条线的颜色一起写进去了

至于这次由于渥太华轻轨的线路目前状况比较混乱（2001年开通的延龄草线（现2号线）自从2020年关闭扩能改造后基本相当于把原有线路拆了重建（到现在还没建好），这里我就算成未开通线路了。再加上3、4号线同样未开通，事实上现在正在运营的只有2019年开通的1号线），我就不打算写线路模版了

**Comment by linchen1965** [comment]
其实我也没太看懂 #45 那个操作……

**Comment by thekingofcity** [comment]
额就是说按照新模板填的话，我们只用点一下merge的按钮就行了，不需要手动复制黏贴进代码了。

**Comment by 52PD** [comment]
> 额就是说按照新模板填标题和内容的话，我们只用点一下merge的按钮就行了，不需要手动复制黏贴进代码了。

哦哦哦，这种啊。确实这样会轻松得多

**Comment by linchen1965** [comment]
> > 额就是说按照新模板填标题和内容的话，我们只用点一下merge的按钮就行了，不需要手动复制黏贴进代码了。
> 
> 哦哦哦，这种啊。确实这样会轻松得多

还是没明白是什么意思……merge的按钮是什么？

**Comment by wongchito** [comment]
> > > 额就是说按照新模板填标题和内容的话，我们只用点一下merge的按钮就行了，不需要手动复制黏贴进代码了。
> > 
> > 
> > 哦哦哦，这种啊。确实这样会轻松得多
> 
> 还是没明白是什么意思……merge的按钮是什么？

等我將前端完成，屆時大家就會知道如何快捷提交顏色😂

**Comment by linchen1965** [comment]
> > > > 额就是说按照新模板填标题和内容的话，我们只用点一下merge的按钮就行了，不需要手动复制黏贴进代码了。
> > > 
> > > 
> > > 哦哦哦，这种啊。确实这样会轻松得多
> > 
> > 
> > 还是没明白是什么意思……merge的按钮是什么？
> 
> 等我將前端完成，屆時大家就會知道如何快捷提交顏色😂

既然如此的话那还是麻烦大家把https://github.com/railmapgen/rmg-palette/issues/45的模板加入了。另外我在更新过后的RMG发现郑州9号线的名称变了，我个人感觉可以像西安14号线那样对该线路命名为9号线（城郊线）

**Comment by linchen1965** [comment]
> > > > 额就是说按照新模板填标题和内容的话，我们只用点一下merge的按钮就行了，不需要手动复制黏贴进代码了。
> > > 
> > > 
> > > 哦哦哦，这种啊。确实这样会轻松得多
> > 
> > 
> > 还是没明白是什么意思……merge的按钮是什么？
> 
> 等我將前端完成，屆時大家就會知道如何快捷提交顏色😂

既然如此的话那还是麻烦大家把#45 的模板上传了。
话说回来，郑州9号线的名称是不是应该叫做“9号线（城郊线）”，毕竟这条线路只是暂时叫做城郊线，本质上还是9号线的一部分。
