### ISSUE TITLE
Resources: New palettes of Xi'an

### ISSUE THREAD

**Issue by LittleLing03** [railmapgen/rmg-palette#538]
**Reference link:** https://www.xianrail.com/#/index

**Justification:** 4号线

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "xian",
    "country": "CN",
    "name": {
        "en": "Xi'an",
        "zh": "西安"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "xa1",
        "colour": "#0077C8",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "xa2",
        "colour": "#EF3340",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "xa3",
        "colour": "#CE70CC",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "xa4",
        "colour": "#02af8e",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "xa5",
        "colour": "#A6E35F",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "xa6",
        "colour": "#485CC7",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "xa8",
        "colour": "#FFE400",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "xa9",
        "colour": "#FF9E1B",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "xa11",
        "colour": "#006400",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "xa14",
        "colour": "#00C1D4",
        "fg": "#fff",
        "name": {
            "en": "Airport Intercity Railway/Line 14",
            "zh-Hans": "机场城际/14号线",
            "zh-Hant": "機場城際/14號線"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @LittleLing03 ,

我們透過閣下提供的連結了解到，4號線的官方顏色與調色盤所收錄的顏色有出入。惟我們無法從其網站內找到合適的顏色代碼（均為低畫質圖像），因此我們無法核實閣下所提供的代碼是否準確。

如閣下認為我們遺漏了含有高畫質圖像或顏色代碼的頁面，請向我們提出。多謝！

Cc: @52PD @linchen1965
