### ISSUE TITLE
Resources: New palettes of Guangzhou

### ISSUE THREAD

**Issue by njrapidity** [railmapgen/rmg-palette#540]
**Reference link:** https://upload.wikimedia.org/wikipedia/commons/6/6f/%E7%8F%A0%E6%B1%9F%E4%B8%89%E8%A7%92%E6%B4%B2%E5%9C%B0%E5%8C%BA%E5%9F%8E%E9%99%85%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A%E7%BD%91%E7%A4%BA%E6%84%8F%E5%9B%BE.png

**Justification:** 我想画珠三角 广东城际与深圳城际营运的线路。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "guangzhou",
    "country": "CN",
    "name": {
        "en": "Guangzhou",
        "zh-Hans": "广州",
        "zh-Hant": "廣州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "PRDIR GFE",
        "colour": "#00b03c",
        "fg": "#fff",
        "name": {
            "en": "Guangzhou East Ring Intercity",
            "ko": "",
            "zh-Hans": "广州东环城际",
            "zh-Hant": ""
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，由于您在提交新的线路颜色时错误删除了该城市颜色库中现有线路的颜色，因此很抱歉我们无法接受您的投稿。
