### ISSUE TITLE
Resources: New palettes of Shenyang

### ISSUE THREAD

**Issue by moodylitchee** [railmapgen/rmg-palette#544]
**Reference link:** https://jump2.bdimg.com/p/8434262900

**Justification:** 更新城市地铁线路颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shenyang",
    "country": "CN",
    "name": {
        "en": "Shenyang",
        "zh-Hans": "沈阳",
        "zh-Hant": "瀋陽"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sy1",
        "colour": "#b63f1f",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "sy2",
        "colour": "#e5703a",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "sy3",
        "colour": "#E6669F",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "sy4",
        "colour": "#6E3E94",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "sy6",
        "colour": "#FEDC00",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "sy9",
        "colour": "#017cbf",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "sy10",
        "colour": "#62aa3c",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "sy5",
        "colour": "#8f2714",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "sy8",
        "colour": "#d322d3",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "sy7",
        "colour": "#119715",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "sy13",
        "colour": "#a4ae24",
        "fg": "#fff",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "sy15",
        "colour": "#2c5615",
        "fg": "#fff",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "syk1",
        "colour": "#119aac",
        "fg": "#fff",
        "name": {
            "en": "Line K1",
            "zh-Hans": "K1号线",
            "zh-Hant": "K1號線"
        }
    },
    {
        "id": "sy16",
        "colour": "#ac2a3d",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "syk2",
        "colour": "#113fac",
        "fg": "#fff",
        "name": {
            "en": "Line K2",
            "zh-Hans": "K2号线",
            "zh-Hant": "K2號線"
        }
    },
    {
        "id": "sys",
        "colour": "#930fc2",
        "fg": "#fff",
        "name": {
            "en": "City Rail",
            "zh-Hans": "市郊铁路"
        }
    }
]</details>

**Comment by langonginc** [comment]
很抱歉，我们不接受非官方的内容（而且我无法通过您给出的链接找到与您提交的颜色相关的内容），感谢您的贡献。

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色来源无效后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
