### ISSUE TITLE
Resources: New palettes of Brisbane

### ISSUE THREAD

**Issue by Jimmilily** [railmapgen/rmg-palette#546]
**Reference link:** https://translink.widen.net/s/mzbn7bvkvb/220531-train-busway-tram-network-map

**Justification:** 添加澳大利亚（国家）- 布里斯班（城市）的调色板，该城市公共交通由州政府与Translink公司共同运营

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "AU",
    "name": {
        "en": "Australia",
        "ko": "호주",
        "zh-Hans": "澳大利亚",
        "zh-Hant": "澳大利亞"
    },
    "language": "en"
}</details>

<details repo="rmg-palette" type="city">{
    "id": "BNE",
    "country": "AU",
    "name": {
        "en": "Brisbane",
        "ko": "브리즈번",
        "zh-Hans": "布里斯班",
        "zh-Hant": "布里斯班"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "fgbn",
        "colour": "#cf202f",
        "fg": "#fff",
        "name": {
            "en": "Ferny Grove and Beenleigh lines",
            "ko": "패니 그로브와 벤틀리 라인",
            "zh-Hans": "芬妮戈洛夫与宾利线",
            "zh-Hant": "芬妮戈洛夫與賓利線"
        }
    },
    {
        "id": "shcl",
        "colour": "#00467f",
        "fg": "#fff",
        "name": {
            "en": "Shorncliffe and Cleveland lines",
            "ko": "션 클리프와 클리블랜드 라인",
            "zh-Hans": "硕恩克里弗与克利夫兰线",
            "zh-Hant": "碩恩克里弗與克利夫蘭線"
        }
    },
    {
        "id": "bdvl",
        "colour": "#ffc425",
        "fg": "#fff",
        "name": {
            "en": "Airport and Gold Coast lines",
            "ko": "공항과 골드코스트",
            "zh-Hans": "机场与黄金海岸线",
            "zh-Hant": "機場與黃金海岸線"
        }
    },
    {
        "id": "gyrw",
        "colour": "#008752",
        "fg": "#fff",
        "name": {
            "en": "Caboolture/Sunshine Coast and Ipswich/Rosewood lines",
            "ko": "카포체/선샤인 코스트 및 입스위치/로즈우드 라인",
            "zh-Hans": "卡波彻/阳光海岸与伊普斯维奇/罗斯伍德线",
            "zh-Hant": "卡波徹/陽光海岸與伊普斯維奇/羅斯伍德線"
        }
    },
    {
        "id": "rpsp",
        "colour": "#1278be",
        "fg": "#fff",
        "name": {
            "en": "Redcliffe Peninsula and Springfield lines",
            "ko": "레드클리프 페닌슐라와 스프링필드 라인",
            "zh-Hans": "雷德克里弗半岛与斯普林菲尔德线",
            "zh-Hant": "雷德克里弗半島與斯普林菲爾德線"
        }
    },
    {
        "id": "dbbr",
        "colour": "#a54399",
        "fg": "#fff",
        "name": {
            "en": "Doomben line",
            "ko": "돔 본선",
            "zh-Hans": "多姆本线",
            "zh-Hant": "多姆本線"
        }
    },
    {
        "id": "sp",
        "colour": "#47626f",
        "fg": "#fff",
        "name": {
            "en": "Special event service only",
            "ko": "특별 행사 기간에만 운영",
            "zh-Hans": "仅特殊活动期间运营",
            "zh-Hant": "僅特殊活動期間運營"
        }
    },
    {
        "id": "bb",
        "colour": "#e8891d",
        "fg": "#fff",
        "name": {
            "en": "Busway lines",
            "ko": "BRT 도로",
            "zh-Hans": "快速公交道路",
            "zh-Hant": "快速公交道路"
        }
    },
    {
        "id": "glks",
        "colour": "#ffdb1e",
        "fg": "#fff",
        "name": {
            "en": "G:link Tram",
            "ko": "골드 코스트 트램",
            "zh-Hans": "黄金海岸有轨电车",
            "zh-Hant": "黃金海岸有軌電車"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，经检查我们发现以下问题：

- 您所提供的各铁路颜色与所提供来源不匹配且色差略大。
  - “芬妮戈洛夫与宾利线”来源中的颜色：``#BC2532``；您所提供的颜色``#cf202f``
  - “硕恩克里弗与克利夫兰线”来源中的颜色：``#003C68``；您所提供的颜色``#00467f``
  - “机场与黄金海岸线”来源中的颜色：``#F6BF35``；您所提供的颜色``#ffc425``
  - “卡波彻/阳光海岸与伊普斯维奇/罗斯伍德线”来源中的颜色：``#007C4C``；您所提供的颜色``#008752``
  - “雷德克里弗半岛与斯普林菲尔德线”来源中的颜色：``#256DA8``；您所提供的颜色``#1278be``
  - “多姆本线”来源中的颜色：``#964088``；您所提供的颜色``#a54399``
  - “仅特殊活动期间运营”来源中的颜色：``#435860``；您所提供的颜色``#47626f``
  - “快速公交道路”来源中的颜色：``#DD822C``；您所提供的颜色``#e8891d``
  - “黄金海岸有轨电车”来源中的颜色：``#F9C822``；您所提供的颜色``#ffdb1e``
  
  下图为两组颜色的色差对比，其中图左为来源颜色，图右为您所提供颜色：
![color compare](https://github.com/railmapgen/rmg-palette/assets/98044618/1b42ef9f-10f2-4546-afc5-a37b67554a90)

请您修正后将正确的线路颜色提交至此issue下，我们将在检查并确认无误后将其写入将汇入程序的代码中。感谢您的贡献。

**Comment by Jimmilily** [comment]
您好，经考虑后我决定切换到并优先使用官网主页线路颜色（可直接由html提取），地址：https://translink.com.au/
改动后线路颜色如下：

- “芬妮戈洛夫与宾利线”：`#e31837`

- “硕恩克里弗与克利夫兰线”：`#00467f`

- “机场与黄金海岸线”：`#ffc425`

- “卡波彻/阳光海岸与伊普斯维奇/罗斯伍德线”：`#008752`

- “雷德克里弗半岛与斯普林菲尔德线”：`#1578be`

- “多姆本线”：`#a54399`

以下线路颜色不存在于除线路图外的任何页面中，将采用您建议的方案：

- “仅特殊活动期间运营”：`#435860`

- “快速公交道路”：`#dd822c`

- “黄金海岸有轨电车”：`#f9c822`

以下是修改后的代码：

[ { "id": "fgbn", "colour": "#e31837", "fg": "#fff", "name": { "en": "Ferny Grove and Beenleigh lines", "ko": "패니 그로브와 벤틀리 라인", "zh-Hans": "芬妮戈洛夫与宾利线", "zh-Hant": "芬妮戈洛夫與賓利線" } }, { "id": "shcl", "colour": "#00467f", "fg": "#fff", "name": { "en": "Shorncliffe and Cleveland lines", "ko": "션 클리프와 클리블랜드 라인", "zh-Hans": "硕恩克里弗与克利夫兰线", "zh-Hant": "碩恩克里弗與克利夫蘭線" } }, { "id": "bdvl", "colour": "#ffc425", "fg": "#fff", "name": { "en": "Airport and Gold Coast lines", "ko": "공항과 골드코스트", "zh-Hans": "机场与黄金海岸线", "zh-Hant": "機場與黃金海岸線" } }, { "id": "gyrw", "colour": "#008752", "fg": "#fff", "name": { "en": "Caboolture/Sunshine Coast and Ipswich/Rosewood lines", "ko": "카포체/선샤인 코스트 및 입스위치/로즈우드 라인", "zh-Hans": "卡波彻/阳光海岸与伊普斯维奇/罗斯伍德线", "zh-Hant": "卡波徹/陽光海岸與伊普斯維奇/羅斯伍德線" } }, { "id": "rpsp", "colour": "#1578be", "fg": "#fff", "name": { "en": "Redcliffe Peninsula and Springfield lines", "ko": "레드클리프 페닌슐라와 스프링필드 라인", "zh-Hans": "雷德克里弗半岛与斯普林菲尔德线", "zh-Hant": "雷德克里弗半島與斯普林菲爾德線" } }, { "id": "dbbr", "colour": "#a54399", "fg": "#fff", "name": { "en": "Doomben line", "ko": "돔 본선", "zh-Hans": "多姆本线", "zh-Hant": "多姆本線" } }, { "id": "sp", "colour": "#435860", "fg": "#fff", "name": { "en": "Special event service only", "ko": "특별 행사 기간에만 운영", "zh-Hans": "仅特殊活动期间运营", "zh-Hant": "僅特殊活動期間運營" } }, { "id": "bb", "colour": "#dd822c", "fg": "#fff", "name": { "en": "Busway lines", "ko": "BRT 도로", "zh-Hans": "快速公交道路", "zh-Hant": "快速公交道路" } }, { "id": "glks", "colour": "#f9c822", "fg": "#fff", "name": { "en": "G:link Tram", "ko": "골드 코스트 트램", "zh-Hans": "黄金海岸有轨电车", "zh-Hant": "黃金海岸有軌電車" } } ]

望考虑并采纳，
Best regards

**Comment by 52PD** [comment]
经检查，所也此前提及的问题均已经修正，我们将会在近期内将其汇入项目中。

感谢您对本项目做出的贡献！
