### ISSUE TITLE
Resources: New palettes of Lanzhou

### ISSUE THREAD

**Issue by 28yfang** [railmapgen/rmg-palette#548]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://en.wikipedia.org/wiki/Lanzhou_Metro

**Justification:** 增加兰州地铁1号线（已开通）和2～5号线（未开通）palette

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "lanzhou",
    "country": "CN",
    "name": {
        "en": "Lanzhou",
        "ko": "란저우",
        "zh-Hans": "兰州",
        "zh-Hant": "蘭州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "lz1",
        "colour": "#0080bc",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "ko": "1호선",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "lz2",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "ko": "2호선",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "lz3",
        "colour": "#8b4513",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "ko": "3호선",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "lz4",
        "colour": "#008000",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "ko": "4호선",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "lz5",
        "colour": "#c71585",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "ko": "5호선",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @28yfang ,

中文維基[Templates:蘭州軌道交通顏色](https://zh.wikipedia.org/wiki/Templates:兰州轨道交通颜色)收錄了規劃中的3、4及5號線，建議閣下一併加入。多謝！
