### ISSUE TITLE
Resources: New palettes of Sydney

### ISSUE THREAD

**Issue by Jimmilily** [railmapgen/rmg-palette#560]
Hi RMG team! I would like to contribute the palettes below.

**Reference link:** https://transportnsw.info/routes/train

**Justification:** 新增城市：悉尼
新增线路：41条（市域铁路8，地铁1，城际铁路5，轮渡23，轻轨4）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "sydney",
    "country": "AU",
    "name": {
        "en": "Sydney",
        "zh-Hans": "悉尼",
        "zh-Hant": "雪梨"
    }
}</details>

<details repo="rmg-palette" type="lines">
[ { "id": "syd1", "colour": "#f99d1c", "fg": "#fff", "name": { "en": "T1 - North Shore & Western Line", "zh-Hans": "T1 - 北海滩与西部线", "zh-Hant": "T1 - 北岸及西線" } }, { "id": "syd2", "colour": "#0098cd", "fg": "#fff", "name": { "en": "T2 - Inner West & Leppington Line", "zh-Hans": "T2 - 中西部与雷平顿线", "zh-Hant": "T2 - 中西部與雷平頓線" } }, { "id": "syd3", "colour": "#f37021", "fg": "#fff", "name": { "en": "T3 - Bankstown Line", "zh-Hans": "T3 - 班克斯顿线", "zh-Hant": "T3 - 班克斯敦線" } }, { "id": "syd4", "colour": "#005aa3", "fg": "#fff", "name": { "en": "T4 - Eastern Suburbs & Illawarra Line", "zh-Hans": "T4 - 东郊与伊拉瓦拉线", "zh-Hant": "T4 - 東郊和伊拉瓦拉線" } }, { "id": "syd5", "colour": "#c4258f", "fg": "#fff", "name": { "en": "T5 - Cumberland Line", "zh-Hans": "T5 - 坎伯兰线", "zh-Hant": "T5 - 坎伯蘭線" } }, { "id": "syd7", "colour": "#6f818e", "fg": "#fff", "name": { "en": "T7 - Olympic Park Line", "zh-Hans": "T7 - 奥林匹克公园线", "zh-Hant": "T7 - 奧林匹克公園線" } }, { "id": "syd8", "colour": "#00954c", "fg": "#fff", "name": { "en": "T8 - Airport & South Line", "zh-Hans": "T8 - 机场与南部线", "zh-Hant": "T8 - 機場南線" } }, { "id": "syd9", "colour": "#d11f2f", "fg": "#fff", "name": { "en": "T9 - Northern Line test", "zh-Hans": "T9 - 北部线（测试中）", "zh-Hant": "T9 - 北線測試" } }, { "id": "sydm", "colour": "#168388", "fg": "#fff", "name": { "en": "Metro North West Line", "zh-Hans": "地铁西北线", "zh-Hant": "地鐵西北線" } }, { "id": "bmt", "colour": "#f99d1c", "fg": "#fff", "name": { "en": "Blue Mountains Line", "zh-Hans": "蓝山线", "zh-Hant": "藍山線" } }, { "id": "ccn", "colour": "#d11f2f", "fg": "#fff", "name": { "en": "Central Cost & Newcastle Line", "zh-Hans": "中部海岸与纽卡斯尔线", "zh-Hant": "中央海岸和紐卡斯爾線" } }, { "id": "hun", "colour": "#833134", "fg": "#fff", "name": { "en": "Hunter Line", "zh-Hans": "亨特线", "zh-Hant": "亨特線" } }, { "id": "sco", "colour": "#005aa3", "fg": "#fff", "name": { "en": "South Coast Line", "zh-Hans": "南部海岸线", "zh-Hant": "南海岸線" } }, { "id": "shl", "colour": "#00954c", "fg": "#fff", "name": { "en": "Southern Highlands Line", "zh-Hans": "南部高地线", "zh-Hant": "南部高地線" } }, { "id": "syf1", "colour": "#00774b", "fg": "#fff", "name": { "en": "F1 - Manly", "zh-Hans": "F1 - 曼利轮渡", "zh-Hant": "F1 - 曼利渡輪" } }, { "id": "syf2", "colour": "#144734", "fg": "#fff", "name": { "en": "F2 - Taronga Zoo", "zh-Hans": "F2 - 塔隆加动物园轮渡", "zh-Hant": "F2 - 塔隆加動物園渡輪" } }, { "id": "syf3", "colour": "#648c3c", "fg": "#fff", "name": { "en": "F3 - Parramatta River", "zh-Hans": "F3 - 帕拉玛塔河轮渡", "zh-Hant": "F3 - 帕拉瑪塔河渡輪" } }, { "id": "syf4", "colour": "#bfd730", "fg": "#fff", "name": { "en": "F4 - Pyrmont Bay", "zh-Hans": "F4 - 派尔蒙特湾轮渡", "zh-Hant": "F4 - 派爾蒙特灣渡輪" } }, { "id": "syf5", "colour": "#286142", "fg": "#fff", "name": { "en": "F5 - Neutral Bay", "zh-Hans": "F5 - 纽图尔湾轮渡", "zh-Hant": "F5 - 紐圖爾灣渡輪" } }, { "id": "syf6", "colour": "#00ab51", "fg": "#fff", "name": { "en": "F6 - Mosman Bay", "zh-Hans": "F6 - 莫斯曼湾轮渡", "zh-Hant": "F6 - 莫斯曼灣渡輪" } }, { "id": "syf7", "colour": "#00b189", "fg": "#fff", "name": { "en": "F7 - Double Bay", "zh-Hans": "F7 - 双湾轮渡", "zh-Hant": "F7 - 雙灣渡輪" } }, { "id": "syf8", "colour": "#55622b", "fg": "#fff", "name": { "en": "F8 - Cockatoo Island", "zh-Hans": "F8 - 凤头鹦鹉岛轮渡", "zh-Hant": "F8 - 鳳頭鸚鵡島渡輪" } }, { "id": "syf9", "colour": "#65b32e", "fg": "#fff", "name": { "en": "F9 - Watsons Bay", "zh-Hans": "F9 - 沃特森斯湾轮渡", "zh-Hant": "F9 - 沃特森斯灣渡輪" } }, { "id": "syff", "colour": "#5ab031", "fg": "#fff", "name": { "en": "Private Ferry and Fast Ferry Services", "zh-Hans": "私营和快速轮渡服务", "zh-Hant": "私營與快速渡輪服務" } }, { "id": "syl1", "colour": "#be1622", "fg": "#fff", "name": { "en": "L1 - Dulwich Hill Line", "zh-Hans": "L1 - 道尔维奇山轻轨", "zh-Hant": "L1 - 道爾維奇山輕軌" } }, { "id": "syl2", "colour": "#dd1e25", "fg": "#fff", "name": { "en": "L2 - Randwick Line", "zh-Hans": "L2 - 兰德维克轻轨", "zh-Hant": "L2 - 蘭德維克輕軌" } }, { "id": "syl3", "colour": "#781140", "fg": "#fff", "name": { "en": "L3 - Kingsford Line", "zh-Hans": "L3 - 金斯福德轻轨", "zh-Hant": "L3 - 金斯福德輕軌" } }, { "id": "sylx", "colour": "#ee343f", "fg": "#fff", "name": { "en": "LX - Special Event Service", "zh-Hans": "LX - 特殊活动期间轻轨服务", "zh-Hant": "LX - 特殊活動期間輕軌服務" } } ]
</details>

**Comment by wongchito** [comment]
Hi @Jimmilily ,

由於閣下提供的各渡輪路線顏色相同，建議閣下將其合併至一條路線「Ferry/渡輪/轮渡」，以便用戶瀏覽及使用。多謝！

**Comment by Jimmilily** [comment]
Changelog：所有非编号轮渡已合并为一条线路；繁体中文”輪渡“已修正为”渡輪“

<details repo="rmg-palette" type="lines">
[ { "id": "syd1", "colour": "#f99d1c", "fg": "#fff", "name": { "en": "T1 - North Shore & Western Line", "zh-Hans": "T1 - 北海滩与西部线", "zh-Hant": "T1 - 北岸及西線" } }, { "id": "syd2", "colour": "#0098cd", "fg": "#fff", "name": { "en": "T2 - Inner West & Leppington Line", "zh-Hans": "T2 - 中西部与雷平顿线", "zh-Hant": "T2 - 中西部與雷平頓線" } }, { "id": "syd3", "colour": "#f37021", "fg": "#fff", "name": { "en": "T3 - Bankstown Line", "zh-Hans": "T3 - 班克斯顿线", "zh-Hant": "T3 - 班克斯敦線" } }, { "id": "syd4", "colour": "#005aa3", "fg": "#fff", "name": { "en": "T4 - Eastern Suburbs & Illawarra Line", "zh-Hans": "T4 - 东郊与伊拉瓦拉线", "zh-Hant": "T4 - 東郊和伊拉瓦拉線" } }, { "id": "syd5", "colour": "#c4258f", "fg": "#fff", "name": { "en": "T5 - Cumberland Line", "zh-Hans": "T5 - 坎伯兰线", "zh-Hant": "T5 - 坎伯蘭線" } }, { "id": "syd7", "colour": "#6f818e", "fg": "#fff", "name": { "en": "T7 - Olympic Park Line", "zh-Hans": "T7 - 奥林匹克公园线", "zh-Hant": "T7 - 奧林匹克公園線" } }, { "id": "syd8", "colour": "#00954c", "fg": "#fff", "name": { "en": "T8 - Airport & South Line", "zh-Hans": "T8 - 机场与南部线", "zh-Hant": "T8 - 機場南線" } }, { "id": "syd9", "colour": "#d11f2f", "fg": "#fff", "name": { "en": "T9 - Northern Line test", "zh-Hans": "T9 - 北部线（测试中）", "zh-Hant": "T9 - 北線測試" } }, { "id": "sydm", "colour": "#168388", "fg": "#fff", "name": { "en": "Metro North West Line", "zh-Hans": "地铁西北线", "zh-Hant": "地鐵西北線" } }, { "id": "bmt", "colour": "#f99d1c", "fg": "#fff", "name": { "en": "Blue Mountains Line", "zh-Hans": "蓝山线", "zh-Hant": "藍山線" } }, { "id": "ccn", "colour": "#d11f2f", "fg": "#fff", "name": { "en": "Central Cost & Newcastle Line", "zh-Hans": "中部海岸与纽卡斯尔线", "zh-Hant": "中央海岸和紐卡斯爾線" } }, { "id": "hun", "colour": "#833134", "fg": "#fff", "name": { "en": "Hunter Line", "zh-Hans": "亨特线", "zh-Hant": "亨特線" } }, { "id": "sco", "colour": "#005aa3", "fg": "#fff", "name": { "en": "South Coast Line", "zh-Hans": "南部海岸线", "zh-Hant": "南海岸線" } }, { "id": "shl", "colour": "#00954c", "fg": "#fff", "name": { "en": "Southern Highlands Line", "zh-Hans": "南部高地线", "zh-Hant": "南部高地線" } }, { "id": "syf1", "colour": "#00774b", "fg": "#fff", "name": { "en": "F1 - Manly", "zh-Hans": "F1 - 曼利轮渡", "zh-Hant": "F1 - 曼利渡輪" } }, { "id": "syf2", "colour": "#144734", "fg": "#fff", "name": { "en": "F2 - Taronga Zoo", "zh-Hans": "F2 - 塔隆加动物园轮渡", "zh-Hant": "F2 - 塔隆加動物園渡輪" } }, { "id": "syf3", "colour": "#648c3c", "fg": "#fff", "name": { "en": "F3 - Parramatta River", "zh-Hans": "F3 - 帕拉玛塔河轮渡", "zh-Hant": "F3 - 帕拉瑪塔河渡輪" } }, { "id": "syf4", "colour": "#bfd730", "fg": "#fff", "name": { "en": "F4 - Pyrmont Bay", "zh-Hans": "F4 - 派尔蒙特湾轮渡", "zh-Hant": "F4 - 派爾蒙特灣渡輪" } }, { "id": "syf5", "colour": "#286142", "fg": "#fff", "name": { "en": "F5 - Neutral Bay", "zh-Hans": "F5 - 纽图尔湾轮渡", "zh-Hant": "F5 - 紐圖爾灣渡輪" } }, { "id": "syf6", "colour": "#00ab51", "fg": "#fff", "name": { "en": "F6 - Mosman Bay", "zh-Hans": "F6 - 莫斯曼湾轮渡", "zh-Hant": "F6 - 莫斯曼灣渡輪" } }, { "id": "syf7", "colour": "#00b189", "fg": "#fff", "name": { "en": "F7 - Double Bay", "zh-Hans": "F7 - 双湾轮渡", "zh-Hant": "F7 - 雙灣渡輪" } }, { "id": "syf8", "colour": "#55622b", "fg": "#fff", "name": { "en": "F8 - Cockatoo Island", "zh-Hans": "F8 - 凤头鹦鹉岛轮渡", "zh-Hant": "F8 - 鳳頭鸚鵡島渡輪" } }, { "id": "syf9", "colour": "#65b32e", "fg": "#fff", "name": { "en": "F9 - Watsons Bay", "zh-Hans": "F9 - 沃特森斯湾轮渡", "zh-Hant": "F9 - 沃特森斯灣渡輪" } }, { "id": "syff", "colour": "#5ab031", "fg": "#fff", "name": { "en": "Private Ferry and Fast Ferry Services", "zh-Hans": "私营和快速轮渡服务", "zh-Hant": "私營與快速渡輪服務" } }, { "id": "syl1", "colour": "#be1622", "fg": "#fff", "name": { "en": "L1 - Dulwich Hill Line", "zh-Hans": "L1 - 道尔维奇山轻轨", "zh-Hant": "L1 - 道爾維奇山輕軌" } }, { "id": "syl2", "colour": "#dd1e25", "fg": "#fff", "name": { "en": "L2 - Randwick Line", "zh-Hans": "L2 - 兰德维克轻轨", "zh-Hant": "L2 - 蘭德維克輕軌" } }, { "id": "syl3", "colour": "#781140", "fg": "#fff", "name": { "en": "L3 - Kingsford Line", "zh-Hans": "L3 - 金斯福德轻轨", "zh-Hant": "L3 - 金斯福德輕軌" } }, { "id": "sylx", "colour": "#ee343f", "fg": "#fff", "name": { "en": "LX - Special Event Service", "zh-Hans": "LX - 特殊活动期间轻轨服务", "zh-Hant": "LX - 特殊活動期間輕軌服務" } } ]
</details>
