### ISSUE TITLE
Resources: New palettes of Los Angeles

### ISSUE THREAD

**Issue by aaronyz2007** [railmapgen/rmg-palette#567]
**Reference link:** https://www.metro.net/riding/schedules/

**Justification:** 增加洛杉矶轨道交通模板（基于洛杉矶轨道交通官网取色结果）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "losangeles",
    "country": "US",
    "name": {
        "en": "Los Angeles",
        "zh-Hans": "洛杉矶",
        "zh-Hant": "洛杉磯",
        "ko": "로스 앤젤레스"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "laa",
        "colour": "#0072bc",
        "fg": "#fff",
        "name": {
            "en": "A Line",
            "zh-Hans": "A线",
            "zh-Hant": "A線",
            "ko": "A선"
        }
    },
    {
        "id": "lab",
        "colour": "#e3131b",
        "fg": "#fff",
        "name": {
            "en": "B Line",
            "zh-Hans": "B线",
            "zh-Hant": "B線",
            "ko": "B선"
        }
    },
    {
        "id": "lac",
        "colour": "#58a738",
        "fg": "#fff",
        "name": {
            "en": "C Line",
            "zh-Hans": "C线",
            "zh-Hant": "C線",
            "ko": "C선"
        }
    },
    {
        "id": "lad",
        "colour": "#a05da5",
        "fg": "#fff",
        "name": {
            "en": "D Line",
            "zh-Hans": "D线",
            "zh-Hant": "D線",
            "ko": "D선"
        }
    },
    {
        "id": "lae",
        "colour": "#5bc2e7",
        "fg": "#000",
        "name": {
            "en": "E Line",
            "zh-Hans": "E线",
            "zh-Hant": "E線",
            "ko": "E선"
        }
    },
    {
        "id": "lak",
        "colour": "#e96bb0",
        "fg": "#000",
        "name": {
            "en": "K Line",
            "zh-Hans": "K线",
            "zh-Hant": "K線",
            "ko": "K선"
        }
    },
    {
        "id": "lal",
        "colour": "#fdb913",
        "fg": "#000",
        "name": {
            "en": "L Line",
            "zh-Hans": "L线",
            "zh-Hant": "L線",
            "ko": "L선"
        }
    },
    {
        "id": "lag",
        "colour": "#fc4c02",
        "fg": "#fff",
        "name": {
            "en": "G Line",
            "zh-Hans": "快速公交G线",
            "zh-Hant": "快速公交G線",
            "ko": "G선"
        }
    },
    {
        "id": "laj",
        "colour": "#adb8bf",
        "fg": "#000",
        "name": {
            "en": "J Line",
            "zh-Hans": "快速公交J线",
            "zh-Hant": "快速公交J線",
            "ko": "J선"
        }
    }
]</details>

**Comment by 28yfang** [comment]
您好，经检查，您所提供的颜色与官方准确无误。尽情期待审核员通过。感谢您对RMG画廊的贡献！
