### ISSUE TITLE
北京地铁2035

### ISSUE THREAD

**Issue by xiliuxian-01** [railmapgen/rmg-palette#569]
**Reference link:** https://railmapgen.github.io/

**Justification:** 北京地铁2035

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "beijing",
    "country": "CN",
    "name": {
        "en": "Beijing",
        "zh-Hans": "北京",
        "zh-Hant": "北京"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "bj1",
        "colour": "#c23a30",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线"
        }
    },
    {
        "id": "bj2",
        "colour": "#006098",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线"
        }
    },
    {
        "id": "bj3",
        "colour": "#d90627",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线"
        }
    },
    {
        "id": "bj4",
        "colour": "#008e9c",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线"
        }
    },
    {
        "id": "bj5",
        "colour": "#a6217f",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线"
        }
    },
    {
        "id": "bj6",
        "colour": "#d29700",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线"
        }
    },
    {
        "id": "bj7",
        "colour": "#f6c582",
        "fg": "#000",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线"
        }
    },
    {
        "id": "bj8",
        "colour": "#009b6b",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线"
        }
    },
    {
        "id": "bj9",
        "colour": "#8fc31f",
        "fg": "#000",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线"
        }
    },
    {
        "id": "bj10",
        "colour": "#009bc0",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线"
        }
    },
    {
        "id": "bj11",
        "colour": "#ED796B",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线"
        }
    },
    {
        "id": "bj12",
        "colour": "#9c4f01",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线"
        }
    },
    {
        "id": "bj13",
        "colour": "#f9e700",
        "fg": "#000",
        "name": {
            "en": "Line 1A",
            "zh-Hans": "13A线"
        }
    },
    {
        "id": "bj14",
        "colour": "#d5a7a1",
        "fg": "#000",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线"
        }
    },
    {
        "id": "bj15",
        "colour": "#5b2c68",
        "fg": "#fff",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线"
        }
    },
    {
        "id": "bj16",
        "colour": "#76a32e",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线"
        }
    },
    {
        "id": "bj17",
        "colour": "#00A9A9",
        "fg": "#fff",
        "name": {
            "en": "Line 17",
            "zh-Hans": "17号线"
        }
    },
    {
        "id": "bj19",
        "colour": "#D6ABC1",
        "fg": "#000",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线"
        }
    },
    {
        "id": "bj22",
        "colour": "#f4c1ca",
        "fg": "#000",
        "name": {
            "en": "Line 22",
            "zh-Hans": "22号线"
        }
    },
    {
        "id": "bj28",
        "colour": "#476205",
        "fg": "#fff",
        "name": {
            "en": "Line 28",
            "zh-Hans": "28号线"
        }
    },
    {
        "id": "bj25",
        "colour": "#e46022",
        "fg": "#fff",
        "name": {
            "en": "Line 25",
            "zh-Hans": "25号线"
        }
    },
    {
        "id": "bj27",
        "colour": "#de82b2",
        "fg": "#000",
        "name": {
            "en": "Line 27",
            "zh-Hans": "27号线"
        }
    },
    {
        "id": "bj24",
        "colour": "#e40077",
        "fg": "#fff",
        "name": {
            "en": "Line 24",
            "zh-Hans": "24号线"
        }
    },
    {
        "id": "bj26",
        "colour": "#b35a20",
        "fg": "#fff",
        "name": {
            "en": "Line 26",
            "zh-Hans": "26号线"
        }
    },
    {
        "id": "bj34",
        "colour": "#a29bbb",
        "fg": "#000",
        "name": {
            "en": "line 34",
            "zh-Hans": "34号线"
        }
    },
    {
        "id": "bj35",
        "colour": "#004a9f",
        "fg": "#fff",
        "name": {
            "en": "line 35",
            "zh-Hans": "35号线"
        }
    },
    {
        "id": "bt",
        "colour": "#e50619",
        "fg": "#fff",
        "name": {
            "en": "Line 29",
            "zh-Hans": "29号线"
        }
    },
    {
        "id": "btt1",
        "colour": "#e5061b",
        "fg": "#fff",
        "name": {
            "en": "Line T1",
            "zh-Hans": "T1线"
        }
    },
    {
        "id": "bj18",
        "colour": "#4a4e82",
        "fg": "#fff",
        "name": {
            "en": "LINE 18",
            "zh-Hans": "18号线"
        }
    },
    {
        "id": "bj20",
        "colour": "#e5a376",
        "fg": "#000",
        "name": {
            "en": "line 13B",
            "zh-Hans": "13B线"
        }
    }
]</details>

**Comment by 28yfang** [comment]
请管理员关闭 #570
