### ISSUE TITLE
Resources: New palettes of South California (Metrolink)

### ISSUE THREAD

**Issue by aaronyz2007** [railmapgen/rmg-palette#573]
**Reference link:** https://metrolinktrains.com/schedules/?type=line

**Justification:** 增加南加州都会铁路各线路颜色

_Submitted palettes are migrated into Los Angeles by @wongchito_

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "losangeles",
    "country": "US",
    "name": {
        "en": "Los Angeles",
        "zh-Hans": "洛杉矶",
        "zh-Hant": "洛杉磯",
        "ko": "로스 앤젤레스"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "laa",
        "colour": "#0072bc",
        "fg": "#fff",
        "name": {
            "en": "A Line",
            "zh-Hans": "A线",
            "zh-Hant": "A線",
            "ko": "A선"
        }
    },
    {
        "id": "lab",
        "colour": "#e3131b",
        "fg": "#fff",
        "name": {
            "en": "B Line",
            "zh-Hans": "B线",
            "zh-Hant": "B線",
            "ko": "B선"
        }
    },
    {
        "id": "lac",
        "colour": "#58a738",
        "fg": "#fff",
        "name": {
            "en": "C Line",
            "zh-Hans": "C线",
            "zh-Hant": "C線",
            "ko": "C선"
        }
    },
    {
        "id": "lad",
        "colour": "#a05da5",
        "fg": "#fff",
        "name": {
            "en": "D Line",
            "zh-Hans": "D线",
            "zh-Hant": "D線",
            "ko": "D선"
        }
    },
    {
        "id": "lae",
        "colour": "#5bc2e7",
        "fg": "#000",
        "name": {
            "en": "E Line",
            "zh-Hans": "E线",
            "zh-Hant": "E線",
            "ko": "E선"
        }
    },
    {
        "id": "lak",
        "colour": "#e96bb0",
        "fg": "#000",
        "name": {
            "en": "K Line",
            "zh-Hans": "K线",
            "zh-Hant": "K線",
            "ko": "K선"
        }
    },
    {
        "id": "lal",
        "colour": "#fdb913",
        "fg": "#000",
        "name": {
            "en": "L Line",
            "zh-Hans": "L线",
            "zh-Hant": "L線",
            "ko": "L선"
        }
    },
    {
        "id": "lag",
        "colour": "#fc4c02",
        "fg": "#fff",
        "name": {
            "en": "G Line",
            "zh-Hans": "快速公交G线",
            "zh-Hant": "快速公交G線",
            "ko": "G선"
        }
    },
    {
        "id": "laj",
        "colour": "#adb8bf",
        "fg": "#000",
        "name": {
            "en": "J Line",
            "zh-Hans": "快速公交J线",
            "zh-Hant": "快速公交J線",
            "ko": "J선"
        }
    },
{
        "id": "scaxav",
        "colour": "#1c9d03",
        "fg": "#fff",
        "name": {
            "en": "Antelope Valley Line",
            "zh-Hans": "羚羊谷线",
            "zh-Hant": "羚羊谷線",
            "ko": "앤텔로프 밸리 라인"
        }
    },
    {
        "id": "scaxio",
        "colour": "#bd295a",
        "fg": "#fff",
        "name": {
            "en": "Inland Empire-Orange County Line",
            "zh-Hans": "内陆帝国-橙县线",
            "zh-Hant": "内陸帝國-橙縣線",
            "ko": "인랜드 엠파이어-오렌지 카운티 라인"
        }
    },
    {
        "id": "scaxoc",
        "colour": "#ff7600",
        "fg": "#fff",
        "name": {
            "en": "Orange County Line",
            "zh-Hans": "橙县线",
            "zh-Hant": "橙縣線",
            "ko": "오렌지 카운티 라인"
        }
    },
    {
        "id": "scaxrs",
        "colour": "#682e86",
        "fg": "#fff",
        "name": {
            "en": "Riverside Line",
            "zh-Hans": "河滨线",
            "zh-Hant": "河濱線",
            "ar": "리버사이드 라인"
        }
    },
    {
        "id": "scaxsb",
        "colour": "#a32136",
        "fg": "#fff",
        "name": {
            "en": "San Bernardino Line",
            "zh-Hans": "圣贝纳迪诺线",
            "zh-Hant": "聖貝納迪諾線",
            "ko": "샌버너디노 라인"
        }
    },
    {
        "id": "scaxvc",
        "colour": "#f6a704",
        "fg": "#fff",
        "name": {
            "en": "Ventura County Line",
            "zh-Hans": "文图拉县线",
            "zh-Hant": "文圖拉縣線",
            "ko": "벤츄라 카운티 라인"
        }
    },
    {
        "id": "scaxpv",
        "colour": "#0071ce",
        "fg": "#fff",
        "name": {
            "en": "91/Perris Valley Line",
            "zh-Hans": "91/佩里斯谷线",
            "zh-Hant": "91/佩里斯谷線",
            "ko": "91/페리스 밸리 라인"
        }
    }
]</details>

**Comment by langonginc** [comment]
经检查您提交的内容正确无误，等待管理员确认并汇入，感谢您的贡献。

**Comment by wongchito** [comment]
Hi @aaronyz2007 ,

由於調色盤按**城市**收錄路線顏色，因此我們將移動這些Metrolink路線顏色至洛杉磯，並將洛杉磯改名為「洛杉磯（南加洲）」，同時閣下的貢獻記錄不受影響。歡迎閣下對該安排提出意見，如無意見我們將進行移動。

**Comment by aaronyz2007** [comment]
好的，但是或许应该是洛杉矶（南加州）而非洲？此“州”应为美国行政单位而非大洲之意

**Comment by wongchito** [comment]
> 好的，但是或许应该是洛杉矶（南加州）而不是洲？此“州”应为美国行政单位而非大洲之意

多謝指正
