### ISSUE TITLE
Resources: New palettes of Xi'an

### ISSUE THREAD

**Issue by XianningluStation** [railmapgen/rmg-palette#577]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://www.xianrail.com/#/index

**Justification:** 西安地铁三期规划逐渐完成，各新增线路标志色逐渐公开，需对原有进行修改

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "xian",
    "country": "CN",
    "name": {
        "en": "Xi'an",
        "zh-Hans": "西安",
        "zh-Hant": "西安"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "xa1",
        "colour": "#0077C8",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "xa2",
        "colour": "#EF3340",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "xa3",
        "colour": "#CE70CC",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "xa4",
        "colour": "#39b09e",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "xa5",
        "colour": "#A6E35F",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "xa6",
        "colour": "#485CC7",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "xa9",
        "colour": "#FF9E1B",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "xa14",
        "colour": "#00C1D4",
        "fg": "#000",
        "name": {
            "en": "Airport Intercity Railway/Line 14",
            "zh-Hans": "机场城际/14号线",
            "zh-Hant": "機場城際/14號線"
        }
    },
    {
        "id": "xa10",
        "colour": "#00a353",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "xa16",
        "colour": "#ee805f",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "xaxh",
        "colour": "#720160",
        "fg": "#fff",
        "name": {
            "en": "Xihu Line",
            "zh-Hans": "西户线",
            "zh-Hant": "西戶線"
        }
    },
    {
        "id": "xxzg",
        "colour": "#bb0601",
        "fg": "#fff",
        "name": {
            "en": "Xixian ART Line 1",
            "zh-Hans": "西咸智轨1号线",
            "zh-Hant": "西咸智軌1號線"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，由于您已经在 #588 中修改过地铁10号线的配色，所以请等待管理员汇入16号线、西户线和西咸智轨1号线的颜色，感谢您的贡献。
