### ISSUE TITLE
Resources: New palettes of Xi'an

### ISSUE THREAD

**Issue by XianningluStation** [railmapgen/rmg-palette#586]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://www.xianrail.com/#/newsCenterDetails/0f20fe32-bdbc-483d-ba7d-56de633ddda1

**Justification:** 对10号线颜色进行改动

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "xian",
    "country": "CN",
    "name": {
        "en": "Xi'an",
        "zh-Hans": "西安",
        "zh-Hant": "西安"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "xa1",
        "colour": "#0077C8",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "xa2",
        "colour": "#EF3340",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "xa3",
        "colour": "#CE70CC",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "xa4",
        "colour": "#2CCCD3",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "xa5",
        "colour": "#A6E35F",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "xa6",
        "colour": "#485CC7",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "xa8",
        "colour": "#FFE400",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "xa9",
        "colour": "#FF9E1B",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "xa10",
        "colour": "#009f4d",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "xa14",
        "colour": "#00C1D4",
        "fg": "#000",
        "name": {
            "en": "Airport Intercity Railway/Line 14",
            "zh-Hans": "机场城际/14号线",
            "zh-Hant": "機場城際/14號線"
        }
    }
]</details>

**Comment by langonginc** [comment]
您好，经检查、您提交到内容存在如下问题：

- 10号线颜色与来源有偏差，标注的“色号Panton 7482c” 对应16进制编码应为 “#009f4d”。

请您检查并修改后通过重新提交，感谢您的贡献。

**Comment by langonginc** [comment]
您好，问题已经在 https://github.com/railmapgen/rmg-palette/commit/c8c3d616f2a6b2e9545b1ac3f0d55c819b69ffe2 中修复，请等待管理员确认并汇入，感谢您的贡献。
