### ISSUE TITLE
Resources: New palettes of Canberra

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmg-palette#592]
**Reference link:** https://www.transport.act.gov.au/__data/assets/pdf_file/0005/1603688/2023_TC_network_map_420x792.pdf

**Justification:** Add for Canberra

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "cbr",
    "country": "AU",
    "name": {
        "en": "Canberra",
        "zh-Hans": "堪培拉",
        "zh-Hant": "堪培拉"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "R1",
        "colour": "#e9322b",
        "fg": "#fff",
        "name": {
            "en": "Light Rail Line 1",
            "zh-Hans": "轻轨1号线",
            "zh-Hant": "輕軌1號線"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，您提交的模板无问题，请等待管理员汇入，感谢您的贡献。
