### ISSUE TITLE
Resources: New palettes of Pyongyang

### ISSUE THREAD

**Issue by coxine** [railmapgen/rmg-palette#595]
**Reference link:** https://zh.wikipedia.org/wiki/%E5%B9%B3%E5%A3%A4%E5%9C%B0%E9%90%B5

**Justification:** 根据开发者在https://github.com/railmapgen/rmp-gallery/issues/255 的建议，做出相应的改进

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "KP",
    "name": {
        "en": "North Korea",
        "zh-Hans": "朝鲜民主主义人民共和国",
        "zh-Hant": "朝鮮民主主義人民共和國",
        "ko": "조선민주주의인민공화국"
    },
    "language": "ko"
}</details>

<details repo="rmg-palette" type="city">{
    "id": "Pyongyang",
    "country": "KP",
    "name": {
        "en": "Pyongyang",
        "zh-Hans": "平壤",
        "zh-Hant": "平壤",
        "ko": "평양"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "chollima",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Chollima Line",
            "zh-Hans": "千里马线",
            "ko": "천리마선",
            "zh-Hant": "千里馬線"
        }
    },
    {
        "id": "hyeoksin",
        "colour": "#00ff00",
        "fg": "#fff",
        "name": {
            "en": "Hyŏksin Line",
            "zh-Hans": "革新线",
            "ko": "혁신선",
            "zh-Hant": "革新線"
        }
    }
]</details>

**Comment by langonginc** [comment]
感谢您的修改，目前没问题了，请等待管理员汇入，感谢您的贡献。
