### ISSUE TITLE
Resources: New palettes of [CITY]

### ISSUE THREAD

**Issue by malaoban8888** [railmapgen/rmg-palette#60]
Hi RMG team! I would like to contribute the palettes below.

__Do not edit lines below, they are meant for bots only!!!__

_Enter new palettes data and follow instruction in https://railmapgen.github.io/rmg-palette/new_

(Input anything you want here)

**Do not edit lines below, they are meant for bots only!!!**

<details repo='rmg-palette' type='city'>
{
    "id": "",
    "country": "",
    "name": {
        "en": ""
    }
}
</details>

<details repo='rmg-palette' type='lines'>
[
    {
        "id": "",
        "colour": "#aaaaaa",
        "fg": "#fff",
        "name": {
            "en": ""
        }
    }
]
</details>

**Comment by wongchito** [comment]
Close as invalid data
