### ISSUE TITLE
Resources: New palettes of Nantes

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmg-palette#600]
**Reference link:** https://www.tan.fr/

**Justification:** Add palettes of Nantes

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "nantes",
    "country": "FR",
    "name": {
        "en": "Nantes",
        "fr": "Nantes",
        "zh-Hans": "南特",
        "zh-Hant": "南特"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "n1",
        "colour": "#007a45",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號缐",
            "fr": "Ligne 1"
        }
    },
    {
        "id": "n2",
        "colour": "#e53138",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號缐",
            "fr": "Ligne 2"
        }
    },
    {
        "id": "n3",
        "colour": "#0079bc",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號缐",
            "fr": "Ligne 3"
        }
    },
    {
        "id": "n4",
        "colour": "#fdc600",
        "fg": "#000",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號缐",
            "fr": "Ligne 4"
        }
    },
    {
        "id": "n5",
        "colour": "#34b4e4",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號缐",
            "fr": "Ligne 5"
        }
    }
]</details>

**Comment by 28yfang** [comment]
您好，经检查，您所提供的颜色均无问题，请等待管理员汇入。感谢您的贡献！
