### ISSUE TITLE
Resources: New palettes of Nagpur

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmg-palette#602]
**Reference link:** https://www.metrorailnagpur.com/project-profile

**Justification:** 那格浦尔地铁（共两条线）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "nagpur",
    "country": "IN",
    "name": {
        "en": "Nagpur",
        "zh-Hans": "那格浦尔",
        "zh-Hant": "那格浦爾",
        "hi": "नागपुर"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "aqua",
        "colour": "#0288d1",
        "fg": "#fff",
        "name": {
            "en": "Aqua Line",
            "zh-Hans": "水线",
            "zh-Hant": "水線",
            "hi": "एक्वा लाइन"
        }
    },
    {
        "id": "orange",
        "colour": "#f57c00",
        "fg": "#fff",
        "name": {
            "en": "Orange Line",
            "zh-Hans": "橙线",
            "zh-Hant": "橙線",
            "hi": "ऑरेंज लाइन"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，我想确认一下您所提交的颜色是否为通过截屏后进行的取色呢？

**Comment by DQB061204** [comment]
> 您好，我想确认一下您所提交的颜色是否为通过截屏后进行的取色呢？

不是

**Comment by 52PD** [comment]
> 不是

您好，如果该颜色来源并非截屏取色的话我想确认一下您是通过何种方式获得这些颜色的呢🤔️

因为我注意到官网上所给出的线路图是使用谷歌地图制作的，而通过这种方式制作的线路图就我所知除非截屏是无法直接通过html代码取色的。

**Comment by DQB061204** [comment]
![image](https://github.com/railmapgen/rmg-palette/assets/103240595/4aba75a2-cc7b-4c8f-af3c-20fb42a03cf9)
是取色器

**Comment by 52PD** [comment]
> 是取色器

好的，那这样的话这一个稿件就没问题了。
