### ISSUE TITLE
Resources: New palettes of Shiraz

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmg-palette#604]
**Reference link:** https://shirazmetro.ir/%D9%86%D9%82%D8%B4%D9%87-%D8%AE%D8%B7%D9%88%D8%B7-%D9%85%D8%AA%D8%B1%D9%88/

**Justification:** 设拉子地铁（一条线）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shiraz",
    "country": "IR",
    "name": {
        "en": "Shiraz",
        "zh-Hans": "设拉子",
        "zh-Hant": "設拉子",
        "fa": "شیراز"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "shiraz1",
        "colour": "#ea1d23",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線",
            "fa": "خط ۱"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，经检查颜色方面已经没有问题。

线路编号和中文名称方面虽然有些不规范，但问题不大所以我们已经对齐进行调整，因为您无需做出任何改动。

感谢您对本项目的支持！
