### ISSUE TITLE
Resources: New palettes of Turin

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmg-palette#606]
**Reference link:** https://www.gtt.to.it/cms/linee-e-orari/torino-e-cintura/urbana/240-metropolitana

**Justification:** 都灵地铁（一条）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "turin",
    "country": "IT",
    "name": {
        "en": "Turin",
        "zh-Hans": "都灵",
        "zh-Hant": "都靈",
        "it": "Torino"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "to1",
        "colour": "#feed03",
        "fg": "#000",
        "name": {
            "en": "Metro Line 1",
            "zh-Hans": "地铁1号线",
            "zh-Hant": "捷運1號線",
            "it": "M1"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，经检查颜色方面已经没有问题。

线路编号和中文名称方面虽然有些不规范，但问题不大所以我们已经对齐进行调整，因为您无需做出任何改动。

感谢您对本项目的支持！
