### ISSUE TITLE
Resources: New palettes of Mexico City

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmg-palette#610]
**Reference link:** https://www.metro.cdmx.gob.mx/la-red/mapa-de-la-red-con-calles

**Justification:** 墨西哥城地铁（十二条线）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "mexicocity",
    "country": "MX",
    "name": {
        "en": "Mexico City",
        "zh-Hans": "墨西哥城",
        "zh-Hant": "墨西哥城",
        "es": "Ciudad de México"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "l1",
        "colour": "#ed699b",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線",
            "es": "Línea 1"
        }
    },
    {
        "id": "l2",
        "colour": "#007bc1",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線",
            "es": "Línea 2"
        }
    },
    {
        "id": "l3",
        "colour": "#bfad1d",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線",
            "es": "Línea 3"
        }
    },
    {
        "id": "l4",
        "colour": "#7bc7ba",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線",
            "es": "Línea 4"
        }
    },
    {
        "id": "l5",
        "colour": "#ffdb25",
        "fg": "#000",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線",
            "es": "Línea 5"
        }
    },
    {
        "id": "l6",
        "colour": "#e82428",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線",
            "es": "Línea 6"
        }
    },
    {
        "id": "l7",
        "colour": "#f17c2f",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線",
            "es": "Línea 7"
        }
    },
    {
        "id": "l8",
        "colour": "#00a263",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線",
            "es": "Línea 8"
        }
    },
    {
        "id": "l9",
        "colour": "#581c00",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線",
            "es": "Línea 9"
        }
    },
    {
        "id": "la",
        "colour": "#8f248e",
        "fg": "#fff",
        "name": {
            "en": "Line A",
            "zh-Hans": "A线",
            "zh-Hant": "A線",
            "es": "Línea A"
        }
    },
    {
        "id": "lb1",
        "colour": "#018752",
        "fg": "#fff",
        "name": {
            "en": "Line B",
            "zh-Hans": "B线（颜色1）",
            "zh-Hant": "B線（顏色1）",
            "es": "Línea B"
        }
    },
    {
        "id": "lb2",
        "colour": "#bebfc1",
        "fg": "#000",
        "name": {
            "en": "Line B",
            "zh-Hans": "B线（颜色2）",
            "zh-Hant": "B線（顏色2）",
            "es": "Línea B"
        }
    },
    {
        "id": "l12",
        "colour": "#b49c4e",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線",
            "es": "Línea 12"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，经检查我们发现以下问题：

- 您所提供的3号线（`#bfad1d`）、5号线（`#ffdb25`）、9号线（`#581c00`）、A线（`#8f248e`）颜色与我们从来源中所取到的颜色（3号线`#FFDB25`、5号线`#BCB600`、9号线`#461906`、A线`#90007B`）肉眼色差过大。
- 在此前您所提交的稿件中我们也提及到您所提交的线路名称和编号并不规范（但由于之前的线路颜色无问题我们已经对齐修改）。正确的线路编号格式应当为城市名缩写（如本issue中的墨西哥城缩写为cdmx）加线路编号，而中文线路名称中的数字部门应采用阿拉伯数字而不是汉字（如Line 1应当写成“1号线”而不是“一号线”）。

在对上述内容修改后，请将修正的内容提交至本issue下，感谢您的支持！

**Comment by DQB061204** [comment]
> 您好，经检查我们发现以下问题：
> 
> * 您所提供的3号线（`#bfad1d`）、5号线（`#ffdb25`）、9号线（`#581c00`）、A线（`#8f248e`）颜色与我们从来源中所取到的颜色（3号线`#FFDB25`、5号线`#BCB600`、9号线`#461906`、A线`#90007B`）肉眼色差过大。
> * 在此前您所提交的稿件中我们也提及到您所提交的线路名称和编号并不规范（但由于之前的线路颜色无问题我们已经对齐修改）。正确的线路编号格式应当为城市名缩写（如本issue中的墨西哥城缩写为cdmx）加线路编号，而中文线路名称中的数字部门应采用阿拉伯数字而不是汉字（如Line 1应当写成“1号线”而不是“一号线”）。
> 
> 在对上述内容修改后，请将修正的内容提交至本issue下，感谢您的支持！
> 
> （请您在收到本条消息后尽快及时回复，我们是不接受超过一个月未回复的问题稿件的）

您好 同样来自于该网页的另外一个链接https://metro.cdmx.gob.mx/storage/app/media/red/plano_red19.pdf

**Comment by DQB061204** [comment]
[ { "id": "l1", "colour": "#ed699b", "fg": "#fff", "name": { "en": "Line 1", "zh-Hans": "1号线", "zh-Hant": "1號線", "es": "Línea 1" } }, { "id": "l2", "colour": "#007bc1", "fg": "#fff", "name": { "en": "Line 2", "zh-Hans": "2号线", "zh-Hant": "2號線", "es": "Línea 2" } }, { "id": "l3", "colour": "#bfad1d", "fg": "#fff", "name": { "en": "Line 3", "zh-Hans": "3号线", "zh-Hant": "3號線", "es": "Línea 3" } }, { "id": "l4", "colour": "#7bc7ba", "fg": "#fff", "name": { "en": "Line 4", "zh-Hans": "4号线", "zh-Hant": "4號線", "es": "Línea 4" } }, { "id": "l5", "colour": "#ffdb25", "fg": "#000", "name": { "en": "Line 5", "zh-Hans": "5号线", "zh-Hant": "5號線", "es": "Línea 5" } }, { "id": "l6", "colour": "#e82428", "fg": "#fff", "name": { "en": "Line 6", "zh-Hans": "6号线", "zh-Hant": "6號線", "es": "Línea 6" } }, { "id": "l7", "colour": "#f17c2f", "fg": "#fff", "name": { "en": "Line 7", "zh-Hans": "7号线", "zh-Hant": "7號線", "es": "Línea 7" } }, { "id": "l8", "colour": "#00a263", "fg": "#fff", "name": { "en": "Line 8", "zh-Hans": "8号线", "zh-Hant": "8號線", "es": "Línea 8" } }, { "id": "l9", "colour": "#581c00", "fg": "#fff", "name": { "en": "Line 9", "zh-Hans": "9号线", "zh-Hant": "9號線", "es": "Línea 9" } }, { "id": "la", "colour": "#8f248e", "fg": "#fff", "name": { "en": "Line A", "zh-Hans": "A线", "zh-Hant": "A線", "es": "Línea A" } }, { "id": "lb1", "colour": "#018752", "fg": "#fff", "name": { "en": "Line B", "zh-Hans": "B线（颜色1）", "zh-Hant": "B線（顏色1）", "es": "Línea B" } }, { "id": "lb2", "colour": "#bebfc1", "fg": "#000", "name": { "en": "Line B", "zh-Hans": "B线（颜色2）", "zh-Hant": "B線（顏色2）", "es": "Línea B" } }, { "id": "l12", "colour": "#b49c4e", "fg": "#fff", "name": { "en": "Line 12", "zh-Hans": "12号线", "zh-Hant": "12號線", "es": "Línea 12" } } ]

**Comment by 52PD** [comment]
您好，经过检查已经没有问题了
