### ISSUE TITLE
Resources: New palettes of Lahore

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmg-palette#612]
**Reference link:** https://pma.punjab.gov.pk/orange-line-metro-train-system

**Justification:** 拉舍尔地铁（一条） 新增巴基斯坦
官网没给线路图

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "PK",
    "name": {
        "en": "Pakistan",
        "zh-Hans": "巴基斯坦",
        "zh-Hant": "巴基斯坦"
    },
    "language": "en"
}</details>

<details repo="rmg-palette" type="city">{
    "id": "lahore",
    "country": "PK",
    "name": {
        "en": "Lahore",
        "zh-Hans": "拉合尔",
        "zh-Hant": "拉合爾"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "orange",
        "colour": "#f66725",
        "fg": "#fff",
        "name": {
            "en": "Orange Line",
            "zh-Hans": "橙线",
            "zh-Hant": "橙線"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的调色板无问题，请等待管理员汇入，感谢您的贡献。

**Comment by wongchito** [comment]
Hi @DQB061204 ,

巴基斯坦官方語言為烏爾都語。請閣下於下次提交新國家/城市時，注意填寫正確的資訊。多謝閣下的貢獻！

cc: @Windows-Taskmgr
