### ISSUE TITLE
Resources: New palettes of Panama City

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmg-palette#614]
**Reference link:** https://www.elmetrodepanama.com/red-maestra/

**Justification:** 巴拿马城地铁（两条 另外一条在建） 新增巴拿马
其余线路均处于规划或者未在建设状态 所以并未提交

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "PA",
    "name": {
        "en": "Panama",
        "zh-Hans": "巴拿马",
        "zh-Hant": "巴拿馬",
        "es": "Panamá"
    },
    "language": "es"
}</details>

<details repo="rmg-palette" type="city">{
    "id": "panamacity",
    "country": "PA",
    "name": {
        "en": "Panama City",
        "zh-Hans": "巴拿马城",
        "zh-Hant": "巴拿馬城",
        "es": "Ciudad de Panamá"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "l1",
        "colour": "#eb1e25",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線",
            "es": "Línea 1"
        }
    },
    {
        "id": "l2",
        "colour": "#28733a",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線",
            "es": "Línea 2"
        }
    },
    {
        "id": "l3",
        "colour": "#d63092",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線",
            "es": "Línea 3"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的调色板包括但不限于以下问题：
- 线路名称应为“阿拉伯数字+号线”
- 3号线名称无需加上“在建”

_（如您有异议，请留下您的证明来源）_
请您在修改后将您的新调色板颜色提交到此issue下，感谢您的贡献。

**（请您在收到此消息后一个月内回复，超过一个月我们将拒绝汇入）**

**Comment by DQB061204** [comment]
[ { "id": "l1", "colour": "#eb1e25", "fg": "#fff", "name": { "en": "Line 1", "zh-Hans": "1号线", "zh-Hant": "1號線", "es": "Línea 1" } }, { "id": "l2", "colour": "#28733a", "fg": "#fff", "name": { "en": "Line 2", "zh-Hans": "2号线", "zh-Hant": "2號線", "es": "Línea 2" } }, { "id": "l3", "colour": "#d63092", "fg": "#fff", "name": { "en": "Line 3", "zh-Hans": "3号线", "zh-Hant": "3號線", "es": "Línea 3" } } ]
