### ISSUE TITLE
Resources: New palettes of Lille

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmg-palette#628]
**Reference link:** https://www.ilevia.fr/infos-trafic#menu

**Justification:** 里尔地铁（两条线）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "lille",
    "country": "FR",
    "name": {
        "en": "Lille",
        "zh-Hans": "里尔",
        "zh-Hant": "里爾",
        "fr": "Lille"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "m1",
        "colour": "#F9B122",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線",
            "fr": "Ligne 1"
        }
    },
    {
        "id": "m2",
        "colour": "#E30613",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線",
            "fr": "Ligne 2"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，我们无法从您所提供的线路来源中找到相关线路的颜色。如果您的线路颜色确实参考自该网站的话，请问能否提供一份更确切的地址呢？

此外，在线路命名方面请不要加入“地铁”“捷運”“Metro"这些字样。如果是数字命名的线路请将其直接命名为“1号线”而不是“捷运1号线”。

（请在收到此回复后尽快做出反应，我们是不接受超过一个月仍未对相关问题进行修复的稿件的。感谢您的配合）

**Comment by DQB061204** [comment]
已经进行更改

**Comment by langonginc** [comment]
上述问题已经解决，请等候汇入，感谢您对调色板的贡献。
