### ISSUE TITLE
Resources: New palettes of Shenyang

### ISSUE THREAD

**Issue by dqwfgzs** [railmapgen/rmg-palette#630]
**Reference link:** http://www.mtii.cn/news/InfoView_913.html

**Justification:** First Release

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shenyang",
    "country": "CN",
    "name": {
        "en": "Shenyang",
        "zh-Hans": "沈阳",
        "zh-Hant": "瀋陽"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sy1",
        "colour": "#b63f1f",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "sy2",
        "colour": "#e5703a",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "sy3",
        "colour": "#E6669F",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "sy4",
        "colour": "#6E3E94",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "sy6",
        "colour": "#FEDC00",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "sy9",
        "colour": "#017cbf",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "sy10",
        "colour": "#62aa3c",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "syhnt1",
        "colour": "#ec020d",
        "fg": "#fff",
        "name": {
            "en": "Hunnan Tram Line 1",
            "zh-Hans": "浑南有轨电车1号线",
            "zh-Hant": "渾南有軌電車1號綫"
        }
    },
    {
        "id": "syhnt2",
        "colour": "#a5499c",
        "fg": "#fff",
        "name": {
            "en": "Hunnan Tram Line 2",
            "zh-Hans": "浑南有轨电车2号线",
            "zh-Hant": "渾南有軌電車2號綫"
        }
    },
    {
        "id": "syhnt3",
        "colour": "#039942",
        "fg": "#fff",
        "name": {
            "en": "Hunnan Tram Line 3",
            "zh-Hans": "浑南有轨电车3号线",
            "zh-Hant": "渾南有軌電車3號綫"
        }
    },
    {
        "id": "syhnt4",
        "colour": "#00a2e8",
        "fg": "#fff",
        "name": {
            "en": "Hunnan Tram Line 4",
            "zh-Hans": "浑南有轨电车4号线",
            "zh-Hant": "渾南有軌電車4號綫"
        }
    },
    {
        "id": "syhnt5",
        "colour": "#1f2188",
        "fg": "#fff",
        "name": {
            "en": "Hunnan Tram Line 5",
            "zh-Hans": "浑南有轨电车5号线",
            "zh-Hant": "渾南有軌電車5號綫"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，经检查我们发现以下问题：

- 您所提供的有轨电车2号线（`#a5499c`）、有轨电车4号线（`#00a2e8`）和有轨电车5号线（`#1f2188`）颜色与我们从来源中所取到的颜色（有轨电车2号线`#610c71`、有轨电车4号线`#4b98ce`、有轨电车5号线`#33398f`）肉眼色差过大。

在对上述内容修改后，请将修正的内容提交至本issue下，感谢您的支持！

（请您在收到本条消息后尽快及时回复，我们是不接受超过一个月未回复的问题稿件的）

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色问题后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
