### ISSUE TITLE
Resources: New palettes of Qingdao

### ISSUE THREAD

**Issue by Minwtraft** [railmapgen/rmg-palette#636]
**Reference link:** https://weibo.com/5124782558/IBbR389tI

**Justification:** 颜色参考来源于 哆啦Joe 一条微博中的图片。
该博主所发布有关青岛地铁的信息相对更加官方
由于调色板中青岛的线路颜色差异较多，故在此更正
comes from an image on 哆啦Joe's Weibo account
The information about Qingdao Metro released by the blogger is relatively more official.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "qingdao",
    "country": "CN",
    "name": {
        "en": "Qingdao",
        "zh-Hans": "青岛",
        "zh-Hant": "青島"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "qd1",
        "colour": "#f7b000",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "qd2",
        "colour": "#c32a05",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "qd3",
        "colour": "#006dbb",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "qd4",
        "colour": "#00763c",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "qd5",
        "colour": "#9e1a96",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "qd6",
        "colour": "#6ca3d8",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "qd7",
        "colour": "#AD96DC",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "qd8",
        "colour": "#e74893",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "qd9",
        "colour": "#62a60a",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "qd10",
        "colour": "#b46e00",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "qd11",
        "colour": "#304299",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "qd12",
        "colour": "#8246ac",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "qd13",
        "colour": "#009c86",
        "fg": "#fff",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "qd14",
        "colour": "#ff5859",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "qd15",
        "colour": "#f3a9b3",
        "fg": "#fff",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "qd16",
        "colour": "#71DBD4",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，我们不接受来自于非官方或维基百科的颜色资料（即使是接近于官方的第三方颜色也不行）。

请在本issue下重新提交一份参考自青岛地铁官方或维基百科的线路颜色并附上对应来源链接，谢谢。

（请您在收到本条消息后尽快及时回复，我们是不接受超过一个月未回复的问题稿件的）

**Comment by 52PD** [comment]
您好，很抱歉由于距上次提及线路颜色来源无效后，你已经超过1个月未对其做出处理。
考虑到开发者和我们资源整合组不可能就此放任不负责任的贡献者的问题投稿一直放在issue中，

因此，我们不会接受你的投稿。请在下次投稿线路模版和颜色时对其负起责任并及时回复开发者对其提出的疑问，谢谢。
