### ISSUE TITLE
Resources: New palettes of Xiamen

### ISSUE THREAD

**Issue by CirenMaogepao** [railmapgen/rmg-palette#65]
(Input anything you want here)

**Do not edit lines below, they are meant for bots only!!!**

<details repo='rmg-palette' type='city'>
{
    "id": "Xiamen",
    "country": "CN",
    "name": {}
}
</details>

<details repo='rmg-palette' type='lines'>
[
    {
        "id": "Line1",
        "colour": "#ed751e",
        "fg": "#fff",
        "name": {}
    },
    {
        "id": "Line2",
        "colour": "#4bb134",
        "fg": "#fff",
        "name": {}
    },
    {
        "id": "Line3",
        "colour": "#0c88de",
        "fg": "#fff",
        "name": {}
    },
    {
        "id": "Line4（old）",
        "colour": "#051db1",
        "fg": "#fff",
        "name": {}
    },
    {
        "id": "Line4（new）",
        "colour": "#d81c1a",
        "fg": "#fff",
        "name": {}
    },
    {
        "id": "Line6",
        "colour": "#892160",
        "fg": "#fff",
        "name": {}
    }
]
</details>

**Comment by wongchito** [comment]
Close as invalid data
