### ISSUE TITLE
Resources: New palettes of Laocai

### ISSUE THREAD

**Issue by franklanyi** [railmapgen/rmg-palette#659]
**Reference link:** https://railmapgen.github.io/?app=rmg

**Justification:** i

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "DG",
    "name": {
        "en": "People's Republic of Daguilandory",
        "zh-Hans": "打鬼人民共和国",
        "zh-Hant": "打鬼人民共和國"
    },
    "language": "zh-Hans"
}</details>

<details repo="rmg-palette" type="city">{
    "id": "laocai",
    "country": "DG",
    "name": {
        "en": "Laocai",
        "zh-Hans": "老蔡",
        "zh-Hant": "老蔡"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "trl",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Trial Line| Ludicium linea",
            "zh-Hans": "试运行线",
            "zh-Hant": "測試綫"
        }
    }
]</details>

**Comment by 28yfang** [comment]
您好，本调色板不支持添加架空城市的地铁线路颜色，感谢您的贡献。

**Comment by 52PD** [comment]
您好，很抱歉我们不接受非现实世界的颜色库投稿
