### ISSUE TITLE
Resources: New palettes of Marseille

### ISSUE THREAD

**Issue by polygon827** [railmapgen/rmg-palette#669]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://api.rtm.fr/fiche-horaires/rtm_plan_reseau.pdf

**Justification:** 马赛交通系统，公共汽车无中文(巴黎也是这样的，求过审)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "marseille",
    "country": "FR",
    "name": {
        "en": "Marseille",
        "zh-Hans": "马赛",
        "zh-Hant": "馬賽",
        "fr": "Marseille"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "marse1",
        "colour": "#019ee5",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號綫",
            "fr": "Ligne 1"
        }
    },
    {
        "id": "marse2",
        "colour": "#e30713",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號綫",
            "fr": "Ligne 2"
        }
    },
    {
        "id": "marse1tram",
        "colour": "#ef8d06",
        "fg": "#000",
        "name": {
            "en": "Tram Line 1",
            "zh-Hans": "有轨电车T1线",
            "zh-Hant": "有軌電車T1綫",
            "fr": "Tramway Ligne 1"
        }
    },
    {
        "id": "marse2tram",
        "colour": "#f3e717",
        "fg": "#000",
        "name": {
            "en": "Tram Line 2",
            "zh-Hans": "有轨电车T2线",
            "zh-Hant": "有軌電車T2綫",
            "fr": "Tramway Ligne 2"
        }
    },
    {
        "id": "marse1bus",
        "colour": "#ee0271",
        "fg": "#fff",
        "name": {
            "en": "Bus B1/B2/B3A/B3B",
            "fr": "Bus B1/B2/B3A/B3B"
        }
    },
    {
        "id": "marse3tram",
        "colour": "#94c219",
        "fg": "#000",
        "name": {
            "en": "Tram Line 3",
            "zh-Hans": "有轨电车T3线",
            "zh-Hant": "有軌電車T3綫",
            "fr": "Tramway Ligne 3"
        }
    },
    {
        "id": "marse2bus",
        "colour": "#01aeea",
        "fg": "#fff",
        "name": {
            "en": "Bus 1/2/3/4/4B/5",
            "fr": "Bus 1/2/3/4/4B/5"
        }
    },
    {
        "id": "marse3bus",
        "colour": "#f69223",
        "fg": "#fff",
        "name": {
            "en": "Bus 6",
            "fr": "Bus 6"
        }
    },
    {
        "id": "marse4bus",
        "colour": "#ffba16",
        "fg": "#000",
        "name": {
            "en": "Bus 7/7B/7T",
            "fr": "Bus 7/7B/7T"
        }
    },
    {
        "id": "marse5bus",
        "colour": "#1ea45b",
        "fg": "#fff",
        "name": {
            "en": "Bus 9",
            "fr": "Bus 9"
        }
    },
    {
        "id": "marse6bus",
        "colour": "#ed5e3c",
        "fg": "#fff",
        "name": {
            "en": "Bus 10",
            "fr": "Bus 10"
        }
    },
    {
        "id": "marse7bus",
        "colour": "#5a2c8f",
        "fg": "#fff",
        "name": {
            "en": "Bus 11",
            "fr": "Bus 11"
        }
    },
    {
        "id": "marse8bus",
        "colour": "#0084d2",
        "fg": "#fff",
        "name": {
            "en": "Bus 12/12B/12S",
            "fr": "Bus 12/12B/12S"
        }
    },
    {
        "id": "marse9bus",
        "colour": "#c4242c",
        "fg": "#fff",
        "name": {
            "en": "Bus 15/15S",
            "fr": "Bus 15/15S"
        }
    },
    {
        "id": "marse10bus",
        "colour": "#cf5a49",
        "fg": "#fff",
        "name": {
            "en": "Bus 16/16S",
            "fr": "Bus 16/16S"
        }
    },
    {
        "id": "marse11bus",
        "colour": "#d2816e",
        "fg": "#fff",
        "name": {
            "en": "Bus 17",
            "fr": "Bus 17"
        }
    },
    {
        "id": "marse12bus",
        "colour": "#7b53a9",
        "fg": "#fff",
        "name": {
            "en": "Bus 18",
            "fr": "Bus 18"
        }
    },
    {
        "id": "marse13bus",
        "colour": "#de3a91",
        "fg": "#fff",
        "name": {
            "en": "Bus 19",
            "fr": "Bus 19"
        }
    },
    {
        "id": "marse14bus",
        "colour": "#602e91",
        "fg": "#fff",
        "name": {
            "en": "Bus 20",
            "fr": "Bus 20"
        }
    },
    {
        "id": "marse16bus",
        "colour": "#f53a31",
        "fg": "#fff",
        "name": {
            "en": "Bus 22/22S",
            "fr": "Bus 22/22S"
        }
    },
    {
        "id": "marse15bus",
        "colour": "#fc8042",
        "fg": "#fff",
        "name": {
            "en": "Bus 21J",
            "fr": "Bus 21J"
        }
    },
    {
        "id": "marse17bus",
        "colour": "#f59614",
        "fg": "#fff",
        "name": {
            "en": "Bus 23",
            "fr": "Bus 23"
        }
    },
    {
        "id": "marse18bus",
        "colour": "#f11e27",
        "fg": "#fff",
        "name": {
            "en": "Bus 24/24B/24T",
            "fr": "Bus 24/24B/24T"
        }
    },
    {
        "id": "marse19bus",
        "colour": "#ed3f38",
        "fg": "#fff",
        "name": {
            "en": "Bus 25",
            "fr": "Bus 25"
        }
    },
    {
        "id": "marse20bus",
        "colour": "#62a5d9",
        "fg": "#fff",
        "name": {
            "en": "Bus 27",
            "fr": "Bus 27"
        }
    },
    {
        "id": "marse21bus",
        "colour": "#e83e2f",
        "fg": "#fff",
        "name": {
            "en": "Bus 28/28B",
            "fr": "Bus 28/28B"
        }
    },
    {
        "id": "marse22bus",
        "colour": "#f23b33",
        "fg": "#fff",
        "name": {
            "en": "Bus 30",
            "fr": "Bus 30"
        }
    },
    {
        "id": "marse23bus",
        "colour": "#01853a",
        "fg": "#fff",
        "name": {
            "en": "Bus 31/32",
            "fr": "Bus 31/32"
        }
    },
    {
        "id": "marse24bus",
        "colour": "#04bdb8",
        "fg": "#fff",
        "name": {
            "en": "Bus 33/34",
            "fr": "Bus 33/34"
        }
    },
    {
        "id": "marse25bus",
        "colour": "#c72032",
        "fg": "#fff",
        "name": {
            "en": "Bus 35",
            "fr": "Bus 35"
        }
    },
    {
        "id": "marse26bus",
        "colour": "#2ca3c5",
        "fg": "#fff",
        "name": {
            "en": "Bus 35T",
            "fr": "Bus 35T"
        }
    },
    {
        "id": "marse27bus",
        "colour": "#b92521",
        "fg": "#fff",
        "name": {
            "en": "Bus 36/36B",
            "fr": "Bus 36/36B"
        }
    },
    {
        "id": "marse28bus",
        "colour": "#332d91",
        "fg": "#fff",
        "name": {
            "en": "Bus 37",
            "fr": "Bus 37"
        }
    },
    {
        "id": "marse29bus",
        "colour": "#eb3c2b",
        "fg": "#fff",
        "name": {
            "en": "Bus 38",
            "fr": "Bus 38"
        }
    },
    {
        "id": "marse30bus",
        "colour": "#2c2c8e",
        "fg": "#fff",
        "name": {
            "en": "Bus 39",
            "fr": "Bus 39"
        }
    },
    {
        "id": "marse31bus",
        "colour": "#63a5d5",
        "fg": "#fff",
        "name": {
            "en": "Bus 40",
            "fr": "Bus 40"
        }
    },
    {
        "id": "marse32bus",
        "colour": "#01b89a",
        "fg": "#fff",
        "name": {
            "en": "Bus 41",
            "fr": "Bus 41"
        }
    },
    {
        "id": "marse33bus",
        "colour": "#5d6ca7",
        "fg": "#fff",
        "name": {
            "en": "Bus 42/42T",
            "fr": "Bus 42/42T"
        }
    },
    {
        "id": "marse34bus",
        "colour": "#f53f32",
        "fg": "#fff",
        "name": {
            "en": "Bus 44",
            "fr": "Bus 44"
        }
    },
    {
        "id": "marse35bus",
        "colour": "#f39019",
        "fg": "#fff",
        "name": {
            "en": "Bus 45",
            "fr": "Bus 45"
        }
    },
    {
        "id": "marse36bus",
        "colour": "#c80442",
        "fg": "#fff",
        "name": {
            "en": "Bus 46/46S",
            "fr": "Bus 46/46S"
        }
    },
    {
        "id": "marse37bus",
        "colour": "#cf484c",
        "fg": "#fff",
        "name": {
            "en": "Bus 47",
            "fr": "Bus 47"
        }
    },
    {
        "id": "marse38bus",
        "colour": "#db7078",
        "fg": "#fff",
        "name": {
            "en": "Bus 48/48T",
            "fr": "Bus 48/48T"
        }
    },
    {
        "id": "marse39bus",
        "colour": "#df5139",
        "fg": "#fff",
        "name": {
            "en": "Bus 49",
            "fr": "Bus 49"
        }
    },
    {
        "id": "marse40bus",
        "colour": "#e53e96",
        "fg": "#fff",
        "name": {
            "en": "Bus 50",
            "fr": "Bus 50"
        }
    },
    {
        "id": "marse41bus",
        "colour": "#a4ce3c",
        "fg": "#000",
        "name": {
            "en": "Bus 51",
            "fr": "Bus 51"
        }
    },
    {
        "id": "marse42bus",
        "colour": "#017dbd",
        "fg": "#fff",
        "name": {
            "en": "Bus 52",
            "fr": "Bus 52"
        }
    },
    {
        "id": "marse43bus",
        "colour": "#00518a",
        "fg": "#fff",
        "name": {
            "en": "Bus 53",
            "fr": "Bus 53"
        }
    },
    {
        "id": "marse44bus",
        "colour": "#0187c6",
        "fg": "#fff",
        "name": {
            "en": "Bus 54",
            "fr": "Bus 54"
        }
    },
    {
        "id": "marse45bus",
        "colour": "#faa226",
        "fg": "#fff",
        "name": {
            "en": "Bus 55/56",
            "fr": "Bus 55/56"
        }
    },
    {
        "id": "marse46bus",
        "colour": "#ede70b",
        "fg": "#000",
        "name": {
            "en": "Bus 60",
            "fr": "Bus 60"
        }
    },
    {
        "id": "marse47bus",
        "colour": "#71be4a",
        "fg": "#fff",
        "name": {
            "en": "Bus 61",
            "fr": "Bus 61"
        }
    },
    {
        "id": "marse48bus",
        "colour": "#47caf6",
        "fg": "#fff",
        "name": {
            "en": "Bus 67",
            "fr": "Bus 67"
        }
    },
    {
        "id": "marse49bus",
        "colour": "#00a54d",
        "fg": "#fff",
        "name": {
            "en": "Bus 70",
            "fr": "Bus 70"
        }
    },
    {
        "id": "marse50bus",
        "colour": "#ec231c",
        "fg": "#fff",
        "name": {
            "en": "Bus 72",
            "fr": "Bus 72"
        }
    },
    {
        "id": "marse51bus",
        "colour": "#e33e9a",
        "fg": "#fff",
        "name": {
            "en": "Bus 73",
            "fr": "Bus 73"
        }
    },
    {
        "id": "marse52bus",
        "colour": "#573292",
        "fg": "#fff",
        "name": {
            "en": "Bus 74",
            "fr": "Bus 74"
        }
    },
    {
        "id": "marse53bus",
        "colour": "#6ec040",
        "fg": "#fff",
        "name": {
            "en": "Bus 80",
            "fr": "Bus 80"
        }
    },
    {
        "id": "marse54bus",
        "colour": "#045185",
        "fg": "#fff",
        "name": {
            "en": "Bus 81",
            "fr": "Bus 81"
        }
    },
    {
        "id": "marse55bus",
        "colour": "#a8ce3d",
        "fg": "#000",
        "name": {
            "en": "Bus 82/82S",
            "fr": "Bus 82/82S"
        }
    },
    {
        "id": "marse56bus",
        "colour": "#b9243a",
        "fg": "#fff",
        "name": {
            "en": "Bus 83",
            "fr": "Bus 83"
        }
    },
    {
        "id": "marse57bus",
        "colour": "#f5632a",
        "fg": "#fff",
        "name": {
            "en": "Bus 84",
            "fr": "Bus 84"
        }
    },
    {
        "id": "marse58bus",
        "colour": "#fde100",
        "fg": "#fff",
        "name": {
            "en": "Bus 88",
            "fr": "Bus 88"
        }
    },
    {
        "id": "marse59bus",
        "colour": "#abce3c",
        "fg": "#000",
        "name": {
            "en": "Bus 86",
            "fr": "Bus 86"
        }
    },
    {
        "id": "marse60bus",
        "colour": "#00883f",
        "fg": "#fff",
        "name": {
            "en": "Bus 89",
            "fr": "Bus 89"
        }
    },
    {
        "id": "marse61bus",
        "colour": "#7ed1ef",
        "fg": "#000",
        "name": {
            "en": "Bus 91",
            "fr": "Bus 91"
        }
    },
    {
        "id": "marse62bus",
        "colour": "#808080",
        "fg": "#fff",
        "name": {
            "en": "Bus 95/95S/96",
            "fr": "Bus 95/95S/96"
        }
    },
    {
        "id": "marse63bus",
        "colour": "#d0cc34",
        "fg": "#000",
        "name": {
            "en": "Bus 97",
            "fr": "Bus 97"
        }
    },
    {
        "id": "marse64bus",
        "colour": "#fe9d1a",
        "fg": "#fff",
        "name": {
            "en": "Bus 98",
            "fr": "Bus 98"
        }
    },
    {
        "id": "marse65bus",
        "colour": "#14bbf2",
        "fg": "#fff",
        "name": {
            "en": "Bus 121",
            "fr": "Bus 121"
        }
    },
    {
        "id": "marse66bus",
        "colour": "#7ac3af",
        "fg": "#fff",
        "name": {
            "en": "Bus 122",
            "fr": "Bus 122"
        }
    },
    {
        "id": "marse67bus",
        "colour": "#00a5ea",
        "fg": "#fff",
        "name": {
            "en": "Bus 142/142J/143/144",
            "fr": "Bus 142/142J/143/144"
        }
    },
    {
        "id": "marse69bus",
        "colour": "#de3838",
        "fg": "#fff",
        "name": {
            "en": "Bus 144J",
            "fr": "Bus 144J"
        }
    },
    {
        "id": "marse70bus",
        "colour": "#f18c24",
        "fg": "#fff",
        "name": {
            "en": "Bus BC1",
            "fr": "Bus BC1"
        }
    },
    {
        "id": "marse71bus",
        "colour": "#03acc3",
        "fg": "#fff",
        "name": {
            "en": "Bus BC2",
            "fr": "Bus BC2"
        }
    },
    {
        "id": "marse72bus",
        "colour": "#7bc041",
        "fg": "#000",
        "name": {
            "en": "Bus BC3",
            "fr": "Bus BC3"
        }
    },
    {
        "id": "marse73bus",
        "colour": "#006ab8",
        "fg": "#fff",
        "name": {
            "en": "Bus C7/C8",
            "fr": "Bus C7/C8"
        }
    },
    {
        "id": "marse74bus",
        "colour": "#0369b3",
        "fg": "#fff",
        "name": {
            "en": "Bus M6/M8",
            "fr": "Bus M6/M8"
        }
    },
    {
        "id": "marse75bus",
        "colour": "#28407c",
        "fg": "#fff",
        "name": {
            "en": "Bus 34/50/51/53/64/88/89/91/36/37/49/69/100/102/240",
            "fr": "Bus M6/M8"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @polygon827 ,

多謝閣下的貢獻！
