### ISSUE TITLE
Resources: New palettes of Jinhua

### ISSUE THREAD

**Issue by HangzhouMetro09024** [railmapgen/rmg-palette#673]
**Reference link:** https://www.metroman.cn/metro.html?city=jh

**Justification:** 新的线路

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "jinhua",
    "country": "CN",
    "name": {
        "zh-Hans": "金华",
        "zh-Hant": "金華",
        "en": "Jinhua"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "jyd",
        "colour": "#e53333",
        "fg": "#fff",
        "name": {
            "zh-Hans": "金义东线",
            "zh-Hant": "金義東線",
            "en": "Jinyidong Line"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @HangzhouMetro09024 ,

我們暫不支援從第三方網站的相片中取得顏色。請考慮使用：

- 維基百科顏色(HEX)
- 官方網站顏色(HEX或取色)
- 政府地標文件

多謝！
