### ISSUE TITLE
Resources: New palettes of Kingtown

### ISSUE THREAD

**Issue by UTPON-CLUB** [railmapgen/rmg-palette#677]
**Reference link:** http://sun.utpon.com

**Justification:** The city is designed by UTPON Club as an elevated spatiotemporal city, and its rail transit situation in 1800. The approximate location is located in the northern part of present-day Nanjing, China.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "JK-SUNCN",
    "name": {
        "en": "The Great Sun Dynasty of China",
        "zh-Hant": "中華大商帝國",
        "zh-Hans": "中华大商帝国"
    },
    "language": "zh-Hant"
}</details>

<details repo="rmg-palette" type="city">{
    "id": "JKSUNCN01001",
    "country": "JK-SUNCN",
    "name": {
        "en": "Kingtown",
        "zh-Hans": "京都",
        "zh-Hant": "京都"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "JD01",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Line 01",
            "zh-Hans": "1 号线",
            "zh-Hant": "一號線"
        }
    },
    {
        "id": "JD02",
        "colour": "#ffff00",
        "fg": "#fff",
        "name": {
            "en": "Line 02",
            "zh-Hans": "2 号线",
            "zh-Hant": "二號線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，很抱歉我们不接受非现实世界的颜色库投稿
