### ISSUE TITLE
Resources: New palettes of Kingtown

### ISSUE THREAD

**Issue by UTPON-CLUB** [railmapgen/rmg-palette#678]
**Reference link:** http://sun.utpon.com

**Justification:** The city is designed by UTPON Club as an elevated spatiotemporal city, and its rail transit situation in 1800. The approximate location is located in the northern part of present-day Nanjing, China.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "JK-SUNCN",
    "name": {
        "en": "The Great Sun Dynasty of China",
        "zh-Hant": "中華大商帝國",
        "zh-Hans": "中华大商帝国"
    },
    "language": "zh-Hant"
}</details>

<details repo="rmg-palette" type="city">{
    "id": "JKSUNCN01001",
    "country": "JK-SUNCN",
    "name": {
        "en": "Kingtown",
        "zh-Hans": "京都",
        "zh-Hant": "京都"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "JD01",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Line 01",
            "zh-Hans": "1 号线",
            "zh-Hant": "一號線"
        }
    },
    {
        "id": "JD02",
        "colour": "#ffff00",
        "fg": "#fff",
        "name": {
            "en": "Line 02",
            "zh-Hans": "2 号线",
            "zh-Hant": "二號線"
        }
    },
    {
        "id": "JD03",
        "colour": "#ff9900",
        "fg": "#fff",
        "name": {
            "en": "Line 03",
            "zh-Hans": "3 号线",
            "zh-Hant": "三號線"
        }
    },
    {
        "id": "JD04",
        "colour": "#00ff00",
        "fg": "#fff",
        "name": {
            "en": "Line 04",
            "zh-Hans": "4 号线",
            "zh-Hant": "四號線"
        }
    },
    {
        "id": "JD05",
        "colour": "#00ffff",
        "fg": "#fff",
        "name": {
            "en": "Line 05",
            "zh-Hans": "5 号线",
            "zh-Hant": "五號線"
        }
    },
    {
        "id": "JD06",
        "colour": "#4a86e8",
        "fg": "#fff",
        "name": {
            "en": "Line 06",
            "zh-Hans": "6 号线",
            "zh-Hant": "六號線"
        }
    },
    {
        "id": "JD07",
        "colour": "#0000ff",
        "fg": "#fff",
        "name": {
            "en": "Line 07",
            "zh-Hans": "7 号线",
            "zh-Hant": "七號線"
        }
    },
    {
        "id": "JD08",
        "colour": "#9900ff",
        "fg": "#fff",
        "name": {
            "en": "Line 08",
            "zh-Hans": "8 号线",
            "zh-Hant": "八號線"
        }
    },
    {
        "id": "JD09",
        "colour": "#980000",
        "fg": "#fff",
        "name": {
            "en": "Line 09",
            "zh-Hans": "9 号线",
            "zh-Hant": "九號線"
        }
    },
    {
        "id": "JD99-A",
        "colour": "#83c38e",
        "fg": "#fff",
        "name": {
            "en": "Jing Jin Line",
            "zh-Hans": "京金线",
            "zh-Hant": "京都-金陵線"
        }
    },
    {
        "id": "JD99-B",
        "colour": "#c38390",
        "fg": "#fff",
        "name": {
            "en": "Jiangdong Line",
            "zh-Hans": "江东线",
            "zh-Hant": "江東線"
        }
    },
    {
        "id": "JD99-C",
        "colour": "#35556e",
        "fg": "#fff",
        "name": {
            "en": "Jing Pu Line",
            "zh-Hans": "京浦线",
            "zh-Hant": "京都-浦口線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，很抱歉我们不接受非现实世界的颜色库投稿
