### ISSUE TITLE
Resources: New palettes of Suzhou

### ISSUE THREAD

**Issue by aaronyz2007** [railmapgen/rmg-palette#690]
**Reference link:** https://www.sz-mtr.com/service/guide/map/index_zh.html

**Justification:** 补充有轨电车和未开通线路标识色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "suzhou",
    "country": "CN",
    "name": {
        "en": "Suzhou",
        "zh-Hans": "苏州",
        "zh-Hant": "蘇州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sz1",
        "colour": "#78BA25",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "sz2",
        "colour": "#ED3240",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "sz3",
        "colour": "#F88211",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "sz4",
        "colour": "#196EAE",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "sz5",
        "colour": "#E63A9A",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "sz6",
        "colour": "#41b6e6",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "sz7",
        "colour": "#a77bca",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "sz8",
        "colour": "#a09200",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "sz10",
        "colour": "#ca9a8e",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "sz11",
        "colour": "#f1c6a6",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "tram",
        "colour": "#d8e4c0",
        "fg": "#fff",
        "name": {
            "en": "Tram",
            "zh-Hans": "有轨电车",
            "zh-Hant": "有軌電車"
        }
    },
    {
        "id": "wkt",
        "colour": "#e0e0e0",
        "fg": "#fff",
        "name": {
            "en": "Lines under construction",
            "zh-Hans": "未开通线路",
            "zh-Hant": "未开通線路"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，经检查我们发现以下问题：

- 您所提供的未开通线路颜色与官网的颜色不匹配（您所提供的为`#e0e0e0`，而官网通过Chrome的开发者工具所提取到的颜色为`#dddddd`）

不过考虑到上述问题并非严重问题，我们会在后台进行修正后直接将其汇入到项目中，因此您无需做出任何操作。感谢您对本项目的支持！
