### ISSUE TITLE
Resources: New palettes of Xiangtan

### ISSUE THREAD

**Issue by XiaoZiMo1234** [railmapgen/rmg-palette#709]
**Reference link:** https://baike.baidu.com/item/%E9%95%BF%E6%A0%AA%E6%BD%AD%E5%9F%8E%E9%99%85%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9A%E8%A5%BF%E7%8E%AF%E7%BA%BF/23628545?fr=ge_ala

**Justification:** 2023年6月28日，長株潭城際軌道交通西環線試運營，這代表著湖南省湘潭市通了地鐵

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "xiangtan",
    "country": "CN",
    "name": {
        "en": "Xiangtan",
        "zh-Hans": "湘潭",
        "zh-Hant": "湘潭"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "xtxh",
        "colour": "#feafc7",
        "fg": "#fff",
        "name": {
            "en": "Changsha-Zhuzhou-Xiangtan Intercity Metro Xihuan Line",
            "zh-Hans": "长株潭城际轨道交通西环线",
            "zh-Hant": "長株潭城際軌道交通西環缐"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，很抱歉考虑到颜色来源的准确性，我们不接受百度百科作为颜色来源。

目前我们只支持以下来源：
- 维基百科中所存储的颜色
- 地铁公司官方网站中所提供的颜色
- 政府官方的地方标准文件中所提供的轨道交通颜色

在准备好上述三个来源中的一个后，如果新来源的颜色与您当前提供的颜色来源无差距的话可直接将新来源提交到本issue中，如果颜色差距较大的话您则需要重新提交一个新的issue用于修正出现色差的线路颜色。
