### ISSUE TITLE
Resources: New palettes of Wenzhou

### ISSUE THREAD

**Issue by WangHaoRan2211** [railmapgen/rmg-palette#719]
**Reference link:** https://baike.baidu.com/starmap/view?nodeId=a46e4d3510f9af03fefb9c44&lemmaTitle=%E6%B8%A9%E5%B7%9E%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9AS3%E7%BA%BF&lemmaId=23365713&starMapFrom=lemma_starMap&fromModule=lemma_starMap

**Justification:** 添加S3线

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "wenzhou",
    "country": "CN",
    "name": {
        "en": "Wenzhou",
        "ko": "원저우",
        "zh-Hans": "温州",
        "zh-Hant": "溫州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "wzs1",
        "colour": "#0061ae",
        "fg": "#fff",
        "name": {
            "en": "Line S1",
            "ko": "S1호선",
            "zh-Hans": "S1线",
            "zh-Hant": "S1線"
        }
    },
    {
        "id": "wzs2",
        "colour": "#e4002b",
        "fg": "#fff",
        "name": {
            "en": "Line S2",
            "ko": "S2호선",
            "zh-Hans": "S2线",
            "zh-Hant": "S2線"
        }
    },
    {
        "id": "wzs3",
        "colour": "#ff7e26",
        "fg": "#fff",
        "name": {
            "en": "Line S3",
            "ko": "S3호선",
            "zh-Hans": "S3线",
            "zh-Hant": "S3線"
        }
    }
]</details>

**Comment by 52PD** [comment]
您好，很抱歉考虑到颜色来源的准确性，我们不接受百度百科作为颜色来源。

目前我们只支持以下来源：
- 维基百科中所存储的颜色
- 地铁公司官方网站中所提供的颜色
- 政府官方的地方标准文件中所提供的轨道交通颜色

在准备好上述三个来源中的一个后，如果新来源的颜色与您当前提供的颜色来源无差距的话可直接将新来源提交到本issue中，如果颜色差距较大的话您则需要重新提交一个新的issue用于修正出现色差的线路颜色。
