### ISSUE TITLE
Resources: New palettes of Taiyuan

### ISSUE THREAD

**Issue by polygon827** [railmapgen/rmg-palette#721]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** http://cpc.people.com.cn/n1/2019/1231/c117005-31529891.html

**Justification:** 太原地铁

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "taiyuan",
    "country": "CN",
    "name": {
        "en": "Taiyuan",
        "zh-Hans": "太原"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "1",
        "colour": "#1b5eac",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "2",
        "colour": "#b31c21",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @polygon827 ,

閣下所提供的連結內並不包含路線顏色，而閣下提供的相片來源不明，且缺少2號線。請提供正確的來源，多謝！
