### ISSUE TITLE
Resources: New palettes of Sapporo

### ISSUE THREAD

**Issue by SilconFinta** [railmapgen/rmg-palette#723]
**Reference link:** https://www.city.sapporo.jp/st/route_konaizu/index.html

**Justification:** 札幌市交通局官方網站,包含線路圖及時刻表

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "Sapporo",
    "country": "JP",
    "name": {
        "en": "Sapporo",
        "ja": "さっぽろ",
        "zh-Hans": "札幌",
        "zh-Hant": "札幌"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "N",
        "colour": "#088000",
        "fg": "#fff",
        "name": {
            "en": "Nanboku Line",
            "zh-Hans": "南北线",
            "zh-Hant": "南北線",
            "ja": " 南北線"
        }
    },
    {
        "id": "T",
        "colour": "#ff9900",
        "fg": "#fff",
        "name": {
            "en": "Tozai Line",
            "zh-Hant": "東西線",
            "ja": "東西線",
            "zh-Hans": "东西线"
        }
    },
    {
        "id": "H",
        "colour": "#0000ff",
        "fg": "#fff",
        "name": {
            "en": "Toho Line",
            "ja": "東豐線",
            "zh-Hant": "東豐線",
            "zh-Hans": "东丰线"
        }
    },
    {
        "id": "SC",
        "colour": "#808080",
        "fg": "#fff",
        "name": {
            "en": "Sapporo Street Car",
            "zh-Hans": "札幌市电",
            "zh-Hant": "札幌市電",
            "ja": "札幌市電"
        }
    }
]</details>

**Comment by linchen1965** [comment]
您好，经检查，您提交的内容存在如下问题：

- 东丰线颜色与来源有偏差，应为#0066CC。
- 札幌市电颜色与来源有偏差，应为#B3B3B3。

请您检查并修改后在本Issue中重新提交修正后的颜色，感谢您的贡献。

**Comment by wongchito** [comment]
Hi @SilconFinta , @linchen1965 ,

從提供的官方網站來看，「駅時刻表」內的顏色較為接近路線圖顏色，以及相較路線圖高清，因此可作可信來源。

另，「升降機/電梯/樓梯案內圖」內的顏色於電腦上顯示效果其實更優，但考慮到與路線圖顏色的差異，因此暫不採用。
