### ISSUE TITLE
Resources: New palettes of Sankt Peterburg

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmg-palette#727]
**Reference link:** https://metroeasy.com/russia/st-petersburg-metro/

**Justification:** The future Line 6, named Krasnosel’sko-Kalininskaya, is currently under construction and spans from the southwest to the northeast. The anticipated operation start is by 2020.

**Do not edit lines below, they are meant for bots only!!!**

**Reference link:** https://metroeasy.com/russia/st-petersburg-metro/

**Justification:** The future Line 6, named Krasnosel’sko-Kalininskaya, is currently under construction and spans from the southwest to the northeast. The anticipated operation start is by 2020.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "sanktpeterburg",
    "country": "RU",
    "name": {
        "en": "Sankt Peterburg",
        "ru": "Санкт-Петербург",
        "zh-Hans": "圣彼得堡",
        "zh-Hant": "聖彼得堡"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "spg1",
        "colour": "#D51D2E",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "ru": "Линия 1 ",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "spg2",
        "colour": "#177ECE",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "ru": "Линия 2 ",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "spg3",
        "colour": "#1C9A53",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "ru": "Линия 3 ",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "spg4",
        "colour": "#DE710A",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "ru": "Линия 4 ",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "spg5",
        "colour": "#6E0A76",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "ru": "Линия 5 ",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "spg6",
        "colour": "#c2a68a",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號綫",
            "ru": "Линия 6"
        }
    }
]</details>

<details repo="rmg-palette" type="city">{
    "id": "sanktpeterburg",
    "country": "RU",
    "name": {
        "en": "Sankt Peterburg",
        "ru": "Санкт-Петербург",
        "zh-Hans": "圣彼得堡",
        "zh-Hant": "聖彼得堡"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "spg1",
        "colour": "#D51D2E",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "ru": "Линия 1 ",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "spg2",
        "colour": "#177ECE",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "ru": "Линия 2 ",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "spg3",
        "colour": "#1C9A53",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "ru": "Линия 3 ",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "spg4",
        "colour": "#DE710A",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "ru": "Линия 4 ",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "spg5",
        "colour": "#6E0A76",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "ru": "Линия 5 ",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "spg6",
        "colour": "#c2a68a",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號綫",
            "ru": "Линия 6"
        }
    }
]</details>

**Comment by Jax-axl099** [comment]
再附上一个维基百科
https://zh.wikipedia.org/zh-cn/%E7%B4%85%E6%9D%91-%E5%8A%A0%E9%87%8C%E5%AF%A7%E7%B7%9A

**Comment by linchen1965** [comment]
Hi, the color from Wikipedia will be accepted, but the color of Line 6 we've detected from Wikipedia is #8D5B2D instead of #c2a68a. In addition, other line palettes have also minor differences in comparison to Wikipedia. Please open a new issue and submit the correct palettes again.
