### ISSUE TITLE
Resources: New palettes of Zhuhai

### ISSUE THREAD

**Issue by Aoeoy** [railmapgen/rmg-palette#729]
**Reference link:** https://baike.baidu.com/item/%E7%8F%A0%E6%B5%B7%E5%9C%B0%E9%93%81/1516356?fr=ge_ala

**Justification:** 根据百度百科对珠海地铁的百科词条阐述内容进行编写，珠海地铁目前仍处于前期筹备状态，但具体线路已经明确

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "珠海",
    "country": "CN",
    "name": {
        "en": "Zhuhai",
        "zh-Hans": "珠海",
        "zh-Hant": "珠海"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "ZH-1",
        "colour": "#ed9c55",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "一号线",
            "zh-Hant": "一號線"
        }
    },
    {
        "id": "ZH-2",
        "colour": "#7f4080",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "二号线",
            "zh-Hant": "二號線"
        }
    },
    {
        "id": "ZHT-1",
        "colour": "#08ade9",
        "fg": "#fff",
        "name": {
            "en": "Tram Line 1",
            "zh-Hans": "有轨电车一号线",
            "zh-Hant": "有軌電車一號線"
        }
    },
    {
        "id": "ZHT-2",
        "colour": "#04ab53",
        "fg": "#fff",
        "name": {
            "en": "Tram Line 1",
            "zh-Hans": "有轨电车二号线",
            "zh-Hant": "有軌電車二號線"
        }
    },
    {
        "id": "ZIR-A",
        "colour": "#348dc4",
        "fg": "#fff",
        "name": {
            "en": "Zhuhai Airport Intercity Rail",
            "zh-Hans": "珠机城际轨道",
            "zh-Hant": "珠機城際軌道"
        }
    },
    {
        "id": "ZIR-GZ",
        "colour": "#c71121",
        "fg": "#fff",
        "name": {
            "en": "Guangzhou Zhuhai Intercity Rail Transit",
            "zh-Hans": "广珠城际轨道",
            "zh-Hant": "廣州珠城際軌道"
        }
    },
    {
        "id": "LRT-ZH",
        "colour": "#3491c7",
        "fg": "#fff",
        "name": {
            "en": "Macao LRT System",
            "zh-Hans": "澳门轻轨",
            "zh-Hant": "澳門捷運"
        }
    }
]</details>

**Comment by wongchito** [comment]
Close as duplicated with #730
