### ISSUE TITLE
资源：上海的新调色板

### ISSUE THREAD

**Issue by 15915996690** [railmapgen/rmg-palette#732]
**Reference link:** https://baike.baidu.com/item/广州地铁16号线/9406383?fr=ge_ala

**Justification:** https://baike.baidu.com/item/广州地铁16号线/9406383?fr=ge_ala

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shanghai",
    "country": "CN",
    "name": {
        "en": "Shanghai",
        "zh-Hans": "上海",
        "zh-Hant": "上海"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "maglev",
        "colour": "#009090",
        "fg": "#fff",
        "name": {
            "en": "Shanghai Maglev Train",
            "zh-Hans": "磁浮线",
            "zh-Hant": "磁浮線"
        }
    },
    {
        "id": "jsr",
        "colour": "#000000",
        "fg": "#fff",
        "name": {
            "zh-Hans": "金山铁路",
            "en": "Jinshan Railway",
            "zh-Hant": " "
        }
    },
    {
        "id": "482",
        "colour": "#a96f3e",
        "fg": "#fff",
        "name": {
            "zh-Hans": "482",
            "zh-Hant": "482",
            "en": "482"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @15915996690 ,

閣下提供的來源、所修改的城市及顏色並不對應。現關閉該Issue。
