### ISSUE TITLE
Resources: New palettes of Shanghai

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmg-palette#734]
**Reference link:** https://www.shmetro.com

**Justification:** 新增金山铁路繁体中文

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "shanghai",
    "country": "CN",
    "name": {
        "en": "Shanghai",
        "zh-Hans": "上海",
        "zh-Hant": "上海"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sh1",
        "colour": "#E3002B",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "sh2",
        "colour": "#8CC220",
        "fg": "#000",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "sh3",
        "colour": "#FCD600",
        "fg": "#000",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "sh4",
        "colour": "#461D84",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "sh5",
        "colour": "#944D9A",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "sh6",
        "colour": "#D40068",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "sh7",
        "colour": "#ED6F00",
        "fg": "#000",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "sh8",
        "colour": "#0094D8",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "sh9",
        "colour": "#87CAED",
        "fg": "#000",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "sh10",
        "colour": "#C6AFD4",
        "fg": "#000",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "sh11",
        "colour": "#871C2B",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "sh12",
        "colour": "#007B61",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "sh13",
        "colour": "#E999C0",
        "fg": "#000",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "sh14",
        "colour": "#626020",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "sh15",
        "colour": "#BCA886",
        "fg": "#000",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "sh16",
        "colour": "#98D1C0",
        "fg": "#000",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "sh17",
        "colour": "#BC796F",
        "fg": "#fff",
        "name": {
            "en": "Line 17",
            "zh-Hans": "17号线",
            "zh-Hant": "17號線"
        }
    },
    {
        "id": "sh18",
        "colour": "#C4984F",
        "fg": "#000",
        "name": {
            "en": "Line 18",
            "zh-Hans": "18号线",
            "zh-Hant": "18號線"
        }
    },
    {
        "id": "sh19",
        "colour": "#48864D",
        "fg": "#fff",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线",
            "zh-Hant": "19號線"
        }
    },
    {
        "id": "sh20",
        "colour": "#365299",
        "fg": "#fff",
        "name": {
            "en": "Line 20",
            "zh-Hans": "20号线",
            "zh-Hant": "20號線"
        }
    },
    {
        "id": "sh21",
        "colour": "#D6C66C",
        "fg": "#000",
        "name": {
            "en": "Line 21",
            "zh-Hans": "21号线",
            "zh-Hant": "21號線"
        }
    },
    {
        "id": "sh23",
        "colour": "#E0815E",
        "fg": "#fff",
        "name": {
            "en": "Line 23",
            "zh-Hans": "23号线",
            "zh-Hant": "23號線"
        }
    },
    {
        "id": "pjl",
        "colour": "#B5B5B6",
        "fg": "#fff",
        "name": {
            "en": "Pujiang Line",
            "zh-Hans": "浦江线",
            "zh-Hant": "浦江線"
        }
    },
    {
        "id": "t1",
        "colour": "#FF0000",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T1",
            "zh-Hans": "松江有轨电车1号线",
            "zh-Hant": "松江有軌電車1號線"
        }
    },
    {
        "id": "t2",
        "colour": "#46837B",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T2",
            "zh-Hans": "松江有轨电车2号线",
            "zh-Hant": "松江有軌電車2號線"
        }
    },
    {
        "id": "t3",
        "colour": "#009400",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T3",
            "zh-Hans": "松江有轨电车3号线",
            "zh-Hant": "松江有軌電車3號線"
        }
    },
    {
        "id": "t4",
        "colour": "#FF00FF",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T4",
            "zh-Hans": "松江有轨电车4号线",
            "zh-Hant": "松江有軌電車4號線"
        }
    },
    {
        "id": "t5",
        "colour": "#00FD00",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T5",
            "zh-Hans": "松江有轨电车5号线",
            "zh-Hant": "松江有軌電車5號線"
        }
    },
    {
        "id": "t6",
        "colour": "#6E00DD",
        "fg": "#fff",
        "name": {
            "en": "Songjiang Tram T6",
            "zh-Hans": "松江有轨电车6号线",
            "zh-Hant": "松江有軌電車6號線"
        }
    },
    {
        "id": "maglev",
        "colour": "#009090",
        "fg": "#fff",
        "name": {
            "en": "Shanghai Maglev Train",
            "zh-Hans": "磁浮线",
            "zh-Hant": "磁浮線"
        }
    },
    {
        "id": "jsr",
        "colour": "#000000",
        "fg": "#fff",
        "name": {
            "zh-Hans": "金山铁路",
            "en": "Jinshan Railway",
            "zh-Hant": "金山鐵路"
        }
    },
    {
        "id": "airport",
        "colour": "#266883",
        "fg": "#fff",
        "name": {
            "en": "Airport Link Line",
            "zh-Hans": "机场联络线",
            "zh-Hant": "機場聯絡線"
        }
    },
    {
        "id": "jiamin",
        "colour": "#733C54",
        "fg": "#fff",
        "name": {
            "en": "Jiamin Line",
            "zh-Hans": "嘉闵线",
            "zh-Hant": "嘉閔線"
        }
    },
    {
        "id": "chongming",
        "colour": "#6BB392",
        "fg": "#000",
        "name": {
            "en": "Chongming Line",
            "zh-Hans": "崇明线",
            "zh-Hant": "崇明線"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的调色板无问题，请等待管理员最终汇入，感谢您的贡献。
 您好，您所提交的調色板無問題，請等待管理員最終匯入，感謝您的貢獻。
 Hello, there is no problem with the color palette you submitted, please wait for the administrator to finally import it, thank you for your contribution. 
안녕하세요, 제출하신 색상 팔레트에는 문제가 없습니다, 관리자가 최종적으로 가져올 때까지 기다려주세요, 기여해 주셔서 감사합니다.
