### ISSUE TITLE
Resources: New palettes of Teyvat

### ISSUE THREAD

**Issue by ATres001** [railmapgen/rmg-palette#748]
**Reference link:** https://webstatic.mihoyo.com/ys/app/interactive-map/index.html?lang=zh-cn#/map/2?shown_types=&center=-121.32,757.79&zoom=0.50

**Justification:** 无，自用调色板

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="country">{
    "id": "MU",
    "name": {
        "en": "miyouni",
        "zh-Hans": "米游宙"
    },
    "language": "zh-Hans"
}</details>

<details repo="rmg-palette" type="city">{
    "id": "teyvat",
    "country": "MU",
    "name": {
        "en": "Teyvat",
        "zh-Hans": "提瓦特"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "l1",
        "colour": "#980000",
        "fg": "#fff",
        "name": {
            "zh-Hans": "line1"
        }
    },
    {
        "id": "l2",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "zh-Hans": "line2"
        }
    },
    {
        "id": "l3",
        "colour": "#ff9900",
        "fg": "#fff",
        "name": {
            "zh-Hans": "line3"
        }
    },
    {
        "id": "l4",
        "colour": "#9900ff",
        "fg": "#fff",
        "name": {
            "zh-Hans": "line4"
        }
    },
    {
        "id": "l5",
        "colour": "#0000ff",
        "fg": "#fff",
        "name": {
            "zh-Hans": "line5"
        }
    },
    {
        "id": "l6",
        "colour": "#4a86e8",
        "fg": "#fff",
        "name": {
            "zh-Hans": "line6"
        }
    },
    {
        "id": "l7",
        "colour": "#ff00d0",
        "fg": "#fff",
        "name": {
            "zh-Hans": "line7"
        }
    },
    {
        "id": "l8",
        "colour": "#73ff00",
        "fg": "#fff",
        "name": {
            "zh-Hans": "line8"
        }
    },
    {
        "id": "l9",
        "colour": "#00e1ff",
        "fg": "#fff",
        "name": {
            "zh-Hans": "line9"
        }
    },
    {
        "id": "me1",
        "colour": "#006b6b",
        "fg": "#fff",
        "name": {
            "zh-Hans": "mondexpress1"
        }
    },
    {
        "id": "me2",
        "colour": "#366b36",
        "fg": "#fff",
        "name": {
            "zh-Hans": "mondexpress2"
        }
    },
    {
        "id": "le1",
        "colour": "#ffff00",
        "fg": "#000",
        "name": {
            "zh-Hans": "liyueexpress1"
        }
    },
    {
        "id": "le2",
        "colour": "#b8b800",
        "fg": "#000",
        "name": {
            "zh-Hans": "liyueexpress2"
        }
    },
    {
        "id": "ie1",
        "colour": "#873691",
        "fg": "#fff",
        "name": {
            "zh-Hans": "Inazumaexpress1"
        }
    },
    {
        "id": "ie2",
        "colour": "#7100bd",
        "fg": "#fff",
        "name": {
            "zh-Hans": "Inazumaexpress2"
        }
    },
    {
        "id": "se1",
        "colour": "#8cff00",
        "fg": "#000",
        "name": {
            "zh-Hans": "Sumeruexpress1"
        }
    },
    {
        "id": "se2",
        "colour": "#00ff11",
        "fg": "#000",
        "name": {
            "zh-Hans": "Sumeruexpress2"
        }
    },
    {
        "id": "t1",
        "colour": "#000000",
        "fg": "#fff",
        "name": {
            "zh-Hans": "ICE - 1"
        }
    },
    {
        "id": "t2",
        "colour": "#404040",
        "fg": "#fff",
        "name": {
            "zh-Hans": "ICE - 2"
        }
    },
    {
        "id": "t3",
        "colour": "#808080",
        "fg": "#fff",
        "name": {
            "zh-Hans": "ICE - 3"
        }
    },
    {
        "id": "t4",
        "colour": "#c0c0c0",
        "fg": "#000",
        "name": {
            "zh-Hans": "ICE - 4"
        }
    },
    {
        "id": "t5",
        "colour": "#ffffff",
        "fg": "#000",
        "name": {
            "zh-Hans": "ICE - 5"
        }
    }
]</details>

**Comment by linchen1965** [comment]
您好，很抱歉我们不接受非现实世界的颜色库投稿

**Comment by ATres001** [comment]
> 您好，很抱歉我们不接受非现实世界的颜色库投稿

@linchen1965 
已阅，谢谢您的审核以及回复. 可以理解无法添加非现实世界的颜色库投稿，不过希望未来的更新中可以推出本地调色板
送上诚挚的祝福 Atres
