### ISSUE TITLE
Resources: New palettes of Genova

### ISSUE THREAD

**Issue by polygon827** [railmapgen/rmg-palette#750]
**Reference link:** http://www.metrogenova.com/

**Justification:** 熱那亞

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "genoa",
    "country": "IT",
    "name": {
        "en": "Genoa",
        "zh-Hans": "热那亚",
        "zh-Hant": "熱那亞"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "m",
        "colour": "#fb0000",
        "fg": "#fff",
        "name": {
            "en": "Metro",
            "zh-Hans": "地铁",
            "zh-Hant": "地鐵",
            "it": "Metropolitana"
        }
    },
    {
        "id": "zl",
        "colour": "#03c504",
        "fg": "#fff",
        "name": {
            "en": "Zecca-Righi Funicular Railway",
            "zh-Hans": "泽卡-里吉缆车铁路",
            "zh-Hant": "澤卡-里吉纜車鐵路",
            "it": "Funicolare Zecca-Righi"
        }
    },
    {
        "id": "sa",
        "colour": "#027800",
        "fg": "#fff",
        "name": {
            "en": "Sant'Anna Funicular Railway",
            "zh-Hans": "圣安娜缆车铁路",
            "zh-Hant": "聖安娜纜車鐵路",
            "it": "Funicolare Sant'Anna"
        }
    },
    {
        "id": "fpg",
        "colour": "#eac55d",
        "fg": "#fff",
        "name": {
            "en": "Principe-Granarolo Rack Railway",
            "zh-Hans": "普林西比-格拉那罗洛齿轨铁路",
            "zh-Hant": "普林西比-格拉那羅洛齒軌鐵路",
            "it": "Ferrovia a Cremagliera Principe-Granarolo"
        }
    },
    {
        "id": "gc",
        "colour": "#be05c2",
        "fg": "#fff",
        "name": {
            "en": "Genova-Casella Railway",
            "zh-Hans": "热那亚-卡塞拉铁路",
            "zh-Hant": "熱那亞-卡塞拉鐵路",
            "it": "Ferrovia Genova-Casella"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @polygon827 ,

由於本人不諳意大利文，無法從閣下提供的網站找到路線圖或相關資訊。請提供直達路線圖/顏色的頁面連結，多謝！

**Comment by polygon827** [comment]
http://www.metrogenova.com/percorso.asp

**Comment by polygon827** [comment]
http://www.metrogenova.com/gecasella.asp

**Comment by polygon827** [comment]
https://www.urbanrail.net/eu/it/gen/genova.htm
