### ISSUE TITLE
Resources: New palettes of Wuhu

### ISSUE THREAD

**Issue by Wuyirende** [railmapgen/rmg-palette#754]
**Reference link:** https://mbd.baidu.com/ma/s/bA4KEEsS

**Justification:** 提供芜湖的颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "wuhu",
    "country": "CN",
    "name": {
        "en": "Wuhu",
        "zh-Hans": "芜湖",
        "zh-Hant": "蕪湖"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "wuhu1",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "wuhu2",
        "colour": "#007aff",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    }
]</details>

**Comment by langonginc** [comment]
很抱歉我们不接受百度的数据，请您搜寻官方数据或维基百科数据，谢谢。
