### ISSUE TITLE
Resources: New palettes of Chuzhou

### ISSUE THREAD

**Issue by ulanbayar** [railmapgen/rmg-palette#769]
**Reference link:** https://railmapgengithub.io

**Justification:** 与南京地铁一致

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "chuzhou",
    "country": "CN",
    "name": {
        "en": "Chuzhou",
        "zh-Hans": "滁州",
        "zh-Hant": "滁州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "ningchu",
        "colour": "#ff631b",
        "fg": "#fff",
        "name": {
            "en": "Ningchu Line",
            "zh-Hans": "S4号线/宁滁线",
            "zh-Hant": "S4號綫/寧滁線"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @ulanbayar ,

該路線從滁州角度不應被稱作「S4號線」 。因此該變更不被接納。
