### ISSUE TITLE
Resources: New palettes of Belo Horizonte

### ISSUE THREAD

**Issue by teossmelo** [railmapgen/rmg-palette#777]
**Reference link:** https://en.wikipedia.org/wiki/Belo_Horizonte_Metro

**Justification:** add this city

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "bhz",
    "country": "BR",
    "name": {
        "en": "Belo Horizonte",
        "pt": "Belo Horizonte",
        "zh-Hans": "贝洛奥里藏特",
        "zh-Hant": "貝洛奧里藏特"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "bh1",
        "colour": "#0000ff",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "pt": "Linha 1"
        }
    }
]</details>

**Comment by wongchito** [comment]
Hi @teossmelo ,

The colour you've provided does not match the colours used in Wikipedia. Please check and fix it. 

Also, as Wikipedia contains future lines (Line 2 to 4), we appreciate if you can add them together. 

Thank you.
