### ISSUE TITLE
Resources: New palettes of Newcastle

### ISSUE THREAD

**Issue by Jimmilily** [railmapgen/rmg-palette#819]
Hi RMG team! I would like to contribute the palettes below.

**Reference link:** https://transportnsw.info/routes/lightrail

**Justification:** Added city of Newcastle (New South Wales, Australia)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "newcastle",
    "country": "AU",
    "name": {
        "en": "Newcastle",
        "zh-Hans": "纽卡斯尔",
        "zh-Hant": "紐卡斯爾"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "nlr",
        "colour": "#ee343f",
        "fg": "#fff",
        "name": {
            "en": "Newcastle Light Rail",
            "zh-Hans": "纽卡斯尔轻轨",
            "zh-Hant": "紐卡斯爾輕軌"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
Hello, there is no problem with the template you submitted, please wait for the administrator to finally import it, thank you for your contribution.
