### ISSUE TITLE
Resources: New palettes of Nanjing

### ISSUE THREAD

**Issue by WIWO-ZHANG** [railmapgen/rmg-palette#844]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://baike.baidu.com/item/%E5%8D%97%E4%BA%AC%E5%9C%B0%E9%93%818%E5%8F%B7%E7%BA%BF/10000718?fr=ge_ala
https://baike.baidu.com/item/%E5%8D%97%E4%BA%AC%E6%B2%B3%E8%A5%BF%E6%9C%89%E8%BD%A8%E7%94%B5%E8%BD%A6/16911442?fr=ge_ala
https://baike.baidu.com/item/%E5%8D%97%E4%BA%AC%E9%BA%92%E9%BA%9F%E6%9C%89%E8%BD%A8%E7%94%B5%E8%BD%A6/9362247?fr=ge_ala

**Justification:** 添加8号线，有轨电车的标识色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "nanjing",
    "country": "CN",
    "name": {
        "en": "Nanjing",
        "zh-Hans": "南京",
        "zh-Hant": "南京"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "nj1",
        "colour": "#009ace",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "nj2",
        "colour": "#c8003f",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "nj3",
        "colour": "#009a44",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "nj4",
        "colour": "#7d55c7",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "nj5",
        "colour": "#FDDA24",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "nj6",
        "colour": "#00b2a9",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "nj7",
        "colour": "#4A7729",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "8",
        "colour": "#f6b402",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "nj9",
        "colour": "#fa4616",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "nj10",
        "colour": "#b9975b",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "nj11",
        "colour": "#ef426f",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "s1",
        "colour": "#00b2a9",
        "fg": "#fff",
        "name": {
            "en": "Line S1/Airport Line",
            "zh-Hans": "S1号线/机场线",
            "zh-Hant": "S1號線/機場線"
        }
    },
    {
        "id": "s3",
        "colour": "#b06096",
        "fg": "#fff",
        "name": {
            "en": "Line S3/Ninghe Line",
            "zh-Hans": "S3号线/宁和线",
            "zh-Hant": "S3號線/寧和線"
        }
    },
    {
        "id": "s4",
        "colour": "#ff6314",
        "fg": "#fff",
        "name": {
            "en": "Line S4/Ningchu Line",
            "zh-Hans": "S4号线/宁滁线",
            "zh-Hant": "S4號線/寧滁線"
        }
    },
    {
        "id": "s6",
        "colour": "#C98BDB",
        "fg": "#fff",
        "name": {
            "en": "Line S6/Ningju Line",
            "zh-Hans": "S6号线/宁句线",
            "zh-Hant": "S6號線/寧句線"
        }
    },
    {
        "id": "s7",
        "colour": "#e89cae",
        "fg": "#fff",
        "name": {
            "en": "Line S7/Ningli Line",
            "zh-Hans": "S7号线/宁溧线",
            "zh-Hant": "S7號線/寧溧線"
        }
    },
    {
        "id": "s8",
        "colour": "#ea7600",
        "fg": "#fff",
        "name": {
            "en": "Line S8/Ningtian Line",
            "zh-Hans": "S8号线/宁天线",
            "zh-Hant": "S8號線/寧天線"
        }
    },
    {
        "id": "s9",
        "colour": "#f1b434",
        "fg": "#fff",
        "name": {
            "en": "Line S9/Ninggao Line",
            "zh-Hans": "S9号线/宁高线",
            "zh-Hant": "S9號線/寧高線"
        }
    },
    {
        "id": "nhmt",
        "colour": "#47efff",
        "fg": "#fff",
        "name": {
            "en": "Nanjing Hexi Modern Tram",
            "zh-Hans": "南京河西有轨电车",
            "zh-Hant": "南京河西有軌電車"
        }
    },
    {
        "id": "nqmt",
        "colour": "#58c45b",
        "fg": "#fff",
        "name": {
            "en": "Nanjing Qilin Modern Tram",
            "zh-Hans": "南京麒麟有轨电车",
            "zh-Hant": "南京河西有軌電車"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，我们暂不信任来自百度百科的参考来源，建议您使用维基百科或铁路公司官方网站作为参考来源，感谢您的贡献。
