### ISSUE TITLE
Resources: New palettes of Dalian

### ISSUE THREAD

**Issue by 1001NB** [railmapgen/rmg-palette#858]
**Reference link:** https://railmapgen.github.io/?app=rmg-palette-upload

**Justification:** 我是大连的所以就想用自己城市的地铁号码和颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "dalian",
    "country": "CN",
    "name": {
        "en": "Dalian",
        "zh-Hans": "大连",
        "zh-Hant": "大連"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "dl1",
        "colour": "#00944B",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "dl2",
        "colour": "#009CD8",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "dl3",
        "colour": "#E1017C",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "dl4",
        "colour": "#5D2D29",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "dl5",
        "colour": "#E50309",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "dl6",
        "colour": "#1D1F8A",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "dl7",
        "colour": "#F58427",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "dl8",
        "colour": "#00601E",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "dl9",
        "colour": "#63C1C0",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "dl10",
        "colour": "#53C2F9",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "dl11",
        "colour": "#DE83A6",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "dl12",
        "colour": "#554B9B",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "dl13",
        "colour": "#F0C701",
        "fg": "#fff",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，请按照#864 的指引将参考链接改为我们符合标准的链接，感谢您的贡献，

**Comment by wongchito** [comment]
Hi @1001NB ,

由於閣下提交的調色盤數據與既有的完全一致，因此關閉該Issue。
