### ISSUE TITLE
Resources: New palettes of Hacker World

### ISSUE THREAD

**Issue by hackerfyl** [railmapgen/rmg-palette#86]
**Justification:** (We are about to create a railway system for the city.)

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">
{
    "id": "hackerworld",
    "country": "HW",
    "name": {
        "en": "Hacker World",
        "zh-Hans": "骇客世界"
    }
}
</details>

<details repo="rmg-palette" type="lines">
[
    {
        "id": "1",
        "colour": "#00B5E2",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "2",
        "colour": "#F3D03E",
        "fg": "#000",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "3",
        "colour": "#D42D1B",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "4",
        "colour": "#ECA154",
        "fg": "#000",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "5",
        "colour": "#00843D",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "6",
        "colour": "#80225F",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "7",
        "colour": "#97D700",
        "fg": "#000",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "8",
        "colour": "#0047BA",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    }
]
</details>

**Comment by 52PD** [comment]
@thekingofcity @wongchito 我记得你们好像是不接受就现实中不存在的城市的地铁系统的颜色和线路图的对吧？

**Comment by thekingofcity** [comment]
嗨，我们暂不支持非现实世界中的调色板，感谢您对项目的支持！
