### ISSUE TITLE
Resources: New palettes of Hangzhou

### ISSUE THREAD

**Issue by Topiours** [railmapgen/rmg-palette#860]
**Reference link:** https://wx.hzmetro.com/index/index/dlt

**Justification:** 修復了2號綫較大的色差，并對其它綫路進行校準。由於19號綫在實際運營中從未使用過“機場快綫”的名稱，故去除。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hangzhou",
    "country": "CN",
    "name": {
        "en": "Hangzhou",
        "zh-Hans": "杭州",
        "zh-Hant": "杭州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "hz1",
        "colour": "#e8384a",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "hz2",
        "colour": "#ed6d00",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "hz3",
        "colour": "#ffcf23",
        "fg": "#000",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "hz4",
        "colour": "#60c04b",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "hz5",
        "colour": "#00afc8",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "hz6",
        "colour": "#0077cf",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "hz7",
        "colour": "#790f8e",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "hz8",
        "colour": "#a80d4d",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "hz9",
        "colour": "#BE4D00",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "hz10",
        "colour": "#daaa00",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "hz16",
        "colour": "#ffaa52",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "hz19",
        "colour": "#4acbe5",
        "fg": "#fff",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线",
            "zh-Hant": "19號線"
        }
    }
]</details>

**Comment by Takagi-Misae** [comment]
![image](https://github.com/railmapgen/rmg-palette/assets/143057061/35c07846-60f7-48a3-8cb8-554db80fe0ce)

您好，根据杭州地铁颜色在维基百科的模版页面
在您提交的模版中，除了10号线以外，其他在校准前的色号才是正确的
但是关于19号线的机场快线名称，是需要修改的
请把所有路线的色号，换成维基百科的色号，并修改机场快线的名称，再重新提交。
请等待管理员关闭本资源，不好意思😬。

**Comment by wongchito** [comment]
Hi @Topiours , @Charlis-Wong ,

根據 #864 中提及的標準，我們接納該顏色來源。但經檢查發現，2號線及9號線顏色與來源網站並不相同，因此我們將其修改，令所有路線顏色取得方式一致。如閣下對我們的修改不滿意，請重新開啟Issue並附上理由。多謝閣下的貢獻！

<img width="793" alt="image" src="https://github.com/railmapgen/rmg-palette/assets/9390786/9ea63e7f-b60c-4102-8120-a41c57fbc75b">

<img width="793" alt="image" src="https://github.com/railmapgen/rmg-palette/assets/9390786/d78bbb43-2de9-4ca8-a99f-3fcab48178d0">

**Comment by Charlis-Wong** [comment]
> Hi @Topiours , @Charlis-Wong ,
> 
> 根據 #864 中提及的標準，我們接納該顏色來源。但經檢查發現，2號線及9號線顏色與來源網站並不相同，因此我們將其修改，令所有路線顏色取得方式一致。如閣下對我們的修改不滿意，請重新開啟Issue並附上理由。多謝閣下的貢獻！
> 
> <img alt="image" width="793" src="https://user-images.githubusercontent.com/9390786/270162929-9ea63e7f-b60c-4102-8120-a41c57fbc75b.png"> <img alt="image" width="793" src="https://user-images.githubusercontent.com/9390786/270162971-d78bbb43-2de9-4ca8-a99f-3fcab48178d0.png">

我是十分滿意本次修改的，但是我的評論是在修改之前發出的，所以跟不到新的規則
所以現在已經合拼了就ok了，感謝🙏
