### ISSUE TITLE
Resources: New palettes of Sendai

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmg-palette#866]
**Reference link:** https://www.kotsu.city.sendai.jp/subway/station/pdf/2023nswe_rail.pdf

**Justification:** Add Sendai Metro palette.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "sendai",
    "country": "JP",
    "name": {
        "en": "Sendai",
        "zh-Hans": "仙台",
        "zh-Hant": "仙台",
        "ja": "仙台",
        "ko": "센다이"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sdn",
        "colour": "#317c66",
        "fg": "#fff",
        "name": {
            "en": "Namboku Line (N)",
            "zh-Hans": "南北线（N）",
            "zh-Hant": "南北線（N）",
            "ja": "南北線（N）",
            "ko": "난보쿠선（N）"
        }
    },
    {
        "id": "sdt",
        "colour": "#00b1dd",
        "fg": "#fff",
        "name": {
            "en": "Tozai Line (T)",
            "zh-Hans": "东西线（T）",
            "zh-Hant": "東西線（T）",
            "ja": "東西線（T）",
            "ko": "도자이선（T）"
        }
    }
]</details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本沒有問題，請等待管理員合拼至範本，謝謝🙏

審核來源：
![image](https://github.com/railmapgen/rmg-palette/assets/143057061/b37373ac-071b-4ca4-923f-cbbff92ed06a)
![image](https://github.com/railmapgen/rmg-palette/assets/143057061/12dcffba-938e-4cd7-b18d-beeb94ad9c8b)
