### ISSUE TITLE
Resources: New palettes of Nagoya

### ISSUE THREAD

**Issue by HUQIUAN** [railmapgen/rmg-palette#873]
**Reference link:** https://www.kotsu.city.nagoya.jp/jp/pc/subway/images/subway_routemap.png

**Justification:** Add Nagoya palette.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "nagoya",
    "country": "JP",
    "name": {
        "en": "Nagoya",
        "zh-Hans": "名古屋",
        "zh-Hant": "名古屋",
        "ja": "名古屋",
        "ko": "나고야"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "h",
        "colour": "#fab123",
        "fg": "#fff",
        "name": {
            "en": "Higashiyama Line",
            "zh-Hans": "东山线",
            "zh-Hant": "東山線",
            "ja": "東山線",
            "ko": "히가시야마선"
        }
    },
    {
        "id": "m",
        "colour": "#b074d6",
        "fg": "#fff",
        "name": {
            "en": "Meijo Line",
            "zh-Hans": "名城线",
            "zh-Hant": "名城線",
            "ja": "名城線",
            "ko": "메이조선"
        }
    },
    {
        "id": "e",
        "colour": "#b074d6",
        "fg": "#fff",
        "name": {
            "en": "Meiko Line",
            "zh-Hans": "名港线",
            "zh-Hant": "名港線",
            "ja": "名港線",
            "ko": "메이코선"
        }
    },
    {
        "id": "t",
        "colour": "#009bbf",
        "fg": "#fff",
        "name": {
            "en": "Tsurumai Line",
            "zh-Hans": "鹤舞线",
            "zh-Hant": "鶴舞線",
            "ja": "鶴舞線",
            "ko": "쓰루마이선"
        }
    },
    {
        "id": "s",
        "colour": "#c92f44",
        "fg": "#fff",
        "name": {
            "en": "Sakura-dori Line",
            "zh-Hans": "樱通线",
            "zh-Hant": "櫻通線",
            "ja": "桜通線",
            "ko": "사쿠라도리선"
        }
    },
    {
        "id": "k",
        "colour": "#fc78b4",
        "fg": "#fff",
        "name": {
            "en": "Kamiiida Line",
            "zh-Hans": "上饭田线",
            "zh-Hant": "上飯田線",
            "ja": "上飯田線",
            "ko": "가미이다선"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
