### ISSUE TITLE
Resources: New palettes of Wuhan

### ISSUE THREAD

**Issue by DQB061204** [railmapgen/rmg-palette#877]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://zh.wikipedia.org/wiki/%E6%AD%A6%E6%B1%89%E5%85%89%E8%B0%B7%E7%8E%B0%E4%BB%A3%E6%9C%89%E8%BD%A8%E7%94%B5%E8%BD%A6#/media/File:%E6%AD%A6%E6%B1%89%E5%85%89%E8%B0%B7%E7%8E%B0%E4%BB%A3%E6%9C%89%E8%BD%A8%E7%94%B5%E8%BD%A6%E8%B5%B0%E5%90%91%E5%9B%BE.png

**Justification:** 另外：空轨链接为：https://www.whggjtjs.com/#/listContent/375_1775

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "wuhan",
    "country": "CN",
    "name": {
        "en": "Wuhan",
        "zh-Hans": "武汉",
        "zh-Hant": "武漢"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "wh1",
        "colour": "#3D84C6",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "wh2",
        "colour": "#EB7CAF",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "wh3",
        "colour": "#D9B966",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "wh4",
        "colour": "#8EC720",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "wh5",
        "colour": "#a62e37",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "wh6",
        "colour": "#008536",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "wh7",
        "colour": "#EB7900",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "wh8",
        "colour": "#98ACAB",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "wh9",
        "colour": "#A5D4AD",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "wh10",
        "colour": "#8C3626",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "wh11",
        "colour": "#F2CF01",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "wh12",
        "colour": "#00A3E9",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "wh13",
        "colour": "#25CAD0",
        "fg": "#fff",
        "name": {
            "en": "Line 13",
            "zh-Hans": "13号线",
            "zh-Hant": "13號線"
        }
    },
    {
        "id": "wh14",
        "colour": "#7D55A3",
        "fg": "#fff",
        "name": {
            "en": "Line 14",
            "zh-Hans": "14号线",
            "zh-Hant": "14號線"
        }
    },
    {
        "id": "wh16",
        "colour": "#CC0256",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "wh21",
        "colour": "#CF0192",
        "fg": "#fff",
        "name": {
            "en": "Line 21",
            "zh-Hans": "21号线",
            "zh-Hant": "21號線"
        }
    },
    {
        "id": "whggkg",
        "colour": "#05aff1",
        "fg": "#fff",
        "name": {
            "en": "Suspended Monorail Line",
            "zh-Hans": "空轨旅游线",
            "zh-Hant": "空軌旅遊線"
        }
    },
    {
        "id": "whggxdygdcl1",
        "colour": "#0000ff",
        "fg": "#fff",
        "name": {
            "en": "Wuhan Optics Valley Modern Tram Line 1",
            "zh-Hans": "武汉光谷现代有轨电车1号线",
            "zh-Hant": "武漢光谷現代電車1號線"
        }
    },
    {
        "id": "whggxdygdcl2",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Wuhan Optics Valley Modern Tram Line 2",
            "zh-Hans": "武汉光谷现代有轨电车2号线",
            "zh-Hant": "武漢光谷現代電車2號線"
        }
    },
    {
        "id": "whggxdygdcl5",
        "colour": "#818181",
        "fg": "#fff",
        "name": {
            "en": "Wuhan Optics Valley Modern Tram Line 5 (Event Time Only)",
            "zh-Hans": "武汉光谷现代有轨电车5号线（大型活动开行）",
            "zh-Hant": "武漢光谷現代電車5號線（大型活動開行）"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
