### ISSUE TITLE
Resources: New palettes of Hangzhou

### ISSUE THREAD

**Issue by HangzhouMetro** [railmapgen/rmg-palette#886]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://www.163.com/dy/article/HCSKF78Q051492LM_pdya11y.html

**Justification:** 增加了杭州四期线路：12、15、18

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hangzhou",
    "country": "CN",
    "name": {
        "en": "Hangzhou",
        "zh-Hans": "杭州",
        "zh-Hant": "杭州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "hz1",
        "colour": "#e8384a",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "hz2",
        "colour": "#e17901",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "hz3",
        "colour": "#ffcf23",
        "fg": "#000",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "hz4",
        "colour": "#60c04b",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "hz5",
        "colour": "#00afc8",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "hz6",
        "colour": "#0077cf",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "hz7",
        "colour": "#790f8e",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "hz8",
        "colour": "#a80d4d",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "hz9",
        "colour": "#c45b03",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "hz10",
        "colour": "#daaa00",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "hz12",
        "colour": "#00778f",
        "fg": "#fff",
        "name": {
            "en": "Line 12",
            "zh-Hans": "12号线",
            "zh-Hant": "12號線"
        }
    },
    {
        "id": "hz15",
        "colour": "#fe86de",
        "fg": "#fff",
        "name": {
            "en": "Line 15",
            "zh-Hans": "15号线",
            "zh-Hant": "15號線"
        }
    },
    {
        "id": "hz16",
        "colour": "#ffaa52",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "hz18",
        "colour": "#71fe71",
        "fg": "#fff",
        "name": {
            "en": "Line 18",
            "zh-Hans": "18号线",
            "zh-Hant": "18號線"
        }
    },
    {
        "id": "hz19",
        "colour": "#4acbe5",
        "fg": "#fff",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线",
            "zh-Hant": "19號線"
        }
    }
]</details>

**Comment by Charlis-Wong** [comment]
您好，請將（REPLACE ME/替代我）刪除，以便Bot識別，感謝您的配合。

**Comment by HangzhouMetro** [comment]
怎样去掉

**Comment by Charlis-Wong** [comment]
編輯，然后去除他就行
![image](https://github.com/railmapgen/rmg-palette/assets/143057061/e8aed110-cbb9-4569-a925-fdb1dc7a353f)

**Comment by Windows-Taskmgr** [comment]
您好，您的参考链接不不符合我们的标准，请您按照 #864 中的要求重新提交，感谢您的贡献。
