### ISSUE TITLE
Resources: New palettes of Hokkaido

### ISSUE THREAD

**Issue by LYSliuyisi** [railmapgen/rmg-palette#891]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://www.jrhokkaido.co.jp/network/index.html

**Justification:** 1. 根据官网调整了线路名称，所有原名为“OO本线”的线路全部更改为“OOxin线”。
2. 根据官网更正了线路颜色。
3. 添加两条新线路：北海道新干线、道南渔火铁道。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hokkaido",
    "country": "JP",
    "name": {
        "en": "Hokkaido",
        "zh-Hans": "北海道",
        "ja": "北海道",
        "zh-Hant": "北海道"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "hoh",
        "colour": "#066fc2",
        "fg": "#fff",
        "name": {
            "en": "Muroran Line · Hakodate Line",
            "zh-Hans": "室兰线 · 函馆线",
            "ja": "室蘭線 · 函館線",
            "zh-Hant": "室蘭線 · 函館線"
        }
    },
    {
        "id": "hos",
        "colour": "#e50401",
        "fg": "#fff",
        "name": {
            "en": "Hakodate Line",
            "zh-Hans": "函馆线",
            "ja": "函館線",
            "zh-Hant": "函館線"
        }
    },
    {
        "id": "hog",
        "colour": "#0d9435",
        "fg": "#fff",
        "name": {
            "en": "Sasshō Line (Gakuen-Toshi Line)",
            "zh-Hans": "札沼线 (学园都市线)",
            "ja": "札沼線 (学園都市線)",
            "zh-Hant": "札沼線 (學圜都市線)"
        }
    },
    {
        "id": "hoap",
        "colour": "#1abeee",
        "fg": "#fff",
        "name": {
            "en": "Chitose Line",
            "zh-Hans": "千岁线",
            "ja": "千歳線",
            "zh-Hant": "千歲線"
        }
    },
    {
        "id": "hoa",
        "colour": "#f07713",
        "fg": "#fff",
        "name": {
            "en": "Sekihoku Line · Hakodate Line",
            "zh-Hans": "石北线 · 函馆线",
            "ja": "石北線 · 函館線",
            "zh-Hant": "石北線 · 函館線"
        }
    },
    {
        "id": "hok",
        "colour": "#47c55b",
        "fg": "#fff",
        "name": {
            "en": "Sekishō Line · Nemuro Line",
            "zh-Hans": "石胜线 · 根室线",
            "ja": "石勝線 · 根室線",
            "zh-Hant": "石勝線 · 根室線"
        }
    },
    {
        "id": "hot",
        "colour": "#ec9fcf",
        "fg": "#fff",
        "name": {
            "en": "Nemuro Line",
            "zh-Hans": "根室线",
            "ja": "根室線",
            "zh-Hant": "根室線"
        }
    },
    {
        "id": "hob",
        "colour": "#e0429b",
        "fg": "#fff",
        "name": {
            "en": "Senmō Line",
            "zh-Hans": "钏网线",
            "ja": "釧網線",
            "zh-Hant": "釧網線"
        }
    },
    {
        "id": "hof",
        "colour": "#9831cf",
        "fg": "#fff",
        "name": {
            "en": "Furano Line",
            "zh-Hans": "富良野线",
            "ja": "富良野線",
            "zh-Hant": "富良野線"
        }
    },
    {
        "id": "how",
        "colour": "#983a4a",
        "fg": "#fff",
        "name": {
            "en": "Sōya Line",
            "zh-Hans": "宗谷线",
            "ja": "宗谷線",
            "zh-Hant": "宗谷線"
        }
    },
    {
        "id": "hoshinkansen",
        "colour": "#413397",
        "fg": "#fff",
        "name": {
            "en": "Hokkaido Shinkansen",
            "zh-Hans": "北海道新干线",
            "zh-Hant": "北海道新幹線",
            "ja": "北海道新幹線"
        }
    },
    {
        "id": "hsh",
        "colour": "#0b4da2",
        "fg": "#fff",
        "name": {
            "en": "South Hokkaido Railway",
            "zh-Hans": "道南渔火铁道",
            "zh-Hant": "道南漁火鐵道",
            "ja": "道南いさりび鉄道"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，您所提交的模板没有问题，请您等待管理员最终汇入，感谢您的贡献。
