### ISSUE TITLE
Resources: New palettes of Suzhou

### ISSUE THREAD

**Issue by beiguangrailtransit** [railmapgen/rmg-palette#894]
**Reference link:** https://baike.baidu.com

**Justification:** 添加苏州有轨电车详情

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "suzhou",
    "country": "CN",
    "name": {
        "en": "Suzhou",
        "zh-Hans": "苏州",
        "zh-Hant": "蘇州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "sz1",
        "colour": "#78BA25",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "sz2",
        "colour": "#ED3240",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "sz3",
        "colour": "#F88211",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "sz4",
        "colour": "#196EAE",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "sz5",
        "colour": "#E63A9A",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "sz6",
        "colour": "#41b6e6",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "sz7",
        "colour": "#a77bca",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "sz8",
        "colour": "#a09200",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "sz10",
        "colour": "#ca9a8e",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "sz11",
        "colour": "#f1c6a6",
        "fg": "#fff",
        "name": {
            "en": "Line 11",
            "zh-Hans": "11号线",
            "zh-Hant": "11號線"
        }
    },
    {
        "id": "tram",
        "colour": "#d8e4c0",
        "fg": "#fff",
        "name": {
            "en": "Tram",
            "zh-Hans": "有轨电车",
            "zh-Hant": "有軌電車"
        }
    },
    {
        "id": "wkt",
        "colour": "#dddddd",
        "fg": "#fff",
        "name": {
            "en": "Lines under construction",
            "zh-Hans": "未开通线路",
            "zh-Hant": "未開通線路"
        }
    },
    {
        "id": "szy1",
        "colour": "#84b47d",
        "fg": "#fff",
        "name": {
            "en": "SND Tram Line 1",
            "zh-Hans": "苏州高新有轨电车1号线",
            "zh-Hant": "蘇州高新有軌電車1號線"
        }
    },
    {
        "id": "szy2",
        "colour": "#7a0702",
        "fg": "#fff",
        "name": {
            "en": "SND Tram Line 2",
            "zh-Hans": "苏州高新有轨电车2号线",
            "zh-Hant": "蘇州高新有軌電車2號線"
        }
    },
    {
        "id": "szy5",
        "colour": "#490a69",
        "fg": "#fff",
        "name": {
            "en": "SND Tram Line 5",
            "zh-Hans": "苏州高新有轨电车5号线",
            "zh-Hant": "蘇州高新有軌電車5號線"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，我们暂不接受来自百度百科的数据，请您按照 #864 的要求替换为我们接受的来源，感谢您的贡献。

**Comment by Windows-Taskmgr** [comment]
您好，由于您已经超过一个月未回复，此issue将会被关闭，感谢您的理解。
