### ISSUE TITLE
Resources: New palettes of Hangzhou

### ISSUE THREAD

**Issue by Windows-Taskmgr** [railmapgen/rmg-palette#896]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://zh.wikipedia.org/zh-cn/杭海城际#/media/File:Hangzhou_Haining_Intercity_Railway.svg

**Justification:** 增加杭海城际调色板

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hangzhou",
    "country": "CN",
    "name": {
        "en": "Hangzhou",
        "zh-Hans": "杭州",
        "zh-Hant": "杭州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "hz1",
        "colour": "#e8384a",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "hz2",
        "colour": "#e17901",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "hz3",
        "colour": "#ffcf23",
        "fg": "#000",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "hz4",
        "colour": "#60c04b",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "hz5",
        "colour": "#00afc8",
        "fg": "#fff",
        "name": {
            "en": "Line 5",
            "zh-Hans": "5号线",
            "zh-Hant": "5號線"
        }
    },
    {
        "id": "hz6",
        "colour": "#0077cf",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    },
    {
        "id": "hz7",
        "colour": "#790f8e",
        "fg": "#fff",
        "name": {
            "en": "Line 7",
            "zh-Hans": "7号线",
            "zh-Hant": "7號線"
        }
    },
    {
        "id": "hz8",
        "colour": "#a80d4d",
        "fg": "#fff",
        "name": {
            "en": "Line 8",
            "zh-Hans": "8号线",
            "zh-Hant": "8號線"
        }
    },
    {
        "id": "hz9",
        "colour": "#c45b03",
        "fg": "#fff",
        "name": {
            "en": "Line 9",
            "zh-Hans": "9号线",
            "zh-Hant": "9號線"
        }
    },
    {
        "id": "hz10",
        "colour": "#daaa00",
        "fg": "#fff",
        "name": {
            "en": "Line 10",
            "zh-Hans": "10号线",
            "zh-Hant": "10號線"
        }
    },
    {
        "id": "hz16",
        "colour": "#ffaa52",
        "fg": "#fff",
        "name": {
            "en": "Line 16",
            "zh-Hans": "16号线",
            "zh-Hant": "16號線"
        }
    },
    {
        "id": "hz19",
        "colour": "#4acbe5",
        "fg": "#fff",
        "name": {
            "en": "Line 19",
            "zh-Hans": "19号线",
            "zh-Hant": "19號線"
        }
    },
    {
        "id": "hangzhouhainingintercityrail",
        "colour": "#0277c8",
        "fg": "#fff",
        "name": {
            "en": "Hangzhou-Haining Intercity Rail",
            "zh-Hans": "杭海城际",
            "zh-Hant": "杭海城際"
        }
    }
]</details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的模板有問題
。杭海城際的顏色錯誤，應為#0077C8

審核來源：
![image](https://github.com/railmapgen/rmg-palette/assets/143057061/41dbfc8e-6c7c-4486-8769-82331c2d9089)

**Comment by langonginc** [comment]
补充说明：根据维基百科网页源代码内提供的信息，此处应为 `#0077C8` .
