### ISSUE TITLE
Resources: New palettes of Taizhou

### ISSUE THREAD

**Issue by Xiao-qian111** [railmapgen/rmg-palette#907]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=%E5%8F%B0%E5%B7%9E%E5%9C%B0%E9%93%81%E5%9B%BE2023&step_word=&hs=0&pn=13&spn=0&di=7264239678495129601&pi=0&rn=1&tn=baiduimagedetail&is=0%2C0&istype=0&ie=utf-8&oe=utf-8&in=&cl=2&lm=-1&st=undefined&cs=2711020669%2C2061745459&os=3801709358%2C99741225&simid=4226136225%2C720528794&adpicid=0&lpn=0&ln=1614&fr=&fmq=1696670137253_R&fm=&ic=undefined&s=undefined&hd=undefined&latest=undefined&copyright=undefined&se=&sme=&tab=0&width=undefined&height=undefined&face=undefined&ist=&jit=&cg=&bdtype=0&oriquery=&objurl=https%3A%2F%2Ft2.focus-img.cn%2Fsh740wsh%2Fzx%2Fduplication%2F4220dafe-448b-4a99-90e5-fe55ff7da381.png&fromurl=ippr_z2C%24qAzdH3FAzdH3Fpz_z%26e3Bu5v7f_z%26e3BvgAzdH3Fztx7gAzdH3Fk8c00bmjud89u0vl_z%26e3Bip4s&gsm=1e&rpstart=0&rpnum=0&islist=&querylist=&nojc=undefined&dyTabStr=MTEsMCwzLDEsNiw0LDUsMiw3LDgsOQ%3D%3D&lid=7258610204020005769

**Justification:** 添加线路颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "taizhou",
    "country": "CN",
    "name": {
        "en": "Taizhou",
        "zh-Hans": "台州",
        "zh-Hant": "臺州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "ta S1",
        "colour": "#0099db",
        "fg": "#fff",
        "name": {
            "en": "Line S1",
            "zh-Hans": "S1线",
            "zh-Hant": "S1線"
        }
    }
]</details>

**Comment by langonginc** [comment]
很抱歉，我们不接受来自百度的来源，请您寻找其它来源，感谢您的贡献。
