### ISSUE TITLE
Resources: New palettes of Montreal

### ISSUE THREAD

**Issue by 52PD** [railmapgen/rmg-palette#91]
**Justification:** 修正了一下之前上传的版本（#88）中在RMG中文界面下仍然只显示英文城市名的问题：
<img width="438" alt="Screen Shot 2022-07-01 at 12 42 24 PM" src="https://user-images.githubusercontent.com/98044618/176936489-abff5193-988c-44c5-ab43-a203e54edf30.png">
（我发现只有把中文城市名填在ChineseSimp和ChineseTrad中才能让RMG正常显示中文城市名，填在ChineseCN，ChineseHK和ChineseTW都会出现只显示英文名的bug）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">
{
    "id": "montreal",
    "country": "CA",
    "name": {
        "en": "Montreal",
        "fr": "Montréal",
        "zh-Hans": "蒙特利尔",
        "zh-Hant": "滿地可"
    }
}
</details>

<details repo="rmg-palette" type="lines">
[
    {
        "id": "green",
        "colour": "#069037",
        "fg": "#fff",
        "name": {
            "en": "Green Line",
            "fr": "Ligne verte",
            "zh-Hans": "绿线",
            "zh-Hant": "綠線"
        }
    },
    {
        "id": "orange",
        "colour": "#f07d05",
        "fg": "#fff",
        "name": {
            "en": "Orange Line",
            "fr": "Ligne orange",
            "zh-Hans": "橙线",
            "zh-Hant": "橙線"
        }
    },
    {
        "id": "yellow",
        "colour": "#fad706",
        "fg": "#000",
        "name": {
            "en": "Yellow Line",
            "fr": "Ligne jaune",
            "zh-Hans": "黄线",
            "zh-Hant": "黃線"
        }
    },
    {
        "id": "blue",
        "colour": "#057bc4",
        "fg": "#fff",
        "name": {
            "en": "Blue Line",
            "fr": "Ligne bleue",
            "zh-Hans": "蓝线",
            "zh-Hant": "藍線"
        }
    }
]
</details>

**Comment by wongchito** [comment]
你好 @52PD ，

閣下回報之問題已於另一commit中修復 - 因該自動化流程目前暫無法更新城市資訊。多謝！

另，閣下提及之語言顯示順序，目前其優先順序如下：

- 於簡體中文環境下，按ChineseSimp (zh-Hans)、Chinese (zh)順序尋找首個被定義之多稱
- 於繁體中文環境下，按ChineseTrad (zh-Hant)、ChineseHK (zh-HK)、Chinese (zh)順序尋找。

我們將因應是次情況，更新RMG Palette之提示，並將ChineseCN (zh-CN)加入至簡體中文RMG之語言列表。

**Comment by 52PD** [comment]
> 你好 @52PD ，
> 
> 閣下回報之問題已於另一commit中修復 - 因該自動化流程目前暫無法更新城市資訊。多謝！
> 
> 另，閣下提及之語言顯示順序，目前其優先順序如下：
> 
> * 於簡體中文環境下，按ChineseSimp (zh-Hans)、Chinese (zh)順序尋找首個被定義之多稱
> * 於繁體中文環境下，按ChineseTrad (zh-Hant)、ChineseHK (zh-HK)、Chinese (zh)順序尋找。
> 
> 我們將因應是次情況，更新RMG Palette之提示，並將ChineseCN (zh-CN)加入至簡體中文RMG之語言列表。

好的好的，谢谢！😄
