### ISSUE TITLE
關於路線顏色錯誤事宜

### ISSUE THREAD

**Issue by Charlis-Wong** [railmapgen/rmg-palette#915]
RMG團隊您好，
本人在使用RMG做 *東京* 路線圖的時候，發現了關於palette的問題。
問題是，在使用每一個車站新增顏色的時候，都會增加一次西武新宿線和東武東上線。

示意圖：
![IMG_1304](https://github.com/railmapgen/rmg/assets/143057061/56f1c91b-0f27-4713-b8fe-c16928cbc532)

請回覆，謝謝🙏

**Comment by thekingofcity** [comment]
Looks like this is a palette problem :(

**Comment by wongchito** [comment]
編碼重複需修正

![image](https://github.com/railmapgen/rmg-palette/assets/9390786/c57acc84-bb9d-4720-be3b-89d59243cfd4)

**Comment by wongchito** [comment]
事實上拜島線屬西武新宿線的延伸段，因此路線編號一致，顏色亦應一致

cc @28yfang as reviewer

**Comment by 28yfang** [comment]
啊怎么at了我

**Comment by wongchito** [comment]
Please keep this issue open until additional checking is added to bot workflow. Thanks.
