### ISSUE TITLE
Resources: New palettes of Kansai Area

### ISSUE THREAD

**Issue by Samuyuki** [railmapgen/rmg-palette#918]
Hi RMG team! I would like to contribute the palettes below.

_Follow instruction in https://railmapgen.github.io/rmg-palette/new and paste the palette data below_

**Reference link:** https://ja.wikipedia.org/

**Justification:** 完善近畿地区线路网信息。
Improve the network info in the Kinki area.

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "kansai",
    "country": "JP",
    "name": {
        "en": "Kansai Area",
        "ja": "近畿地方",
        "zh-Hans": "近畿地方（关西地方）",
        "zh-Hant": "近畿地方（關西地方）"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "a",
        "colour": "#007ac2",
        "fg": "#fff",
        "name": {
            "en": "JR Hokuriku Line/Biwako Line/Kyōto Line/Kōbe Line (Tōkaidō Line)/San-yō Line/Akō Line (A)",
            "ja": "JR北陸線・琵琶湖線・京都線・神戸線（東海道線）・山陽線・赤穂線",
            "zh-Hans": "JR北陆线/琵琶湖线/京都线/神户线/山阳线/赤穗线",
            "zh-Hant": "JR北陸線/琵琶湖線/京都線/神戶線/山陽線/赤穗線"
        }
    },
    {
        "id": "b",
        "colour": "#00b2e6",
        "fg": "#fff",
        "name": {
            "en": "JR Kosei Line (B)",
            "ja": "JR湖西線",
            "zh-Hans": "JR湖西线",
            "zh-Hant": "JR湖西線"
        }
    },
    {
        "id": "c",
        "colour": "#65b04c",
        "fg": "#fff",
        "name": {
            "en": "JR Kusatsu Line (C)",
            "ja": "JR草津線",
            "zh-Hans": "JR草津线",
            "zh-Hant": "JR草津線"
        }
    },
    {
        "id": "d",
        "colour": "#ba7c31",
        "fg": "#fff",
        "name": {
            "en": "JR Nara Line (D)",
            "ja": "JR奈良線",
            "zh-Hans": "JR奈良线",
            "zh-Hant": "JR奈良線"
        }
    },
    {
        "id": "e",
        "colour": "#7585c1",
        "fg": "#fff",
        "name": {
            "en": "JR Sagano Line/San-in Line (E)",
            "ja": "JR嵯峨野線・山陰線",
            "zh-Hans": "JR嵯峨野线/山阴线",
            "zh-Hant": "JR嵯峨野線/山陰線"
        }
    },
    {
        "id": "f",
        "colour": "#447694",
        "fg": "#fff",
        "name": {
            "en": "JR Ōsaka Higashi Line (F)",
            "ja": "JRおおさか東線",
            "zh-Hans": "JR大阪东线",
            "zh-Hant": "JR大阪東線"
        }
    },
    {
        "id": "g",
        "colour": "#fec210",
        "fg": "#000",
        "name": {
            "en": "JR Takarazuka Line/Fukuchiyama Line (G)",
            "ja": "ＪＲ宝塚線・福知山線",
            "zh-Hans": "JR宝冢线/福知山线",
            "zh-Hant": "JR寶塚線/福知山線"
        }
    },
    {
        "id": "h",
        "colour": "#ee3689",
        "fg": "#fff",
        "name": {
            "en": "JR Tōzai Line/Gakkentoshi Line (Katamachi Line) (H)",
            "ja": "ＪＲ東西線・学研都市線（片町線）",
            "zh-Hans": "JR东西线/学研都市线",
            "zh-Hant": "JR東西線/學研都市線"
        }
    },
    {
        "id": "i",
        "colour": "#03b08e",
        "fg": "#fff",
        "name": {
            "en": "JR Kakogawa Line (I)",
            "ja": "JR加古川線",
            "zh-Hans": "JR加古川线",
            "zh-Hant": "JR加古川線"
        }
    },
    {
        "id": "j",
        "colour": "#af2756",
        "fg": "#fff",
        "name": {
            "en": "JR Bantan Line (J)",
            "ja": "JR播但線",
            "zh-Hans": "JR播但线",
            "zh-Hant": "JR播但線"
        }
    },
    {
        "id": "k",
        "colour": "#ef4b2b",
        "fg": "#fff",
        "name": {
            "en": "JR Kishin Line (K)",
            "ja": "JR姫新線",
            "zh-Hans": "JR姬新线",
            "zh-Hant": "JR姬新線"
        }
    },
    {
        "id": "l",
        "colour": "#f89c1c",
        "fg": "#000",
        "name": {
            "en": "JR Maizuru Line (L)",
            "ja": "JR舞鶴線",
            "zh-Hans": "JR舞鹤线",
            "zh-Hant": "JR舞鶴線"
        }
    },
    {
        "id": "o",
        "colour": "#ee354f",
        "fg": "#fff",
        "name": {
            "en": "JR Ōsaka Loop Line (O)",
            "ja": "JR大阪環状線",
            "zh-Hans": "JR大阪环状线",
            "zh-Hant": "JR大阪環狀線"
        }
    },
    {
        "id": "p",
        "colour": "#233f97",
        "fg": "#fff",
        "name": {
            "en": "JR Yumesaki Line (Sakurajima Line) (P)",
            "ja": "ＪＲゆめ咲線（桜島線）",
            "zh-Hans": "JR梦咲线",
            "zh-Hant": "JR夢咲線"
        }
    },
    {
        "id": "q",
        "colour": "#02ad73",
        "fg": "#fff",
        "name": {
            "en": "JR Yamatoji Line (Q)",
            "ja": "JR大和路線",
            "zh-Hans": "JR大和路线",
            "zh-Hant": "JR大和路線"
        }
    },
    {
        "id": "r",
        "colour": "#f89c1c",
        "fg": "#000",
        "name": {
            "en": "JR Hanwa Line (R)",
            "ja": "JR阪和線・羽衣線",
            "zh-Hans": "JR阪和线/羽衣线",
            "zh-Hant": "JR阪和線/羽衣線"
        }
    },
    {
        "id": "s",
        "colour": "#007ac2",
        "fg": "#fff",
        "name": {
            "en": "JR Kansai-airport Line (S)",
            "ja": "JR関西空港線",
            "zh-Hans": "JR关西机场线",
            "zh-Hant": "JR關西機場線"
        }
    },
    {
        "id": "t",
        "colour": "#f5a2ba",
        "fg": "#000",
        "name": {
            "en": "JR Wakayama Line (T)",
            "ja": "JR和歌山線",
            "zh-Hans": "JR和歌山线",
            "zh-Hant": "JR和歌山線"
        }
    },
    {
        "id": "u",
        "colour": "#cf2232",
        "fg": "#fff",
        "name": {
            "en": "JR Man-yō Mahoroba Line (Sakurai Line) (U)",
            "ja": "JR万葉まほろば線（桜井線）",
            "zh-Hans": "JR万叶MAHOROBA线",
            "zh-Hant": "JR萬葉MAHOROBA線"
        }
    },
    {
        "id": "v",
        "colour": "#4b3f85",
        "fg": "#fff",
        "name": {
            "en": "JR Kansai Line (V)",
            "ja": "JR関西線",
            "zh-Hans": "JR关西线",
            "zh-Hant": "JR關西線"
        }
    },
    {
        "id": "w",
        "colour": "#00b0c1",
        "fg": "#fff",
        "name": {
            "en": "JR Kinokuni Line (Kisei Line) (W)",
            "ja": "JRきのくに線（紀勢線）",
            "zh-Hans": "JR纪国线",
            "zh-Hant": "JR紀國線"
        }
    },
    {
        "id": "",
        "colour": "#0072bc",
        "fg": "#fff",
        "name": {
            "en": "JR Obama Line",
            "zh-Hans": "JR小滨线",
            "zh-Hant": "JR小濱線",
            "ja": "JR小浜線"
        }
    },
    {
        "id": "shinkansen",
        "colour": "#233f97",
        "fg": "#fff",
        "name": {
            "en": "Tōkaidō, San-yō Shinkansen",
            "ja": "東海道・山陽新幹線",
            "zh-Hans": "东海道 · 山阳新干线",
            "zh-Hant": "東海道 · 山陽新幹線"
        }
    },
    {
        "id": "K",
        "colour": "#009944",
        "fg": "#fff",
        "name": {
            "en": "Kyoto Municipal Subway Karasuma Line (K)",
            "zh-Hans": "京都市营地下铁乌丸线",
            "zh-Hant": "京都市営地下鉄烏丸線",
            "ja": "京都市営地下鉄烏丸線"
        }
    },
    {
        "id": "T",
        "colour": "#e60012",
        "fg": "#fff",
        "name": {
            "en": "Kyoto Municipal Subway Tōzai Line (T)",
            "zh-Hans": "京都市营地下铁东西线",
            "zh-Hant": "京都市営地下鉄東西線",
            "ja": "京都市営地下鉄東西線"
        }
    },
    {
        "id": "A",
        "colour": "#d21644",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Namba Line/Nara Line (A)",
            "zh-Hans": "近铁难波线/近铁奈良线",
            "zh-Hant": "近鉄難波線/近鉄奈良線",
            "ja": "近鉄難波線・近鉄奈良線"
        }
    },
    {
        "id": "G",
        "colour": "#d21644",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Ikoma Line (G)",
            "zh-Hans": "近铁生驹线",
            "zh-Hant": "近鉄生駒線",
            "ja": "近鉄生駒線"
        }
    },
    {
        "id": "B",
        "colour": "#f8b400",
        "fg": "#000",
        "name": {
            "en": "Kintetsu Kyōto Line/Kashihara Line (B)",
            "zh-Hans": "近铁京都线/橿原线",
            "zh-Hant": "近鉄京都線/橿原線",
            "ja": "近鉄京都線・橿原線"
        }
    },
    {
        "id": "H",
        "colour": "#f8b400",
        "fg": "#000",
        "name": {
            "en": "Kintetsu Tenri Line (H)",
            "zh-Hans": "近铁天理线",
            "zh-Hant": "近鉄天理線",
            "ja": "近鉄天理線"
        }
    },
    {
        "id": "I",
        "colour": "#f8b400",
        "fg": "#000",
        "name": {
            "en": "Kintetsu Tawaramoto Line (I)",
            "zh-Hans": "近铁田原本线",
            "zh-Hant": "近鉄田原本線",
            "ja": "近鉄田原本線"
        }
    },
    {
        "id": "C",
        "colour": "#7bbf4b",
        "fg": "#000",
        "name": {
            "en": "Kintetsu Keihanna Line (C)",
            "zh-Hans": "近铁京阪奈线",
            "zh-Hant": "近鉄京阪奈線",
            "ja": "近鉄けいはんな線"
        }
    },
    {
        "id": "D",
        "colour": "#4694d1",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Ōsaka Line (D)",
            "zh-Hans": "近铁大阪线",
            "zh-Hant": "近鉄大阪線",
            "ja": "近鉄大阪線"
        }
    },
    {
        "id": "J",
        "colour": "#4694d1",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Shigi Line (J)",
            "zh-Hans": "近铁信贵线",
            "zh-Hant": "近鉄信貴線",
            "ja": "近鉄信貴線"
        }
    },
    {
        "id": "E",
        "colour": "#153f97",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Nagoya Line (E)",
            "zh-Hans": "近铁名古屋线",
            "zh-Hant": "近鉄名古屋線",
            "ja": "近鉄名古屋線"
        }
    },
    {
        "id": "K",
        "colour": "#153f97",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Yunoyama Line (K)",
            "zh-Hans": "近铁汤之山线",
            "zh-Hant": "近鉄湯之山線",
            "ja": "近鉄湯の山線"
        }
    },
    {
        "id": "L",
        "colour": "#153f97",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Suzuka Line (L)",
            "zh-Hans": "近铁铃鹿线",
            "zh-Hant": "近鉄鈴鹿線",
            "ja": "近鉄鈴鹿線"
        }
    },
    {
        "id": "F",
        "colour": "#008e45",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Minami-Ōsaka Line/Yoshino Line (F)",
            "zh-Hans": "近铁南大阪线/吉野线",
            "zh-Hant": "近鉄南大阪線/吉野線",
            "ja": "近鉄南大阪線・吉野線"
        }
    },
    {
        "id": "N",
        "colour": "#008e45",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Dōmyōji Line (N)",
            "zh-Hans": "近铁道明寺线",
            "zh-Hant": "近鉄道明寺線",
            "ja": "近鉄道明寺線"
        }
    },
    {
        "id": "O",
        "colour": "#008e45",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Nagano Line (O)",
            "zh-Hans": "近铁长野线",
            "zh-Hant": "近鉄長野線",
            "ja": "近鉄長野線"
        }
    },
    {
        "id": "P",
        "colour": "#008e45",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Gose Line (P)",
            "zh-Hans": "近铁御所线",
            "zh-Hant": "近鉄御所線",
            "ja": "近鉄御所線"
        }
    },
    {
        "id": "M",
        "colour": "#00b3c1",
        "fg": "#fff",
        "name": {
            "en": "Kintetsu Yamada Line/Toba Line/Shima Line (M)",
            "zh-Hans": "近铁山田线/鸟羽线/志摩线",
            "zh-Hant": "近鉄山田線/鳥羽線/志摩線",
            "ja": "近鉄山田線・鳥羽線・志摩線"
        }
    },
    {
        "id": "HK",
        "colour": "#0d6fb8",
        "fg": "#fff",
        "name": {
            "en": "Hankyū Kobe Main Line/Kobe Kōsoku Line/Itami Line/Imazu Line/Kōyō Line (HK)",
            "zh-Hans": "阪急神户本线/神户高速线/伊丹线/今津线/甲阳线",
            "zh-Hant": "阪急神戸本線/神戸高速線/伊丹線/今津線/甲陽線",
            "ja": "阪急神戸本線・神戸高速線・伊丹線・今津線・甲陽線"
        }
    },
    {
        "id": "HK",
        "colour": "#ee7700",
        "fg": "#fff",
        "name": {
            "en": "Hankyū Takarazuka Main Line/Mino-o Line (HK)",
            "zh-Hans": "阪急宝冢本线/箕面线",
            "zh-Hant": "阪急宝塚本線/箕面線",
            "ja": "阪急宝塚本線・箕面線"
        }
    },
    {
        "id": "HK",
        "colour": "#23ac38",
        "fg": "#fff",
        "name": {
            "en": "Hankyū Kyōto Main Line/Senri Line/Arashiyama Line (HK)",
            "zh-Hans": "阪急京都本线/千里线/岚山线",
            "zh-Hant": "阪急京都本線・千里線・嵐山線",
            "ja": "阪急京都本線/千里線/嵐山線"
        }
    },
    {
        "id": "NK",
        "colour": "#0065af",
        "fg": "#fff",
        "name": {
            "en": "Nankai Main Line/Takashinohama Line/Tanagawa Line/Kada Line/Wakayamakō Line (NK)",
            "zh-Hans": "南海本线/高师滨线/多奈川线/加太线/和歌山港线",
            "zh-Hant": "南海本線/高師浜線/多奈川線/加太線/和歌山港線",
            "ja": "南海本線・高師浜線・多奈川線・加太線・和歌山港線"
        }
    },
    {
        "id": "NK",
        "colour": "#594bac",
        "fg": "#fff",
        "name": {
            "en": "Nankai Airport Line (NK)",
            "zh-Hans": "南海空港线",
            "zh-Hant": "南海空港線",
            "ja": "南海空港線"
        }
    },
    {
        "id": "NK",
        "colour": "#009a41",
        "fg": "#fff",
        "name": {
            "en": "Nankai Kōya Line/Kōyasan Cable Car (NK)",
            "zh-Hans": "南海高野线/高野山地面缆车",
            "zh-Hant": "南海高野線/高野山地面纜車",
            "ja": "南海高野線・高野山ケーブル"
        }
    },
    {
        "id": "SB",
        "colour": "#a5760c",
        "fg": "#fff",
        "name": {
            "en": "Semboku Rapid Raiway (SB)",
            "zh-Hans": "泉北高速铁道线",
            "zh-Hant": "泉北高速鉄道線",
            "ja": "泉北高速鉄道線"
        }
    },
    {
        "id": "HS",
        "colour": "#f5b62f",
        "fg": "#000",
        "name": {
            "en": "Hanshin Main Line/Namba Line/Mukogawa Line (HS)",
            "zh-Hans": "阪神本线/阪神难波线/阪神武库川线",
            "zh-Hant": "阪神本線/阪神難波線/阪神武庫川線",
            "ja": "阪神本線・阪神なんば線・阪神武庫川線"
        }
    },
    {
        "id": "KH",
        "colour": "#1d2088",
        "fg": "#fff",
        "name": {
            "en": "Keihan Main Line/Ōtō Line/Nakanoshima Line/Katano Line/Uji Line (KH)",
            "zh-Hans": "京阪本线/鸭东线/中之岛线/交野线/宇治线",
            "zh-Hant": "京阪本線/鴨東線/中之島線/交野線/宇治線",
            "ja": "京阪本線・鴨東線・中之島線・交野線・宇治線"
        }
    },
    {
        "id": "OT",
        "colour": "#70c8e0",
        "fg": "#000",
        "name": {
            "en": "Keihan Ishiyama Sakamoto Line (OT)",
            "zh-Hans": "京阪石山坂本线",
            "zh-Hant": "京阪石山坂本線",
            "ja": "京阪石山坂本線"
        }
    },
    {
        "id": "OT",
        "colour": "#aace24",
        "fg": "#000",
        "name": {
            "en": "Keihan Keishin Line",
            "zh-Hans": "京阪京津线",
            "zh-Hant": "京阪京津線",
            "ja": "京阪京津線"
        }
    },
    {
        "id": "SY",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "San-yō Electric Railway (SY)",
            "zh-Hans": "山阳电气铁道",
            "zh-Hant": "山陽電気鉄道",
            "ja": "山陽電気鉄道"
        }
    },
    {
        "id": "",
        "colour": "#111986",
        "fg": "#fff",
        "name": {
            "en": "Ōsaka Monorail",
            "zh-Hans": "大阪单轨电车",
            "zh-Hant": "大阪單軌電車",
            "ja": "大阪モノレール"
        }
    },
    {
        "id": "M",
        "colour": "#000080",
        "fg": "#fff",
        "name": {
            "en": "Kita-Ōsaka Kyūkō Line (M)",
            "zh-Hans": "北大阪急行线",
            "zh-Hant": "北大阪急行線",
            "ja": "北大阪急行線"
        }
    },
    {
        "id": "P",
        "colour": "#00ae6c",
        "fg": "#fff",
        "name": {
            "en": "Port Island Line",
            "zh-Hans": "港湾人工岛线",
            "zh-Hant": "港灣人工島線",
            "ja": "ポートアイランド線"
        }
    },
    {
        "id": "R",
        "colour": "#9686bd",
        "fg": "#fff",
        "name": {
            "en": "Rokkō Island Line",
            "zh-Hans": "六甲人工岛线",
            "zh-Hant": "六甲人工島線",
            "ja": "六甲アイランド線"
        }
    },
    {
        "id": "OR",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Ōmi Railway Main Line/Taga Line (OR)",
            "zh-Hans": "近江铁道本线/多贺线（彦根・多贺大社线）",
            "zh-Hant": "近江鉄道本線/多賀線（彦根・多賀大社線）",
            "ja": "近江鉄道本線・多賀線（彦根・多賀大社線）"
        }
    },
    {
        "id": "OR",
        "colour": "#0070c0",
        "fg": "#fff",
        "name": {
            "en": "Ōmi Railway Main Line (OR)",
            "zh-Hans": "近江铁道本线（湖东近江路线）",
            "zh-Hant": "近江鉄道本線（湖東近江路線）",
            "ja": "近江鉄道本線（湖東近江路線）"
        }
    },
    {
        "id": "OR",
        "colour": "#ffc000",
        "fg": "#000",
        "name": {
            "en": "Ōmi Railway Main Line (OR)",
            "zh-Hans": "近江铁道本线（水口・蒲生野线）",
            "zh-Hant": "近江鉄道本線（水口・蒲生野線）",
            "ja": "近江鉄道本線（水口・蒲生野線）"
        }
    },
    {
        "id": "OR",
        "colour": "#00b050",
        "fg": "#fff",
        "name": {
            "en": "Ōmi Railway Yōkaichi Line (OR)",
            "zh-Hans": "近江铁道八日市线",
            "zh-Hant": "近江鉄道八日市線",
            "ja": "近江鉄道八日市線"
        }
    },
    {
        "id": "E",
        "colour": "#00994d",
        "fg": "#fff",
        "name": {
            "en": "Eizan Main Line (E)",
            "zh-Hans": "叡山电铁叡山本线",
            "zh-Hant": "叡山電鉄叡山本線",
            "ja": "叡山電鉄叡山本線"
        }
    },
    {
        "id": "E",
        "colour": "#d11c39",
        "fg": "#fff",
        "name": {
            "en": "Kurama Line (E)",
            "zh-Hans": "叡山电铁鞍马线",
            "zh-Hant": "叡山電鉄鞍馬線",
            "ja": "叡山電鉄鞍馬線"
        }
    },
    {
        "id": "A",
        "colour": "#b8193f",
        "fg": "#fff",
        "name": {
            "en": "Arashiyama Main Line (A)",
            "zh-Hans": "京福电气铁道岚山本线",
            "zh-Hant": "京福電気鉄道嵐山本線",
            "ja": "京福電気鉄道嵐山本線"
        }
    },
    {
        "id": "B",
        "colour": "#004b8d",
        "fg": "#fff",
        "name": {
            "en": "Kitano Line (B)",
            "zh-Hans": "京福电气铁道北野线",
            "zh-Hant": "京福電気鉄道北野線",
            "ja": "京福電気鉄道北野線"
        }
    },
    {
        "id": "",
        "colour": "#b22222",
        "fg": "#fff",
        "name": {
            "en": "Sagano Scenic Railway",
            "zh-Hans": "嵯峨野观光线",
            "zh-Hant": "嵯峨野観光線",
            "ja": "嵯峨野観光線"
        }
    },
    {
        "id": "HN",
        "colour": "#006506",
        "fg": "#fff",
        "name": {
            "en": "Hankai Tramway Hankai Line (HN)",
            "zh-Hans": "阪堺电气轨道阪堺线",
            "zh-Hant": "阪堺電気軌道阪堺線",
            "ja": "阪堺電気軌道阪堺線"
        }
    },
    {
        "id": "HN",
        "colour": "#ffa500",
        "fg": "#000",
        "name": {
            "en": "Hankai Tramway Uemachi Line (HN)",
            "zh-Hans": "阪堺电气轨道上町线",
            "zh-Hant": "阪堺電気軌道上町線",
            "ja": "阪堺電気軌道上町線"
        }
    },
    {
        "id": "NS",
        "colour": "#451c1d",
        "fg": "#fff",
        "name": {
            "en": "Nose Electric Railway (NS)",
            "zh-Hans": "能势电铁",
            "zh-Hant": "能勢電鉄",
            "ja": "能勢電鉄"
        }
    },
    {
        "id": "",
        "colour": "#dc143c",
        "fg": "#fff",
        "name": {
            "en": "Kishigawa Line",
            "zh-Hans": "贵志川线",
            "zh-Hant": "貴志川線",
            "ja": "貴志川線"
        }
    },
    {
        "id": "",
        "colour": "#8c512f",
        "fg": "#fff",
        "name": {
            "en": "Hōjō Line",
            "zh-Hans": "北条线",
            "zh-Hant": "北条線",
            "ja": "北条線"
        }
    },
    {
        "id": "",
        "colour": "#112299",
        "fg": "#fff",
        "name": {
            "en": "Chizu Express",
            "zh-Hans": "智头急行线",
            "zh-Hant": "智頭急行線",
            "ja": "智頭急行線"
        }
    },
    {
        "id": "",
        "colour": "#00a779",
        "fg": "#fff",
        "name": {
            "en": "Shigaraki Line",
            "zh-Hans": "信乐线",
            "zh-Hant": "信楽線",
            "ja": "信楽線"
        }
    },
    {
        "id": "",
        "colour": "#87ceeb",
        "fg": "#fff",
        "name": {
            "en": "Mizuma Line",
            "zh-Hans": "水间线",
            "zh-Hant": "水間線",
            "ja": "水間線"
        }
    },
    {
        "id": "",
        "colour": "#1e5f30",
        "fg": "#fff",
        "name": {
            "en": "Kishū Railway Line",
            "zh-Hans": "纪州铁道线",
            "zh-Hant": "紀州鉄道線",
            "ja": "紀州鉄道線"
        }
    },
    {
        "id": "",
        "colour": "#ea4f6f",
        "fg": "#fff",
        "name": {
            "en": "Kyoto Tango Railway",
            "zh-Hans": "京都丹后铁道",
            "zh-Hant": "京都丹後鉄道",
            "ja": "京都丹後鉄道"
        }
    }
]</details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的Reference Link好像不太對。請您在本issue的留言區附上正確的連結，感謝您的配合🙏

**Comment by Samuyuki** [comment]
主要参考了Wikipedia，此外也参考了所有铁道公司的官网以及GoogleMap。
JR西日本：https://www.jr-odekake.net/route/
京都市交通局：https://www.city.kyoto.lg.jp/kotsu/page/0000008995.html
近铁：https://www.kintetsu.co.jp/station/
近铁是根据线路系统分颜色的，我将颜色相同但编号不同的线路单独列出了。
阪急：https://www.hankyu.co.jp/station/index.html
南海&泉北：https://www.nankai.co.jp/traffic/railmap.html
阪神：https://rail.hanshin.co.jp/
阪神线路色在GoogleMap上是黄色，故从其官网选用了官网配色的黄色#f5b62f。
京阪：https://www.keihan.co.jp/traffic/station/
京阪的石山坂本线和京津线的取色来源于Wikipedia。
山阳：https://www.sanyo-railway.co.jp/index.html
山阳线路色在GoogleMap上是红色，故从其官网选用了官网配色的红色#ff0000。
大阪单轨：https://www.osaka-monorail.co.jp/station/
北大阪急行：https://ja.wikipedia.org/
「[駅番号]を構成する路線記号はMで、番号は[直通運転]している御堂筋線と一体で振られている。江坂駅以外の各駅は青地に白抜きのM（ M ）だが、江坂駅は赤地に白抜きのM（ M ）で描かれている。」故从该页选取青色#000080。
神户新交通：https://ja.wikipedia.org/
六甲人工岛线选用了线路标志中的#9686bd。
港湾人工岛线选用了线路标志中的#00ae6c。
近江铁道：https://ja.wikipedia.org/
本线&加贺线的线路色取自Wikipedia的本线界面。
八日市线的线路色取自Wikipedia的八日市线界面。
叡山电铁：https://eizandensha.co.jp/guide/station/
京福电气铁道：https://www.keifuku.co.jp/randen_timetable.php
嵯峨野观光线：https://ja.wikipedia.org/
阪堺电车：https://www.hankai.co.jp/route/
目前的版本参考了Wikipedia页面中的线路图。
会在下一个更新中更新为官网页面的线路色。
能势电铁：https://noseden.hankyu.co.jp/railway/station.html
目前的版本参考了Wikipedia页面中的线路色。
会在下一个更新中更新为官网页面的线路色。
贵志川线：https://ja.wikipedia.org/
北条线：http://www.hojorailway.jp/
选用了该社logo的#8c512f。
智头急行：https://ja.wikipedia.org/
信乐线：https://ja.wikipedia.org/
水间线：https://ja.wikipedia.org/
纪州铁道：http://kishu-railway.com/
选用了该社logo的#1e5f30。
京都丹后铁道：https://ja.wikipedia.org/
宫福、宫舞、宫丰三线的页面中均选用了相同的线路色#ea4f6f。
end

**Comment by Samuyuki** [comment]
看到了隔壁#922的。京都的两条地铁既然有单独列项了，可以不做在关西地区的线路列表内，会在下一个更新中删除。

**Comment by Samuyuki** [comment]
上文中的**故从该页选取青色#80。**部分，#80应为颜色的 # 000080 。

**Comment by 52PD** [comment]
> 上文中的**故从该页选取青色https://github.com/railmapgen/rmg-palette/pull/80。**部分，#80应为颜色的 # 000080 。

您好，由于您此前提及了所提交的线路颜色中有出现了颜色错误，因此您需要在本Issue下重新提交修正后的颜色模版，谢谢。

**Comment by Samuyuki** [comment]
您好，这不是我提交的颜色有误，而是在详细信息中，颜色代码的 # 000080 正好为纯数字而被GitHub缩略成 # 80 了，特此告知。RGB:0,0,128,HEX:000080。
原文：{ "id": "M", "colour": "https://github.com/railmapgen/rmg-palette/pull/80", "fg": "#fff", "name": { "en": "Kita-Ōsaka Kyūkō Line (M)", "zh-Hans": "北大阪急行线", "zh-Hant": "北大阪急行線", "ja": "北大阪急行線" } }

**Comment by Charlis-Wong** [comment]
您好 @Samuyuki
请试试编辑issue重新再写一次 `#000080`，感谢您的贡献🙏

**Comment by 52PD** [comment]
> 您好，由于您此前提及了所提交的线路颜色中有出现了颜色错误，因此您需要在本Issue下重新提交修正后的颜色模版，谢谢。

> 由于这个因GitHub简化而导致的错误可能会导致整个投稿文件出问题报废。我们建议您对本issue进行重新再写一次 `#000080`，感谢您的贡献🙏

您好，目前我们已经对汇入项目的文件进行仔细检查。所幸的是，该GitHub强行缩减的部分（`#80`）并未导致汇入文件损坏，因为您无需作出其他动作，在确认无任何颜色信息错误后我们将会将其汇入，感谢您的贡献。

**Comment by Swiftiecott** [comment]
您好，由于目前线路颜色过多以及来源重复（目前根据您的描述，绝大部分线路均有维基百科和官方两个来源参考）导致审核及其困难。加之您所提交的部分线路对应城市已经有单独的列表，因此很抱歉您的稿件可能无法通过审核。

我们建议您将未有明显跨城市的线路（如城区内地铁之类未延伸至其他城市的通勤铁路）单独分类至该城市下，而有明显跨城市的线路归类至关西地区下，并对各系列提供单一来源后再进行提交。感谢您对本项目的支持。
