### ISSUE TITLE
Resources: New palettes of Kyoto

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmg-palette#922]
**Reference link:** https://en.wikipedia.org/wiki/Kyoto_Municipal_Subway

**Justification:** Add kyoto colors

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "kyoto",
    "country": "JP",
    "name": {
        "en": "Kyoto",
        "zh-Hans": "京都",
        "zh-Hant": "京都",
        "ja": "京都"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "ktt",
        "colour": "#e35c42",
        "fg": "#fff",
        "name": {
            "en": "Tozai Line",
            "zh-Hans": "东西线",
            "zh-Hant": "東西綫",
            "ja": "東西線"
        }
    },
    {
        "id": "ktk",
        "colour": "#60b177",
        "fg": "#fff",
        "name": {
            "en": "Karasuma Line",
            "zh-Hans": "鸟丸线",
            "zh-Hant": "鳥丸綫",
            "ja": "烏丸線"
        }
    }
]</details>

**Comment by Charlis-Wong** [comment]
您好，感謝提交範本。但是我檢查到了一些錯誤
- 鳥丸線的顏色色號應為 #3CB371
- 東西線的顏色色號應為 #FF4500
請在修改後重開一個issue提交，感謝您的配合以及貢獻🙏

審核來源：
![IMG_1367](https://github.com/railmapgen/rmg-palette/assets/143057061/78bc7587-291b-4e7f-bf5a-589f1d61dfb4)
![IMG_1365](https://github.com/railmapgen/rmg-palette/assets/143057061/24f15588-7a6c-4573-ac8f-30a6f52a2b38)

**Comment by Charlis-Wong** [comment]
由於京都地下鐵的官方網站設計糟糕，所以暫不使用官網摘取顏色

**Comment by 28yfang** [comment]
无需重开议题，直接编辑即可
