### ISSUE TITLE
Resources: New palettes of Kyoto

### ISSUE THREAD

**Issue by axl099** [railmapgen/rmg-palette#924]
**Reference link:** https://en.wikipedia.org/wiki/Kyoto_Municipal_Subway

**Justification:** Add kyoto colors

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "kyoto",
    "country": "JP",
    "name": {
        "en": "Kyoto",
        "zh-Hans": "京都",
        "zh-Hant": "京都",
        "ja": "京都"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "ktt",
        "colour": "#ff4500",
        "fg": "#fff",
        "name": {
            "en": "Tozai Line",
            "zh-Hans": "东西线",
            "zh-Hant": "東西綫",
            "ja": "東西線"
        }
    },
    {
        "id": "ktk",
        "colour": "#3cb371",
        "fg": "#fff",
        "name": {
            "en": "Karasuma Line",
            "zh-Hans": "鸟丸线",
            "zh-Hant": "鳥丸綫",
            "ja": "烏丸線"
        }
    }
]</details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的範本沒有問題，請等待管理員合拼至RMG。感謝您的貢獻🙏
