### ISSUE TITLE
Resources: New palettes of Bandung

### ISSUE THREAD

**Issue by Dylangamin** [railmapgen/rmg-palette#928]
**Reference link:** https://railmapgen.github.io/rmg/

**Justification:** Its Opened

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "b",
    "country": "ID",
    "name": {
        "id": "Bandung",
        "en": "Bandung",
        "zh-Hans": "万隆",
        "zh-Hant": "萬隆"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "jbhs",
        "colour": "#404040",
        "fg": "#fff",
        "name": {
            "en": "Jakarta Bandung High Speed",
            "zh-Hans": "到中国传统的",
            "zh-Hant": " 到中國傳統的",
            "id": "Kereta Cepat Jakarta Bandung"
        }
    }
]</details>

**Comment by Charlis-Wong** [comment]
Hello, Please use a right reference link to submit a colour. Please See the guidelines at https://github.com/railmapgen/rmg-palette/wiki/Review-Criteria
Thank you.
