### ISSUE TITLE
Resources: New palettes of Jinan

### ISSUE THREAD

**Issue by 4237155** [railmapgen/rmg-palette#948]
**Reference link:** https://www.ndrc.gov.cn/xxgk/zcfb/pifu/202010/t20201030_1316561.html

**Justification:** 添加了在建的6号线；修正了3号线的颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "jinan",
    "country": "CN",
    "name": {
        "en": "Jinan",
        "zh-Hans": "济南",
        "zh-Hant": "濟南"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "jn1",
        "colour": "#BE1FA1",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    },
    {
        "id": "jn2",
        "colour": "#FFB620",
        "fg": "#fff",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线",
            "zh-Hant": "2號線"
        }
    },
    {
        "id": "jn3",
        "colour": "#00579e",
        "fg": "#fff",
        "name": {
            "en": "Line 3",
            "zh-Hans": "3号线",
            "zh-Hant": "3號線"
        }
    },
    {
        "id": "jn4",
        "colour": "#229719",
        "fg": "#fff",
        "name": {
            "en": "Line 4",
            "zh-Hans": "4号线",
            "zh-Hant": "4號線"
        }
    },
    {
        "id": "jn6",
        "colour": "#ff0000",
        "fg": "#fff",
        "name": {
            "en": "Line 6",
            "zh-Hans": "6号线",
            "zh-Hant": "6號線"
        }
    }
]</details>

**Comment by langonginc** [comment]
抱歉，我未能在您给出的来源链接中找到相关数据，如其存在，请您说明其位置，感谢您的贡献。

**Comment by Windows-Taskmgr** [comment]
您好，由于您已经超过一个月未回复，此issue将会被关闭，感谢您的理解。
