### ISSUE TITLE
Resources: New palettes of Kyoto

### ISSUE THREAD

**Issue by WanyunMediaGroup** [railmapgen/rmg-palette#952]
**Reference link:** https://zh.wikipedia.org/wiki/%E7%83%8F%E4%B8%B8%E7%B7%9A

**Justification:** 根据维基百科的写法，应为“乌丸线”，第一个字是“乌”不是“鸟”。

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "kyoto",
    "country": "JP",
    "name": {
        "en": "Kyoto",
        "zh-Hans": "京都",
        "zh-Hant": "京都",
        "ja": "京都"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "ktt",
        "colour": "#ff4500",
        "fg": "#fff",
        "name": {
            "en": "Tozai Line",
            "zh-Hans": "东西线",
            "zh-Hant": "東西綫",
            "ja": "東西線"
        }
    },
    {
        "id": "ktk",
        "colour": "#3cb371",
        "fg": "#fff",
        "name": {
            "en": "Karasuma Line",
            "zh-Hans": "乌丸线",
            "zh-Hant": "烏丸綫",
            "ja": "烏丸線"
        }
    }
]</details>

**Comment by Charlis-Wong** [comment]
您好，您所提交的乌丸线修改名称没有问题，请等待管理员合拼至范本，感谢您的贡献🙏
