### ISSUE TITLE
Resources: New palettes of Bangalore

### ISSUE THREAD

**Issue by linchen1965** [railmapgen/rmg-palette#958]
**Reference link:** https://english.bmrc.co.in/#/

**Justification:** Add palettes of Bangalore

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "bangalore",
    "country": "IN",
    "name": {
        "en": "Bangalore",
        "zh-Hans": "班加罗尔",
        "zh-Hant": "班加羅爾"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "bg",
        "colour": "#58ba49",
        "fg": "#fff",
        "name": {
            "en": "Green Line",
            "zh-Hans": "绿线",
            "zh-Hant": "緑缐"
        }
    },
    {
        "id": "bp",
        "colour": "#a952a0",
        "fg": "#fff",
        "name": {
            "en": "Purple Line",
            "zh-Hans": "紫线",
            "zh-Hant": "紫缐"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，您的参考链接似乎打不开，请您核实后在进行提交。
如此参考链接无问题，您可以提出说明。
（请您在收到此消息后一个月内及时回复，超过此期限的我们将拒绝汇入，敬请谅解。）

**Comment by langonginc** [comment]
我能打开该链接，但是不知道哪里有相应的颜色 😭

**Comment by linchen1965** [comment]
> 我能打开该链接，但是不知道哪里有相应的颜色 😭

参见：https://english.bmrc.co.in/#/schematic-route-map
