### ISSUE TITLE
Resources: New palettes of Nagoya

### ISSUE THREAD

**Issue by liberecolynn** [railmapgen/rmg-palette#962]
**Reference link:** https://zh.wikipedia.org/wiki/名古屋市營地下鐵

**Justification:** 新增了名古屋地铁的调色板

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "nagoya",
    "country": "JP",
    "name": {
        "en": "Nagoya",
        "zh-Hans": "名古屋",
        "zh-Hant": "名古屋",
        "ja": "名古屋"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "ngh",
        "colour": "#fda909",
        "fg": "#fff",
        "name": {
            "en": "Higashiyama Line",
            "zh-Hans": "东山线",
            "zh-Hant": "東山線",
            "ja": "東山線"
        }
    },
    {
        "id": "ngm",
        "colour": "#7c5dcc",
        "fg": "#fff",
        "name": {
            "en": "Meijō Line/Meikō Line",
            "zh-Hans": "名城线/名港线",
            "zh-Hant": "名城線/名港線",
            "ja": "名城線/名港線"
        }
    },
    {
        "id": "ngt",
        "colour": "#108ab1",
        "fg": "#fff",
        "name": {
            "en": "Tsurumai Line",
            "zh-Hans": "鹤舞线",
            "zh-Hant": "鶴舞線",
            "ja": "鶴舞線"
        }
    },
    {
        "id": "ngs",
        "colour": "#ad210e",
        "fg": "#fff",
        "name": {
            "en": "Sakuradōri Line",
            "zh-Hans": "樱通线",
            "zh-Hant": "櫻通線",
            "ja": "桜通線"
        }
    },
    {
        "id": "ngk",
        "colour": "#df638d",
        "fg": "#fff",
        "name": {
            "en": "Kami-iida Line",
            "zh-Hans": "上饭田线",
            "zh-Hant": "上飯田線",
            "ja": "上飯田線"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，我们发现您的颜色与实际与较大差别，请您重新提交，感谢您的贡献。
**（注：东山线颜色为#CC9200，名城线及名港线颜色为#3B2479，鹤舞线颜色为#007C99，樱通线颜色为#972A23，上饭田线颜色为#7A1638）**

**Comment by Windows-Taskmgr** [comment]
您好，由于您已经超过一个月未回复，此issue将会被关闭，感谢您的理解。
