### ISSUE TITLE
Resources: New palettes of Hezhou

### ISSUE THREAD

**Issue by KimJisso0610** [railmapgen/rmg-palette#963]
**Reference link:** https://www.baidu.com

**Justification:** 自用（幻想时间）

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "hezhou",
    "country": "CN",
    "name": {
        "en": "Hezhou",
        "zh-Hans": "贺州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "hz1",
        "colour": "#4d9f68",
        "fg": "#fff",
        "name": {
            "en": "Line 1",
            "zh-Hans": "1号线"
        }
    },
    {
        "id": "hz2",
        "colour": "#f8d84c",
        "fg": "#000",
        "name": {
            "en": "Line 2",
            "zh-Hans": "2号线"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，我们暂不支持幻想作品，感谢您的配合。如果您想使用其他颜色，您可以不使用调色板直接自定义颜色，由此带来的不便，我们深表歉意。
