### ISSUE TITLE
Resources: New palettes of Taizhou

### ISSUE THREAD

**Issue by Xiao-qian111** [railmapgen/rmg-palette#967]
**Reference link:** https://railmapgen.github.io/rmp-gallery/resources/thumbnails/taizhou.png

**Justification:** 添加线路颜色

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "taizhou",
    "country": "CN",
    "name": {
        "en": "Taizhou",
        "zh-Hans": "台州",
        "zh-Hant": "臺州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "ta S1",
        "colour": "#6363f2",
        "fg": "#fff",
        "name": {
            "en": "Line S1",
            "zh-Hans": "S1线",
            "zh-Hant": "S1線"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，我们暂不支持画廊为参考链接，请您以官方文件或维基百科为参考来源，感谢您的贡献。
