### ISSUE TITLE
Resources: New palettes of Wenzhou

### ISSUE THREAD

**Issue by AndreaFrederica** [railmapgen/rmg-palette#975]
**Reference link:** https://baike.baidu.com/item/%E6%B8%A9%E5%B7%9E%E8%BD%A8%E9%81%93%E4%BA%A4%E9%80%9AS3%E7%BA%BF/23365713

**Justification:** 线路已在建设 预留

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "wenzhou",
    "country": "CN",
    "name": {
        "en": "Wenzhou",
        "ko": "원저우",
        "zh-Hans": "温州",
        "zh-Hant": "溫州"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "wzs1",
        "colour": "#0061ae",
        "fg": "#fff",
        "name": {
            "en": "Line S1",
            "ko": "S1호선",
            "zh-Hans": "S1线",
            "zh-Hant": "S1線"
        }
    },
    {
        "id": "wzs2",
        "colour": "#e4002b",
        "fg": "#fff",
        "name": {
            "en": "Line S2",
            "ko": "S2호선",
            "zh-Hans": "S2线",
            "zh-Hant": "S2線"
        }
    },
    {
        "id": "wzs3",
        "colour": "#ff9900",
        "fg": "#fff",
        "name": {
            "en": "LineS3",
            "zh-Hans": "S3线",
            "zh-Hant": "S3線"
        }
    }
]</details>

**Comment by Windows-Taskmgr** [comment]
您好，我们暂不支持来自百度百科、360百科的数据，请您以官方文件或维基百科作为参考来源，感谢您的贡献。
