### ISSUE TITLE
Resources: New palettes of undefined

### ISSUE THREAD

**Issue by zzrcmd** [railmapgen/rmg-palette#981]
**Reference link:** http://114514.com

**Justification:** 114514

**Do not edit lines below, they are meant for bots only!!!**

<details repo="rmg-palette" type="city">{
    "id": "creeper",
    "country": "CN",
    "name": {
        "zh-Hans": "苦力怕虚拟轨道交通",
        "zh-Hant": "苦力怕虛擬軌道交通"
    }
}</details>

<details repo="rmg-palette" type="lines">[
    {
        "id": "1",
        "colour": "#aaaaaa",
        "fg": "#fff",
        "name": {
            "zh-Hans": "1号线",
            "zh-Hant": "1號線"
        }
    }
]</details>

**Comment by 28yfang** [comment]
您好，请不要提交任何无意义的颜色信息，并写上114514了事。若您无视此警告并继续提交相关内容，我们将对您实施封禁处理，感谢。
