### ISSUE TITLE
Add pantone input in picker

### ISSUE THREAD

**Issue by CatAlan1028** [railmapgen/rmg-palette#985]
You have pantone for the palette, why don't add pantone&cmyk to rmp color settings?
![image](https://github.com/railmapgen/rmp/assets/146333201/920c3d3d-8f59-4d47-a026-961cb5357104)
你们的调色板有潘通颜色。为什么不把潘通和CMYK颜色样式加入地铁线路图绘制器的颜色设定呢？

**Comment by wongchito** [comment]
Hi @CatAlan1028!

Thanks for your advice and we'll add Pantone input to **Palette - Picker** at our earliest possible. 

However, please be aware that the colour picker you highlighted is a part of Google Chrome and implemented by Google, and using a different browser you'll see a different colour picker. We're unable to change what the colour picker is provided.

**Comment by CatAlan1028** [comment]
It's OK. That doesn't matter.
